const n5List = [

{no:1,jp:"〜です／〜ます",vi:"Câu khẳng định lịch sự ở hiện tại",en:"Polite affirmative sentence (present tense)"},
{no:2,jp:"〜でした／〜ました",vi:"Câu khẳng định lịch sự ở quá khứ",en:"Polite affirmative sentence (past tense)"},
{no:3,jp:"〜じゃない／〜くない",vi:"Phủ định hiện tại của tính từ đuôi な／い",en:"Present negative form of な-adjectives / い-adjectives"},
{no:4,jp:"〜じゃなかった／〜くなかった",vi:"Phủ định quá khứ của tính từ đuôi な／い",en:"Past negative form of な-adjectives / い-adjectives"},
{no:5,jp:"〜があります／〜がいます",vi:"Có (vật / người)",en:"There is / There are (things / people)"},
{no:6,jp:"〜がありません／〜がいません",vi:"Không có (vật / người)",en:"There is not / There are not (things / people)"},
{no:7,jp:"〜ています",vi:"Đang làm, hoặc trạng thái đang diễn ra",en:"Be doing / ongoing action or resulting state"},
{no:8,jp:"〜ていません",vi:"Không đang làm, phủ định hành động đang diễn ra",en:"Not doing / negative ongoing action"},
{no:9,jp:"〜ました／〜ていました",vi:"Đã làm / Đã từng làm (Quá khứ tiếp diễn)",en:"Did / was doing (past or past continuous)"},
{no:10,jp:"〜たことがあります",vi:"Đã từng làm (Trải nghiệm trong quá khứ)",en:"Have ever done (past experience)"},

{ no: 11, jp: "〜てください", vi: "Hãy làm... (Mệnh lệnh nhẹ, lịch sự)", en: "Please do... (a polite, mild request)" },
{no:12,jp:"〜ないでください",vi:"Đừng làm…",en:"Please don't do..."},
{no:13,jp:"〜てはいけません",vi:"Không được làm…",en:"Must not / not allowed to..."},
{no:14,jp:"〜なければなりません",vi:"Phải làm…",en:"Must / have to..."},
{no:15,jp:"〜なくてもいいです",vi:"Không cần phải làm…",en:"Don't have to..."},
{no:16,jp:"〜てもいいです",vi:"Được phép làm…",en:"May / allowed to..."},
{no:17,jp:"〜ましょう",vi:"Hãy cùng làm…",en:"Let's do..."},
{no:18,jp:"〜ましょうか",vi:"Mình làm cùng nhé? / Tôi làm giúp nhé?",en:"Shall we...? / Shall I...?"},
{no:19,jp:"〜たいです",vi:"Muốn làm…",en:"Want to do..."},
{no:20,jp:"〜たくないです",vi:"Không muốn làm…",en:"Do not want to do..."},
{no:21,jp:"〜たほうがいい",vi:"Nên làm…",en:"Should do..."},

{no:22,jp:"〜たら",vi:"Nếu… thì… / Sau khi…",en:"If... then... / After..."},
{no:23,jp:"〜と",vi:"Hễ mà… thì… (Kết quả tất yếu)",en:"Whenever... (automatic result)"},
{no:24,jp:"〜ば",vi:"Nếu… thì… (Giả định logic)",en:"If... (logical condition)"},
{no:25,jp:"〜なら",vi:"Nếu là… thì…",en:"If it is... then..."},
{no:26,jp:"〜のに",vi:"Mặc dù… nhưng…",en:"Although... but..."},
{no:27,jp:"〜ても",vi:"Dù… vẫn… (Điều kiện ngược)",en:"Even if... still..."},
{no:28,jp:"〜かもしれません",vi:"Có thể… / Không chừng…",en:"Maybe / might..."},
{no:29,jp:"〜でしょう",vi:"Có lẽ… / Chắc là…",en:"Probably / I guess..."},

{no:30,jp:"〜に行きます／〜に来ます",vi:"Đi / đến... để làm gì đó",en:"Go / come... to do something."},
{no:31,jp:"〜に行きたい",vi:"Muốn đi để làm gì đó",en:"Want to go to do something"},
{no:32,jp:"〜てから",vi:"Sau khi làm A thì làm B",en:"After doing A, do B"},
{no:33,jp:"〜までに",vi:"Trước ..., chậm nhất là... (hạn chót)",en:"By ..., no later than ... (deadline)"},
{no:34,jp:"〜まえに",vi:"Trước khi làm…",en:"Before doing..."},
{no:35,jp:"〜あと",vi:"Sau khi làm…",en:"After doing..."},
{no:36,jp:"〜ておきます",vi:"Làm trước để chuẩn bị",en:"Do in advance (preparation)"},
{no:37,jp:"〜てみます",vi:"Thử làm…",en:"Try doing..."},
{no:38,jp:"〜ながら",vi:"Vừa làm A vừa làm B",en:"While doing A, do B"},
{no:39,jp:"〜かた",vi:"Cách làm…",en:"Way / method of doing..."},

{no:40,jp:"〜より〜",vi:"~ hơn ~",en:"More ... than ..."},
{no:41,jp:"〜の中で〜が一番〜",vi:"Trong số… thì ~ là nhất",en:"The most ... among ..."},
{no:42,jp:"〜と〜とどちらが〜ですか？",vi:"So sánh (A với B… cái nào hơn?)",en:"Which is more..., A or B?"},
{no:43,jp:"〜ほど〜ない",vi:"Không bằng…,Không tới mức như...",en:"Not as ... as ..., not to the extent that..."},
{no:44,jp:"〜すぎます",vi:"Quá… (Quá mức)",en:"Too much / excessively..."},
{no:45,jp:"〜やすい／にくい",vi:"Dễ làm / Khó làm",en:"Easy / difficult to do"},

{no:46,jp:"〜から",vi:"Vì... nên... (Lý do khách quan)",en:"Because... (objective reason)"},
{no:47,jp:"〜ので",vi:"Vì... nên... (Lý do nhẹ nhàng, khách quan)",en:"Because... (objective / softer reason)"},
{no:48,jp:"〜のに",vi:"Mặc dù… nhưng… (Trái kỳ vọng)",en:"Although... (unexpected result)"},
{no:49,jp:"〜ても",vi:"Dù… vẫn…",en:"Even if... still..."},
{no:50,jp:"〜ために",vi:"Vì… / Để… (Trang trọng)",en:"For / in order to (formal)"},
{no:51,jp:"〜間に",vi:"Trong khi… thì…",en:"During / while..."},

{no:52,jp:"〜と思う",vi:"Tôi nghĩ rằng…",en:"I think that..."},
{no:53,jp:"〜と言う",vi:"(Ai đó) nói rằng…",en:"(Someone) says that..."},
{no:54,jp:"〜でしょう",vi:"Có lẽ...nhỉ?\n(Xác nhận lại, dự đoán hoặc hỏi ý kiến nhẹ nhàng)",en:"Probably...right? (used for confirmation, prediction, or asking softly for opinions)"},
{no:55,jp:"〜んです",vi:"Vì...Giải thích lý do, nhấn mạnh\n(thân mật, mềm mại)",en:"Because...Explain / emphasize reason"},
{no:56,jp:"〜こと",vi:"Chuyện, việc, điều...\n(Danh từ hoá động từ)",en:"Things / actions...\n(Nominalization of verbs)"},
{no:57,jp:"〜のが好き / 嫌い / 上手 / 下手",vi:"Thích / Ghét / Giỏi / Kém làm việc gì đó.\n<br>( Danh từ hoá động từ)",en:"Like / dislike / be good or bad at doing something\n(Nominalization of verbs)"},
{no:58,jp:"〜たり〜たりする",vi:"Nào là...nào là...\n(Liệt kê hành động)",en:"Do things like...and...\n(Listing actions)"},
{no:59,jp:"〜ようです",vi:"Có vẻ như... / Hình như...\n(suy đoán dựa vào cảm giác, quan sát)",en:"Seems like... / Apparently...\n(guessing based on feelings or observation)"},
{no:60,jp:"〜前に / 〜後で",vi:"Trước khi... / Sau khi...",en:"Before... / After..."}
];