const n5_list_kanji = [

{stt:1, kanji:"一", hanviet:"Nhất", on:"イチ", kun:"ひと", vn:"Một", en:"One", strokes:1},
{stt:2, kanji:"二", hanviet:"Nhị", on:"ニ", kun:"ふた", vn:"Hai", en:"Two", strokes:2},
{stt:3, kanji:"三", hanviet:"Tam", on:"サン", kun:"み", vn:"Ba", en:"Three", strokes:3},
{stt:4, kanji:"四", hanviet:"Tứ", on:"シ", kun:"よん/よ", vn:"Bốn", en:"Four", strokes:5},
{stt:5, kanji:"五", hanviet:"Ngũ", on:"ゴ", kun:"いつ", vn:"Năm", en:"Five", strokes:4},
{stt:6, kanji:"六", hanviet:"Lục", on:"ロク", kun:"む", vn:"Sáu", en:"Six", strokes:4},
{stt:7, kanji:"七", hanviet:"Thất", on:"シチ", kun:"なな", vn:"Bảy", en:"Seven", strokes:2},
{stt:8, kanji:"八", hanviet:"Bát", on:"ハチ", kun:"や", vn:"Tám", en:"Eight", strokes:2},
{stt:9, kanji:"九", hanviet:"Cửu", on:"キュウ", kun:"ここの", vn:"Chín", en:"Nine", strokes:2},
{stt:10, kanji:"十", hanviet:"Thập", on:"ジュウ", kun:"とお", vn:"Mười", en:"Ten", strokes:2},
{stt:11, kanji:"百", hanviet:"Bách", on:"ヒャク", kun:"もも", vn:"Trăm", en:"Hundred", strokes:6},
{stt:12, kanji:"千", hanviet:"Thiên", on:"セン", kun:"ち", vn:"Nghìn", en:"Thousand", strokes:3},
{stt:13, kanji:"万", hanviet:"Vạn", on:"マン", kun:"よろず", vn:"Mười nghìn", en:"Ten thousand", strokes:3},
{stt:14, kanji:"円", hanviet:"Viên", on:"エン", kun:"まる", vn:"Yên, tròn", en:"Yen/Circle", strokes:4},

{stt:15, kanji:"日", hanviet:"Nhật", on:"ニチ", kun:"ひ", vn:"Ngày/Mặt trời", en:"Sun/Day", strokes:4},
{stt:16, kanji:"月", hanviet:"Nguyệt", on:"ゲツ", kun:"つき", vn:"Tháng/Mặt trăng", en:"Moon/Month", strokes:4},
{stt:17, kanji:"午", hanviet:"Ngọ", on:"ゴ", kun:"うま", vn:"Buổi trưa", en:"Noon", strokes:4},
{stt:18, kanji:"後", hanviet:"Hậu", on:"ゴ/コウ", kun:"のち/うし/あと", vn:"Sau/Phía sau", en:"After/Behind", strokes:9},
{stt:19, kanji:"時", hanviet:"Thời", on:"ジ", kun:"とき", vn:"Giờ", en:"Time/Hour", strokes:10},
{stt:20, kanji:"間", hanviet:"Gian", on:"カン", kun:"あいだ", vn:"Khoảng thời gian/Giữa", en:"Interval/Space", strokes:12},
{stt:21, kanji:"分", hanviet:"Phân", on:"フン/ブン", kun:"わ", vn:"Phút/Chia", en:"Minute/Part", strokes:4},
{stt:22, kanji:"半", hanviet:"Bán", on:"ハン", kun:"なか", vn:"Một nửa", en:"Half", strokes:5},
{stt:23, kanji:"前", hanviet:"Tiền", on:"ゼン", kun:"まえ", vn:"Trước", en:"Before/Front", strokes:9},
{stt:24, kanji:"北", hanviet:"Bắc", on:"ホク", kun:"きた", vn:"Hướng Bắc", en:"North", strokes:5},
{stt:25, kanji:"南", hanviet:"Nam", on:"ナン", kun:"みなみ", vn:"Hướng Nam", en:"South", strokes:9},
{stt:26, kanji:"東", hanviet:"Đông", on:"トウ", kun:"ひがし", vn:"Hướng Đông", en:"East", strokes:8},
{stt:27, kanji:"西", hanviet:"Tây", on:"セイ/サイ", kun:"にし", vn:"Hướng Tây", en:"West", strokes:6},
{stt:28, kanji:"右", hanviet:"Hữu", on:"ウ", kun:"みぎ", vn:"Bên phải", en:"Right", strokes:5},
{stt:29, kanji:"左", hanviet:"Tả", on:"サ", kun:"ひだり", vn:"Bên trái", en:"Left", strokes:5},
{stt:30, kanji:"上", hanviet:"Thượng", on:"ジョウ", kun:"うえ", vn:"Trên", en:"Up", strokes:3},
{stt:31, kanji:"下", hanviet:"Hạ", on:"カ", kun:"した", vn:"Dưới", en:"Down", strokes:3},
{stt:32, kanji:"中", hanviet:"Trung", on:"チュウ", kun:"なか", vn:"Giữa", en:"Middle", strokes:4},
{stt:33, kanji:"外", hanviet:"Ngoại", on:"ガイ", kun:"そと", vn:"Bên ngoài", en:"Outside", strokes:5},
{stt:34, kanji:"何", hanviet:"Hà", on:"カ", kun:"なに", vn:"Cái gì", en:"What", strokes:7},
{stt:35, kanji:"本", hanviet:"Bản", on:"ホン", kun:"もと", vn:"Sách/Gốc", en:"Book/Origin", strokes:5},
{stt:36, kanji:"生", hanviet:"Sinh", on:"セイ", kun:"い/う", vn:"Sinh sống/Sinh ra", en:"Life/Birth", strokes:5},

{stt:37, kanji:"火", hanviet:"Hoả", on:"カ", kun:"ひ", vn:"Lửa", en:"Fire", strokes:4},
{stt:38, kanji:"水", hanviet:"Thủy", on:"スイ", kun:"みず", vn:"Nước", en:"Water", strokes:4},
{stt:39, kanji:"木", hanviet:"Mộc", on:"ボク/モク", kun:"き", vn:"Cây", en:"Tree/Wood", strokes:4},
{stt:40, kanji:"金", hanviet:"Kim", on:"キン", kun:"かね", vn:"Vàng/Tiền", en:"Gold/Money", strokes:8},
{stt:41, kanji:"土", hanviet:"Thổ", on:"ド", kun:"つち", vn:"Đất", en:"Earth", strokes:3},
{stt:42, kanji:"山", hanviet:"Sơn", on:"サン", kun:"やま", vn:"Núi", en:"Mountain", strokes:3},
{stt:43, kanji:"川", hanviet:"Xuyên", on:"セン", kun:"かわ", vn:"Sông", en:"River", strokes:3},
{stt:44, kanji:"田", hanviet:"Điền", on:"デン", kun:"た", vn:"Ruộng", en:"Field", strokes:5},
{stt:45, kanji:"天", hanviet:"Thiên", on:"テン", kun:"あま", vn:"Trời", en:"Sky/Heaven", strokes:4},
{stt:46, kanji:"空", hanviet:"Không", on:"クウ", kun:"そら", vn:"Bầu trời/Trống", en:"Sky/Empty", strokes:8},
{stt:47, kanji:"雨", hanviet:"Vũ", on:"ウ", kun:"あめ", vn:"Mưa", en:"Rain", strokes:8},
{stt:48, kanji:"花", hanviet:"Hoa", on:"カ", kun:"はな", vn:"Hoa", en:"Flower", strokes:7},
{stt:49, kanji:"国", hanviet:"Quốc", on:"コク", kun:"くに", vn:"Quốc gia", en:"Country", strokes:8},
{stt:50, kanji:"社", hanviet:"Xã", on:"シャ", kun:"やしろ", vn:"Đền/Công ty", en:"Company/Shrine", strokes:7},
{stt:51, kanji:"店", hanviet:"Điếm", on:"テン", kun:"みせ", vn:"Cửa hàng", en:"Shop", strokes:8},
{stt:52, kanji:"駅", hanviet:"Dịch", on:"エキ", kun:"", vn:"Ga", en:"Station", strokes:14},

{stt:53, kanji:"人", hanviet:"Nhân", on:"ジン/ニン", kun:"ひと", vn:"Người", en:"Person", strokes:2},
{stt:54, kanji:"子", hanviet:"Tử", on:"シ", kun:"こ", vn:"Con/Trẻ", en:"Child", strokes:3},
{stt:55, kanji:"女", hanviet:"Nữ", on:"ジョ", kun:"おんな", vn:"Nữ giới", en:"Woman", strokes:3},
{stt:56, kanji:"男", hanviet:"Nam", on:"ダン/ナン", kun:"おとこ", vn:"Nam giới", en:"Man", strokes:7},
{stt:57, kanji:"父", hanviet:"Phụ", on:"フ", kun:"ちち", vn:"Cha", en:"Father", strokes:4},
{stt:58, kanji:"母", hanviet:"Mẫu", on:"ボ", kun:"はは", vn:"Mẹ", en:"Mother", strokes:5},
{stt:59, kanji:"友", hanviet:"Hữu", on:"ユウ", kun:"とも", vn:"Bạn", en:"Friend", strokes:4},
{stt:60, kanji:"目", hanviet:"Mục", on:"モク", kun:"め", vn:"Mắt", en:"Eye", strokes:5},
{stt:61, kanji:"口", hanviet:"Khẩu", on:"コウ", kun:"くち", vn:"Miệng", en:"Mouth", strokes:3},
{stt:62, kanji:"耳", hanviet:"Nhĩ", on:"ジ", kun:"みみ", vn:"Tai", en:"Ear", strokes:6},
{stt:63, kanji:"手", hanviet:"Thủ", on:"シュ", kun:"て", vn:"Tay", en:"Hand", strokes:4},
{stt:64, kanji:"足", hanviet:"Túc", on:"ソク", kun:"あし", vn:"Chân", en:"Foot/Leg", strokes:7},
{stt:65, kanji:"力", hanviet:"Lực", on:"リョク/リキ", kun:"ちから", vn:"Sức mạnh", en:"Power/Force", strokes:2},
{stt:66, kanji:"学", hanviet:"Học", on:"ガク", kun:"まなぶ", vn:"Học", en:"Study/Learn", strokes:8},
{stt:67, kanji:"校", hanviet:"Hiệu", on:"コウ", kun:"", vn:"Trường học", en:"School", strokes:10},

{stt:68, kanji:"先", hanviet:"Tiên", on:"セン", kun:"さき", vn:"Trước", en:"Before/Ahead", strokes:6},
{stt:69, kanji:"休", hanviet:"Hưu", on:"キュウ", kun:"やすむ", vn:"Nghỉ ngơi", en:"Rest", strokes:6},
{stt:70, kanji:"行", hanviet:"Hành", on:"コウ/ギョウ", kun:"いく/ゆく", vn:"Đi", en:"Go", strokes:6},
{stt:71, kanji:"来", hanviet:"Lai", on:"ライ", kun:"くる", vn:"Đến", en:"Come", strokes:7},
{stt:72, kanji:"出", hanviet:"Xuất", on:"シュツ", kun:"でる/だす", vn:"Ra, xuất", en:"Exit/Go out", strokes:5},
{stt:73, kanji:"入", hanviet:"Nhập", on:"ニュウ", kun:"はい/いる", vn:"Vào, nhập", en:"Enter", strokes:2},
{stt:74, kanji:"食", hanviet:"Thực", on:"ショク", kun:"たべる", vn:"Ăn", en:"Eat", strokes:9},
{stt:75, kanji:"飲", hanviet:"Ẩm", on:"イン", kun:"のむ", vn:"Uống", en:"Drink", strokes:12},
{stt:76, kanji:"言", hanviet:"Ngôn", on:"ゲン/ゴン", kun:"い-う", vn:"Nói", en:"Say/Word", strokes:7},
{stt:77, kanji:"話", hanviet:"Thoại", on:"ワ", kun:"はなす", vn:"Nói chuyện", en:"Talk", strokes:13},
{stt:78, kanji:"読", hanviet:"Độc", on:"ドク", kun:"よむ", vn:"Đọc", en:"Read", strokes:14},
{stt:79, kanji:"書", hanviet:"Thư", on:"ショ", kun:"かく", vn:"Viết", en:"Write", strokes:10},
{stt:80, kanji:"見", hanviet:"Kiến", on:"ケン", kun:"みる", vn:"Nhìn", en:"See/Look", strokes:7},
{stt:81, kanji:"聞", hanviet:"Văn", on:"ブン/モン", kun:"きく", vn:"Nghe", en:"Hear/Ask", strokes:14},
{stt:82, kanji:"買", hanviet:"Mãi", on:"バイ", kun:"かう", vn:"Mua", en:"Buy", strokes:12},
{stt:83, kanji:"立", hanviet:"Lập", on:"リツ", kun:"たつ", vn:"Đứng", en:"Stand", strokes:5},
{stt:84, kanji:"座", hanviet:"Tọa", on:"ザ", kun:"すわる", vn:"Ngồi", en:"Sit", strokes:10},
{stt:85, kanji:"会", hanviet:"Hội", on:"カイ/エ", kun:"あう", vn:"Gặp", en:"Meet", strokes:6},

{stt:86, kanji:"大", hanviet:"Đại", on:"ダイ/タイ", kun:"おおきい", vn:"Lớn", en:"Big", strokes:3},
{stt:87, kanji:"小", hanviet:"Tiểu", on:"ショウ", kun:"ちいさい", vn:"Nhỏ", en:"Small", strokes:3},
{stt:88, kanji:"高", hanviet:"Cao", on:"コウ", kun:"たかい", vn:"Cao", en:"Tall/High", strokes:10},
{stt:89, kanji:"安", hanviet:"An", on:"アン", kun:"やすい", vn:"Rẻ, an toàn", en:"Cheap/Safe", strokes:6},
{stt:90, kanji:"新", hanviet:"Tân", on:"シン", kun:"あたらしい", vn:"Mới", en:"New", strokes:13},
{stt:91, kanji:"古", hanviet:"Cổ", on:"コ", kun:"ふるい", vn:"Cũ", en:"Old", strokes:5},
{stt:92, kanji:"多", hanviet:"Đa", on:"タ", kun:"おおい", vn:"Nhiều", en:"Many", strokes:6},
{stt:93, kanji:"少", hanviet:"Thiểu", on:"ショウ", kun:"すくない", vn:"Ít", en:"Few", strokes:4},
{stt:94, kanji:"早", hanviet:"Tảo", on:"ソウ", kun:"はやい", vn:"Sớm/Nhanh", en:"Early/Fast", strokes:6},
{stt:95, kanji:"長", hanviet:"Trường", on:"チョウ", kun:"ながい", vn:"Dài", en:"Long", strokes:8},
{stt:96, kanji:"白", hanviet:"Bạch", on:"ハク/ビャク", kun:"しろ", vn:"Trắng", en:"White", strokes:5},
{stt:97, kanji:"赤", hanviet:"Xích", on:"セキ/シャク", kun:"あか", vn:"Đỏ", en:"Red", strokes:7},
{stt:98, kanji:"明", hanviet:"Minh", on:"メイ", kun:"あかり/あかるい", vn:"Sáng", en:"Bright", strokes:8},
{stt:99, kanji:"電", hanviet:"Điện", on:"デン", kun:"", vn:"Điện", en:"Electricity", strokes:13},
{stt:100, kanji:"車", hanviet:"Xa", on:"シャ", kun:"くるま", vn:"Xe", en:"Car", strokes:7}

];