window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[16] = [

{
level:"N5",
lesson:16,
id:1,
kanji:"乗ります",
kana:"のります",
hanviet:"THỪA",
vi:"đi, lên (tàu, xe)",
en:"get on, ride",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby>、<ruby>七時<rt>しちじ</rt></ruby>に <ruby>電車<rt>でんしゃ</rt></ruby>に <span class='target-word'><ruby>乗<rt>の</rt></ruby>って</span> <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいあさ しちじに でんしゃに のって かいしゃへ いきます",
example_vi:"Mỗi sáng lúc 7 giờ, tôi lên tàu điện để đến công ty.",
example_en:"Every morning at 7, I get on the train and go to the office."
},

{
level:"N5",
lesson:16,
id:2,
kanji:"降ります",
kana:"おります",
hanviet:"GIÁNG",
vi:"xuống (tàu, xe)",
en:"get off",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>次<rt>つぎ</rt></ruby>の <ruby>駅<rt>えき</rt></ruby>で <ruby>電車<rt>でんしゃ</rt></ruby>を <span class='target-word'><ruby>降<rt>お</rt></ruby>ります</span>。",
example_read:"つぎの えきで でんしゃを おります",
example_vi:"Tôi xuống tàu ở ga tiếp theo.",
example_en:"I get off the train at the next station."
},

{
level:"N5",
lesson:16,
id:3,
kanji:"乗り換えます",
kana:"のりかえます",
hanviet:"THỪA HOÁN",
vi:"chuyển, đổi tàu",
en:"transfer",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>東京駅<rt>とうきょうえき</rt></ruby>で <ruby>山手線<rt>やまのてせん</rt></ruby>に <span class='target-word'><ruby>乗<rt>の</rt></ruby>り<ruby>換<rt>か</rt></ruby>えます</span>。",
example_read:"とうきょうえきで やまのてせんに のりかえます",
example_vi:"Tôi chuyển sang tuyến Yamanote ở ga Tokyo.",
example_en:"I transfer to the Yamanote Line at Tokyo Station."
},

{
level:"N5",
lesson:16,
id:4,
kanji:"浴びます",
kana:"あびます",
hanviet:"DỤC",
vi:"tắm (vòi sen)",
en:"take a shower",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>の <ruby>後<rt>あと</rt></ruby>に シャワーを <span class='target-word'><ruby>浴<rt>あ</rt></ruby>びます</span>。",
example_read:"しごとの あとに シャワーを あびます",
example_vi:"Sau khi làm việc, tôi tắm vòi sen.",
example_en:"I take a shower after work."
},

{
level:"N5",
lesson:16,
id:5,
kanji:"入れます",
kana:"いれます",
hanviet:"NHẬP",
vi:"cho vào, bỏ vào",
en:"put in",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>鞄<rt>かばん</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>入<rt>い</rt></ruby>れます</span>。",
example_read:"かばんに ほんを いれます",
example_vi:"Tôi cho sách vào cặp.",
example_en:"I put the book into my bag."
},

{
level:"N5",
lesson:16,
id:6,
kanji:"出します",
kana:"だします",
hanviet:"XUẤT",
vi:"lấy ra, đưa ra, gửi",
en:"take out, submit, send",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>郵便局<rt>ゆうびんきょく</rt></ruby>で <ruby>手紙<rt>てがみ</rt></ruby>を <span class='target-word'><ruby>出<rt>だ</rt></ruby>します</span>。",
example_read:"ゆうびんきょくで てがみを だします",
example_vi:"Tôi gửi thư ở bưu điện.",
example_en:"I mail a letter at the post office."
},

{
level:"N5",
lesson:16,
id:7,
kanji:"下ろします",
kana:"おろします",
hanviet:"HẠ",
vi:"rút (tiền)",
en:"withdraw",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>銀行<rt>ぎんこう</rt></ruby>で <ruby>お金<rt>おかね</rt></ruby>を <span class='target-word'><ruby>下<rt>お</rt></ruby>ろします</span>。",
example_read:"ぎんこうで おかねを おろします",
example_vi:"Tôi rút tiền ở ngân hàng.",
example_en:"I withdraw money at the bank."
},

{
level:"N5",
lesson:16,
id:8,
kanji:"入ります",
kana:"はいります",
hanviet:"NHẬP",
vi:"vào, nhập học",
en:"enter",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>来年<rt>らいねん</rt></ruby>、<span class='target-word'><ruby>大学<rt>だいがく</rt></ruby>に <ruby>入<rt>はい</rt></ruby>ります</span>。",
example_read:"らいねん だいがくに はいります",
example_vi:"Năm sau tôi sẽ vào đại học.",
example_en:"I will enter university next year."
},

{
level:"N5",
lesson:16,
id:9,
kanji:"出ます",
kana:"でます",
hanviet:"XUẤT",
vi:"ra, tốt nghiệp",
en:"leave, graduate",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>来年<rt>らいねん</rt></ruby>、<ruby>大学<rt>だいがく</rt></ruby>を <span class='target-word'><ruby>出<rt>で</rt></ruby>ます</span>。",
example_read:"らいねん だいがくを でます",
example_vi:"Năm sau tôi sẽ tốt nghiệp đại học.",
example_en:"I will graduate from university."
},

{
level:"N5",
lesson:16,
id:10,
kanji:"押します",
kana:"おします",
hanviet:"ÁP",
vi:"bấm, ấn (nút)",
en:"press",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>エレベーター</ruby>の <ruby>ボタン</ruby>を <span class='target-word'><ruby>押<rt>お</rt></ruby>します</span>。",
example_read:"エレベーターの ボタンを おします",
example_vi:"Tôi bấm nút thang máy.",
example_en:"I press the elevator button."
},

{
level:"N5",
lesson:16,
id:11,
kanji:"飲みます",
kana:"のみます",
hanviet:"ẨM",
vi:"uống (bia, rượu, nước)",
en:"drink",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>熱<rt>ねつ</rt></ruby>が あるので、<ruby>薬<rt>くすり</rt></ruby>を <span class='target-word'><ruby>飲<rt>の</rt></ruby>みます</span>。",
example_read:"ねつが あるので、くすりを のみます",
example_vi:"Vì bị sốt nên tôi uống thuốc.",
example_en:"I take medicine because I have a fever."
},

{
level:"N5",
lesson:16,
id:12,
kanji:"始めます",
kana:"はじめます",
hanviet:"THỦY",
vi:"bắt đầu",
en:"start",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>は <ruby>午前<rt>ごぜん</rt></ruby><ruby>九時<rt>くじ</rt></ruby>に <ruby>授業<rt>じゅぎょう</rt></ruby>を <span class='target-word'><ruby>始<rt>はじ</rt></ruby>めます</span>。",
example_read:"せんせいは ごぜん くじに じゅぎょうを はじめます",
example_vi:"Giáo viên bắt đầu buổi học lúc 9 giờ sáng.",
example_en:"The teacher starts the class at 9:00 a.m."
},

{
level:"N5",
lesson:16,
id:13,
kanji:"見学します",
kana:"けんがくします",
hanviet:"KIẾN HỌC",
vi:"tham quan, kiến tập",
en:"observe, tour",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>たちは<ruby>工場<rt>こうじょう</rt></ruby>を  <span class='target-word'><ruby>見学<rt>けんがく</rt></ruby>します</span>。",
example_read:"がくせいたちは こうじょうを けんがくします",
example_vi:"Các sinh viên tham quan nhà máy.",
example_en:"The students tour a factory."
},

{
level:"N5",
lesson:16,
id:14,
kanji:"電話します",
kana:"でんわします",
hanviet:"ĐIỆN THOẠI",
vi:"gọi điện thoại",
en:"call",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>今夜<rt>こんや</rt></ruby>、<ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'><ruby>電話<rt>でんわ</rt></ruby>します</span>。",
example_read:"こんや ともだちに でんわします",
example_vi:"Tối nay tôi sẽ gọi điện cho bạn.",
example_en:"I will call my friend tonight."
},

{
level:"N5",
lesson:16,
id:15,
kanji:"若い",
kana:"わかい",
hanviet:"NHƯỢC",
vi:"trẻ",
en:"young",
word_type_vi:"Tính từ い",
word_type_en:"i-adjective",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'><ruby>若<rt>わか</rt></ruby>い</span>ころ、<ruby>東京<rt>とうきょう</rt></ruby>に <ruby>住<rt>す</rt></ruby>んでいました。",
example_read:"ちちは わかい ころ とうきょうに すんでいました",
example_vi:"Khi còn trẻ, bố tôi đã sống ở Tokyo.",
example_en:"My father lived in Tokyo when he was young."
},

{
level:"N5",
lesson:16,
id:16,
kanji:"長い",
kana:"ながい",
hanviet:"TRƯỜNG",
vi:"dài",
en:"long",
word_type_vi:"Tính từ い",
word_type_en:"i-adjective",
category:"Minna 1",
example:"この <ruby>橋<rt>はし</rt></ruby>は とても <span class='target-word'><ruby>長<rt>なが</rt></ruby>い</span>です。",
example_read:"この はしは とても ながいです",
example_vi:"Cây cầu này rất dài.",
example_en:"This bridge is very long."
},

{
level:"N5",
lesson:16,
id:17,
kanji:"短い",
kana:"みじかい",
hanviet:"ĐOẢN",
vi:"ngắn",
en:"short",
word_type_vi:"Tính từ い",
word_type_en:"i-adjective",
category:"Minna 1",
example:"<ruby>妹<rt>いもうと</rt></ruby>の <ruby>髪<rt>かみ</rt></ruby>は <span class='target-word'><ruby>短<rt>みじか</rt></ruby>い</span>です。",
example_read:"いもうとの かみは みじかいです",
example_vi:"Tóc của em gái tôi ngắn.",
example_en:"My younger sister's hair is short."
},

{
level:"N5",
lesson:16,
id:18,
kanji:"明るい",
kana:"あかるい",
hanviet:"MINH",
vi:"sáng",
en:"bright",
word_type_vi:"Tính từ い",
word_type_en:"i-adjective",
category:"Minna 1",
example:"この <ruby>部屋<rt>へや</rt></ruby>は とても <span class='target-word'><ruby>明<rt>あか</rt></ruby>るい</span>です。",
example_read:"この へやは とても あかるいです",
example_vi:"Căn phòng này rất sáng.",
example_en:"This room is very bright."
},

{
level:"N5",
lesson:16,
id:19,
kanji:"暗い",
kana:"くらい",
hanviet:"ÁM",
vi:"tối",
en:"dark",
word_type_vi:"Tính từ い",
word_type_en:"i-adjective",
category:"Minna 1",
example:"この<ruby>道<rt>みち</rt></ruby>は <ruby>夜<rt>よる</rt></ruby>になると とても <span class='target-word'><ruby>暗<rt>くら</rt></ruby>い</span>です。",
example_read:"このみちは よるに なると とても くらいです",
example_vi:"Con đường này khi đêm xuống thì rất tối.",
example_en:"This road gets very dark at night."
},

{
level:"N5",
lesson:16,
id:20,
kanji:"体",
kana:"からだ",
hanviet:"THỂ",
vi:"cơ thể",
en:"body",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>体<rt>からだ</rt></ruby></span>を <ruby>大切<rt>たいせつ</rt></ruby>に してください。",
example_read:"からだを たいせつに してください",
example_vi:"Hãy giữ gìn sức khỏe nhé.",
example_en:"Please take good care of yourself."
},

{
level:"N5",
lesson:16,
id:21,
kanji:"頭",
kana:"あたま",
hanviet:"ĐẦU",
vi:"đầu",
en:"head",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>頭<rt>あたま</rt></ruby></span>が <ruby>痛<rt>いた</rt></ruby>いです。",
example_read:"あたまが いたいです",
example_vi:"Tôi bị đau đầu.",
example_en:"My head hurts."
},

{
level:"N5",
lesson:16,
id:22,
kanji:"髪",
kana:"かみ",
hanviet:"PHÁT",
vi:"tóc",
en:"hair",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby>、<ruby>美容院<rt>びよういん</rt></ruby>で <span class='target-word'><ruby>髪<rt>かみ</rt></ruby></span>を <ruby>切<rt>き</rt></ruby>りました。",
example_read:"きのう びよういんで かみを きりました",
example_vi:"Hôm qua tôi đi cắt tóc ở tiệm.",
example_en:"I went to the salon and got a haircut yesterday."
},

{
level:"N5",
lesson:16,
id:23,
kanji:"顔",
kana:"かお",
hanviet:"NHAN",
vi:"mặt",
en:"face",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby>、<span class='target-word'><ruby>顔<rt>かお</rt></ruby></span>を <ruby>洗<rt>あら</rt></ruby>います。",
example_read:"まいあさ かおを あらいます",
example_vi:"Tôi rửa mặt mỗi sáng.",
example_en:"I wash my face every morning."
},

{
level:"N5",
lesson:16,
id:24,
kanji:"目",
kana:"め",
hanviet:"MỤC",
vi:"mắt",
en:"eye",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>パソコン</ruby>を <ruby>長<rt>なが</rt></ruby>く <ruby>見<rt>み</rt></ruby>ていて、<span class='target-word'><ruby>目<rt>め</rt></ruby></span>が <ruby>疲<rt>つか</rt></ruby>れました。",
example_read:"パソコンを ながく みていて、めが つかれました",
example_vi:"Tôi nhìn máy tính lâu nên mắt bị mỏi.",
example_en:"My eyes are tired because I looked at the computer for a long time."
},

{
level:"N5",
lesson:16,
id:25,
kanji:"耳",
kana:"みみ",
hanviet:"NHĨ",
vi:"tai",
en:"ear",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>耳<rt>みみ</rt></ruby></span>を <ruby>澄<rt>す</rt></ruby>ませて <ruby>聞<rt>き</rt></ruby>きます。",
example_read:"みみを すませて ききます",
example_vi:"Tôi lắng tai nghe.",
example_en:"I listen carefully."
},

{
level:"N5",
lesson:16,
id:26,
kanji:"鼻",
kana:"はな",
hanviet:"TỴ",
vi:"mũi",
en:"nose",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>風邪<rt>かぜ</rt></ruby>を <ruby>引<rt>ひ</rt></ruby>いて、<span class='target-word'><ruby>鼻<rt>はな</rt></ruby></span>が <ruby>詰<rt>つ</rt></ruby>まっています。",
example_read:"かぜを ひいて、はなが つまっています",
example_vi:"Tôi bị cảm nên bị nghẹt mũi.",
example_en:"I have a cold and a stuffy nose."
},

{
level:"N5",
lesson:16,
id:27,
kanji:"口",
kana:"くち",
hanviet:"KHẨU",
vi:"miệng",
en:"mouth",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>お医者<rt>いしゃ</rt></ruby>さんに <span class='target-word'><ruby>口<rt>くち</rt></ruby></span>を <ruby>大<rt>おお</rt></ruby>きく <ruby>開<rt>あ</rt></ruby>けてくださいと <ruby>言<rt>い</rt></ruby>われました。",
example_read:"おいしゃさんに くちを おおきく あけてくださいと いわれました",
example_vi:"Tôi được bác sĩ bảo hãy há miệng thật to.",
example_en:"The doctor told me to open my mouth wide."
},

{
level:"N5",
lesson:16,
id:28,
kanji:"歯",
kana:"は",
hanviet:"NHA",
vi:"răng",
en:"tooth",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎晩<rt>まいばん</rt></ruby>、<span class='target-word'><ruby>歯<rt>は</rt></ruby></span>を <ruby>磨<rt>みが</rt></ruby>きます。",
example_read:"まいばん はを みがきます",
example_vi:"Tôi đánh răng mỗi tối.",
example_en:"I brush my teeth every night."
},

{
level:"N5",
lesson:16,
id:29,
kanji:"お腹",
kana:"おなか",
hanviet:"PHÚC",
vi:"bụng",
en:"stomach",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昼ご飯<rt>ひるごはん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べなかったので、<span class='target-word'><ruby>お腹<rt>おなか</rt></ruby></span>が <ruby>空<rt>す</rt></ruby>きました。",
example_read:"ひるごはんを たべなかったので、おなかが すきました",
example_vi:"Vì đã không ăn trưa nên tôi đói rồi.",
example_en:"I didn't eat lunch, so I'm hungry."
},

{
level:"N5",
lesson:16,
id:30,
kanji:"足",
kana:"あし",
hanviet:"TÚC",
vi:"chân",
en:"leg / foot",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>たくさん<rt></rt></ruby> <ruby>歩<rt>ある</rt></ruby>いたので、<span class='target-word'><ruby>足<rt>あし</rt></ruby></span>が <ruby>痛<rt>いた</rt></ruby>いです。",
example_read:"たくさん あるいたので、あしが いたいです",
example_vi:"Vì tôi đi bộ nhiều nên chân bị đau.",
example_en:"My legs hurt because I walked a lot."
},

{
level:"N5",
lesson:16,
id:31,
kanji:"背",
kana:"せ",
hanviet:"BỐI",
vi:"lưng / chiều cao (cơ thể)",
en:"back / height",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>背<rt>せ</rt></ruby></span>が <ruby>高<rt>たか</rt></ruby>いですね。モデルみたいです。",
example_read:"せが たかいですね、モデルみたいです",
example_vi:"Bạn cao thật đấy, giống như người mẫu vậy.",
example_en:"You're tall, like a model."
},

{
level:"N5",
lesson:16,
id:32,
kanji:"サービス",
kana:"サービス",
hanviet:"",
vi:"dịch vụ",
en:"service",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>店<rt>みせ</rt></ruby>は <span class='target-word'>サービス</span>が <ruby>良<rt>よ</rt></ruby>くて、とても <ruby>人気<rt>にんき</rt></ruby>です。",
example_read:"この みせは サービスが よくて、とても にんきです",
example_vi:"Cửa hàng này dịch vụ tốt nên rất được ưa chuộng.",
example_en:"This shop has good service and is very popular."
},

{
level:"N5",
lesson:16,
id:33,
kanji:"ジョギング",
kana:"ジョギング",
hanviet:"",
vi:"việc chạy bộ",
en:"jogging",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>健康<rt>けんこう</rt></ruby>の<ruby>為<rt>ため</rt></ruby>に、<ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>公園<rt>こうえん</rt></ruby>で <span class='target-word'>ジョギング</span>を しています。",
example_read:"けんこうのために、まいあさ こうえんで ジョギングを しています",
example_vi:"Để tốt cho sức khỏe, tôi chạy bộ ở công viên mỗi sáng.",
example_en:"I go jogging in the park every morning for my health."
},

{
level:"N5",
lesson:16,
id:34,
kanji:"シャワー",
kana:"シャワー",
hanviet:"",
vi:"vòi hoa sen",
en:"shower",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby> <ruby>起<rt>お</rt></ruby>きて <span class='target-word'>シャワー</span>を <ruby>浴<rt>あ</rt></ruby>びます。",
example_read:"あさ おきて シャワーを あびます",
example_vi:"Buổi sáng tôi thức dậy và tắm vòi sen.",
example_en:"I take a shower after waking up in the morning."
},

{
level:"N5",
lesson:16,
id:35,
kanji:"緑",
kana:"みどり",
hanviet:"LỤC",
vi:"màu xanh lá cây",
en:"green",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>春<rt>はる</rt></ruby>に なると、この <ruby>町<rt>まち</rt></ruby>は <span class='target-word'><ruby>緑<rt>みどり</rt></ruby></span>が <ruby>綺麗<rt>きれい</rt></ruby>です。",
example_read:"はるに なると、この まちは みどりが きれいです",
example_vi:"Khi vào mùa xuân, thị trấn này có màu xanh rất đẹp.",
example_en:"In spring, this town becomes beautifully green."
},

{
level:"N5",
lesson:16,
id:36,
kanji:"寺",
kana:"てら",
hanviet:"TỰ",
vi:"chùa",
en:"temple (Buddhist)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>京都<rt>きょうと</rt></ruby>で <ruby>有名<rt>ゆうめい</rt></ruby>な <span class='target-word'><ruby>寺<rt>てら</rt></ruby></span>を <ruby>見学<rt>けんがく</rt></ruby>します。",
example_read:"きょうとで ゆうめいな てらを けんがくします",
example_vi:"Tôi tham quan một ngôi chùa nổi tiếng ở Kyoto.",
example_en:"I visit a famous temple in Kyoto."
},

{
level:"N5",
lesson:16,
id:37,
kanji:"神社",
kana:"じんじゃ",
hanviet:"THẦN XÃ",
vi:"đền Thần đạo",
en:"Shinto shrine",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"お<ruby>正月<rt>しょうがつ</rt></ruby>に <span class='target-word'><ruby>神社<rt>じんじゃ</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"おしょうがつに じんじゃへ いきます",
example_vi:"Tôi đi đền Thần đạo vào dịp năm mới.",
example_en:"I go to a shrine during the New Year holiday."
},

{
level:"N5",
lesson:16,
id:38,
kanji:"一番",
kana:"いちばん",
hanviet:"NHẤT BAN",
vi:"số một / nhất",
en:"the most / number one",
word_type_vi:"Phó từ / danh từ",
word_type_en:"Adverb / noun",
category:"Minna 1",
example:"この <ruby>料理<rt>りょうり</rt></ruby>が <span class='target-word'><ruby>一番<rt>いちばん</rt></ruby></span> <ruby>好<rt>す</rt></ruby>きです。",
example_read:"この りょうりが いちばん すきです",
example_vi:"Đây là món ăn tôi thích nhất.",
example_en:"This dish is my favorite."
},

{
level:"N5",
lesson:16,
id:39,
kanji:"どうやって",
kana:"どうやって",
hanviet:"",
vi:"làm thế nào",
en:"how",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>まで <span class='target-word'>どうやって</span> <ruby>行<rt>い</rt></ruby>きますか。",
example_read:"えきまで どうやって いきますか",
example_vi:"Đi đến ga bằng cách nào vậy?",
example_en:"How do you get to the station?"
},

{
level:"N5",
lesson:16,
id:40,
kanji:"どれ",
kana:"どれ",
hanviet:"",
vi:"cái nào (trong 3 cái trở lên)",
en:"which one",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<ruby>靴<rt>くつ</rt></ruby>は <span class='target-word'>どれ</span>が <ruby>一番<rt>いちばん</rt></ruby> <ruby>安<rt>やす</rt></ruby>いですか。",
example_read:"くつは どれが いちばん やすいですか",
example_vi:"Đôi giày nào rẻ nhất?",
example_en:"Which pair of shoes is the cheapest?"
},

{
level:"N5",
lesson:16,
id:41,
kanji:"どの",
kana:"どの",
hanviet:"",
vi:"cái nào (dùng trước danh từ)",
en:"which",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'>どの</span> <ruby>本<rt>ほん</rt></ruby>を <ruby>買<rt>か</rt></ruby>いますか。",
example_read:"どの ほんを かいますか",
example_vi:"Bạn sẽ mua quyển sách nào?",
example_en:"Which book will you buy?"
},

{
level:"N5",
lesson:16,
id:42,
kanji:"どれ",
kana:"どれ",
hanviet:"",
vi:"cái nào (trong 3 cái trở lên)",
en:"which one",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<ruby>飲<rt>の</rt></ruby>み<ruby>物<rt>もの</rt></ruby>は <span class='target-word'>どれ</span>が いいですか。",
example_read:"のみものは どれが いいですか",
example_vi:"Bạn muốn chọn đồ uống nào?",
example_en:"Which drink would you like?"
},

{
level:"N5",
lesson:16,
id:43,
kanji:"凄いですね",
kana:"すごいですね",
hanviet:"THÊ",
vi:"thật là tuyệt / ghê quá",
en:"amazing / incredible",
word_type_vi:"Câu giao tiếp",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>三時間<rt>さんじかん</rt></ruby>も <ruby>勉強<rt>べんきょう</rt></ruby>するんですか。<span class='target-word'><ruby>凄<rt>すご</rt></ruby>いですね。</span>",
example_read:"まいにち さんじかんも べんきょうするんですか。すごいですね",
example_vi:"Ngày nào bạn cũng học đến 3 tiếng à? Giỏi thật đấy!",
example_en:"You study for three hours every day? That's amazing!"
},

{
level:"N5",
lesson:16,
id:44,
kanji:"まだまだです",
kana:"まだまだです",
hanviet:"",
vi:"tôi còn kém lắm",
en:"not yet good enough",
word_type_vi:"Câu giao tiếp",
word_type_en:"Expression",
category:"Minna 1",
example:"いいえ、<span class='target-word'><ruby>まだまだ<rt>まだまだ</rt></ruby>です。</span>",
example_read:"いいえ まだまだです",
example_vi:"Không đâu, tôi còn phải cố gắng nhiều.",
example_en:"No, I still have a long way to go."
},

{
level:"N5",
lesson:16,
id:45,
kanji:"お引き出しですか",
kana:"おひきだしですか",
hanviet:"DẪN XUẤT",
vi:"anh/chị rút tiền ạ?",
en:"Are you withdrawing money?",
word_type_vi:"Câu giao tiếp",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'><ruby>お引<rt>お</rt></ruby>き<ruby>出<rt>だ</rt></ruby>しですか。</span> キャッシュカードを <ruby>入<rt>い</rt></ruby>れてください。",
example_read:"おひきだしですか。キャッシュカードを いれてください",
example_vi:"Anh/chị rút tiền phải không ạ? Xin hãy đưa thẻ vào.",
example_en:"Are you making a withdrawal? Please insert your cash card."
},

{
level:"N5",
lesson:16,
id:46,
kanji:"まず",
kana:"まず",
hanviet:"",
vi:"trước hết",
en:"first of all",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>まず</span> <ruby>手<rt>て</rt></ruby>を <ruby>洗<rt>あら</rt></ruby>ってください。",
example_read:"まず てを あらってください",
example_vi:"Trước hết, hãy rửa tay.",
example_en:"First, please wash your hands."
},

{
level:"N5",
lesson:16,
id:47,
kanji:"次に",
kana:"つぎに",
hanviet:"THỨ",
vi:"tiếp theo",
en:"next",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>まず</ruby> カードを <ruby>入<rt>い</rt></ruby>れます。<span class='target-word'><ruby>次<rt>つぎ</rt></ruby>に</span> <ruby>暗証番号<rt>あんしょうばんごう</rt></ruby>を <ruby>入力<rt>にゅうりょく</rt></ruby>します。",
example_read:"まず カードを いれます。つぎに あんしょうばんごうを にゅうりょくします",
example_vi:"Trước hết cho thẻ vào. Tiếp theo nhập mã PIN.",
example_en:"First, insert the card. Next, enter your PIN."
},

{
level:"N5",
lesson:16,
id:48,
kanji:"キャッシュカード",
kana:"キャッシュカード",
hanviet:"",
vi:"thẻ ngân hàng, thẻ ATM",
en:"cash card / ATM card",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"ATMに <span class='target-word'>キャッシュカード</span>を <ruby>入<rt>い</rt></ruby>れます。",
example_read:"エーティーエムに キャッシュカードを いれます",
example_vi:"Tôi đút thẻ vào máy ATM.",
example_en:"I insert my ATM card into the ATM."
},
{
level:"N5",
lesson:16,
id:49,
kanji:"暗証番号",
kana:"あんしょうばんごう",
hanviet:"ÁM CHỨNG BẢNG HÀO",
vi:"mã số bí mật (mật khẩu)",
en:"PIN code",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>暗証番号<rt>あんしょうばんごう</rt></ruby></span>を <ruby>覚<rt>おぼ</rt></ruby>えていますか。",
example_read:"あんしょうばんごうを おぼえていますか",
example_vi:"Bạn có nhớ mã PIN không?",
example_en:"Do you remember your PIN?"
},
{
level:"N5",
lesson:16,
id:50,
kanji:"金額",
kana:"きんがく",
hanviet:"KIM NGẠCH",
vi:"số tiền, khoản tiền",
en:"amount of money",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>入力<rt>にゅうりょく</rt></ruby>した <span class='target-word'><ruby>金額<rt>きんがく</rt></ruby></span>を <ruby>確認<rt>かくにん</rt></ruby>してください。",
example_read:"にゅうりょくした きんがくを かくにんしてください",
example_vi:"Vui lòng kiểm tra số tiền đã nhập.",
example_en:"Please check the amount you entered."
},
{
level:"N5",
lesson:16,
id:51,
kanji:"確認",
kana:"かくにん",
hanviet:"XÁC NHẬN",
vi:"sự xác nhận, kiểm tra (~します: xác nhận)",
en:"confirmation / check",
word_type_vi:"Danh từ",
word_type_en:"Noun / suru-verb",
category:"Minna 1",
example:"<ruby>申込書<rt>もうしこみしょ</rt></ruby>の <ruby>内容<rt>ないよう</rt></ruby>を <span class='target-word'><ruby>確認<rt>かくにん</rt></ruby></span>します。",
example_read:"もうしこみしょの ないようを かくにんします",
example_vi:"Tôi sẽ kiểm tra nội dung của đơn đăng ký.",
example_en:"I'll check the contents of the application form."
},
{
level:"N5",
lesson:16,
id:52,
kanji:"ボタン",
kana:"ボタン",
hanviet:"",
vi:"nút bấm",
en:"button",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>確認<rt>かくにん</rt></ruby>の <span class='target-word'>ボタン</span>を <ruby>押<rt>お</rt></ruby>してください。",
example_read:"かくにんの ボタンを おしてください",
example_vi:"Vui lòng bấm nút Xác nhận.",
example_en:"Please press the Confirm button."
},

{
level:"N5",
lesson:16,
id:53,
kanji:"JR",
kana:"ジェイアール",
hanviet:"",
vi:"công ty đường sắt Nhật Bản",
en:"Japan Railways (JR)",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>JR<rt>ジェイアール</rt></ruby></span>で <ruby>東京<rt>とうきょう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ジェイアールで とうきょうへ いきます",
example_vi:"Tôi đi đến Tokyo bằng tàu JR.",
example_en:"I go to Tokyo by JR train."
},

{
level:"N5",
lesson:16,
id:54,
kanji:"雪祭",
kana:"ゆきまつり",
hanviet:"TUYẾT TẾ",
vi:"lễ hội tuyết",
en:"snow festival",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>冬休<rt>ふゆやす</rt></ruby>みに <span class='target-word'><ruby>雪祭<rt>ゆきまつり</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>に <ruby>札幌<rt>さっぽろ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ふゆやすみに ゆきまつりを みに さっぽろへ いきます",
example_vi:"Kỳ nghỉ đông tôi sẽ đến Sapporo để xem lễ hội tuyết.",
example_en:"I'm going to Sapporo during the winter vacation to see the Snow Festival."
},

{
level:"N5",
lesson:16,
id:55,
kanji:"バンドン",
kana:"バンドン",
hanviet:"",
vi:"Bandung (ở Indonesia)",
en:"Bandung",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>バンドン</ruby></span>は <ruby>インドネシア<rt>インドネシア</rt></ruby>の <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>都市<rt>とし</rt></ruby>です。",
example_read:"バンドンは インドネシアの ゆうめいな としです",
example_vi:"Bandung là một thành phố nổi tiếng của Indonesia.",
example_en:"Bandung is a famous city in Indonesia."
},

{
level:"N5",
lesson:16,
id:56,
kanji:"フランケン",
kana:"フランケン",
hanviet:"",
vi:"Franken (ở Đức)",
en:"Franken",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>フランケン</ruby></span>は <ruby>ドイツ<rt>ドイツ</rt></ruby>の <ruby>地域<rt>ちいき</rt></ruby>です。",
example_read:"フランケンは ドイツの ちいきです",
example_vi:"Franken là một vùng ở Đức.",
example_en:"Franconia is a region in Germany."
},

{
level:"N5",
lesson:16,
id:57,
kanji:"ベラクルス",
kana:"ベラクルス",
hanviet:"",
vi:"Veracruz (ở Mexico)",
en:"Veracruz",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>ベラクルス</ruby></span>は <ruby>メキシコ<rt>メキシコ</rt></ruby>の <ruby>都市<rt>とし</rt></ruby>です。",
example_read:"ベラクルスは メキシコの としです",
example_vi:"Veracruz là một thành phố ở Mexico.",
example_en:"Veracruz is a city in Mexico."
},

{
level:"N5",
lesson:16,
id:58,
kanji:"梅田",
kana:"うめだ",
hanviet:"MAI ĐIỀN",
vi:"quận Umeda (Osaka)",
en:"Umeda district",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>梅田<rt>うめだ</rt></ruby></span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>を します。",
example_read:"うめだで かいものを します",
example_vi:"Tôi đi mua sắm ở Umeda.",
example_en:"I go shopping in Umeda."
},

{
level:"N5",
lesson:16,
id:59,
kanji:"大学前",
kana:"だいがくまえ",
hanviet:"ĐẠI HỌC TIỀN",
vi:"trạm xe buýt Đại học (giả tưởng)",
en:"University-mae (bus stop)",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>大学前<rt>だいがくまえ</rt></ruby></span>まで バスで <ruby>行<rt>い</rt></ruby>きます。",
example_read:"だいがくまえまで バスで いきます",
example_vi:"Tôi đi xe buýt đến trạm Đại học.",
example_en:"I go to University-mae by bus."
}
];