window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[20] = [

{
level:"N5",
lesson:20,
id:1,
kanji:"要ります",
kana:"いります",
hanviet:"YẾU",
vi:"cần",
en:"need",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>くには <span class='target-word'><ruby>要<rt>い</rt></ruby>ります</span>ビザが <ruby>要<rt>い</rt></ruby>ります。",
example_read:"にほんへ いくには ビザが いります",
example_vi:"Để đến Nhật thì cần có visa.",
example_en:"You need a visa to go to Japan."
},

{
level:"N5",
lesson:20,
id:2,
kanji:"調べます",
kana:"しらべます",
hanviet:"ĐIỀU",
vi:"tìm hiểu, tra cứu",
en:"check, look up",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>分<rt>わ</rt></ruby>からない <ruby>言葉<rt>ことば</rt></ruby>を <span class='target-word'><ruby>調<rt>しら</rt></ruby>べます</span>。",
example_read:"わからない ことばを しらべます",
example_vi:"Tôi tra cứu những từ không biết.",
example_en:"I look up words I don't know."
},

{
level:"N5",
lesson:20,
id:3,
kanji:"修理します",
kana:"しゅうりします",
hanviet:"TU LÝ",
vi:"sửa chữa",
en:"repair, fix",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>壊<rt>こわ</rt></ruby>れた <ruby>自転車<rt>じてんしゃ</rt></ruby>を <span class='target-word'><ruby>修理<rt>しゅうり</rt></ruby>します</span>。",
example_read:"ちちは こわれた じてんしゃを しゅうりします",
example_vi:"Bố tôi sửa chiếc xe đạp bị hỏng.",
example_en:"My father repairs the broken bicycle."
},

{
level:"N5",
lesson:20,
id:4,
kanji:"僕",
kana:"ぼく",
hanviet:"BỘC",
vi:"tớ (nam giới)",
en:"I (used by males)",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'><ruby>僕<rt>ぼく</rt></ruby></span>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"ぼくは まいにち にほんごを べんきょうしています",
example_vi:"Tớ học tiếng Nhật mỗi ngày.",
example_en:"I study Japanese every day."
},

{
level:"N5",
lesson:20,
id:5,
kanji:"君",
kana:"きみ",
hanviet:"QUÂN",
vi:"cậu, bạn",
en:"you",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'><ruby>君<rt>きみ</rt></ruby></span>も <ruby>一緒<rt>いっしょ</rt></ruby>に <ruby>行<rt>い</rt></ruby>く？",
example_read:"きみも いっしょに いく",
example_vi:"Cậu cũng đi cùng chứ?",
example_en:"Are you coming too?"
},

{
level:"N5",
lesson:20,
id:6,
kanji:"～君",
kana:"～くん",
hanviet:"QUÂN",
vi:"cậu..., anh... (cách gọi thân mật nam giới)",
en:"Mr.~, ~kun",
word_type_vi:"Hậu tố",
word_type_en:"Suffix",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>は <span class='target-word'><ruby>田中<rt>たなか</rt></ruby>君</span>を <ruby>呼<rt>よ</rt></ruby>びました。",
example_read:"せんせいは たなかくんを よびました",
example_vi:"Thầy giáo gọi bạn Tanaka.",
example_en:"The teacher called Tanaka."
},

{
level:"N5",
lesson:20,
id:7,
kanji:"うん",
kana:"うん",
hanviet:"",
vi:"ừ",
en:"yeah",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"A：<ruby>明日<rt>あした</rt></ruby>も <ruby>来<rt>く</rt></ruby>る？<br>B：<span class='target-word'>うん</span>、<ruby>行<rt>い</rt></ruby>くよ。",
example_read:"あしたも くる うん いくよ",
example_vi:"A: Mai cậu cũng đến chứ? B: Ừ, mình sẽ đến.",
example_en:"A: Are you coming tomorrow too? B: Yeah, I am."
},

{
level:"N5",
lesson:20,
id:8,
kanji:"ううん",
kana:"ううん",
hanviet:"",
vi:"không",
en:"no",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"A：<ruby>忙<rt>いそが</rt></ruby>しい？<br>B：<span class='target-word'>ううん</span>、<ruby>大丈夫<rt>だいじょうぶ</rt></ruby>。",
example_read:"いそがしい ううん だいじょうぶ",
example_vi:"A: Cậu bận à? B: Không, không sao đâu.",
example_en:"A: Are you busy? B: No, I'm fine."
},

{
level:"N5",
lesson:20,
id:9,
kanji:"言葉",
kana:"ことば",
hanviet:"NGÔN DIỆP",
vi:"từ, ngôn ngữ, lời nói",
en:"word, language",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>の <span class='target-word'><ruby>言葉<rt>ことば</rt></ruby></span>が よく <ruby>分<rt>わ</rt></ruby>かりませんでした。",
example_read:"せんせいの ことばが よく わかりませんでした",
example_vi:"Tôi không hiểu rõ lời của giáo viên.",
example_en:"I couldn't understand the teacher's words very well."
},

{
level:"N5",
lesson:20,
id:10,
kanji:"着物",
kana:"きもの",
hanviet:"TRỨ VẬT",
vi:"kimono",
en:"kimono",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>祭<rt>まつ</rt></ruby>りで <span class='target-word'><ruby>着物<rt>きもの</rt></ruby></span>を <ruby>着<rt>き</rt></ruby>ました。",
example_read:"まつりで きものを きました",
example_vi:"Tôi đã mặc kimono tại lễ hội.",
example_en:"I wore a kimono at the festival."
},

{
level:"N5",
lesson:20,
id:11,
kanji:"ビザ",
kana:"ビザ",
hanviet:"",
vi:"visa, thị thực",
en:"visa",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>くために <span class='target-word'>ビザ</span>を <ruby>取<rt>と</rt></ruby>りました。",
example_read:"にほんへ いくために ビザを とりました",
example_vi:"Tôi đã xin visa để đi Nhật.",
example_en:"I obtained a visa to go to Japan."
},

{
level:"N5",
lesson:20,
id:12,
kanji:"始め",
kana:"はじめ",
hanviet:"THỦY",
vi:"ban đầu, lúc đầu",
en:"beginning, start",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>始<rt>はじ</rt></ruby>め</span>は <ruby>難<rt>むずか</rt></ruby>しかったですが、<ruby>今<rt>いま</rt></ruby>は <ruby>慣<rt>な</rt></ruby>れました。",
example_read:"はじめは むずかしかったですが いまは なれました",
example_vi:"Lúc đầu thì khó nhưng bây giờ tôi đã quen rồi.",
example_en:"It was difficult at first, but now I'm used to it."
},

{
level:"N5",
lesson:20,
id:13,
kanji:"終わり",
kana:"おわり",
hanviet:"CHUNG",
vi:"kết thúc",
en:"end",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>映画<rt>えいが</rt></ruby>の <span class='target-word'><ruby>終<rt>お</rt></ruby>わり</span>は とても <ruby>感動的<rt>かんどうてき</rt></ruby>でした。",
example_read:"えいがの おわりは とても かんどうてきでした",
example_vi:"Kết thúc của bộ phim rất cảm động.",
example_en:"The ending of the movie was very touching."
},

{
level:"N5",
lesson:20,
id:14,
kanji:"こっち",
kana:"こっち",
hanviet:"",
vi:"phía này, chỗ này",
en:"this way, here",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'>こっち</span>へ <ruby>来<rt>き</rt></ruby>てください。",
example_read:"こっちへ きてください",
example_vi:"Hãy đến phía này.",
example_en:"Please come this way."
},

{
level:"N5",
lesson:20,
id:15,
kanji:"そっち",
kana:"そっち",
hanviet:"",
vi:"phía đó, chỗ đó",
en:"that way, there",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'>そっち</span>は <ruby>危<rt>あぶ</rt></ruby>ないですよ。",
example_read:"そっちは あぶないですよ",
example_vi:"Phía đó nguy hiểm đấy.",
example_en:"It's dangerous over there."
},

{
level:"N5",
lesson:20,
id:16,
kanji:"あっち",
kana:"あっち",
hanviet:"",
vi:"phía kia, chỗ kia",
en:"over there",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'>あっち</span>に <ruby>富士山<rt>ふじさん</rt></ruby>が <ruby>見<rt>み</rt></ruby>えます。",
example_read:"あっちに ふじさんが みえます",
example_vi:"Có thể nhìn thấy núi Phú Sĩ ở phía kia.",
example_en:"You can see Mount Fuji over there."
},

{
level:"N5",
lesson:20,
id:17,
kanji:"どっち",
kana:"どっち",
hanviet:"",
vi:"cái nào, phía nào",
en:"which, which way",
word_type_vi:"Đại từ nghi vấn",
word_type_en:"Interrogative pronoun",
category:"Minna 1",
example:"この <ruby>二<rt>ふた</rt></ruby>つの <ruby>中<rt>なか</rt></ruby>で <span class='target-word'>どっち</span>が いいですか。",
example_read:"この ふたつの なかで どっちが いいですか",
example_vi:"Trong hai cái này, bạn thích cái nào hơn?",
example_en:"Which one do you prefer out of these two?"
},

{
level:"N5",
lesson:20,
id:18,
kanji:"皆んなで",
kana:"みんなで",
hanviet:"GIAI",
vi:"mọi người cùng",
en:"together with everyone",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>皆<rt>みん</rt></ruby>なで</span> <ruby>写真<rt>しゃしん</rt></ruby>を <ruby>撮<rt>と</rt></ruby>りましょう。",
example_read:"みんなで しゃしんを とりましょう",
example_vi:"Mọi người cùng chụp ảnh nhé.",
example_en:"Let's take a picture together."
},

{
level:"N5",
lesson:20,
id:19,
kanji:"～けど",
kana:"～けど",
hanviet:"",
vi:"nhưng",
en:"but",
word_type_vi:"Trợ từ / Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>忙<rt>いそが</rt></ruby>しい<span class='target-word'>けど</span>、<ruby>行<rt>い</rt></ruby>きます。",
example_read:"きょうは いそがしいけど いきます",
example_vi:"Hôm nay bận nhưng tôi vẫn đi.",
example_en:"I'm busy today, but I'll go."
},

{
level:"N5",
lesson:20,
id:20,
kanji:"お腹がいっぱいです",
kana:"おなかがいっぱいです",
hanviet:"PHÚC",
vi:"(Tôi) no rồi",
en:"I'm full",
word_type_vi:"Cụm câu",
word_type_en:"Phrase",
category:"Minna 1",
example:"<ruby>昼<rt>ひる</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を たくさん <ruby>食<rt>た</rt></ruby>べたので、<span class='target-word'>お<ruby>腹<rt>なか</rt></ruby>がいっぱいです</span>。",
example_read:"ひるごはんを たくさん たべたので おなかが いっぱいです",
example_vi:"Vì đã ăn rất nhiều vào bữa trưa nên tôi no rồi.",
example_en:"I ate a lot for lunch, so I'm full."
},

{
level:"N5",
lesson:20,
id:21,
kanji:"よかったら",
kana:"よかったら",
hanviet:"",
vi:"nếu bạn thích thì, nếu được thì",
en:"if you'd like",
word_type_vi:"Cụm từ",
word_type_en:"Phrase",
category:"Minna 1",
example:"<span class='target-word'>よかったら</span>、<ruby>一緒<rt>いっしょ</rt></ruby>に <ruby>昼<rt>ひる</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べませんか。",
example_read:"よかったら いっしょに ひるごはんを たべませんか",
example_vi:"Nếu bạn thích thì chúng ta cùng ăn trưa nhé.",
example_en:"If you'd like, shall we have lunch together?"
},

{
level:"N5",
lesson:20,
id:22,
kanji:"色々",
kana:"いろいろ",
hanviet:"SẮC SẮC",
vi:"nhiều thứ, nhiều loại",
en:"various, many things",
word_type_vi:"Danh từ / Trạng từ",
word_type_en:"Noun / Adverb",
category:"Minna 1",
example:"<ruby>旅行<rt>りょこう</rt></ruby>で <span class='target-word'><ruby>色々<rt>いろいろ</rt></ruby></span>な <ruby>経験<rt>けいけん</rt></ruby>を しました。",
example_read:"りょこうで いろいろな けいけんを しました",
example_vi:"Trong chuyến du lịch, tôi đã có nhiều trải nghiệm khác nhau.",
example_en:"I had various experiences during the trip."
}
];