window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[17] = [
  
{
level:"N5",
lesson:17,
id:1,
kanji:"覚えます",
kana:"おぼえます",
hanviet:"GIÁC",
vi:"nhớ",
en:"memorize, remember",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>の <ruby>電話番号<rt>でんわばんごう</rt></ruby>を <span class='target-word'><ruby>覚<rt>おぼ</rt></ruby>えています</span>。",
example_read:"ちちの でんわばんごうを おぼえています",
example_vi:"Tôi nhớ số điện thoại của bố.",
example_en:"I remember my father's phone number."
},
{
level:"N5",
lesson:17,
id:2,
kanji:"忘れます",
kana:"わすれます",
hanviet:"VONG",
vi:"quên",
en:"forget",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>時々<rt>ときどき</rt></ruby> <ruby>人<rt>ひと</rt></ruby>の <ruby>名前<rt>なまえ</rt></ruby>を <span class='target-word'><ruby>忘<rt>わす</rt></ruby>れます</span>。",
example_read:"ときどき ひとの なまえを わすれます",
example_vi:"Thỉnh thoảng tôi quên tên người khác.",
example_en:"I sometimes forget people's names."
},
{
level:"N5",
lesson:17,
id:3,
kanji:"無くします",
kana:"なくします",
hanviet:"VÔ",
vi:"làm mất, đánh mất",
en:"lose, misplace",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby> <ruby>財布<rt>さいふ</rt></ruby>を <span class='target-word'><ruby>無<rt>な</rt></ruby>くしました</span>。",
example_read:"きのう さいふを なくしました",
example_vi:"Hôm qua tôi đã làm mất ví.",
example_en:"I lost my wallet yesterday."
},

{
level:"N5",
lesson:17,
id:4,
kanji:"払います",
kana:"はらいます",
hanviet:"PHẤT",
vi:"trả tiền",
en:"pay",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>レストラン</ruby>で <ruby>食事代<rt>しょくじだい</rt></ruby>を <span class='target-word'><ruby>払<rt>はら</rt></ruby>いました</span>。",
example_read:"レストランで しょくじだいを はらいました",
example_vi:"Tôi đã trả tiền bữa ăn ở nhà hàng.",
example_en:"I paid for the meal at the restaurant."
},
{
level:"N5",
lesson:17,
id:5,
kanji:"返します",
kana:"かえします",
hanviet:"PHẢN",
vi:"trả lại",
en:"return",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>図書館<rt>としょかん</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>返<rt>かえ</rt></ruby>します</span>。",
example_read:"としょかんに ほんを かえします",
example_vi:"Tôi trả sách cho thư viện.",
example_en:"I return the book to the library."
},
{
level:"N5",
lesson:17,
id:6,
kanji:"出かけます",
kana:"でかけます",
hanviet:"XUẤT",
vi:"ra ngoài",
en:"go out",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>日曜日<rt>にちようび</rt></ruby>に <ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>出<rt>で</rt></ruby>かけます</span>。",
example_read:"にちようびに ともだちと でかけます",
example_vi:"Chủ nhật tôi đi chơi với bạn.",
example_en:"I'm going out with a friend on Sunday."
},
{
level:"N5",
lesson:17,
id:7,
kanji:"脱ぎます",
kana:"ぬぎます",
hanviet:"THOÁT",
vi:"cởi (quần áo)",
en:"take off (clothes)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>家<rt>いえ</rt></ruby>に <ruby>入<rt>はい</rt></ruby>る <ruby>前<rt>まえ</rt></ruby>に、<ruby>靴<rt>くつ</rt></ruby>を <span class='target-word'><ruby>脱<rt>ぬ</rt></ruby>ぎます</span>。",
example_read:"いえに はいる まえに くつを ぬぎます",
example_vi:"Trước khi vào nhà, tôi cởi giày.",
example_en:"I take off my shoes before entering the house."
},
{
level:"N5",
lesson:17,
id:8,
kanji:"持って行きます",
kana:"もっていきます",
hanviet:"TRÌ HÀNH",
vi:"mang đi, mang theo",
en:"take (something) with you",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Compound verb",
category:"Minna 1",
example:"<ruby>学校<rt>がっこう</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>持<rt>も</rt></ruby>って<ruby>行<rt>い</rt></ruby>きます</span>。",
example_read:"がっこうに ほんを もっていきます",
example_vi:"Tôi mang sách đi đến trường.",
example_en:"I take my books to school."
},
{
level:"N5",
lesson:17,
id:9,
kanji:"持って来ます",
kana:"もってきます",
hanviet:"TRÌ LAI",
vi:"mang đến",
en:"bring",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Compound verb",
category:"Minna 1",
example:"<ruby>冷<rt>つめ</rt></ruby>たい <ruby>水<rt>みず</rt></ruby>を <span class='target-word'><ruby>持<rt>も</rt></ruby>って<ruby>来<rt>き</rt></ruby>ます</span>。",
example_read:"つめたい みずを もってきます",
example_vi:"Tôi mang nước lạnh đến.",
example_en:"I'll bring some cold water."
},
{
level:"N5",
lesson:17,
id:10,
kanji:"心配します",
kana:"しんぱいします",
hanviet:"TÂM PHỐI",
vi:"lo lắng",
en:"worry",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>は <ruby>私<rt>わたし</rt></ruby>のことを <span class='target-word'><ruby>心配<rt>しんぱい</rt></ruby></span>しています。",
example_read:"ははは わたしのことを しんぱいしています",
example_vi:"Mẹ luôn lo lắng cho tôi.",
example_en:"My mother is worried about me."
},
{
level:"N5",
lesson:17,
id:11,
kanji:"残業します",
kana:"ざんぎょうします",
hanviet:"TÀN NGHIỆP",
vi:"làm thêm giờ",
en:"work overtime",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>毎週<rt>まいしゅう</rt></ruby> <ruby>金曜日<rt>きんようび</rt></ruby>は <span class='target-word'><ruby>残業<rt>ざんぎょう</rt></ruby>します</span>。",
example_read:"まいしゅう きんようびは ざんぎょうします",
example_vi:"Mỗi thứ Sáu tôi đều làm thêm giờ.",
example_en:"I work overtime every Friday."
},
{
level:"N5",
lesson:17,
id:12,
kanji:"出張します",
kana:"しゅっちょうします",
hanviet:"XUẤT TRƯƠNG",
vi:"đi công tác",
en:"go on a business trip",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>来週<rt>らいしゅう</rt></ruby> <ruby>大阪<rt>おおさか</rt></ruby>へ <span class='target-word'><ruby>出張<rt>しゅっちょう</rt></ruby>します</span>。",
example_read:"らいしゅう おおさかへ しゅっちょうします",
example_vi:"Tuần sau tôi sẽ đi công tác đến Osaka.",
example_en:"I'm going on a business trip to Osaka next week."
},

{
level:"N5",
lesson:17,
id:13,
kanji:"飲みます",
kana:"のみます",
hanviet:"ẨM",
vi:"uống (thuốc)",
en:"take (medicine)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>食後<rt>しょくご</rt></ruby>に <ruby>薬<rt>くすり</rt></ruby>を <span class='target-word'><ruby>飲<rt>の</rt></ruby>みます</span>。",
example_read:"しょくごに くすりを のみます",
example_vi:"Tôi uống thuốc sau bữa ăn.",
example_en:"I take medicine after meals."
},
{
level:"N5",
lesson:17,
id:14,
kanji:"入ります",
kana:"はいります",
hanviet:"NHẬP",
vi:"vào (bồn tắm)",
en:"enter (bath)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>毎晩<rt>まいばん</rt></ruby> <ruby>お風呂<rt>おふろ</rt></ruby>に <span class='target-word'><ruby>入<rt>はい</rt></ruby>ります</span>。",
example_read:"まいばん おふろに はいります",
example_vi:"Tối nào tôi cũng tắm bồn.",
example_en:"I take a bath every night."
},
{
level:"N5",
lesson:17,
id:15,
kanji:"大切[な]",
kana:"たいせつ[な]",
hanviet:"ĐẠI THIẾT",
vi:"quan trọng, quý giá",
en:"important / precious",
word_type_vi:"Tính từ na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"これは <span class='target-word'><ruby>大切<rt>たいせつ</rt></ruby>な</span> <ruby>書類<rt>しょるい</rt></ruby>です。",
example_read:"これは たいせつな しょるいです",
example_vi:"Đây là một tài liệu quan trọng.",
example_en:"This is an important document."
},
{
level:"N5",
lesson:17,
id:16,
kanji:"大丈夫[な]",
kana:"だいじょうぶ[な]",
hanviet:"ĐẠI TRƯỢNG PHU",
vi:"không sao, ổn",
en:"okay / safe / fine",
word_type_vi:"Tính từ na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>大丈夫<rt>だいじょうぶ</rt></ruby></span>です。<ruby>心配<rt>しんぱい</rt></ruby>しないでください。",
example_read:"だいじょうぶです。しんぱいしないでください",
example_vi:"Tôi không sao đâu. Đừng lo nhé.",
example_en:"I'm okay. Please don't worry."
},
{
level:"N5",
lesson:17,
id:17,
kanji:"危ない",
kana:"あぶない",
hanviet:"NGUY",
vi:"nguy hiểm",
en:"dangerous",
word_type_vi:"Tính từ i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"ここは <span class='target-word'><ruby>危<rt>あぶ</rt></ruby>ない</span>です。",
example_read:"ここは あぶないです",
example_vi:"Chỗ này nguy hiểm.",
example_en:"This place is dangerous."
},
{
level:"N5",
lesson:17,
id:18,
kanji:"禁煙",
kana:"きんえん",
hanviet:"CẤM YÊN",
vi:"cấm hút thuốc",
en:"no smoking",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"このレストランは <span class='target-word'><ruby>禁煙<rt>きんえん</rt></ruby></span>です。",
example_read:"この みせは きんえんです",
example_vi:"Cửa hàng này cấm hút thuốc.",
example_en:"This restaurant is non-smoking."
},
{
level:"N5",
lesson:17,
id:19,
kanji:"健康保険証",
kana:"けんこうほけんしょう",
hanviet:"KIỆN KHANG BẢO HIỂN CHỨNG",
vi:"thẻ bảo hiểm y tế",
en:"health insurance card",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>受付<rt>うけつけ</rt></ruby>で <span class='target-word'><ruby>健康保険証<rt>けんこうほけんしょう</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>せます。",
example_read:"うけつけで けんこうほけんしょうを みせます",
example_vi:"Tôi xuất trình thẻ bảo hiểm y tế ở quầy tiếp tân.",
example_en:"I show my health insurance card at the reception desk."
},
{
level:"N5",
lesson:17,
id:20,
kanji:"熱",
kana:"ねつ",
hanviet:"NHIỆT",
vi:"sốt",
en:"fever",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby>から <span class='target-word'><ruby>熱<rt>ねつ</rt></ruby></span>が あります。",
example_read:"きのうから ねつが あります",
example_vi:"Tôi bị sốt từ hôm qua.",
example_en:"I've had a fever since yesterday."
},
{
level:"N5",
lesson:17,
id:21,
kanji:"病気",
kana:"びょうき",
hanviet:"BỆNH KHÍ",
vi:"bệnh",
en:"illness",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>先週<rt>せんしゅう</rt></ruby> <span class='target-word'><ruby>病気<rt>びょうき</rt></ruby></span>に なりました。",
example_read:"せんしゅう びょうきに なりました",
example_vi:"Tuần trước tôi đã bị bệnh.",
example_en:"I got sick last week."
},
{
level:"N5",
lesson:17,
id:22,
kanji:"薬",
kana:"くすり",
hanviet:"DƯỢC",
vi:"thuốc",
en:"medicine",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>風邪<rt>かぜ</rt></ruby>なので、<span class='target-word'><ruby>薬<rt>くすり</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"かぜなので、くすりを のみます",
example_vi:"Vì bị cảm nên tôi uống thuốc.",
example_en:"I take medicine because I have a cold."
},
{
level:"N5",
lesson:17,
id:23,
kanji:"お風呂",
kana:"おふろ",
hanviet:"PHONG LỮ",
vi:"bồn tắm",
en:"bath",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>の <ruby>後<rt>あと</rt></ruby>に <span class='target-word'><ruby>お風呂<rt>おふろ</rt></ruby></span>に <ruby>入<rt>はい</rt></ruby>ります。",
example_read:"しごとの あとに おふろに はいります",
example_vi:"Sau giờ làm tôi tắm bồn.",
example_en:"I take a bath after work."
},
{
level:"N5",
lesson:17,
id:24,
kanji:"上着",
kana:"うわぎ",
hanviet:"THƯỢNG TRỨ",
vi:"áo khoác",
en:"jacket",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>寒<rt>さむ</rt></ruby>いので、<span class='target-word'><ruby>上着<rt>うわぎ</rt></ruby></span>を <ruby>着<rt>き</rt></ruby>ます。",
example_read:"さむいので、うわぎを きます",
example_vi:"Vì trời lạnh nên tôi mặc áo khoác.",
example_en:"I put on a jacket because it's cold."
},
{
level:"N5",
lesson:17,
id:25,
kanji:"下着",
kana:"したぎ",
hanviet:"HẠ TRỨ",
vi:"đồ lót",
en:"underwear",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>新<rt>あたら</rt></ruby>しい <span class='target-word'><ruby>下着<rt>したぎ</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"あたらしい したぎを かいました",
example_vi:"Tôi đã mua đồ lót mới.",
example_en:"I bought new underwear."
},
{
level:"N5",
lesson:17,
id:26,
kanji:"二、三日",
kana:"に、さんにち",
hanviet:"NHỊ TAM NHẬT",
vi:"2–3 ngày",
en:"2–3 days",
word_type_vi:"Danh từ",
word_type_en:"Time expression",
category:"Minna 1",
example:"<ruby>風邪<rt>かぜ</rt></ruby>なので、<span class='target-word'><ruby>二、三日<rt>にさんにち</rt></ruby></span> <ruby>会社<rt>かいしゃ</rt></ruby>を <ruby>休<rt>やす</rt></ruby>みます。",
example_read:"かぜなので、にさんにち かいしゃを やすみます",
example_vi:"Vì bị cảm nên tôi sẽ nghỉ làm khoảng hai, ba ngày.",
example_en:"Because I have a cold, I'll take two or three days off work."
},

{
level:"N5",
lesson:17,
id:27,
kanji:"２，３～",
kana:"２，３～",
hanviet:"",
vi:"vài ~ (hậu tố đếm)",
en:"a few ~",
word_type_vi:"Hậu tố",
word_type_en:"Counter suffix",
category:"Minna 1",
example:"<span class='target-word'>２、３<ruby>分<rt>ぷん</rt></ruby></span> <ruby>待<rt>ま</rt></ruby>ってください。",
example_read:"にさんぷん まってください",
example_vi:"Xin vui lòng đợi khoảng 2–3 phút.",
example_en:"Please wait for two or three minutes."
},
{
level:"N5",
lesson:17,
id:28,
kanji:"～までに",
kana:"～までに",
hanviet:"",
vi:"trước ~ (hạn chót)",
en:"by (deadline)",
word_type_vi:"Trợ từ / cụm cố định",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>金曜日<rt>きんようび</rt></ruby> <span class='target-word'>までに</span> レポートを <ruby>出<rt>だ</rt></ruby>します。",
example_read:"きんようび までに れぽーとを だします",
example_vi:"Tôi sẽ nộp báo cáo trước thứ Sáu.",
example_en:"I'll submit the report by Friday."
},
{
level:"N5",
lesson:17,
id:29,
kanji:"ですから",
kana:"ですから",
hanviet:"",
vi:"vì thế, do đó",
en:"therefore, so",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby>は <ruby>試験<rt>しけん</rt></ruby> <span class='target-word'>ですから</span>、<ruby>今日<rt>きょう</rt></ruby>は <ruby>早<rt>はや</rt></ruby>く <ruby>寝<rt>ね</rt></ruby>ます。",
example_read:"あしたは しけんですから、きょうは はやく ねます",
example_vi:"Vì ngày mai có bài kiểm tra nên hôm nay tôi đi ngủ sớm.",
example_en:"Because I have a test tomorrow, I'll go to bed early today."
},
{
level:"N5",
lesson:17,
id:30,
kanji:"どうしましたか",
kana:"どうしましたか",
hanviet:"",
vi:"Bạn bị làm sao vậy?",
en:"What happened?",
word_type_vi:"Câu hỏi",
word_type_en:"Question",
category:"Minna 1",
example:"<ruby>顔色<rt>かおいろ</rt></ruby>が <ruby>悪<rt>わる</rt></ruby>いですね。<span class='target-word'>どうしましたか。</span>",
example_read:"かおいろが わるいですね。どうしましたか",
example_vi:"Sắc mặt bạn không được tốt. Có chuyện gì vậy?",
example_en:"You look pale. What's wrong?"
},
{
level:"N5",
lesson:17,
id:31,
kanji:"喉",
kana:"のど",
hanviet:"HẦU",
vi:"cổ họng",
en:"throat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>風邪<rt>かぜ</rt></ruby>で <span class='target-word'><ruby>喉<rt>のど</rt></ruby></span>が <ruby>痛<rt>いた</rt></ruby>いです。",
example_read:"かぜで のどが いたいです",
example_vi:"Vì bị cảm nên tôi bị đau họng.",
example_en:"I have a sore throat because I have a cold."
},
{
level:"N5",
lesson:17,
id:32,
kanji:"[～が]痛いです",
kana:"[～が]いたいです",
hanviet:"THỐNG",
vi:"bị đau ~",
en:"hurt, ache",
word_type_vi:"Cấu trúc",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby>から <span class='target-word'><ruby>歯<rt>は</rt></ruby>が <ruby>痛<rt>いた</rt></ruby>いです</span>。",
example_read:"あさから はが いたいです",
example_vi:"Tôi bị đau răng từ sáng đến giờ.",
example_en:"My tooth has been hurting since this morning."
},
{
level:"N5",
lesson:17,
id:33,
kanji:"風邪",
kana:"かぜ",
hanviet:"PHONG TÀ",
vi:"cảm, cúm",
en:"cold",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>風邪<rt>かぜ</rt></ruby></span>を <ruby>引<rt>ひ</rt></ruby>いたので、<ruby>学校<rt>がっこう</rt></ruby>を <ruby>休<rt>やす</rt></ruby>みます。",
example_read:"かぜを ひいたので、がっこうを やすみます",
example_vi:"Vì bị cảm nên tôi nghỉ học.",
example_en:"I'm taking the day off from school because I caught a cold."
},
{
level:"N5",
lesson:17,
id:34,
kanji:"それから",
kana:"それから",
hanviet:"",
vi:"và sau đó",
en:"and then",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby><ruby>ご飯<rt>ごはん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。<span class='target-word'>それから</span> <ruby>学校<rt>がっこう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"あさごはんを たべます。それから がっこうへ いきます",
example_vi:"Tôi ăn sáng. Sau đó tôi đi học.",
example_en:"I eat breakfast. Then I go to school."
},
{
level:"N5",
lesson:17,
id:35,
kanji:"お大事に",
kana:"おだいじに",
hanviet:"",
vi:"chúc mau khỏe",
en:"get well soon",
word_type_vi:"Câu chúc",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>無理<rt>むり</rt></ruby>を しないでください。<span class='target-word'>お<ruby>大事<rt>だいじ</rt></ruby>に。</span>",
example_read:"むりを しないでください。おだいじに",
example_vi:"Đừng cố quá nhé. Chúc bạn mau khỏe.",
example_en:"Don't push yourself too hard. Take care."
}
];