window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[8] = [

{
level:"N5",
lesson:8,
id:1,
kanji:"ハンサム[な]",
kana:"ハンサム[な]",
hanviet:"",
vi:"đẹp trai",
en:"handsome",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"あの <span class='target-word'>ハンサムな</span> <ruby>生徒<rt>せいと</rt></ruby>は クラスで <ruby>一番<rt>いちばん</rt></ruby> <ruby>人気<rt>にんき</rt></ruby>です。",
example_read:"あの はんさむな せいとは くらすで いちばん にんきです。",
example_vi:"Cậu học sinh đẹp trai đó là người được yêu thích nhất trong lớp.",
example_en:"That handsome student is the most popular student in the class."
},

{
level:"N5",
lesson:8,
id:2,
kanji:"綺麗[な]",
kana:"きれい[な]",
hanviet:"KHỈ LỆ",
vi:"đẹp, sạch",
en:"beautiful, clean",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この <ruby>部屋<rt>へや</rt></ruby>は <span class='target-word'><ruby>綺麗<rt>きれい</rt></ruby>です</span>。",
example_read:"この へやは きれいです。",
example_vi:"Căn phòng này sạch đẹp.",
example_en:"This room is clean and beautiful."
},

{
level:"N5",
lesson:8,
id:3,
kanji:"静か[な]",
kana:"しずか[な]",
hanviet:"TĨNH",
vi:"yên tĩnh",
en:"quiet",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この <ruby>図書館<rt>としょかん</rt></ruby>は とても <span class='target-word'><ruby>静<rt>しず</rt></ruby>かです</span>。",
example_read:"この としょかんは とても しずかです。",
example_vi:"Thư viện này rất yên tĩnh.",
example_en:"This library is very quiet."
},

{
level:"N5",
lesson:8,
id:4,
kanji:"賑やか[な]",
kana:"にぎやか[な]",
hanviet:"CHẨN",
vi:"náo nhiệt",
en:"lively, bustling",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この <ruby>町<rt>まち</rt></ruby>は いつも <span class='target-word'><ruby>賑<rt>にぎ</rt></ruby>やかです</span>。",
example_read:"この まちは いつも にぎやかです。",
example_vi:"Thành phố này lúc nào cũng náo nhiệt.",
example_en:"This city is always lively."
},

{
level:"N5",
lesson:8,
id:5,
kanji:"有名[な]",
kana:"ゆうめい[な]",
hanviet:"HỮU DANH",
vi:"nổi tiếng",
en:"famous",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>富士山<rt>ふじさん</rt></ruby>は <span class='target-word'><ruby>有名<rt>ゆうめい</rt></ruby>な</span> <ruby>山<rt>やま</rt></ruby>です。",
example_read:"ふじさんは ゆうめいな やまです。",
example_vi:"Núi Phú Sĩ là ngọn núi nổi tiếng.",
example_en:"Mount Fuji is a famous mountain."
},

{
level:"N5",
lesson:8,
id:6,
kanji:"親切[な]",
kana:"しんせつ[な]",
hanviet:"THÂN THIẾT",
vi:"tốt bụng, thân thiện",
en:"kind",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"その <ruby>先生<rt>せんせい</rt></ruby>は とても <span class='target-word'><ruby>親切<rt>しんせつ</rt></ruby>です</span>。",
example_read:"その せんせいは とても しんせつです。",
example_vi:"Người giáo viên đó rất tốt bụng.",
example_en:"That teacher is very kind."
},

{
level:"N5",
lesson:8,
id:7,
kanji:"元気[な]",
kana:"げんき[な]",
hanviet:"NGUYÊN KHÍ",
vi:"khỏe",
en:"healthy, energetic",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>今日<rt>きょう</rt></ruby> とても <span class='target-word'><ruby>元気<rt>げんき</rt></ruby>です</span>。",
example_read:"わたしは きょう とても げんきです。",
example_vi:"Hôm nay tôi rất khỏe.",
example_en:"I am very energetic today."
},

{
level:"N5",
lesson:8,
id:8,
kanji:"暇[な]",
kana:"ひま[な]",
hanviet:"HẠ",
vi:"rảnh rỗi",
en:"free (time)",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>暇<rt>ひま</rt></ruby>です</span>。",
example_read:"きょうは ひまです。",
example_vi:"Hôm nay tôi rảnh.",
example_en:"I am free today."
},

{
level:"N5",
lesson:8,
id:9,
kanji:"便利[な]",
kana:"べんり[な]",
hanviet:"TIỆN LỢI",
vi:"tiện lợi",
en:"convenient",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この アプリは とても <span class='target-word'>便利です</span>。",
example_read:"この あぷりは とても べんりです。",
example_vi:"Ứng dụng này rất tiện lợi.",
example_en:"This app is very convenient."
},

{
level:"N5",
lesson:8,
id:10,
kanji:"素敵[な]",
kana:"すてき[な]",
hanviet:"TỐ ĐỊCH",
vi:"đẹp, hay, tuyệt vời",
en:"lovely, wonderful",
word_type_vi:"Tính từ - na",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"その <ruby>服<rt>ふく</rt></ruby>は とても <span class='target-word'><ruby>素敵<rt>すてき</rt></ruby>ですね</span>。",
example_read:"その ふくは とても すてきですね。",
example_vi:"Bộ quần áo đó thật tuyệt vời.",
example_en:"That outfit is really wonderful."
},

{
level:"N5",
lesson:8,
id:11,
kanji:"大きい",
kana:"おおきい",
hanviet:"ĐẠI",
vi:"lớn, to",
en:"big",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>家<rt>いえ</rt></ruby>は <span class='target-word'><ruby>大<rt>おお</rt></ruby>きいです</span>。",
example_read:"この いえは おおきいです。",
example_vi:"Ngôi nhà này rất lớn.",
example_en:"This house is big."
},

{
level:"N5",
lesson:8,
id:12,
kanji:"小さい",
kana:"ちいさい",
hanviet:"TIỂU",
vi:"bé, nhỏ",
en:"small",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"その <ruby>犬<rt>いぬ</rt></ruby>は <span class='target-word'><ruby>小<rt>ちい</rt></ruby>さいです</span>。",
example_read:"その いぬは ちいさいです。",
example_vi:"Con chó đó nhỏ.",
example_en:"That dog is small."
},

{
level:"N5",
lesson:8,
id:13,
kanji:"新しい",
kana:"あたらしい",
hanviet:"TÂN",
vi:"mới",
en:"new",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>新<rt>あたら</rt></ruby>しい</span>かばんを <ruby>買<rt>か</rt></ruby>いました。",
example_read:"わたしは あたらしい かばんを かいました。",
example_vi:"Tôi đã mua một cái cặp mới.",
example_en:"I bought a new bag."
},

{
level:"N5",
lesson:8,
id:14,
kanji:"古い",
kana:"ふるい",
hanviet:"CỔ",
vi:"cũ",
en:"old",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>本<rt>ほん</rt></ruby>は とても <span class='target-word'><ruby>古<rt>ふる</rt></ruby>いです</span>。",
example_read:"この ほんは とても ふるいです。",
example_vi:"Cuốn sách này rất cũ.",
example_en:"This book is very old."
},

{
level:"N5",
lesson:8,
id:15,
kanji:"いい/良い",
kana:"いい/よい",
hanviet:"LƯƠNG",
vi:"tốt",
en:"good",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'>いい</span> <ruby>天気<rt>てんき</rt></ruby>です。",
example_read:"きょうは いい てんきです。",
example_vi:"Hôm nay thời tiết đẹp.",
example_en:"It's nice weather today."
},

{
level:"N5",
lesson:8,
id:16,
kanji:"悪い",
kana:"わるい",
hanviet:"ÁC",
vi:"xấu, tệ",
en:"bad",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"きょうは <ruby>天気<rt>てんき</rt></ruby>が <span class='target-word'><ruby>悪<rt>わる</rt></ruby>いです</span>から、<ruby>家<rt>いえ</rt></ruby>に います。",
example_read:"きょうは てんきが わるいですから、いえに います。",
example_vi:"Vì thời tiết hôm nay xấu nên tôi ở nhà.",
example_en:"Because the weather is bad today, I stay at home."
},

{
level:"N5",
lesson:8,
id:17,
kanji:"暑い",
kana:"あつい",
hanviet:"THỬ",
vi:"nóng (thời tiết)",
en:"hot (weather)",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は とても <span class='target-word'><ruby>暑<rt>あつ</rt></ruby>いです</span>から、<ruby>冷<rt>つめ</rt></ruby>たい <ruby>飲<rt>の</rt></ruby>み<ruby>物<rt>もの</rt></ruby>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"きょうは とても あついですから、つめたい のみものを のみます。",
example_vi:"Hôm nay rất nóng nên tôi uống đồ uống lạnh.",
example_en:"It is very hot today, so I drink a cold beverage."
},

{
level:"N5",
lesson:8,
id:18,
kanji:"寒い",
kana:"さむい",
hanviet:"HÀN",
vi:"lạnh (thời tiết)",
en:"cold (weather)",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>の <ruby>冬<rt>ふゆ</rt></ruby>は とても <span class='target-word'><ruby>寒<rt>さむ</rt></ruby>いです</span>。",
example_read:"にほんの ふゆは とても さむいです。",
example_vi:"Mùa đông ở Nhật Bản rất lạnh.",
example_en:"Winter in Japan is very cold."
},

{
level:"N5",
lesson:8,
id:19,
kanji:"冷たい",
kana:"つめたい",
hanviet:"LÃNH",
vi:"lạnh (cảm giác)",
en:"cold (touch)",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>冷蔵庫<rt>れいぞうこ</rt></ruby>から <ruby>出<rt>だ</rt></ruby>した この <ruby>水<rt>みず</rt></ruby>は <span class='target-word'><ruby>冷<rt>つめ</rt></ruby>たいです</span>。",
example_read:"れいぞうこから だした この みずは つめたいです。",
example_vi:"Nước này vừa lấy từ tủ lạnh ra nên rất lạnh.",
example_en:"This water is cold because it was taken out of the refrigerator."
},

{
level:"N5",
lesson:8,
id:20,
kanji:"難しい",
kana:"むずかしい",
hanviet:"NAN",
vi:"khó",
en:"difficult",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>漢字<rt>かんじ</rt></ruby>の <ruby>問題<rt>もんだい</rt></ruby>は とても <span class='target-word'><ruby>難<rt>むずか</rt></ruby>しいです</span>。",
example_read:"この かんじの もんだいは とても むずかしいです。",
example_vi:"Bài tập Kanji này rất khó.",
example_en:"This Kanji exercise is very difficult."
},

{
level:"N5",
lesson:8,
id:21,
kanji:"易しい",
kana:"やさしい",
hanviet:"DỊCH",
vi:"dễ",
en:"easy",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この テストは <span class='target-word'>易しいです</span>。",
example_read:"この てすとは やさしいです。",
example_vi:"Bài kiểm tra này dễ.",
example_en:"This test is easy."
},

{
level:"N5",
lesson:8,
id:22,
kanji:"高い",
kana:"たかい",
hanviet:"CAO",
vi:"cao, đắt",
en:"high, expensive",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この ビルは <span class='target-word'>高いです</span>。",
example_read:"この びるは たかいです。",
example_vi:"Tòa nhà này cao.",
example_en:"This building is tall."
},

{
level:"N5",
lesson:8,
id:23,
kanji:"安い",
kana:"やすい",
hanviet:"AN",
vi:"rẻ",
en:"cheap",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>本<rt>ほん</rt></ruby>は <ruby>三百円<rt>さんびゃくえん</rt></ruby>です。とても <span class='target-word'><ruby>安<rt>やす</rt></ruby>いです</span>。",
example_read:"この ほんは さんびゃくえんです。とても やすいです。",
example_vi:"Cuốn sách này giá 300 yên. Nó rất rẻ.",
example_en:"This book costs 300 yen. It is very cheap."
},

{
level:"N5",
lesson:8,
id:24,
kanji:"低い",
kana:"ひくい",
hanviet:"ĐÊ",
vi:"thấp",
en:"low",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>椅子<rt>いす</rt></ruby>は <span class='target-word'><ruby>低<rt>ひく</rt></ruby>いです</span>から、<ruby>座<rt>すわ</rt></ruby>りやすいです。",
example_read:"この いすは ひくいですから、すわりやすいです。",
example_vi:"Cái ghế này thấp nên dễ ngồi.",
example_en:"This chair is low, so it is easy to sit on."
},

{
level:"N5",
lesson:8,
id:25,
kanji:"面白い",
kana:"おもしろい",
hanviet:"DIỆN BẠCH",
vi:"thú vị, hay",
en:"interesting",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>漫画<rt>まんが</rt></ruby>は とても <span class='target-word'><ruby>面白<rt>おもしろ</rt></ruby>いです</span>。",
example_read:"この まんがは とても おもしろいです。",
example_vi:"Bộ truyện tranh này rất thú vị.",
example_en:"This manga is very interesting."
},

{
level:"N5",
lesson:8,
id:26,
kanji:"美味しい",
kana:"おいしい",
hanviet:"MỸ VỊ",
vi:"ngon",
en:"delicious",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>が <ruby>作<rt>つく</rt></ruby>った <ruby>料理<rt>りょうり</rt></ruby>は <span class='target-word'><ruby>美味<rt>おい</rt></ruby>しいです</span>。",
example_read:"ははが つくった りょうりは おいしいです。",
example_vi:"Món ăn mẹ nấu rất ngon.",
example_en:"The food my mother cooked is delicious."
},

{
level:"N5",
lesson:8,
id:27,
kanji:"忙しい",
kana:"いそがしい",
hanviet:"MANG",
vi:"bận",
en:"busy",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>仕事<rt>しごと</rt></ruby>が たくさん ありますから、<span class='target-word'><ruby>忙<rt>いそが</rt></ruby>しいです</span>。",
example_read:"きょうは しごとが たくさん ありますから、いそがしいです。",
example_vi:"Hôm nay có nhiều việc nên tôi bận.",
example_en:"I am busy today because I have a lot of work to do."
},

{
level:"N5",
lesson:8,
id:28,
kanji:"楽しい",
kana:"たのしい",
hanviet:"LẠC",
vi:"vui",
en:"fun",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby>の パーティーは とても <span class='target-word'><ruby>楽<rt>たの</rt></ruby>しかったです</span>。",
example_read:"きのうの ぱーてぃーは とても たのしかったです。",
example_vi:"Bữa tiệc hôm qua rất vui.",
example_en:"The party yesterday was very enjoyable."
},

{
level:"N5",
lesson:8,
id:29,
kanji:"白い",
kana:"しろい",
hanviet:"BẠCH",
vi:"trắng",
en:"white",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>猫<rt>ねこ</rt></ruby>は <span class='target-word'><ruby>白<rt>しろ</rt></ruby>くて</span> かわいいです。",
example_read:"この ねこは しろくて かわいいです。",
example_vi:"Con mèo này trắng và rất dễ thương.",
example_en:"This cat is white and cute."
},

{
level:"N5",
lesson:8,
id:30,
kanji:"黒い",
kana:"くろい",
hanviet:"HẮC",
vi:"đen",
en:"black",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>黒<rt>くろ</rt></ruby>い <ruby>靴<rt>くつ</rt></ruby>は とても かっこいいです。",
example_read:"この くろい くつは とても かっこいいです。",
example_vi:"Đôi giày màu đen này rất ngầu.",
example_en:"These black shoes are very cool."
},

{
level:"N5",
lesson:8,
id:31,
kanji:"赤い",
kana:"あかい",
hanviet:"XÍCH",
vi:"đỏ",
en:"red",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"あの <ruby>赤<rt>あか</rt></ruby>い <ruby>車<rt>くるま</rt></ruby>は <ruby>父<rt>ちち</rt></ruby>のです。",
example_read:"あの あかい くるまは ちちのです。",
example_vi:"Chiếc xe màu đỏ kia là của bố tôi.",
example_en:"That red car belongs to my father."
},

{
level:"N5",
lesson:8,
id:32,
kanji:"青い",
kana:"あおい",
hanviet:"THANH",
vi:"xanh dương",
en:"blue",
word_type_vi:"Tính từ - i",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>天気<rt>てんき</rt></ruby>が よくて、<ruby>空<rt>そら</rt></ruby>が とても <span class='target-word'><ruby>青<rt>あお</rt></ruby>いです</span>。",
example_read:"きょうは てんきが よくて、そらが とても あおいです。",
example_vi:"Hôm nay thời tiết đẹp nên bầu trời rất xanh.",
example_en:"The weather is nice today, so the sky is very blue."
},

{
level:"N5",
lesson:8,
id:33,
kanji:"桜",
kana:"さくら",
hanviet:"ANH",
vi:"hoa anh đào",
en:"cherry blossom",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>春<rt>はる</rt></ruby>になると、<ruby>公園<rt>こうえん</rt></ruby>の <span class='target-word'><ruby>桜<rt>さくら</rt></ruby></span>が きれいに <ruby>咲<rt>さ</rt></ruby>きます。",
example_read:"はるになると、こうえんの さくらが きれいに さきます。",
example_vi:"Khi mùa xuân đến, hoa anh đào trong công viên nở rất đẹp.",
example_en:"When spring comes, the cherry blossoms in the park bloom beautifully."
},

{
level:"N5",
lesson:8,
id:34,
kanji:"山",
kana:"やま",
hanviet:"SAN/SƠN",
vi:"núi",
en:"mountain",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"あの <span class='target-word'><ruby>山<rt>やま</rt></ruby></span>は とても <ruby>高<rt>たか</rt></ruby>いです。",
example_read:"あの やまは とても たかいです。",
example_vi:"Ngọn núi kia rất cao.",
example_en:"That mountain is very tall."
},

{
level:"N5",
lesson:8,
id:35,
kanji:"町",
kana:"まち",
hanviet:"ĐINH",
vi:"thị trấn",
en:"town",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>町<rt>まち</rt></ruby></span>は <ruby>店<rt>みせ</rt></ruby>が たくさん あって、とても にぎやかです。",
example_read:"この まちは みせが たくさん あって、とても にぎやかです。",
example_vi:"Thị trấn này có rất nhiều cửa hàng nên rất náo nhiệt.",
example_en:"This town has many shops, so it is very lively."
},

{
level:"N5",
lesson:8,
id:36,
kanji:"食べ物",
kana:"たべもの",
hanviet:"THỰC VẬT",
vi:"đồ ăn",
en:"food",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この レストランの <span class='target-word'><ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby></span>は とても おいしいので、よく <ruby>行<rt>い</rt></ruby>きます。",
example_read:"この れすとらんの たべものは とても おいしいので、よく いきます。",
example_vi:"Đồ ăn ở nhà hàng này rất ngon nên tôi thường đến đây.",
example_en:"The food at this restaurant is very delicious, so I often go there."
},

{
level:"N5",
lesson:8,
id:37,
kanji:"所",
kana:"ところ",
hanviet:"SỞ",
vi:"nơi, chỗ",
en:"place",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"ここは <ruby>静<rt>しず</rt></ruby>かで、いい <span class='target-word'><ruby>所<rt>ところ</rt></ruby></span>ですね。",
example_read:"ここは しずかで、いい ところですね。",
example_vi:"Nơi này yên tĩnh, thật là một nơi tuyệt vời.",
example_en:"This place is quiet and nice."
},

{
level:"N5",
lesson:8,
id:38,
kanji:"寮",
kana:"りょう",
hanviet:"LIÊU",
vi:"ký túc xá",
en:"dormitory",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>寮<rt>りょう</rt></ruby></span>に <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"わたしは りょうに すんでいます。",
example_vi:"Tôi sống trong ký túc xá.",
example_en:"I live in a dormitory."
},

{
level:"N5",
lesson:8,
id:39,
kanji:"レストラン",
kana:"レストラン",
hanviet:"",
vi:"nhà hàng",
en:"restaurant",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'>レストラン</span>は <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"この れすとらんは ゆうめいです。",
example_vi:"Nhà hàng này nổi tiếng.",
example_en:"This restaurant is famous."
},

{
level:"N5",
lesson:8,
id:40,
kanji:"生活",
kana:"せいかつ",
hanviet:"SINH HOẠT",
vi:"cuộc sống, sinh hoạt",
en:"life, living",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>の <span class='target-word'><ruby>生活<rt>せいかつ</rt></ruby></span>は <ruby>便利<rt>べんり</rt></ruby>です。",
example_read:"にほんの せいかつは べんりです。",
example_vi:"Cuộc sống ở Nhật rất tiện lợi.",
example_en:"Life in Japan is convenient."
},

{
level:"N5",
lesson:8,
id:41,
kanji:"[お]仕事",
kana:"[お]しごと",
hanviet:"SĨ SỰ",
vi:"công việc",
en:"job, work",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>最近<rt>さいきん</rt></ruby>の <span class='target-word'><ruby>お仕事<rt>おしごと</rt></ruby></span>は どうですか。",
example_read:"さいきんのおしごとは どうですか。",
example_vi:"Công việc dạo này của bạn thế nào?",
example_en:"How has your work been recently?"
},

{
level:"N5",
lesson:8,
id:42,
kanji:"どう",
kana:"どう",
hanviet:"",
vi:"thế nào",
en:"how",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この ケーキは <span class='target-word'>どう</span>ですか。",
example_read:"この けーきは どうですか。",
example_vi:"Cái bánh này thế nào?",
example_en:"How is this cake?"
},

{
level:"N5",
lesson:8,
id:43,
kanji:"どんな",
kana:"どんな",
hanviet:"",
vi:"như thế nào",
en:"what kind of",
word_type_vi:"Từ hỏi",
word_type_en:"Question word",
category:"Minna 1",
example:"あなたは <span class='target-word'>どんな</span> <ruby>本<rt>ほん</rt></ruby>が <ruby>好き<rt>すき</rt></ruby>ですか。",
example_read:"あなたは どんな ほんが すきですか。",
example_vi:"Bạn thích loại sách nào?",
example_en:"What kind of books do you like?"
},

{
level:"N5",
lesson:8,
id:44,
kanji:"とても",
kana:"とても",
hanviet:"",
vi:"rất",
en:"very",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この <ruby>店<rt>みせ</rt></ruby>は <span class='target-word'>とても</span> <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"この みせは とても ゆうめいです。",
example_vi:"Cửa hàng này rất nổi tiếng.",
example_en:"This shop is very famous."
},

{
level:"N5",
lesson:8,
id:45,
kanji:"あまり",
kana:"あまり",
hanviet:"",
vi:"không… lắm",
en:"not very",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この <ruby>本<rt>ほん</rt></ruby>は <span class='target-word'>あまり</span> <ruby>面白<rt>おもしろ</rt></ruby>くないです。",
example_read:"この ほんは あまり おもしろくないです。",
example_vi:"Cuốn sách này không thú vị lắm.",
example_en:"This book is not very interesting."
},

{
level:"N5",
lesson:8,
id:46,
kanji:"そして",
kana:"そして",
hanviet:"",
vi:"và, rồi",
en:"and then",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>晩<rt>ばん</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べました。<span class='target-word'>そして</span> <ruby>勉強<rt>べんきょう</rt></ruby>しました。",
example_read:"わたしは ばんごはんを たべました。 そして べんきょうしました。",
example_vi:"Tôi đã ăn cơm tối. Sau đó tôi học bài.",
example_en:"I had dinner and then studied."
},

{
level:"N5",
lesson:8,
id:47,
kanji:"～が、～",
kana:"～が、～",
hanviet:"",
vi:"~, nhưng ~",
en:"but",
word_type_vi:"Cấu trúc",
word_type_en:"Grammar pattern",
category:"Minna 1",
example:"この <ruby>部屋<rt>へや</rt></ruby>は <ruby>広<rt>ひろ</rt></ruby>いです<span class='target-word'>が</span>、すこし <ruby>暗<rt>くら</rt></ruby>いです。",
example_read:"この へやは ひろいですが、すこし くらいです。",
example_vi:"Căn phòng này rộng nhưng hơi tối.",
example_en:"This room is spacious but a little dark."
},

{
level:"N5",
lesson:8,
id:48,
kanji:"お元気ですか",
kana:"おげんきですか",
hanviet:"NGUYÊN KHÍ",
vi:"Bạn có khỏe không?",
en:"How are you?",
word_type_vi:"Câu giao tiếp",
word_type_en:"Fixed expression",
category:"Minna 1",
example:"A: <span class='target-word'><ruby>お元気<rt>おげんき</rt></ruby>ですか</span>。<br>B: はい、<ruby>元気<rt>げんき</rt></ruby>です。",
example_read:"おげんきですか。はい、げんきです。",
example_vi:"A: Bạn có khỏe không? B: Vâng, tôi khỏe.",
example_en:"A: How are you? B: I'm fine."
},

{
level:"N5",
lesson:8,
id:49,
kanji:"そうですね",
kana:"そうですね",
hanviet:"",
vi:"Thế à / Như vậy à",
en:"Hmm / Well…",
word_type_vi:"Câu phản ứng",
word_type_en:"Interjection",
category:"Minna 1",
example:"A: この <ruby>映画<rt>えいが</rt></ruby>は <span class='target-word'><ruby>面白<rt>おもしろ</rt></ruby>いですか</span>。<br>B: <span class='target-word'>そうですね</span>、おもしろいですが ちょっと <ruby>長<rt>なが</rt></ruby>いです。",
example_read:"この えいがは おもしろいですか。そうですね、おもしろいですが ちょっと ながいです。",
example_vi:"A: Bộ phim này có hay không? B: Thế à / Ừm, thú vị nhưng hơi dài một chút.",
example_en:"A: Is this movie interesting? B: Hmm / Well… it's interesting but a bit long."
},

{
level:"N5",
lesson:8,
id:50,
kanji:"[~]もう一杯いかがですか",
kana:"[~]もういっぱいいかがですか",
hanviet:"NHẤT BÔI",
vi:"Bạn dùng thêm một ly/chén [~] nữa không?",
en:"Would you like another [~] drink?",
word_type_vi:"Câu mời",
word_type_en:"Polite offer",
category:"Minna 1",
example:"コーヒーを <span class='target-word'>もう<ruby>一杯<rt>いっぱい</rt></ruby>いかがですか</span>。",
example_read:"こーひーを もういっぱいいかがですか。",
example_vi:"Bạn dùng thêm một ly cà phê nữa không?",
example_en:"Would you like another cup of coffee?"
},

{
level:"N5",
lesson:8,
id:51,
kanji:"いいえ,結構です",
kana:"いいえ,けっこうです",
hanviet:"KẾT CẤU",
vi:"đủ rồi / không cần",
en:"no, thank you (enough)",
word_type_vi:"Câu từ chối lịch sự",
word_type_en:"Polite refusal",
category:"Minna 1",
example:"A: もう<ruby>一杯<rt>いっぱい</rt></ruby>いかがですか。<br>B: <span class='target-word'>いいえ、<ruby>結構<rt>けっこう</rt></ruby>です</span>。",
example_read:"もういっぱい いかがですか。いいえ、けっこうです。",
example_vi:"A: Bạn dùng thêm một ly nữa không? B: Không, đủ rồi ạ.",
example_en:"A: Would you like another drink? B: No, thank you."
},

{
level:"N5",
lesson:8,
id:52,
kanji:"もう～です[ね]",
kana:"もう～です[ね]",
hanviet:"",
vi:"Đã ~ rồi nhỉ./ Đã ~ rồi, đúng không ạ?",
en:"Already ~, right?",
word_type_vi:"Cấu trúc",
word_type_en:"Grammar pattern",
category:"Minna 1",
example:"A: <ruby>もう<rt>もう</rt></ruby> <span class='target-word'><ruby>晩<rt>ばん</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>ですね</span>。<br>B: そうですね、そろそろ <ruby>食<rt>た</rt></ruby>べましょうか。",
example_read:"もう ばんごはんですね。そうですね、そろそろ たべましょうか。",
example_vi:"A: Đã đến bữa tối rồi nhỉ. B: Ừ nhỉ, chắc chuẩn bị ăn thôi.",
example_en:"A: It's already dinner time. B: Yeah, maybe we should eat soon."
},

{
level:"N5",
lesson:8,
id:53,
kanji:"そろそろ失礼します",
kana:"そろそろしつれいします",
hanviet:"THẤT LỄ",
vi:"Tôi xin phép về",
en:"I should be leaving now",
word_type_vi:"Câu lịch sự",
word_type_en:"Fixed expression",
category:"Minna 1",
example:"A: もうこんな<ruby>時間<rt>じかん</rt></ruby>ですね。<br>B: <span class='target-word'><ruby>そうですね</ruby></span>。そろそろ <ruby>失礼<rt>しつれい</rt></ruby>します。",
example_read:"もう こんな じかんですね。そうですね。そろそろ しつれいします。",
example_vi:"A: Đã muộn thế này rồi nhỉ. B: Ừ nhỉ, tôi xin phép về trước ạ.",
example_en:"A: It's already this late, isn't it? B: Yeah, I should get going now."
},

{
level:"N5",
lesson:8,
id:54,
kanji:"いいえ",
kana:"いいえ",
hanviet:"",
vi:"không / không có gì",
en:"no / you're welcome",
word_type_vi:"Câu đáp",
word_type_en:"Response",
category:"Minna 1",
example:"A: ありがとうございます。<br>B: <span class='target-word'><ruby>いいえ</ruby></span>、どういたしまして。",
example_read:"ありがとうございます。いいえ、どういたしまして。",
example_vi:"A: Cảm ơn bạn rất nhiều. B: Không có gì ạ.",
example_en:"A: Thank you very much. B: Not at all, you're welcome."
},

{
level:"N5",
lesson:8,
id:55,
kanji:"またいらっしゃってください",
kana:"またいらっしゃってください",
hanviet:"",
vi:"Lần sau lại đến nhé",
en:"Please come again",
word_type_vi:"Câu mời",
word_type_en:"Polite invitation",
category:"Minna 1",
example:"ぜひ <span class='target-word'><ruby>また<rt>また</rt></ruby><ruby>いらっしゃってください</ruby></span>。",
example_read:"ぜひ またいらっしゃってください。",
example_vi:"Nhất định lần sau hãy quay lại nhé.",
example_en:"Please do come again."
},

{
level:"N5",
lesson:8,
id:56,
kanji:"上海",
kana:"しゃんはい",
hanviet:"THƯỢNG HẢI",
vi:"Thượng Hải",
en:"Shanghai",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>先週<rt>せんしゅう</rt></ruby></span> <ruby>上海<rt>しゃんはい</rt></ruby>に <ruby>行<rt>い</rt></ruby>きました。",
example_read:"わたしは せんしゅう しゃんはいに いきました。",
example_vi:"Tuần trước tôi đã đi Thượng Hải.",
example_en:"I went to Shanghai last week."
},

{
level:"N5",
lesson:8,
id:57,
kanji:"金閣寺",
kana:"きんかくじ",
hanviet:"KIM CÁC TỰ",
vi:"Chùa Kinkakuji",
en:"Kinkakuji Temple",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>京都<rt>きょうと</rt></ruby>で <span class='target-word'><ruby>金閣寺<rt>きんかくじ</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>ました。",
example_read:"きょうとで きんかくじを みました。",
example_vi:"Tôi đã tham quan chùa Kinkakuji ở Kyoto.",
example_en:"I visited Kinkakuji Temple in Kyoto."
},

{
level:"N5",
lesson:8,
id:58,
kanji:"奈良公園",
kana:"ならこうえん",
hanviet:"NẠI LƯƠNG CÔNG VIÊN",
vi:"Công viên Nara",
en:"Nara Park",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>奈良公園<rt>ならこうえん</rt></ruby>で <span class='target-word'><ruby>鹿<rt>しか</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>ました。",
example_read:"ならこうえんで しかを みました。",
example_vi:"Tôi đã thấy hươu ở Công viên Nara.",
example_en:"I saw deer at Nara Park."
},

{
level:"N5",
lesson:8,
id:59,
kanji:"富士山",
kana:"ふじさん",
hanviet:"PHÚ SĨ SƠN",
vi:"Núi Phú Sĩ",
en:"Mount Fuji",
word_type_vi:"Danh từ",
word_type_en:"Proper noun",
category:"Minna 1",
example_context:"いつか <ruby>富士山<rt>ふじさん</rt></ruby>に <ruby>登<rt>のぼ</rt></ruby>ってみたいです。",
example_context_read:"いつか ふじさんに のぼってみたいです。",
example_context_vi:"Một ngày nào đó, tôi muốn thử leo núi Phú Sĩ.",
example_context_en:"I want to climb Mount Fuji someday."
},

{
level:"N5",
lesson:8,
id:60,
kanji:"七人の侍",
kana:"しちにんのさむらい",
hanviet:"THẤT NHÂN THỊ",
vi:"Bảy võ sĩ Samurai",
en:"Seven Samurai",
word_type_vi:"Danh từ",
word_type_en:"Movie title",
category:"Minna 1",
example:"<span class='target-word'><ruby>七人の侍<rt>しちにんのさむらい</rt></ruby></span>は <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>映画<rt>えいが</rt></ruby>です。",
example_read:"しちにんのさむらいは ゆうめいな えいがです。",
example_vi:"Bộ phim Bảy Võ Sĩ Samurai rất nổi tiếng.",
example_en:"Seven Samurai is a famous movie."
}
];