window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[22] = [

{
level:"N5",
lesson:22,
id:1,
kanji:"着ます",
kana:"きます",
hanviet:"TRỨ",
vi:"mặc (áo, váy...)",
en:"wear (clothes)",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>寒<rt>さむ</rt></ruby>いので、コートを <span class='target-word'><ruby>着<rt>き</rt></ruby>ます</span>。",
example_read:"きょうは さむいので コートを きます",
example_vi:"Hôm nay trời lạnh nên tôi mặc áo khoác.",
example_en:"It's cold today, so I'm wearing a coat."
},

{
level:"N5",
lesson:22,
id:2,
kanji:"履きます",
kana:"はきます",
hanviet:"LÝ",
vi:"mặc, đi (quần, giày...)",
en:"wear (pants, shoes)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>黒<rt>くろ</rt></ruby>い <ruby>靴<rt>くつ</rt></ruby>を <span class='target-word'><ruby>履<rt>は</rt></ruby>きます</span>。",
example_read:"まいにち くろい くつを はきます",
example_vi:"Mỗi ngày tôi đi đôi giày màu đen.",
example_en:"I wear black shoes every day."
},

{
level:"N5",
lesson:22,
id:3,
kanji:"被ります",
kana:"かぶります",
hanviet:"BỊ",
vi:"đội (mũ)",
en:"wear (a hat)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>夏<rt>なつ</rt></ruby>は <ruby>帽子<rt>ぼうし</rt></ruby>を <span class='target-word'><ruby>被<rt>かぶ</rt></ruby>ります</span>。",
example_read:"なつは ぼうしを かぶります",
example_vi:"Mùa hè tôi đội mũ.",
example_en:"I wear a hat in summer."
},

{
level:"N5",
lesson:22,
id:4,
kanji:"掛けます",
kana:"かけます",
hanviet:"QUẢI",
vi:"đeo (kính)",
en:"wear (glasses)",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>本<rt>ほん</rt></ruby>を <ruby>読<rt>よ</rt></ruby>むとき、<ruby>眼鏡<rt>めがね</rt></ruby>を <span class='target-word'><ruby>掛<rt>か</rt></ruby>けます</span>。",
example_read:"ちちは ほんを よむとき めがねを かけます",
example_vi:"Bố tôi đeo kính khi đọc sách.",
example_en:"My father wears glasses when he reads."
},

{
level:"N5",
lesson:22,
id:5,
kanji:"します",
kana:"します",
hanviet:"",
vi:"đeo (cà vạt)",
en:"wear (a tie)",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>くとき、ネクタイを <span class='target-word'>します</span>。",
example_read:"かいしゃへ いくとき ネクタイを します",
example_vi:"Khi đi làm tôi đeo cà vạt.",
example_en:"I wear a tie when I go to work."
},

{
level:"N5",
lesson:22,
id:6,
kanji:"生まれます",
kana:"うまれます",
hanviet:"SINH",
vi:"được sinh ra",
en:"be born",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は ベトナムで <span class='target-word'><ruby>生<rt>う</rt></ruby>まれました</span>。",
example_read:"わたしは ベトナムで うまれました",
example_vi:"Tôi sinh ra ở Việt Nam.",
example_en:"I was born in Vietnam."
},

{
level:"N5",
lesson:22,
id:7,
kanji:"私達",
kana:"わたしたち",
hanviet:"TƯ ĐẠT",
vi:"chúng tôi, chúng ta",
en:"we",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'><ruby>私達<rt>わたしたち</rt></ruby></span>は <ruby>一緒<rt>いっしょ</rt></ruby>に <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"わたしたちは いっしょに べんきょうします",
example_vi:"Chúng tôi học cùng nhau.",
example_en:"We study together."
},

{
level:"N5",
lesson:22,
id:8,
kanji:"コート",
kana:"コート",
hanviet:"",
vi:"áo khoác",
en:"coat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>冬<rt>ふゆ</rt></ruby>は <span class='target-word'>コート</span>を <ruby>着<rt>き</rt></ruby>ます。",
example_read:"ふゆは コートを きます",
example_vi:"Mùa đông tôi mặc áo khoác.",
example_en:"I wear a coat in winter."
},

{
level:"N5",
lesson:22,
id:9,
kanji:"セーター",
kana:"セーター",
hanviet:"",
vi:"áo len",
en:"sweater",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>が <span class='target-word'>セーター</span>を <ruby>買<rt>か</rt></ruby>ってくれました。",
example_read:"ははが セーターを かってくれました",
example_vi:"Mẹ đã mua cho tôi một chiếc áo len.",
example_en:"My mother bought me a sweater."
},

{
level:"N5",
lesson:22,
id:10,
kanji:"スーツ",
kana:"スーツ",
hanviet:"",
vi:"com-lê",
en:"suit",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>毎日<rt>まいにち</rt></ruby> <span class='target-word'>スーツ</span>を <ruby>着<rt>き</rt></ruby>て <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ちちは まいにち スーツを きて かいしゃへ いきます",
example_vi:"Bố tôi mặc com-lê đi làm mỗi ngày.",
example_en:"My father wears a suit to work every day."
},

{
level:"N5",
lesson:22,
id:11,
kanji:"帽子",
kana:"ぼうし",
hanviet:"MẠO TỬ",
vi:"mũ",
en:"hat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日差<rt>ひざ</rt></ruby>しが <ruby>強<rt>つよ</rt></ruby>いので、<span class='target-word'><ruby>帽子<rt>ぼうし</rt></ruby></span>を <ruby>被<rt>かぶ</rt></ruby>ります。",
example_read:"ひざしが つよいので ぼうしを かぶります",
example_vi:"Vì nắng gắt nên tôi đội mũ.",
example_en:"I wear a hat because the sun is strong."
},

{
level:"N5",
lesson:22,
id:12,
kanji:"眼鏡",
kana:"めがね",
hanviet:"NHÃN KÍNH",
vi:"kính",
en:"glasses",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>本<rt>ほん</rt></ruby>を <ruby>読<rt>よ</rt></ruby>むとき、<span class='target-word'><ruby>眼鏡<rt>めがね</rt></ruby></span>を <ruby>掛<rt>か</rt></ruby>けます。",
example_read:"ほんを よむとき めがねを かけます",
example_vi:"Tôi đeo kính khi đọc sách.",
example_en:"I wear glasses when I read."
},

{
level:"N5",
lesson:22,
id:13,
kanji:"ケーキ",
kana:"ケーキ",
hanviet:"",
vi:"bánh ngọt",
en:"cake",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>誕生日<rt>たんじょうび</rt></ruby>に <span class='target-word'>ケーキ</span>を <ruby>食<rt>た</rt></ruby>べました。",
example_read:"たんじょうびに ケーキを たべました",
example_vi:"Tôi đã ăn bánh sinh nhật vào ngày sinh nhật.",
example_en:"I ate cake on my birthday."
},

{
level:"N5",
lesson:22,
id:14,
kanji:"お弁当",
kana:"おべんとう",
hanviet:"BIỆN ĐƯƠNG",
vi:"cơm hộp",
en:"boxed lunch",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <span class='target-word'><ruby>お弁当<rt>おべんとう</rt></ruby></span>を <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>持<rt>も</rt></ruby>って <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいにち おべんとうを かいしゃへ もって いきます",
example_vi:"Mỗi ngày tôi mang cơm hộp đến công ty.",
example_en:"I take a boxed lunch to work every day."
},

{
level:"N5",
lesson:22,
id:15,
kanji:"ロボット",
kana:"ロボット",
hanviet:"",
vi:"rô-bốt",
en:"robot",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'>ロボット</span>は <ruby>話<rt>はな</rt></ruby>すことが <ruby>出来<rt>でき</rt></ruby>ます。",
example_read:"この ロボットは はなすことが できます",
example_vi:"Con rô-bốt này có thể nói chuyện.",
example_en:"This robot can talk."
},

{
level:"N5",
lesson:22,
id:16,
kanji:"ユーモア",
kana:"ユーモア",
hanviet:"",
vi:"sự hài hước",
en:"humor",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>彼<rt>かれ</rt></ruby>は <span class='target-word'>ユーモア</span>が あって <ruby>人気<rt>にんき</rt></ruby>です。",
example_read:"かれは ユーモアが あって にんきです",
example_vi:"Anh ấy có khiếu hài hước nên rất được yêu mến.",
example_en:"He has a good sense of humor, so he's popular."
},

{
level:"N5",
lesson:22,
id:17,
kanji:"都合",
kana:"つごう",
hanviet:"ĐÔ HỢP",
vi:"sự thuận tiện, phù hợp",
en:"convenience",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby>は <span class='target-word'><ruby>都合<rt>つごう</rt></ruby></span>が いいですか。",
example_read:"あしたは つごうが いいですか",
example_vi:"Ngày mai bạn có thuận tiện không?",
example_en:"Is tomorrow convenient for you?"
},

{
level:"N5",
lesson:22,
id:18,
kanji:"よく",
kana:"よく",
hanviet:"",
vi:"thường, hay",
en:"often",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>よく</span> この <ruby>店<rt>みせ</rt></ruby>へ <ruby>来<rt>き</rt></ruby>ます。",
example_read:"わたしは よく この みせへ きます",
example_vi:"Tôi thường đến cửa hàng này.",
example_en:"I often come to this shop."
},

{
level:"N5",
lesson:22,
id:19,
kanji:"えーと",
kana:"えーと",
hanviet:"",
vi:"ờ..., à...",
en:"well..., let me see...",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>えーと</span>、<ruby>名前<rt>なまえ</rt></ruby>を <ruby>思<rt>おも</rt></ruby>い<ruby>出<rt>だ</rt></ruby>せません。",
example_read:"えーと なまえを おもいだせません",
example_vi:"Ờ..., tôi không nhớ ra tên.",
example_en:"Well..., I can't remember the name."
},

{
level:"N5",
lesson:22,
id:20,
kanji:"おめでとうございます",
kana:"おめでとうございます",
hanviet:"",
vi:"chúc mừng",
en:"Congratulations!",
word_type_vi:"Câu cảm thán",
word_type_en:"Phrase",
category:"Minna 1",
example:"<ruby>卒業<rt>そつぎょう</rt></ruby>、<span class='target-word'>おめでとうございます</span>！",
example_read:"そつぎょう おめでとうございます",
example_vi:"Chúc mừng bạn tốt nghiệp!",
example_en:"Congratulations on your graduation!"
},

{
level:"N5",
lesson:22,
id:21,
kanji:"お探しですか",
kana:"おさがしですか",
hanviet:"",
vi:"Anh/chị đang tìm ~ phải không?",
en:"Are you looking for ~?",
word_type_vi:"Mẫu câu",
word_type_en:"Phrase",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>探<rt>さが</rt></ruby>しですか</span>。",
example_read:"おさがしですか",
example_vi:"Anh/chị đang tìm gì phải không?",
example_en:"Are you looking for something?"
},

{
level:"N5",
lesson:22,
id:22,
kanji:"では",
kana:"では",
hanviet:"",
vi:"vậy thì, thế thì",
en:"well then",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<span class='target-word'>では</span>、<ruby>始<rt>はじ</rt></ruby>めましょう。",
example_read:"では はじめましょう",
example_vi:"Vậy thì chúng ta bắt đầu nhé.",
example_en:"Well then, let's begin."
},

{
level:"N5",
lesson:22,
id:23,
kanji:"こちら",
kana:"こちら",
hanviet:"",
vi:"cái này, phía này",
en:"this one",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"<span class='target-word'>こちら</span>は <ruby>新<rt>あたら</rt></ruby>しい <ruby>商品<rt>しょうひん</rt></ruby>です。",
example_read:"こちらは あたらしい しょうひんです",
example_vi:"Đây là sản phẩm mới.",
example_en:"This is our new product."
},

{
level:"N5",
lesson:22,
id:24,
kanji:"家賃",
kana:"やちん",
hanviet:"GIA TIỀN",
vi:"tiền thuê nhà",
en:"rent",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>家賃<rt>やちん</rt></ruby></span>は <ruby>毎月<rt>まいつき</rt></ruby> <ruby>払<rt>はら</rt></ruby>います。",
example_read:"やちんは まいつき はらいます",
example_vi:"Tôi trả tiền thuê nhà mỗi tháng.",
example_en:"I pay the rent every month."
},

{
level:"N5",
lesson:22,
id:25,
kanji:"ダイニングキッチン",
kana:"ダイニングキッチン",
hanviet:"",
vi:"bếp kèm phòng ăn",
en:"dining kitchen",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'>ダイニングキッチン</span>は <ruby>広<rt>ひろ</rt></ruby>いです。",
example_read:"この ダイニングキッチンは ひろいです",
example_vi:"Phòng bếp kết hợp phòng ăn này rất rộng.",
example_en:"This dining kitchen is spacious."
},

{
level:"N5",
lesson:22,
id:26,
kanji:"和室",
kana:"わしつ",
hanviet:"HÒA THẤT",
vi:"phòng kiểu Nhật",
en:"Japanese-style room",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>和室<rt>わしつ</rt></ruby></span>は とても <ruby>静<rt>しず</rt></ruby>かです。",
example_read:"この わしつは とても しずかです",
example_vi:"Căn phòng kiểu Nhật này rất yên tĩnh.",
example_en:"This Japanese-style room is very quiet."
},

{
level:"N5",
lesson:22,
id:27,
kanji:"押し入れ",
kana:"おしいれ",
hanviet:"",
vi:"tủ để chăn đệm trong phòng kiểu Nhật",
en:"built-in closet",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>布団<rt>ふとん</rt></ruby>は <span class='target-word'><ruby>押<rt>お</rt></ruby>し<ruby>入<rt>い</rt></ruby>れ</span>に <ruby>入<rt>い</rt></ruby>れます。",
example_read:"ふとんは おしいれに いれます",
example_vi:"Tôi cất chăn đệm vào tủ âm tường kiểu Nhật.",
example_en:"I put the futon in the built-in closet."
},

{
level:"N5",
lesson:22,
id:28,
kanji:"布団",
kana:"ふとん",
hanviet:"BỐ ĐOÀN",
vi:"chăn đệm kiểu Nhật",
en:"futon",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夜<rt>よる</rt></ruby>は <span class='target-word'><ruby>布団<rt>ふとん</rt></ruby></span>で <ruby>寝<rt>ね</rt></ruby>ます。",
example_read:"よるは ふとんで ねます",
example_vi:"Ban đêm tôi ngủ trên nệm futon.",
example_en:"I sleep on a futon at night."
},

{
level:"N5",
lesson:22,
id:29,
kanji:"パリ",
kana:"パリ",
hanviet:"",
vi:"Paris",
en:"Paris",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>パリ</span>へ <ruby>旅行<rt>りょこう</rt></ruby>したいです。",
example_read:"パリへ りょこうしたいです",
example_vi:"Tôi muốn đi du lịch Paris.",
example_en:"I want to travel to Paris."
},

{
level:"N5",
lesson:22,
id:30,
kanji:"万里の長城",
kana:"ばんりのちょうじょう",
hanviet:"VẠN LÝ TRƯỜNG THÀNH",
vi:"Vạn Lý Trường Thành",
en:"the Great Wall of China",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>万里<rt>ばんり</rt></ruby>の<ruby>長城<rt>ちょうじょう</rt></ruby></span>は とても <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"ばんりのちょうじょうは とても ゆうめいです",
example_vi:"Vạn Lý Trường Thành rất nổi tiếng.",
example_en:"The Great Wall of China is very famous."
},

{
level:"N5",
lesson:22,
id:31,
kanji:"みんなのアンケート",
kana:"みんなのアンケート",
hanviet:"",
vi:"Khảo sát của mọi người",
en:"Everyone's Survey",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>みんなのアンケート</span>を <ruby>読<rt>よ</rt></ruby>んで、<ruby>結果<rt>けっか</rt></ruby>を <ruby>確認<rt>かくにん</rt></ruby>しました。",
example_read:"みんなの アンケートを よんで けっかを かくにんしました",
example_vi:"Tôi đã đọc bảng khảo sát của mọi người và xem kết quả.",
example_en:"I read everyone's survey and checked the results."
}
];