window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[21] = [

{
level:"N5",
lesson:21,
id:1,
kanji:"思います",
kana:"おもいます",
hanviet:"TƯ",
vi:"nghĩ",
en:"think",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は この <ruby>映画<rt>えいが</rt></ruby>は とても <ruby>面白<rt>おもしろ</rt></ruby>いと <span class='target-word'><ruby>思<rt>おも</rt></ruby>います</span>。",
example_read:"わたしは この えいがは とても おもしろいと おもいます",
example_vi:"Tôi nghĩ bộ phim này rất thú vị.",
example_en:"I think this movie is very interesting."
},

{
level:"N5",
lesson:21,
id:2,
kanji:"言います",
kana:"いいます",
hanviet:"NGÔN",
vi:"nói",
en:"say",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>は <ruby>学生<rt>がくせい</rt></ruby>に <ruby>大切<rt>たいせつ</rt></ruby>なことを <span class='target-word'><ruby>言<rt>い</rt></ruby>います</span>。",
example_read:"せんせいは がくせいに たいせつなことを いいます",
example_vi:"Giáo viên nói với học sinh một điều quan trọng.",
example_en:"The teacher tells the students something important."
},

{
level:"N5",
lesson:21,
id:3,
kanji:"勝ちます",
kana:"かちます",
hanviet:"THẮNG",
vi:"thắng",
en:"win",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>たちの チームは <ruby>試合<rt>しあい</rt></ruby>に <span class='target-word'><ruby>勝<rt>か</rt></ruby>ちます</span>。",
example_read:"わたしたちの チームは しあいに かちます",
example_vi:"Đội của chúng tôi thắng trận đấu.",
example_en:"Our team wins the match."
},

{
level:"N5",
lesson:21,
id:4,
kanji:"負けます",
kana:"まけます",
hanviet:"PHỤ",
vi:"thua",
en:"lose",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby>の <ruby>試合<rt>しあい</rt></ruby>で <ruby>日本<rt>にほん</rt></ruby>は <span class='target-word'><ruby>負<rt>ま</rt></ruby>けました</span>。",
example_read:"きのうの しあいで にほんは まけました",
example_vi:"Trong trận đấu hôm qua, Nhật Bản đã thua.",
example_en:"Japan lost yesterday's match."
},

{
level:"N5",
lesson:21,
id:5,
kanji:"あります",
kana:"あります",
hanviet:"",
vi:"được tổ chức, diễn ra, có",
en:"be held, take place",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>来週<rt>らいしゅう</rt></ruby> <ruby>町<rt>まち</rt></ruby>で <span class='target-word'><ruby>お祭<rt>おまつ</rt></ruby>り</span>が あります。",
example_read:"らいしゅう まちで おまつりが あります",
example_vi:"Tuần sau sẽ có lễ hội ở thị trấn.",
example_en:"There will be a festival in the town next week."
},

{
level:"N5",
lesson:21,
id:6,
kanji:"役に立ちます",
kana:"やくにたちます",
hanviet:"DỊCH LẬP",
vi:"giúp ích",
en:"be useful",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"この <ruby>辞書<rt>じしょ</rt></ruby>は <ruby>日本語<rt>にほんご</rt></ruby>の <ruby>勉強<rt>べんきょう</rt></ruby>に <span class='target-word'><ruby>役<rt>やく</rt></ruby>に <ruby>立<rt>た</rt></ruby>ちます</span>。",
example_read:"この じしょは にほんごの べんきょうに やくにたちます",
example_vi:"Cuốn từ điển này rất hữu ích cho việc học tiếng Nhật.",
example_en:"This dictionary is useful for studying Japanese."
},

{
level:"N5",
lesson:21,
id:7,
kanji:"動きます",
kana:"うごきます",
hanviet:"ĐỘNG",
vi:"chuyển động, chạy",
en:"move",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"この <ruby>時計<rt>とけい</rt></ruby>は まだ <span class='target-word'><ruby>動<rt>うご</rt></ruby>きます</span>。",
example_read:"この とけいは まだ うごきます",
example_vi:"Chiếc đồng hồ này vẫn còn chạy.",
example_en:"This clock still works."
},

{
level:"N5",
lesson:21,
id:8,
kanji:"辞めます",
kana:"やめます",
hanviet:"TỪ",
vi:"nghỉ, thôi (công việc)",
en:"quit",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <ruby>会社<rt>かいしゃ</rt></ruby>を <span class='target-word'><ruby>辞<rt>や</rt></ruby>めます</span>。",
example_read:"あには かいしゃを やめます",
example_vi:"Anh trai tôi nghỉ việc ở công ty.",
example_en:"My older brother quits his job."
},

{
level:"N5",
lesson:21,
id:9,
kanji:"気をつけます",
kana:"きをつけます",
hanviet:"KHÍ",
vi:"chú ý, cẩn thận, bảo trọng",
en:"be careful",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>車<rt>くるま</rt></ruby>に <span class='target-word'><ruby>気<rt>き</rt></ruby>をつけます</span>。",
example_read:"くるまに きをつけます",
example_vi:"Tôi cẩn thận với xe cộ.",
example_en:"I am careful about traffic."
},

{
level:"N5",
lesson:21,
id:10,
kanji:"留学します",
kana:"りゅうがくします",
hanviet:"LƯU HỌC",
vi:"du học",
en:"study abroad",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>来年<rt>らいねん</rt></ruby> <ruby>日本<rt>にほん</rt></ruby>へ <span class='target-word'><ruby>留学<rt>りゅうがく</rt></ruby>します</span>。",
example_read:"らいねん にほんへ りゅうがくします",
example_vi:"Năm sau tôi sẽ đi du học Nhật Bản.",
example_en:"I will study abroad in Japan next year."
},

{
level:"N5",
lesson:21,
id:11,
kanji:"無駄[な]",
kana:"むだ[な]",
hanviet:"VÔ ĐÀ",
vi:"lãng phí, vô ích",
en:"wasteful, useless",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>時間<rt>じかん</rt></ruby>を <span class='target-word'><ruby>無駄<rt>むだ</rt></ruby>に</span> しないでください。",
example_read:"じかんを むだに しないでください",
example_vi:"Xin đừng lãng phí thời gian.",
example_en:"Please don't waste your time."
},

{
level:"N5",
lesson:21,
id:12,
kanji:"不便",
kana:"ふべん",
hanviet:"BẤT TIỆN",
vi:"bất tiện",
en:"inconvenient",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この <ruby>町<rt>まち</rt></ruby>は <ruby>駅<rt>えき</rt></ruby>が <ruby>遠<rt>とお</rt></ruby>くて <span class='target-word'><ruby>不便<rt>ふべん</rt></ruby></span>です。",
example_read:"この まちは えきが とおくて ふべんです",
example_vi:"Thị trấn này khá bất tiện vì ga ở xa.",
example_en:"This town is inconvenient because the station is far away."
},

{
level:"N5",
lesson:21,
id:13,
kanji:"凄い",
kana:"すごい",
hanviet:"THÊ",
vi:"ghê quá, giỏi quá, tuyệt quá",
en:"amazing, incredible",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>凄<rt>すご</rt></ruby>い</span>！ <ruby>日本語<rt>にほんご</rt></ruby>が とても <ruby>上手<rt>じょうず</rt></ruby>ですね。",
example_read:"すごい にほんごが とても じょうずですね",
example_vi:"Giỏi quá! Tiếng Nhật của bạn thật là tốt.",
example_en:"Amazing! Your Japanese is really good."
},

{
level:"N5",
lesson:21,
id:14,
kanji:"本当",
kana:"ほんとう",
hanviet:"BẢN ĐƯƠNG",
vi:"sự thật",
en:"truth",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"それは <span class='target-word'><ruby>本当<rt>ほんとう</rt></ruby></span>ですか。",
example_read:"それは ほんとうですか",
example_vi:"Đó là sự thật sao?",
example_en:"Is that true?"
},

{
level:"N5",
lesson:21,
id:15,
kanji:"嘘",
kana:"うそ",
hanviet:"HƯ",
vi:"lời nói dối, giả dối",
en:"lie",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>嘘<rt>うそ</rt></ruby></span>を <ruby>言<rt>い</rt></ruby>っては いけません。",
example_read:"うそを いっては いけません",
example_vi:"Không được nói dối.",
example_en:"You must not tell lies."
},

{
level:"N5",
lesson:21,
id:16,
kanji:"自動車",
kana:"じどうしゃ",
hanviet:"TỰ ĐỘNG XA",
vi:"ô tô, xe hơi",
en:"automobile, car",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'><ruby>自動車<rt>じどうしゃ</rt></ruby></span>で <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>通<rt>かよ</rt></ruby>っています。",
example_read:"ちちは じどうしゃで かいしゃへ かよっています",
example_vi:"Bố tôi đi làm bằng ô tô.",
example_en:"My father goes to work by car."
},

{
level:"N5",
lesson:21,
id:17,
kanji:"交通",
kana:"こうつう",
hanviet:"GIAO THÔNG",
vi:"giao thông",
en:"traffic, transportation",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby>は <span class='target-word'><ruby>交通<rt>こうつう</rt></ruby></span>が <ruby>混<rt>こ</rt></ruby>んでいます。",
example_read:"あさは こうつうが こんでいます",
example_vi:"Buổi sáng giao thông rất đông đúc.",
example_en:"Traffic is heavy in the morning."
},

{
level:"N5",
lesson:21,
id:18,
kanji:"物価",
kana:"ぶっか",
hanviet:"VẬT GIÁ",
vi:"giá cả, vật giá",
en:"prices, cost of living",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>は <span class='target-word'><ruby>物価<rt>ぶっか</rt></ruby></span>が <ruby>高<rt>たか</rt></ruby>いです。",
example_read:"にほんは ぶっかが たかいです",
example_vi:"Giá cả ở Nhật khá cao.",
example_en:"Prices in Japan are high."
},

{
level:"N5",
lesson:21,
id:19,
kanji:"放送",
kana:"ほうそう",
hanviet:"PHÓNG TỐNG",
vi:"phát sóng, phát thanh",
en:"broadcast",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今夜<rt>こんや</rt></ruby> <span class='target-word'><ruby>放送<rt>ほうそう</rt></ruby></span>される <ruby>番組<rt>ばんぐみ</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"こんや ほうそうされる ばんぐみを みます",
example_vi:"Tối nay tôi sẽ xem chương trình được phát sóng.",
example_en:"I'll watch the program being broadcast tonight."
},

{
level:"N5",
lesson:21,
id:20,
kanji:"ニュース",
kana:"ニュース",
hanviet:"",
vi:"tin tức, bản tin",
en:"news",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'>ニュース</span>を <ruby>見<rt>み</rt></ruby>てから <ruby>仕事<rt>しごと</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいあさ ニュースを みてから しごとへ いきます",
example_vi:"Mỗi sáng tôi xem bản tin rồi mới đi làm.",
example_en:"I watch the news every morning before going to work."
},

{
level:"N5",
lesson:21,
id:21,
kanji:"アニメ",
kana:"アニメ",
hanviet:"",
vi:"phim hoạt hình (Nhật Bản)",
en:"anime",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>アニメ</span>を <ruby>見<rt>み</rt></ruby>ることが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは アニメを みることが すきです",
example_vi:"Tôi thích xem anime.",
example_en:"I like watching anime."
},

{
level:"N5",
lesson:21,
id:22,
kanji:"マンガ",
kana:"マンガ",
hanviet:"",
vi:"truyện tranh",
en:"manga",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>弟<rt>おとうと</rt></ruby>は <span class='target-word'>マンガ</span>を <ruby>毎日<rt>まいにち</rt></ruby> <ruby>読<rt>よ</rt></ruby>んでいます。",
example_read:"おとうとは マンガを まいにち よんでいます",
example_vi:"Em trai tôi đọc truyện tranh mỗi ngày.",
example_en:"My younger brother reads manga every day."
},

{
level:"N5",
lesson:21,
id:23,
kanji:"デザイン",
kana:"デザイン",
hanviet:"",
vi:"thiết kế",
en:"design",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>姉<rt>あね</rt></ruby>は <span class='target-word'>デザイン</span>の <ruby>仕事<rt>しごと</rt></ruby>を しています。",
example_read:"あねは デザインの しごとを しています",
example_vi:"Chị gái tôi làm công việc thiết kế.",
example_en:"My older sister works as a designer."
},

{
level:"N5",
lesson:21,
id:24,
kanji:"夢",
kana:"ゆめ",
hanviet:"MỘNG",
vi:"giấc mơ, ước mơ",
en:"dream",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>の <span class='target-word'><ruby>夢<rt>ゆめ</rt></ruby></span>は <ruby>医者<rt>いしゃ</rt></ruby>に なることです。",
example_read:"わたしの ゆめは いしゃに なることです",
example_vi:"Ước mơ của tôi là trở thành bác sĩ.",
example_en:"My dream is to become a doctor."
},

{
level:"N5",
lesson:21,
id:25,
kanji:"天才",
kana:"てんさい",
hanviet:"THIÊN TÀI",
vi:"thiên tài",
en:"genius",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"あの <ruby>子<rt>こ</rt></ruby>は <span class='target-word'><ruby>天才<rt>てんさい</rt></ruby></span>だと <ruby>思<rt>おも</rt></ruby>います。",
example_read:"あの こは てんさいだと おもいます",
example_vi:"Tôi nghĩ đứa trẻ đó là một thiên tài.",
example_en:"I think that child is a genius."
},

{
level:"N5",
lesson:21,
id:26,
kanji:"試合",
kana:"しあい",
hanviet:"THÍ HỢP",
vi:"trận đấu",
en:"match, game",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby> <span class='target-word'><ruby>試合<rt>しあい</rt></ruby></span>が あります。",
example_read:"あした しあいが あります",
example_vi:"Ngày mai có một trận đấu.",
example_en:"There is a match tomorrow."
},

{
level:"N5",
lesson:21,
id:27,
kanji:"意見",
kana:"いけん",
hanviet:"Ý KIẾN",
vi:"ý kiến",
en:"opinion",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>会議<rt>かいぎ</rt></ruby>で <span class='target-word'><ruby>意見<rt>いけん</rt></ruby></span>を <ruby>言<rt>い</rt></ruby>いました。",
example_read:"かいぎで いけんを いいました",
example_vi:"Tôi đã phát biểu ý kiến trong cuộc họp.",
example_en:"I gave my opinion at the meeting."
},

{
level:"N5",
lesson:21,
id:28,
kanji:"[お]話",
kana:"[お]はなし",
hanviet:"THOẠI",
vi:"câu chuyện, bài nói chuyện",
en:"story, talk",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>話<rt>はなし</rt></ruby></span>を <ruby>聞<rt>き</rt></ruby>かせてください。",
example_read:"おはなしを きかせてください",
example_vi:"Xin hãy kể cho tôi nghe câu chuyện.",
example_en:"Please tell me the story."
},

{
level:"N5",
lesson:21,
id:29,
kanji:"地球",
kana:"ちきゅう",
hanviet:"ĐỊA CẦU",
vi:"Trái Đất",
en:"the Earth",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>地球<rt>ちきゅう</rt></ruby></span>は <ruby>丸<rt>まる</rt></ruby>いです。",
example_read:"ちきゅうは まるいです",
example_vi:"Trái Đất có hình tròn.",
example_en:"The Earth is round."
},

{
level:"N5",
lesson:21,
id:30,
kanji:"月",
kana:"つき",
hanviet:"NGUYỆT",
vi:"mặt trăng",
en:"the Moon",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今夜<rt>こんや</rt></ruby>は <span class='target-word'><ruby>月<rt>つき</rt></ruby></span>が とても <ruby>きれい</ruby>です。",
example_read:"こんやは つきが とても きれいです",
example_vi:"Tối nay trăng rất đẹp.",
example_en:"The moon is very beautiful tonight."
},

{
level:"N5",
lesson:21,
id:31,
kanji:"最近",
kana:"さいきん",
hanviet:"TỐI CẬN",
vi:"gần đây",
en:"recently; lately",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>最近<rt>さいきん</rt></ruby></span>、<ruby>毎日<rt>まいにち</rt></ruby> <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"さいきん まいにち にほんごを べんきょうしています",
example_vi:"Gần đây tôi học tiếng Nhật mỗi ngày.",
example_en:"Recently, I've been studying Japanese every day."
},

{
level:"N5",
lesson:21,
id:32,
kanji:"たぶん",
kana:"たぶん",
hanviet:"",
vi:"chắc, có lẽ",
en:"probably; maybe",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>たぶん</span> <ruby>明日<rt>あした</rt></ruby>は <ruby>雨<rt>あめ</rt></ruby>が <ruby>降<rt>ふ</rt></ruby>るでしょう。",
example_read:"たぶん あしたは あめが ふるでしょう",
example_vi:"Có lẽ ngày mai trời sẽ mưa.",
example_en:"It will probably rain tomorrow."
},

{
level:"N5",
lesson:21,
id:33,
kanji:"きっと",
kana:"きっと",
hanviet:"",
vi:"chắc chắn, nhất định",
en:"surely; certainly",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>きっと</span> <ruby>試験<rt>しけん</rt></ruby>に <ruby>合格<rt>ごうかく</rt></ruby>できます。",
example_read:"きっと しけんに ごうかくできます",
example_vi:"Chắc chắn bạn sẽ đỗ kỳ thi.",
example_en:"You'll surely pass the exam."
},

{
level:"N5",
lesson:21,
id:34,
kanji:"本当に",
kana:"ほんとうに",
hanviet:"BẢN ĐƯƠNG",
vi:"thật sự",
en:"really; truly",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>本当<rt>ほんとう</rt></ruby>に</span> <ruby>助<rt>たす</rt></ruby>かりました。ありがとうございます。",
example_read:"ほんとうに たすかりました ありがとうございます",
example_vi:"Tôi thật sự đã được giúp rất nhiều. Cảm ơn bạn.",
example_en:"You really helped me. Thank you very much."
},

{
level:"N5",
lesson:21,
id:35,
kanji:"そんなに",
kana:"そんなに",
hanviet:"",
vi:"đến mức đó, (không)... lắm",
en:"that much; so much",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この <ruby>問題<rt>もんだい</rt></ruby>は <span class='target-word'>そんなに</span> <ruby>難<rt>むずか</rt></ruby>しくありません。",
example_read:"この もんだいは そんなに むずかしくありません",
example_vi:"Vấn đề này không khó lắm.",
example_en:"This problem isn't that difficult."
},

{
level:"N5",
lesson:21,
id:36,
kanji:"～について",
kana:"～について",
hanviet:"",
vi:"về..., liên quan đến...",
en:"about; regarding",
word_type_vi:"Mẫu ngữ pháp",
word_type_en:"Grammar pattern",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>の <ruby>文化<rt>ぶんか</rt></ruby><span class='target-word'>について</span> <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"にほんの ぶんかについて べんきょうしています",
example_vi:"Tôi đang học về văn hóa Nhật Bản.",
example_en:"I'm studying about Japanese culture."
},

{
level:"N5",
lesson:21,
id:37,
kanji:"久しぶりですね",
kana:"ひさしぶりですね",
hanviet:"CỬU",
vi:"lâu rồi không gặp nhỉ",
en:"Long time no see.",
word_type_vi:"Câu giao tiếp",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A：こんにちは。<br>B：<span class='target-word'><ruby>久<rt>ひさ</rt></ruby>しぶりですね</span>。",
example_read:"こんにちは ひさしぶりですね",
example_vi:"A: Xin chào. B: Lâu rồi không gặp nhỉ.",
example_en:"A: Hello. B: Long time no see."
},

{
level:"N5",
lesson:21,
id:38,
kanji:"～でも飲みませんか",
kana:"～でものみませんか",
hanviet:"",
vi:"Anh/chị uống ~ nhé?",
en:"Would you like to have ~?",
word_type_vi:"Mẫu câu",
word_type_en:"Sentence pattern",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>の <ruby>後<rt>あと</rt></ruby>、コーヒー<span class='target-word'>でも <ruby>飲<rt>の</rt></ruby>みませんか</span>。",
example_read:"しごとの あと コーヒーでも のみませんか",
example_vi:"Sau giờ làm, đi uống cà phê nhé?",
example_en:"Would you like to have some coffee after work?"
},

{
level:"N5",
lesson:21,
id:39,
kanji:"もちろん",
kana:"もちろん",
hanviet:"",
vi:"tất nhiên",
en:"of course",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"A：<ruby>手伝<rt>てつだ</rt></ruby>ってくれますか。<br>B：<span class='target-word'>もちろん</span>です。",
example_read:"てつだってくれますか もちろんです",
example_vi:"A: Bạn giúp mình nhé? B: Tất nhiên rồi.",
example_en:"A: Could you help me? B: Of course."
},

{
level:"N5",
lesson:21,
id:40,
kanji:"帰らないと…",
kana:"かえらないと",
hanviet:"",
vi:"phải về thôi...",
en:"I have to go home...",
word_type_vi:"Mẫu câu",
word_type_en:"Sentence pattern",
category:"Minna 1",
example:"<ruby>時間<rt>じかん</rt></ruby>が ないので、<span class='target-word'><ruby>帰<rt>かえ</rt></ruby>らないと…</span>",
example_read:"じかんが ないので かえらないと",
example_vi:"Vì không còn thời gian nên tôi phải về thôi...",
example_en:"I'm out of time, so I have to go home..."
},

{
level:"N5",
lesson:21,
id:41,
kanji:"アインシュタイン",
kana:"アインシュタイン",
hanviet:"",
vi:"Albert Einstein",
en:"Albert Einstein",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>アインシュタイン</span>は <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>科学者<rt>かがくしゃ</rt></ruby>です。",
example_read:"アインシュタインは ゆうめいな かがくしゃです",
example_vi:"Albert Einstein là một nhà khoa học nổi tiếng.",
example_en:"Albert Einstein was a famous scientist."
},

{
level:"N5",
lesson:21,
id:42,
kanji:"ガガーリン",
kana:"ガガーリン",
hanviet:"",
vi:"Yuri Gagarin",
en:"Yuri Gagarin",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ガガーリン</span>は <ruby>初<rt>はじ</rt></ruby>めて <ruby>宇宙<rt>うちゅう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>った <ruby>人<rt>ひと</rt></ruby>です。",
example_read:"ガガーリンは はじめて うちゅうへ いった ひとです",
example_vi:"Yuri Gagarin là người đầu tiên bay vào vũ trụ.",
example_en:"Yuri Gagarin was the first person to travel into space."
},

{
level:"N5",
lesson:21,
id:43,
kanji:"ガリレオ",
kana:"ガリレオ",
hanviet:"",
vi:"Galileo Galilei",
en:"Galileo Galilei",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ガリレオ</span>は <ruby>天文学<rt>てんもんがく</rt></ruby>で <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"ガリレオは てんもんがくで ゆうめいです",
example_vi:"Galileo nổi tiếng trong lĩnh vực thiên văn học.",
example_en:"Galileo is famous for astronomy."
},

{
level:"N5",
lesson:21,
id:44,
kanji:"キング牧師",
kana:"キングぼくし",
hanviet:"MỤC SƯ",
vi:"Mục sư Martin Luther King Jr.",
en:"Martin Luther King Jr.",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>キング<ruby>牧師<rt>ぼくし</rt></ruby></span>は <ruby>平和<rt>へいわ</rt></ruby>のために <ruby>活動<rt>かつどう</rt></ruby>しました。",
example_read:"キングぼくしは へいわのために かつどうしました",
example_vi:"Mục sư Martin Luther King Jr. đã hoạt động vì hòa bình.",
example_en:"Martin Luther King Jr. worked for peace."
},

{
level:"N5",
lesson:21,
id:45,
kanji:"フランクリン",
kana:"フランクリン",
hanviet:"",
vi:"Benjamin Franklin",
en:"Benjamin Franklin",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>フランクリン</span>は <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>政治家<rt>せいじか</rt></ruby>でした。",
example_read:"フランクリンは ゆうめいな せいじかでした",
example_vi:"Benjamin Franklin là một chính trị gia nổi tiếng.",
example_en:"Benjamin Franklin was a famous politician."
},

{
level:"N5",
lesson:21,
id:46,
kanji:"かぐや姫",
kana:"かぐやひめ",
hanviet:"HUY CÔNG CHÚA",
vi:"Công chúa Kaguya",
en:"Princess Kaguya",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>かぐや<ruby>姫<rt>ひめ</rt></ruby></span>は <ruby>日本<rt>にほん</rt></ruby>の <ruby>昔話<rt>むかしばなし</rt></ruby>です。",
example_read:"かぐやひめは にほんの むかしばなしです",
example_vi:"Công chúa Kaguya là một câu chuyện cổ tích nổi tiếng của Nhật Bản.",
example_en:"Princess Kaguya is a famous Japanese folktale."
},

{
level:"N5",
lesson:21,
id:47,
kanji:"天神祭",
kana:"てんじんまつり",
hanviet:"THIÊN THẦN TẾ",
vi:"Lễ hội Tenjin",
en:"Tenjin Festival",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>天神祭<rt>てんじんまつり</rt></ruby></span>は <ruby>大阪<rt>おおさか</rt></ruby>で <ruby>有名<rt>ゆうめい</rt></ruby>な お<ruby>祭<rt>まつ</rt></ruby>りです。",
example_read:"てんじんまつりは おおさかで ゆうめいな おまつりです",
example_vi:"Lễ hội Tenjin là một lễ hội nổi tiếng ở Osaka.",
example_en:"The Tenjin Festival is a famous festival in Osaka."
},

{
level:"N5",
lesson:21,
id:48,
kanji:"吉野山",
kana:"よしのやま",
hanviet:"CÁT DÃ SƠN",
vi:"Núi Yoshino",
en:"Mount Yoshino",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>吉野山<rt>よしのやま</rt></ruby></span>は <ruby>桜<rt>さくら</rt></ruby>で <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"よしのやまは さくらで ゆうめいです",
example_vi:"Núi Yoshino nổi tiếng với hoa anh đào.",
example_en:"Mount Yoshino is famous for its cherry blossoms."
},

{
level:"N5",
lesson:21,
id:49,
kanji:"カンガルー",
kana:"カンガルー",
hanviet:"",
vi:"chuột túi",
en:"kangaroo",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>カンガルー</span>は オーストラリアの <ruby>動物<rt>どうぶつ</rt></ruby>です。",
example_read:"カンガルーは オーストラリアの どうぶつです",
example_vi:"Chuột túi là loài động vật của Úc.",
example_en:"Kangaroos are animals native to Australia."
},

{
level:"N5",
lesson:21,
id:50,
kanji:"キャプテン・クック",
kana:"キャプテン・クック",
hanviet:"",
vi:"Thuyền trưởng James Cook",
en:"Captain James Cook",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>キャプテン・クック</span>は <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>探検家<rt>たんけんか</rt></ruby>でした。",
example_read:"キャプテン クックは ゆうめいな たんけんかでした",
example_vi:"Thuyền trưởng James Cook là một nhà thám hiểm nổi tiếng.",
example_en:"Captain James Cook was a famous explorer."
},

{
level:"N5",
lesson:21,
id:51,
kanji:"ヨーネン",
kana:"ヨーネン",
hanviet:"",
vi:"Công ty Yonen (tên công ty giả định)",
en:"Yonen (fictional company name)",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <span class='target-word'>ヨーネン</span>で <ruby>働<rt>はたら</rt></ruby>いています。",
example_read:"あには ヨーネンで はたらいています",
example_vi:"Anh trai tôi đang làm việc tại công ty Yonen.",
example_en:"My older brother works at Yonen."
}
];