window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[11] = [
{
level:"N5",
lesson:11,
id:1,
kanji:"居ます",
kana:"います",
hanviet:"CƯ",
vi:"Có, ở (dùng cho người và động vật)",
en:"Exist / Be (animate)",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>公園<rt>こうえん</rt></ruby>に <ruby>子供<rt>こども</rt></ruby>が <span class='target-word'><ruby>居<rt>い</rt></ruby>ます</span>。",
example_read:"こうえんに こどもが います。",
example_vi:"Có trẻ em ở công viên.",
example_en:"There are children in the park."
},

{
level:"N5",
lesson:11,
id:2,
kanji:"日本",
kana:"にほん",
hanviet:"NHẬT BẢN",
vi:"Nhật Bản",
en:"Japan",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <span class='target-word'><ruby>日本<rt>にほん</rt></ruby></span>に います。",
example_read:"あには にほんに います。",
example_vi:"Anh trai tôi đang ở Nhật Bản.",
example_en:"My older brother is in Japan."
},

{
level:"N5",
lesson:11,
id:3,
kanji:"掛かります",
kana:"かかります",
hanviet:"QUẢI",
vi:"Mất, tốn (thời gian, tiền bạc)",
en:"Take (time/money)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>大阪<rt>おおさか</rt></ruby>まで ２<ruby>時間<rt>じかん</rt></ruby> <span class='target-word'><ruby>掛<rt>か</rt></ruby>かります</span>。",
example_read:"おおさかまで にじかん かかります。",
example_vi:"Mất 2 tiếng để đến Osaka.",
example_en:"It takes two hours to get to Osaka."
},

{
level:"N5",
lesson:11,
id:4,
kanji:"休みます",
kana:"やすみます",
hanviet:"HƯU",
vi:"Nghỉ (công việc, học tập)",
en:"Take a day off",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>会社<rt>かいしゃ</rt></ruby>を <span class='target-word'><ruby>休<rt>やす</rt></ruby>みます</span>。",
example_read:"きょうは かいしゃを やすみます。",
example_vi:"Hôm nay tôi nghỉ làm.",
example_en:"I take a day off from work today."
},

{
level:"N5",
lesson:11,
id:5,
kanji:"一つ",
kana:"ひとつ",
hanviet:"NHẤT",
vi:"Một cái",
en:"One thing",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"りんごを <span class='target-word'><ruby>一<rt>ひと</rt></ruby>つ</span> ください。",
example_read:"りんごを ひとつ ください。",
example_vi:"Cho tôi một quả táo.",
example_en:"Please give me one apple."
},

{
level:"N5",
lesson:11,
id:6,
kanji:"二つ",
kana:"ふたつ",
hanviet:"NHỊ",
vi:"Hai cái",
en:"Two things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"みかんを <span class='target-word'><ruby>二<rt>ふた</rt></ruby>つ</span> <ruby>買<rt>か</rt></ruby>いました。",
example_read:"みかんを ふたつ かいました。",
example_vi:"Tôi đã mua hai quả quýt.",
example_en:"I bought two oranges."
},

{
level:"N5",
lesson:11,
id:7,
kanji:"三つ",
kana:"みっつ",
hanviet:"TAM",
vi:"Ba cái",
en:"Three things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"たまごを <span class='target-word'><ruby>三<rt>みっ</rt></ruby>つ</span> <ruby>使<rt>つか</rt></ruby>います。",
example_read:"たまごを みっつ つかいます。",
example_vi:"Tôi dùng ba quả trứng.",
example_en:"I use three eggs."
},

{
level:"N5",
lesson:11,
id:8,
kanji:"四つ",
kana:"よっつ",
hanviet:"TỨ",
vi:"Bốn cái",
en:"Four things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"ケーキを <span class='target-word'><ruby>四<rt>よっ</rt></ruby>つ</span> <ruby>作<rt>つく</rt></ruby>りました。",
example_read:"けーきを よっつ つくりました。",
example_vi:"Tôi đã làm bốn cái bánh.",
example_en:"I made four cakes."
},

{
level:"N5",
lesson:11,
id:9,
kanji:"五つ",
kana:"いつつ",
hanviet:"NGŨ",
vi:"Năm cái",
en:"Five things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"りんごが <span class='target-word'><ruby>五<rt>いつ</rt></ruby>つ</span> あります。",
example_read:"りんごが いつつ あります。",
example_vi:"Có năm quả táo.",
example_en:"There are five apples."
},

{
level:"N5",
lesson:11,
id:10,
kanji:"六つ",
kana:"むっつ",
hanviet:"LỤC",
vi:"Sáu cái",
en:"Six things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"コップが <span class='target-word'><ruby>六<rt>むっ</rt></ruby>つ</span> あります。",
example_read:"こっぷが むっつ あります。",
example_vi:"Có sáu cái cốc.",
example_en:"There are six cups."
},

{
level:"N5",
lesson:11,
id:11,
kanji:"七つ",
kana:"ななつ",
hanviet:"THẤT",
vi:"Bảy cái",
en:"Seven things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"みかんが <span class='target-word'><ruby>七<rt>なな</rt></ruby>つ</span> あります。",
example_read:"みかんが ななつ あります。",
example_vi:"Có bảy quả quýt.",
example_en:"There are seven oranges."
},

{
level:"N5",
lesson:11,
id:12,
kanji:"八つ",
kana:"やっつ",
hanviet:"BÁT",
vi:"Tám cái",
en:"Eight things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"ケーキを <span class='target-word'><ruby>八<rt>やっ</rt></ruby>つ</span> <ruby>買<rt>か</rt></ruby>いました。",
example_read:"けーきを やっつ かいました。",
example_vi:"Tôi đã mua tám cái bánh.",
example_en:"I bought eight cakes."
},

{
level:"N5",
lesson:11,
id:13,
kanji:"九つ",
kana:"ここのつ",
hanviet:"CỬU",
vi:"Chín cái",
en:"Nine things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"りんごを <span class='target-word'><ruby>九<rt>ここの</rt></ruby>つ</span> <ruby>食<rt>た</rt></ruby>べました。",
example_read:"りんごを ここのつ たべました。",
example_vi:"Tôi đã ăn chín quả táo.",
example_en:"I ate nine apples."
},

{
level:"N5",
lesson:11,
id:14,
kanji:"十",
kana:"とお",
hanviet:"THẬP",
vi:"Mười cái",
en:"Ten things",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"みかんを <span class='target-word'><ruby>十<rt>とお</rt></ruby></span> <ruby>買<rt>か</rt></ruby>いました。",
example_read:"みかんを とお かいました。",
example_vi:"Tôi đã mua mười quả quýt.",
example_en:"I bought ten oranges."
},

{
level:"N5",
lesson:11,
id:15,
kanji:"幾つ",
kana:"いくつ",
hanviet:"KI/KỶ/KÝ",
vi:"Mấy cái, bao nhiêu cái",
en:"How many",
word_type_vi:"Nghi vấn từ",
word_type_en:"Question word",
category:"Minna 1",
example:"りんごは <span class='target-word'><ruby>幾<rt>いく</rt></ruby>つ</span> ありますか。",
example_read:"りんごは いくつ ありますか。",
example_vi:"Có bao nhiêu quả táo?",
example_en:"How many apples are there?"
},

{
level:"N5",
lesson:11,
id:16,
kanji:"一人",
kana:"ひとり",
hanviet:"NHẤT NHÂN",
vi:"Một người",
en:"One person",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<span class='target-word'><ruby>一人<rt>ひとり</rt></ruby></span>で <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ひとりで いきます。",
example_vi:"Tôi đi một mình.",
example_en:"I go alone."
},

{
level:"N5",
lesson:11,
id:17,
kanji:"二人",
kana:"ふたり",
hanviet:"NHỊ NHÂN",
vi:"Hai người",
en:"Two people",
word_type_vi:"Danh từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<span class='target-word'><ruby>二人<rt>ふたり</rt></ruby></span>で <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"ふたりで えいがを みます。",
example_vi:"Hai người cùng xem phim.",
example_en:"Two people watch a movie together."
},

{
level:"N5",
lesson:11,
id:18,
kanji:"～人",
kana:"～にん",
hanviet:"NHÂN",
vi:"~ người",
en:"~ people",
word_type_vi:"Trợ số từ",
word_type_en:"Counter suffix",
category:"Minna 1",
example:"クラスに <span class='target-word'>２０<ruby>人<rt>にん</rt></ruby></span> います。",
example_read:"くらすに にじゅうにん います。",
example_vi:"Có 20 người trong lớp.",
example_en:"There are 20 people in the class."
},

{
level:"N5",
lesson:11,
id:19,
kanji:"～台",
kana:"～だい",
hanviet:"THAI/ĐÀI",
vi:"~ cái (máy móc, xe cộ)",
en:"Counter for machines/vehicles",
word_type_vi:"Trợ số từ",
word_type_en:"Counter suffix",
category:"Minna 1",
example:"<ruby>車<rt>くるま</rt></ruby>が <span class='target-word'>３<ruby>台<rt>だい</rt></ruby></span> あります。",
example_read:"くるまが さんだい あります。",
example_vi:"Có 3 chiếc xe ô tô.",
example_en:"There are three cars."
},

{
level:"N5",
lesson:11,
id:20,
kanji:"～枚",
kana:"～まい",
hanviet:"MAI",
vi:"~ tờ, ~ tấm",
en:"Counter for flat objects",
word_type_vi:"Trợ số từ",
word_type_en:"Counter suffix",
category:"Minna 1",
example:"<ruby>切手<rt>きって</rt></ruby>を <span class='target-word'>５<ruby>枚<rt>まい</rt></ruby></span> <ruby>買<rt>か</rt></ruby>いました。",
example_read:"きってを ごまい かいました。",
example_vi:"Tôi đã mua 5 con tem.",
example_en:"I bought five stamps."
},

{
level:"N5",
lesson:11,
id:21,
kanji:"～回",
kana:"～かい",
hanviet:"HỒI",
vi:"~ lần",
en:"Counter for occurrences",
word_type_vi:"Trợ số từ",
word_type_en:"Counter suffix",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>へ <span class='target-word'>３<ruby>回<rt>かい</rt></ruby></span> <ruby>行<rt>い</rt></ruby>ったことが あります。",
example_read:"にほんへ さんかい いったことが あります。",
example_vi:"Tôi đã đến Nhật 3 lần.",
example_en:"I have been to Japan three times."
},

{
level:"N5",
lesson:11,
id:22,
kanji:"林檎",
kana:"りんご",
hanviet:"LÂM CẦM",
vi:"Táo",
en:"Apple",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>林檎<rt>りんご</rt></ruby></span>を <ruby>一つ<rt>ひとつ </rt></ruby><ruby>食<rt>た</rt></ruby>べます。",
example_read:"りんごを ひとつ たべます。",
example_vi:"Tôi ăn một quả táo.",
example_en:"I eat one apple."
},

{
level:"N5",
lesson:11,
id:23,
kanji:"蜜柑",
kana:"みかん",
hanviet:"MẬT CAM",
vi:"Quýt",
en:"Mandarin orange",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>蜜柑<rt>みかん</rt></ruby></span>を <ruby>二つ<rt>ふたつ</rt></ruby> <ruby>買<rt>か</rt></ruby>いました。",
example_read:"みかんを ふたつ かいました。",
example_vi:"Tôi đã mua hai quả quýt.",
example_en:"I bought two mandarins."
},

{
level:"N5",
lesson:11,
id:24,
kanji:"サンドイッチ",
kana:"サンドイッチ",
hanviet:"",
vi:"Bánh sandwich",
en:"Sandwich",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昼ご飯<rt>ひるごはん</rt></ruby>に <span class='target-word'>サンドイッチ</span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"ひるごはんに さんどいっちを たべます。",
example_vi:"Tôi ăn sandwich vào bữa trưa.",
example_en:"I eat a sandwich for lunch."
},

{
level:"N5",
lesson:11,
id:25,
kanji:"カレー[ライス]",
kana:"カレー[ライス]",
hanviet:"",
vi:"Cơm cà ri",
en:"Curry rice",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>の <ruby>晩ご飯<rt>ばんごはん</rt></ruby>は <span class='target-word'>カレーライス</span>です。",
example_read:"きょうの ばんごはんは かれーらいすです。",
example_vi:"Bữa tối hôm nay là cơm cà ri.",
example_en:"Tonight's dinner is curry rice."
},

{
level:"N5",
lesson:11,
id:26,
kanji:"アイスクリーム",
kana:"アイスクリーム",
hanviet:"",
vi:"Kem",
en:"Ice cream",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いので <span class='target-word'>アイスクリーム</span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"あついので あいすくりーむを たべます。",
example_vi:"Vì trời nóng nên tôi ăn kem.",
example_en:"Because it's hot, I eat ice cream."
},

{
level:"N5",
lesson:11,
id:27,
kanji:"切手",
kana:"きって",
hanviet:"THIẾT THỦ",
vi:"Tem",
en:"Stamp",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>郵便局<rt>ゆうびんきょく</rt></ruby>で <span class='target-word'><ruby>切手<rt>きって</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"ゆうびんきょくで きってを かいました。",
example_vi:"Tôi đã mua tem ở bưu điện.",
example_en:"I bought stamps at the post office."
},

{
level:"N5",
lesson:11,
id:28,
kanji:"葉書",
kana:"はがき",
hanviet:"DIỆP THƯ",
vi:"Bưu thiếp",
en:"Postcard",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>葉書<rt>はがき</rt></ruby></span>を <ruby>友達<rt>ともだち</rt></ruby>に <ruby>送<rt>おく</rt></ruby>ります。",
example_read:"はがきを ともだちに おくります。",
example_vi:"Tôi gửi bưu thiếp cho bạn.",
example_en:"I send a postcard to my friend."
},

{
level:"N5",
lesson:11,
id:29,
kanji:"封筒",
kana:"ふうとう",
hanviet:"PHONG ĐỒNG",
vi:"Phong bì",
en:"Envelope",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>手紙<rt>てがみ</rt></ruby>を <span class='target-word'><ruby>封筒<rt>ふうとう</rt></ruby></span>に <ruby>入<rt>い</rt></ruby>れます。",
example_read:"てがみを ふうとうに いれます。",
example_vi:"Tôi bỏ thư vào phong bì.",
example_en:"I put the letter into an envelope."
},

{
level:"N5",
lesson:11,
id:30,
kanji:"両親",
kana:"りょうしん",
hanviet:"LƯỠNG THÂN",
vi:"Bố mẹ",
en:"Parents",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>両親<rt>りょうしん</rt></ruby></span>は <ruby>大阪<rt>おおさか</rt></ruby>に <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"りょうしんは おおさかに すんでいます。",
example_vi:"Bố mẹ tôi sống ở Osaka.",
example_en:"My parents live in Osaka."
},

{
level:"N5",
lesson:11,
id:31,
kanji:"兄弟",
kana:"きょうだい",
hanviet:"HUYNH ĐỆ",
vi:"Anh chị em",
en:"Brothers and sisters / siblings",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>兄弟<rt>きょうだい</rt></ruby></span>が 3<ruby>人<rt>にん</rt></ruby> います。",
example_read:"わたしは きょうだいが さんにん います。",
example_vi:"Tôi có ba anh chị em.",
example_en:"I have three siblings."
},

{
level:"N5",
lesson:11,
id:32,
kanji:"兄",
kana:"あに",
hanviet:"HUYNH",
vi:"Anh trai (của mình)",
en:"(My) older brother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>兄<rt>あに</rt></ruby></span>は <ruby>会社員<rt>かいしゃいん</rt></ruby>です。",
example_read:"あには かいしゃいんです。",
example_vi:"Anh trai tôi là nhân viên công ty.",
example_en:"My older brother is a company employee."
},

{
level:"N5",
lesson:11,
id:33,
kanji:"お兄さん",
kana:"おにいさん",
hanviet:"HUYNH",
vi:"Anh trai (của người khác)",
en:"Older brother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>田中<rt>たなか</rt></ruby>さんの <span class='target-word'><ruby>お兄<rt>おにい</rt></ruby>さん</span>は <ruby>医者<rt>いしゃ</rt></ruby>です。",
example_read:"たなかさんの おにいさんは いしゃです。",
example_vi:"Anh trai của anh Tanaka là bác sĩ.",
example_en:"Mr. Tanaka's older brother is a doctor."
},

{
level:"N5",
lesson:11,
id:34,
kanji:"姉",
kana:"あね",
hanviet:"TỶ",
vi:"Chị gái (của mình)",
en:"(My) older sister",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>姉<rt>あね</rt></ruby></span>は <ruby>東京<rt>とうきょう</rt></ruby>に <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"あねは とうきょうに すんでいます。",
example_vi:"Chị gái tôi sống ở Tokyo.",
example_en:"My older sister lives in Tokyo."
},

{
level:"N5",
lesson:11,
id:35,
kanji:"お姉さん",
kana:"おねえさん",
hanviet:"TỶ",
vi:"Chị gái (của người khác)",
en:"Older sister",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>山田<rt>やまだ</rt></ruby>さんの <span class='target-word'><ruby>お姉<rt>おねえ</rt></ruby>さん</span>は <ruby>先生<rt>せんせい</rt></ruby>です。",
example_read:"やまださんの おねえさんは せんせいです。",
example_vi:"Chị gái của anh Yamada là giáo viên.",
example_en:"Mr. Yamada's older sister is a teacher."
},

{
level:"N5",
lesson:11,
id:36,
kanji:"弟",
kana:"おとうと",
hanviet:"ĐỆ",
vi:"Em trai (của mình)",
en:"(My) younger brother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>弟<rt>おとうと</rt></ruby></span>は <ruby>高校生<rt>こうこうせい</rt></ruby>です。",
example_read:"おとうとは こうこうせいです。",
example_vi:"Em trai tôi là học sinh cấp ba.",
example_en:"My younger brother is a high school student."
},

{
level:"N5",
lesson:11,
id:37,
kanji:"弟さん",
kana:"おとうとさん",
hanviet:"ĐỆ",
vi:"Em trai (của người khác)",
en:"Younger brother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>鈴木<rt>すずき</rt></ruby>さんの <span class='target-word'><ruby>弟<rt>おとうと</rt></ruby>さん</span>は <ruby>大学生<rt>だいがくせい</rt></ruby>です。",
example_read:"すずきさんの おとうとさんは だいがくせいです。",
example_vi:"Em trai của anh Suzuki là sinh viên đại học.",
example_en:"Mr. Suzuki's younger brother is a university student."
},

{
level:"N5",
lesson:11,
id:38,
kanji:"妹",
kana:"いもうと",
hanviet:"MUỘI",
vi:"Em gái (của mình)",
en:"(My) younger sister",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>妹<rt>いもうと</rt></ruby></span>は <ruby>中学生<rt>ちゅうがくせい</rt></ruby>です。",
example_read:"いもうとは ちゅうがくせいです。",
example_vi:"Em gái tôi là học sinh cấp hai.",
example_en:"My younger sister is a junior high school student."
},

{
level:"N5",
lesson:11,
id:39,
kanji:"妹さん",
kana:"いもうとさん",
hanviet:"MUỘI",
vi:"Em gái (của người khác)",
en:"Younger sister",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>木村<rt>きむら</rt></ruby>さんの <span class='target-word'><ruby>妹<rt>いもうと</rt></ruby>さん</span>は <ruby>高校生<rt>こうこうせい</rt></ruby>です。",
example_read:"きむらさんの いもうとさんは こうこうせいです。",
example_vi:"Em gái của anh Kimura là học sinh cấp ba.",
example_en:"Mr. Kimura's younger sister is a high school student."
},

{
level:"N5",
lesson:11,
id:40,
kanji:"外国",
kana:"がいこく",
hanviet:"NGOẠI QUỐC",
vi:"Nước ngoài",
en:"Foreign country",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>外国<rt>がいこく</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きたいです。",
example_read:"がいこくへ いきたいです。",
example_vi:"Tôi muốn đi nước ngoài.",
example_en:"I want to go abroad."
},

{
level:"N5",
lesson:11,
id:41,
kanji:"留学生",
kana:"りゅうがくせい",
hanviet:"LƯU HỌC SINH",
vi:"Lưu học sinh, du học sinh",
en:"International student",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>留学生<rt>りゅうがくせい</rt></ruby></span>が <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"りゅうがくせいが にほんごを べんきょうしています。",
example_vi:"Du học sinh đang học tiếng Nhật.",
example_en:"An international student is studying Japanese."
},

{
level:"N5",
lesson:11,
id:42,
kanji:"クラス",
kana:"クラス",
hanviet:"",
vi:"Lớp học",
en:"Class",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'>クラス</span>に <ruby>留学生<rt>りゅうがくせい</rt></ruby>が たくさん います。",
example_read:"この くらすに りゅうがくせいが たくさん います。",
example_vi:"Trong lớp này có nhiều du học sinh.",
example_en:"There are many international students in this class."
},

{
level:"N5",
lesson:11,
id:43,
kanji:"～時間",
kana:"～じかん",
hanviet:"THỜI GIAN",
vi:"~ tiếng",
en:"~ hours",
word_type_vi:"Lượng từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> 2<span class='target-word'><ruby>時間<rt>じかん</rt></ruby></span> <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"まいにち にじかん べんきょうします。",
example_vi:"Mỗi ngày tôi học 2 tiếng.",
example_en:"I study for two hours every day."
},

{
level:"N5",
lesson:11,
id:44,
kanji:"～週間",
kana:"～しゅうかん",
hanviet:"CHU GIAN",
vi:"~ tuần",
en:"~ weeks",
word_type_vi:"Lượng từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>に 3<span class='target-word'><ruby>週間<rt>しゅうかん</rt></ruby></span> いました。",
example_read:"にほんに さんしゅうかん いました。",
example_vi:"Tôi đã ở Nhật 3 tuần.",
example_en:"I stayed in Japan for three weeks."
},

{
level:"N5",
lesson:11,
id:45,
kanji:"～か月",
kana:"～かげつ",
hanviet:"NGUYỆT",
vi:"~ tháng",
en:"~ months",
word_type_vi:"Lượng từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<ruby>日本語<rt>にほんご</rt></ruby>を 6<span class='target-word'>か<ruby>月<rt>げつ</rt></ruby></span> <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"にほんごを ろっかげつ べんきょうしています。",
example_vi:"Tôi đã học tiếng Nhật được 6 tháng.",
example_en:"I have been studying Japanese for six months."
},

{
level:"N5",
lesson:11,
id:46,
kanji:"～年",
kana:"～ねん",
hanviet:"NIÊN",
vi:"~ năm",
en:"~ years",
word_type_vi:"Lượng từ",
word_type_en:"Counter",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>に 2<span class='target-word'><ruby>年<rt>ねん</rt></ruby></span> <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"にほんに にねん すんでいます。",
example_vi:"Tôi sống ở Nhật được 2 năm rồi.",
example_en:"I have lived in Japan for two years."
},

{
level:"N5",
lesson:11,
id:47,
kanji:"～ぐらい",
kana:"～ぐらい",
hanviet:"",
vi:"Khoảng ~",
en:"About / approximately",
word_type_vi:"Trợ từ",
word_type_en:"Particle",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>まで 10<span class='target-word'>ぐらい</span> かかります。",
example_read:"えきまで じゅっぷんぐらい かかります。",
example_vi:"Mất khoảng 10 phút đến nhà ga.",
example_en:"It takes about 10 minutes to get to the station."
},

{
level:"N5",
lesson:11,
id:48,
kanji:"どのくらい",
kana:"どのくらい",
hanviet:"",
vi:"Bao lâu, khoảng bao nhiêu",
en:"How long / how much",
word_type_vi:"Nghi vấn từ",
word_type_en:"Question word",
category:"Minna 1",
example:"<ruby>日本語<rt>にほんご</rt></ruby>を <span class='target-word'>どのくらい</span> <ruby>勉強<rt>べんきょう</rt></ruby>しましたか。",
example_read:"にほんごを どのくらい べんきょうしましたか。",
example_vi:"Bạn đã học tiếng Nhật được bao lâu rồi?",
example_en:"How long have you studied Japanese?"
},

{
level:"N5",
lesson:11,
id:49,
kanji:"全部で",
kana:"ぜんぶで",
hanviet:"TOÀN BỘ",
vi:"Tổng cộng",
en:"In total",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>全部<rt>ぜんぶ</rt></ruby>で</span> 5,000<ruby>円<rt>えん</rt></ruby>です。",
example_read:"ぜんぶで ごせんえんです。",
example_vi:"Tổng cộng là 5.000 yên.",
example_en:"The total is 5,000 yen."
},

{
level:"N5",
lesson:11,
id:50,
kanji:"皆",
kana:"みんな",
hanviet:"GIAI",
vi:"Mọi người, tất cả",
en:"Everyone / all",
word_type_vi:"Danh từ / trạng từ",
word_type_en:"Noun / Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>皆<rt>みんな</rt></ruby></span>で <ruby>写真<rt>しゃしん</rt></ruby>を <ruby>撮<rt>と</rt></ruby>りました。",
example_read:"みんなで しゃしんを とりました。",
example_vi:"Mọi người đã chụp ảnh cùng nhau.",
example_en:"Everyone took a picture together."
},

{
level:"N5",
lesson:11,
id:51,
kanji:"～だけ",
kana:"～だけ",
hanviet:"",
vi:"Chỉ ~",
en:"Only / just",
word_type_vi:"Trợ từ",
word_type_en:"Particle",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'>パンだけ</span> <ruby>食<rt>た</rt></ruby>べました。",
example_read:"きょうは ぱんだけ たべました。",
example_vi:"Hôm nay tôi chỉ ăn bánh mì.",
example_en:"I ate only bread today."
},

{
level:"N5",
lesson:11,
id:52,
kanji:"かしこまりました",
kana:"かしこまりました",
hanviet:"",
vi:"Tôi đã rõ rồi ạ",
en:"Certainly / Understood",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"「9<ruby>時<rt>じ</rt></ruby>ですね。」「はい、<span class='target-word'>かしこまりました</span>。」",
example_read:"くじですね。はい、かしこまりました。",
example_vi:"“9 giờ nhé.” “Vâng, tôi đã rõ ạ.”",
example_en:"“At 9 o'clock, okay?” “Yes, certainly.”"
},

{
level:"N5",
lesson:11,
id:53,
kanji:"いい[お]天気ですね",
kana:"いい[お]てんきですね",
hanviet:"THIÊN KHÍ",
vi:"Trời đẹp nhỉ",
en:"Nice weather, isn't it?",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'>いい[お]<ruby>天気<rt>てんき</rt></ruby>ですね</span>。<ruby>散歩<rt>さんぽ</rt></ruby>しませんか。",
example_read:"いいおてんきですね。さんぽしませんか。",
example_vi:"Trời đẹp nhỉ. Đi dạo nhé?",
example_en:"Nice weather, isn't it? Shall we take a walk?"
},

{
level:"N5",
lesson:11,
id:54,
kanji:"お出かけですか",
kana:"おでかけですか",
hanviet:"XUẤT",
vi:"Anh/chị đi ra ngoài đấy à?",
en:"Are you going out?",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"「<span class='target-word'>お<ruby>出<rt>で</rt></ruby>かけですか</span>。」「はい、ちょっと <ruby>駅<rt>えき</rt></ruby>まで。」",
example_read:"おでかけですか。はい、ちょっと えきまで。",
example_vi:"“Anh/chị đi ra ngoài à?” “Vâng, tôi đi ra ga một chút.”",
example_en:"“Are you going out?” “Yes, just to the station.”"
},

{
level:"N5",
lesson:11,
id:55,
kanji:"ちょっと～まで",
kana:"ちょっと～まで",
hanviet:"",
vi:"Tôi đi ~ một chút",
en:"Just to ~",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"「どちらへ？」「<span class='target-word'>ちょっと スーパーまで</span>。」",
example_read:"どちらへ。ちょっと すーぱーまで。",
example_vi:"“Đi đâu đấy?” “Tôi đi siêu thị một chút.”",
example_en:"“Where are you going?” “Just to the supermarket.”"
},

{
level:"N5",
lesson:11,
id:56,
kanji:"行っていらっしゃい",
kana:"いっていらっしゃい",
hanviet:"HÀNH",
vi:"Anh/chị đi nhé",
en:"See you / Have a good day",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>：「<span class='target-word'><ruby>行<rt>い</rt></ruby>っていらっしゃい</span>。」",
example_read:"いっていらっしゃい。",
example_vi:"Mẹ nói: “Con đi nhé.”",
example_en:"Mother says: “Take care.”"
},

{
level:"N5",
lesson:11,
id:57,
kanji:"行ってきます",
kana:"いってきます",
hanviet:"HÀNH",
vi:"Tôi đi đây",
en:"I'm leaving",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"「<span class='target-word'><ruby>行<rt>い</rt></ruby>ってきます。</span>」と <ruby>言<rt>い</rt></ruby>って <ruby>家<rt>いえ</rt></ruby>を <ruby>出<rt>で</rt></ruby>ます。",
example_read:"いってきます と いって いえを でます。",
example_vi:"Tôi nói “Tôi đi đây” rồi ra khỏi nhà.",
example_en:"I say “I'm leaving” and leave the house."
},

{
level:"N5",
lesson:11,
id:58,
kanji:"船便",
kana:"ふなびん",
hanviet:"THUYỀN TIỆN",
vi:"Gửi bằng đường biển",
en:"Surface mail / sea mail",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>荷物<rt>にもつ</rt></ruby>は <span class='target-word'><ruby>船便<rt>ふなびん</rt></ruby></span>で <ruby>送<rt>おく</rt></ruby>ります。",
example_read:"この にもつは ふなびんで おくります。",
example_vi:"Tôi gửi kiện hàng này bằng đường biển.",
example_en:"I will send this package by sea mail."
},

{
level:"N5",
lesson:11,
id:59,
kanji:"航空便",
kana:"こうくうびん",
hanviet:"HÀNG KHÔNG TIỆN",
vi:"Gửi bằng đường hàng không",
en:"Airmail",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>航空便<rt>こうくうびん</rt></ruby></span>の<ruby> 方<rt>ほう</rt></ruby>が <ruby> 速<rt>はや</rt></ruby>いです。",
example_read:"こうくうびんの ほうが はやいです。",
example_vi:"Gửi bằng đường hàng không thì nhanh hơn.",
example_en:"Sending by airmail is faster."
},

{
level:"N5",
lesson:11,
id:60,
kanji:"お願いします",
kana:"おねがいします",
hanviet:"NGUYỆN",
vi:"Làm ơn / Nhờ anh chị",
en:"Please",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"この <ruby>荷物<rt>にもつ</rt></ruby>を <span class='target-word'><ruby>お願<rt>ねが</rt></ruby>いします</span>。",
example_read:"この にもつを おねがいします。",
example_vi:"Làm ơn gửi giúp tôi kiện hàng này.",
example_en:"Please handle this package for me."
},

{
level:"N5",
lesson:11,
id:61,
kanji:"オーストラリア",
kana:"オーストラリア",
hanviet:"",
vi:"Úc",
en:"Australia",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>オーストラリア</span>へ <ruby>旅行<rt>りょこう</rt></ruby>したいです。",
example_read:"おーすとらりあへ りょこうしたいです。",
example_vi:"Tôi muốn đi du lịch Úc.",
example_en:"I want to travel to Australia."
}
];