window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[10] = [

{
level:"N5",
lesson:10,
id:1,
kanji:"有ります",
kana:"あります",
hanviet:"HỮU",
vi:"Có (tồn tại, dùng cho đồ vật)",
en:"There is / There are (inanimate)",
word_type_vi:"Động từ",
word_type_en:"Verb",
category:"Minna 1",
example:"テーブルの <ruby>上<rt>うえ</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>が <span class='target-word'><ruby>有<rt>あり</rt></ruby>ます</span>。",
example_read:"てーぶるの うえに ほんが あります。",
example_vi:"Có quyển sách trên bàn.",
example_en:"There is a book on the table."
},

{
level:"N5",
lesson:10,
id:2,
kanji:"居ます",
kana:"います",
hanviet:"CƯ",
vi:"Có, ở (tồn tại, dùng cho người và động vật)",
example:"<ruby>公園<rt>こうえん</rt></ruby>に <ruby>子供<rt>こども</rt></ruby>や <ruby>犬<rt>いぬ</rt></ruby>が <span class='target-word'><ruby>居<rt>い</rt></ruby>ます</span>。",
example_read:"こうえんに こどもや いぬが います。",
example_vi:"Trong công viên có trẻ em và chó.",
example_en:"There are children and dogs in the park."
},

{
level:"N5",
lesson:10,
id:3,
kanji:"色々[な]",
kana:"いろいろ[な]",
hanviet:"SẮC",
vi:"nhiều, đa dạng",
en:"Various / many kinds",
word_type_vi:"Tính từ-な / phó từ",
word_type_en:"Na- Adjective / Adverb",
category:"Minna 1",
example:"この <ruby>部屋<rt>へや</rt></ruby>には <span class='target-word'><ruby>色々<rt>いろいろ</rt></ruby>な</span> <ruby>物<rt>もの</rt></ruby>が <ruby>置<rt>お</rt></ruby>いて あります。",
example_read:"この へやには いろいろな ものが おいてあります。",
example_vi:"Trong phòng này có nhiều loại đồ vật khác nhau.",
example_en:"There are various kinds of things in this room."
},

{
level:"N5",
lesson:10,
id:4,
kanji:"男の人",
kana:"おとこのひと",
hanviet:"NAM NHÂN",
vi:"người đàn ông",
en:"man",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>道<rt>みち</rt></ruby>に <span class='target-word'><ruby>男<rt>おとこ</rt></ruby>の<ruby>人<rt>ひと</rt></ruby></span>が <ruby>立<rt>た</rt></ruby>っています。",
example_read:"みちに おとこのひとが たっています。",
example_vi:"Có một người đàn ông đang đứng trên đường.",
example_en:"A man is standing on the road."
},

{
level:"N5",
lesson:10,
id:5,
kanji:"女の人",
kana:"おんなのひと",
hanviet:"NỮ NHÂN",
vi:"người phụ nữ",
en:"woman",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>で <span class='target-word'><ruby>女<rt>おんな</rt></ruby>の<ruby>人<rt>ひと</rt></ruby></span>が <ruby>友達<rt>ともだち</rt></ruby>と <ruby>話<rt>はな</rt></ruby>しています。",
example_read:"えきで おんなのひとが ともだちと はなしています。",
example_vi:"Ở ga có một người phụ nữ đang nói chuyện với bạn.",
example_en:"A woman is talking with her friend at the station."
},

{
level:"N5",
lesson:10,
id:6,
kanji:"男の子",
kana:"おとこのこ",
hanviet:"NAM TỬ",
vi:"cậu con trai",
en:"boy",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>公園<rt>こうえん</rt></ruby>で <span class='target-word'><ruby>男<rt>おとこ</rt></ruby>の<ruby>子<rt>こ</rt></ruby></span>が <ruby>遊<rt>あそ</rt></ruby>んでいます。",
example_read:"こうえんで おとこのこが あそんでいます。",
example_vi:"Ở công viên có một cậu bé đang chơi.",
example_en:"A boy is playing in the park."
},

{
level:"N5",
lesson:10,
id:7,
kanji:"女の子",
kana:"おんなのこ",
hanviet:"NỮ TỬ",
vi:"cô bé",
en:"girl",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>公園<rt>こうえん</rt></ruby>で <span class='target-word'><ruby>女<rt>おんな</rt></ruby>の<ruby>子<rt>こ</rt></ruby></span>が <ruby>歌<rt>うた</rt></ruby>っています。",
example_read:"こうえんで おんなのこが うたっています。",
example_vi:"Ở công viên có một cô bé đang hát.",
example_en:"A girl is singing in the park."
},

{
level:"N5",
lesson:10,
id:8,
kanji:"犬",
kana:"いぬ",
hanviet:"KHUYỂN",
vi:"chó",
en:"dog",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>公園<rt>こうえん</rt></ruby>に <span class='target-word'><ruby>犬<rt>いぬ</rt></ruby></span>が います。",
example_read:"こうえんに いぬが います。",
example_vi:"Trong công viên có một con chó.",
example_en:"There is a dog in the park."
},

{
level:"N5",
lesson:10,
id:9,
kanji:"猫",
kana:"ねこ",
hanviet:"MIÊU",
vi:"mèo",
en:"cat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>部屋<rt>へや</rt></ruby>に <span class='target-word'><ruby>猫<rt>ねこ</rt></ruby></span>が います。",
example_read:"へやに ねこが います。",
example_vi:"Trong phòng có một con mèo.",
example_en:"There is a cat in the room."
},

{
level:"N5",
lesson:10,
id:10,
kanji:"パンダ",
kana:"パンダ",
hanviet:"",
vi:"gấu trúc",
en:"panda",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>動物園<rt>どうぶつえん</rt></ruby>に <span class='target-word'>パンダ</span>が います。",
example_read:"どうぶつえんに ぱんだが います。",
example_vi:"Ở sở thú có gấu trúc.",
example_en:"There is a panda at the zoo."
},

{
level:"N5",
lesson:10,
id:11,
kanji:"象",
kana:"ぞう",
hanviet:"TƯỢNG",
vi:"voi",
en:"elephant",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>動物園<rt>どうぶつえん</rt></ruby>の <span class='target-word'><ruby>象<rt>ぞう</rt></ruby></span>は とても <ruby>大<rt>おお</rt></ruby>きいです。",
example_read:"どうぶつえんの ぞうは とても おおきいです。",
example_vi:"Con voi ở sở thú rất to.",
example_en:"The elephant at the zoo is very big."
},

{
level:"N5",
lesson:10,
id:12,
kanji:"木",
kana:"き",
hanviet:"MỘC",
vi:"cây, gỗ",
en:"tree / wood",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>大<rt>おお</rt></ruby>きな <span class='target-word'><ruby>木<rt>き</rt></ruby></span>の <ruby>下<rt>した</rt></ruby>に <ruby>犬<rt>いぬ</rt></ruby>が います。",
example_read:"おおきな きの したに いぬが います。",
example_vi:"Có một con chó dưới gốc cây lớn.",
example_en:"There is a dog under a big tree."
},

{
level:"N5",
lesson:10,
id:13,
kanji:"物",
kana:"もの",
hanviet:"VẬT",
vi:"đồ vật",
en:"thing / object",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>箱<rt>はこ</rt></ruby>の <ruby>中<rt>なか</rt></ruby>に<ruby>色々<rt>いろいろ</rt></ruby>な  <span class='target-word'><ruby>物<rt>もの</rt></ruby></span>が あります。",
example_read:"この はこの なかに いろいろな ものが あります。",
example_vi:"Trong cái hộp này có nhiều loại đồ vật.",
example_en:"There are various things in this box."
},

{
level:"N5",
lesson:10,
id:14,
kanji:"電池",
kana:"でんち",
hanviet:"ĐIỆN TRÌ",
vi:"pin",
en:"battery",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>時計<rt>とけい</rt></ruby>は <span class='target-word'><ruby>電池<rt>でんち</rt></ruby></span>が ありません。",
example_read:"この とけいは でんちが ありません。",
example_vi:"Cái đồng hồ này không có pin.",
example_en:"This clock has no battery."
},

{
level:"N5",
lesson:10,
id:15,
kanji:"箱",
kana:"はこ",
hanviet:"TƯƠNG",
vi:"hộp",
en:"box",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>机<rt>つくえ</rt></ruby>の <ruby>上<rt>うえ</rt></ruby>に <span class='target-word'><ruby>箱<rt>はこ</rt></ruby></span>が あります。",
example_read:"つくえの うえに はこが あります。",
example_vi:"Có cái hộp trên bàn.",
example_en:"There is a box on the table."
},

{
level:"N5",
lesson:10,
id:16,
kanji:"スイッチ",
kana:"スイッチ",
hanviet:"",
vi:"công tắc",
en:"switch",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夜<rt>よる</rt></ruby>に <ruby>部屋<rt>へや</rt></ruby>の <span class='target-word'>スイッチ</span>を つけます。",
example_read:"よるに へやの すいっちを つけます。",
example_vi:"Ban đêm tôi bật công tắc trong phòng.",
example_en:"I turn on the switch in the room at night."
},

{
level:"N5",
lesson:10,
id:17,
kanji:"冷蔵庫",
kana:"れいぞうこ",
hanviet:"LÃNH TẠNG KHỐ",
vi:"tủ lạnh",
en:"refrigerator",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>冷蔵庫<rt>れいぞうこ</rt></ruby></span>の <ruby>中<rt>なか</rt></ruby>に <ruby>水<rt>みず</rt></ruby>が あります。",
example_read:"れいぞうこの なかに みずが あります。",
example_vi:"Có nước trong tủ lạnh.",
example_en:"There is water in the refrigerator."
},

{
level:"N5",
lesson:10,
id:18,
kanji:"テーブル",
kana:"テーブル",
hanviet:"",
vi:"bàn",
en:"table",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>テーブル</span>の <ruby>上<rt>うえ</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>が あります。",
example_read:"てーぶるの うえに ほんが あります。",
example_vi:"Có quyển sách trên bàn.",
example_en:"There is a book on the table."
},

{
level:"N5",
lesson:10,
id:19,
kanji:"ベッド",
kana:"ベッド",
hanviet:"",
vi:"giường",
en:"bed",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夜<rt>よる</rt></ruby>は <span class='target-word'>ベッド</span>で <ruby>本<rt>ほん</rt></ruby>を <ruby>読<rt>よ</rt></ruby>んでから <ruby>寝<rt>ね</rt></ruby>ます。",
example_read:"よるは べっどで ほんを よんでから ねます。",
example_vi:"Ban đêm tôi đọc sách trên giường rồi đi ngủ.",
example_en:"At night I read a book in bed and then sleep."
},

{
level:"N5",
lesson:10,
id:20,
kanji:"棚",
kana:"たな",
hanviet:"BẰNG",
vi:"giá sách, kệ",
en:"shelf",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>棚<rt>たな</rt></ruby></span>に <ruby>本<rt>ほん</rt></ruby>が たくさん あります。",
example_read:"たなに ほんが たくさん あります。",
example_vi:"Có rất nhiều sách trên kệ.",
example_en:"There are many books on the shelf."
},

{
level:"N5",
lesson:10,
id:21,
kanji:"ドア",
kana:"ドア",
hanviet:"",
vi:"cửa",
en:"door",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>部屋<rt>へや</rt></ruby>の <span class='target-word'>ドア</span>が <ruby>開<rt>あ</rt></ruby>いています。",
example_read:"へやの どあが あいています。",
example_vi:"Cửa phòng đang mở.",
example_en:"The room door is open."
},

{
level:"N5",
lesson:10,
id:22,
kanji:"窓",
kana:"まど",
hanviet:"SONG",
vi:"cửa sổ",
en:"window",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いですから、<span class='target-word'><ruby>窓<rt>まど</rt></ruby></span>を <ruby>開<rt>あ</rt></ruby>けます。",
example_read:"あついですから まどを あけます。",
example_vi:"Vì trời nóng nên tôi mở cửa sổ.",
example_en:"Because it is hot, I open the window."
},

{
level:"N5",
lesson:10,
id:23,
kanji:"ポスト",
kana:"ポスト",
hanviet:"",
vi:"hộp thư",
en:"mailbox",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ポスト</span>に <ruby>手紙<rt>てがみ</rt></ruby>を <ruby>入<rt>い</rt></ruby>れます。",
example_read:"ぽすとに てがみを いれます。",
example_vi:"Bỏ thư vào hòm thư.",
example_en:"Put a letter into the mailbox."
},

{
level:"N5",
lesson:10,
id:24,
kanji:"ビル",
kana:"ビル",
hanviet:"",
vi:"tòa nhà",
en:"building",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>の <ruby>前<rt>まえ</rt></ruby>に ある <span class='target-word'>ビル</span>は とても <ruby>高<rt>たか</rt></ruby>いです。",
example_read:"えきの まえに ある びるは とても たかいです。",
example_vi:"Tòa nhà ở trước nhà ga rất cao.",
example_en:"The building in front of the station is very tall."
},

{
level:"N5",
lesson:10,
id:25,
kanji:"ATM",
kana:"ATM",
hanviet:"",
vi:"máy rút tiền ATM",
en:"ATM",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>銀行<rt>ぎんこう</rt></ruby>の <span class='target-word'>ATM</span>で <ruby>お金<rt>おかね</rt></ruby>を <ruby>下<rt>お</rt></ruby>ろします。",
example_read:"ぎんこうの えーてぃーえむで おかねを おろします。",
example_vi:"Tôi rút tiền ở ATM của ngân hàng.",
example_en:"I withdraw money from the bank's ATM."
},

{
level:"N5",
lesson:10,
id:26,
kanji:"コンビニ",
kana:"コンビニ",
hanviet:"",
vi:"cửa hàng tiện lợi",
en:"convenience store",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>の <ruby>帰<rt>かえ</rt></ruby>りに <span class='target-word'>コンビニ</span>で <ruby>水<rt>みず</rt></ruby>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"しごとの かえりに こんびにで みずを かいます。",
example_vi:"Trên đường đi làm về tôi mua nước ở cửa hàng tiện lợi.",
example_en:"I buy water at a convenience store on my way home from work."
},

{
level:"N5",
lesson:10,
id:27,
kanji:"公園",
kana:"こうえん",
hanviet:"CÔNG VIÊN",
vi:"công viên",
en:"park",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>休<rt>やす</rt></ruby>みの <ruby>日<rt>ひ</rt></ruby>は <span class='target-word'><ruby>子<rt>こ</rt></ruby>ども</span>と <ruby>公園<rt>こうえん</rt></ruby>で <ruby>遊<rt>あそ</rt></ruby>びます。",
example_read:"やすみの ひは こどもと こうえんで あそびます。",
example_vi:"Vào ngày nghỉ tôi chơi ở công viên cùng con.",
example_en:"I play in the park with my child on my days off."
},

{
level:"N5",
lesson:10,
id:28,
kanji:"喫茶店",
kana:"きっさてん",
hanviet:"KHIẾT TRÀ ĐIẾM",
vi:"quán cà phê",
en:"café",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>喫茶店<rt>きっさてん</rt></ruby></span>で コーヒーを <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"ともだちと きっさてんで こーひーを のみます。",
example_vi:"Tôi uống cà phê với bạn ở quán cà phê.",
example_en:"I drink coffee with my friend at a café."
},

{
level:"N5",
lesson:10,
id:29,
kanji:"～屋",
kana:"～や",
hanviet:"ỐC",
vi:"cửa hàng ~",
en:"shop of ~",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'>パン<ruby>屋<rt>や</rt></ruby></span>へ <ruby>焼<rt>や</rt></ruby>きたての パンを <ruby>買<rt>か</rt></ruby>いに <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいあさ ぱんやへ やきたての ぱんを かいに いきます。",
example_vi:"Mỗi sáng tôi đến tiệm bánh để mua bánh mì mới nướng.",
example_en:"Every morning, I go to a bakery to buy freshly baked bread."
},

{
level:"N5",
lesson:10,
id:30,
kanji:"乗り場",
kana:"のりば",
hanviet:"THỪA TRÀNG",
vi:"bến xe",
en:"boarding platform",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"バスの <span class='target-word'><ruby>乗<rt>の</rt></ruby>り<ruby>場<rt>ば</rt></ruby></span>は あちらです。",
example_read:"ばすの のりばは あちらです。",
example_vi:"Điểm lên xe buýt ở đằng kia.",
example_en:"The bus stop is over there."
},

{
level:"N5",
lesson:10,
id:31,
kanji:"県",
kana:"けん",
hanviet:"HUYỆN",
vi:"tỉnh",
en:"prefecture",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>千葉<rt>ちば</rt></ruby><span class='target-word'><ruby>県<rt>けん</rt></ruby></span>に <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"ちばけんに すんでいます。",
example_vi:"Tôi đang sống ở tỉnh Chiba.",
example_en:"I live in Chiba Prefecture."
},

{
level:"N5",
lesson:10,
id:32,
kanji:"上",
kana:"うえ",
hanviet:"THƯỢNG",
vi:"trên",
en:"above / on top",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"テーブルの <span class='target-word'><ruby>上<rt>うえ</rt></ruby></span>に <ruby>新聞<rt>しんぶん</rt></ruby>が あります。",
example_read:"てーぶるの うえに しんぶんが あります。",
example_vi:"Có tờ báo ở trên bàn.",
example_en:"There is a newspaper on the table."
},

{
level:"N5",
lesson:10,
id:33,
kanji:"下",
kana:"した",
hanviet:"HẠ",
vi:"dưới",
en:"below / under",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"テーブルの <span class='target-word'><ruby>下<rt>した</rt></ruby></span>に <ruby>猫<rt>ねこ</rt></ruby>が います。",
example_read:"てーぶるの したに ねこが います。",
example_vi:"Có một con mèo ở dưới bàn.",
example_en:"There is a cat under the table."
},

{
level:"N5",
lesson:10,
id:34,
kanji:"前",
kana:"まえ",
hanviet:"TIỀN",
vi:"trước",
en:"front / before",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>の <span class='target-word'><ruby>前<rt>まえ</rt></ruby></span>に <ruby>喫茶店<rt>きっさてん</rt></ruby>が あります。",
example_read:"えきの まえに きっさてんが あります。",
example_vi:"Có quán cà phê ở trước nhà ga.",
example_en:"There is a café in front of the station."
},

{
level:"N5",
lesson:10,
id:35,
kanji:"後",
kana:"うしろ",
hanviet:"HẬU",
vi:"sau / phía sau",
en:"behind",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>椅子<rt>いす</rt></ruby>の <span class='target-word'><ruby>後<rt>うし</rt></ruby>ろ</span>に <ruby>猫<rt>ねこ</rt></ruby>が います。",
example_read:"いすの うしろに ねこが います。",
example_vi:"Có một con mèo ở phía sau cái ghế.",
example_en:"There is a cat behind the chair."
},

{
level:"N5",
lesson:10,
id:36,
kanji:"右",
kana:"みぎ",
hanviet:"HỮU",
vi:"bên phải",
en:"right",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>の <ruby>前<rt>まえ</rt></ruby>で <span class='target-word'><ruby>右<rt>みぎ</rt></ruby>へ</span> <ruby>曲<rt>ま</rt></ruby>がってください。",
example_read:"えきの まえで みぎへ まがってください。",
example_vi:"Xin hãy rẽ phải ở trước nhà ga.",
example_en:"Please turn right in front of the station."
},

{
level:"N5",
lesson:10,
id:37,
kanji:"左",
kana:"ひだり",
hanviet:"TẢ",
vi:"bên trái",
en:"left",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>の <span class='target-word'><ruby>左<rt>ひだり</rt></ruby></span>に <ruby>銀行<rt>ぎんこう</rt></ruby>が あります。",
example_read:"えきの ひだりに ぎんこうが あります。",
example_vi:"Có ngân hàng ở bên trái nhà ga.",
example_en:"There is a bank to the left of the station."
},

{
level:"N5",
lesson:10,
id:38,
kanji:"中",
kana:"なか",
hanviet:"TRUNG",
vi:"trong / giữa",
en:"inside",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>箱<rt>はこ</rt></ruby>の <span class='target-word'><ruby>中<rt>なか</rt></ruby></span>に <ruby>色々<rt>いろいろ</rt></ruby>な <ruby>物<rt>もの</rt></ruby>が あります。",
example_read:"はこの なかに いろいろな ものが あります。",
example_vi:"Có nhiều loại đồ vật trong hộp.",
example_en:"There are various things inside the box."
},

{
level:"N5",
lesson:10,
id:39,
kanji:"外",
kana:"そと",
hanviet:"NGOẠI",
vi:"ngoài",
en:"outside",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>外<rt>そと</rt></ruby></span>は <ruby>寒<rt>さむ</rt></ruby>いですから、コートを <ruby>着<rt>き</rt></ruby>てください。",
example_read:"そとは さむいですから こーとを きてください。",
example_vi:"Bên ngoài lạnh nên hãy mặc áo khoác nhé.",
example_en:"It's cold outside, so please wear a coat."
},

{
level:"N5",
lesson:10,
id:40,
kanji:"隣",
kana:"となり",
hanviet:"LÂN",
vi:"bên cạnh",
en:"next to",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"コンビニの <span class='target-word'><ruby>隣<rt>となり</rt></ruby></span>に<ruby>駅 <rt>えき</rt></ruby>が あります。",
example_read:"こんびにの となりに えきが あります。",
example_vi:"Bên cạnh cửa hàng tiện lợi có nhà ga.",
example_en:"There is a station next to the convenience store."
},

{
level:"N5",
lesson:10,
id:41,
kanji:"近く",
kana:"ちかく",
hanviet:"CẬN",
vi:"gần",
en:"near / nearby",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>近<rt>ちか</rt></ruby>く</span>に <ruby>公園<rt>こうえん</rt></ruby>が あります。",
example_read:"ちかくに こうえんが あります。",
example_vi:"Gần đây có công viên.",
example_en:"There is a park nearby."
},

{
level:"N5",
lesson:10,
id:42,
kanji:"間",
kana:"あいだ",
hanviet:"GIAN",
vi:"giữa",
en:"between",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"テーブルと <ruby>椅子<rt>いす</rt></ruby>の <span class='target-word'><ruby>間<rt>あいだ</rt></ruby></span>に <ruby>猫<rt>ねこ</rt></ruby>が います。",
example_read:"てーぶると いすの あいだに ねこが います。",
example_vi:"Có một con mèo ở giữa bàn và ghế.",
example_en:"There is a cat between the table and the chair."
},

{
level:"N5",
lesson:10,
id:43,
kanji:"～や～など",
kana:"～や～など",
hanviet:"",
vi:"~ và ~, v.v.",
en:"and so on",
word_type_vi:"Cấu trúc",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>動物園<rt>どうぶつえん</rt></ruby>には <ruby>象<rt>ぞう</rt></ruby>や パンダなどが います。",
example_read:"どうぶつえんには ぞうや ぱんだなどが います。",
example_vi:"Trong sở thú có voi, gấu trúc và nhiều loài khác.",
example_en:"There are elephants, pandas, and other animals at the zoo."
},

{
level:"N5",
lesson:10,
id:44,
kanji:"[どうも]すみません",
kana:"[どうも]すみません",
hanviet:"",
vi:"Cám ơn (rất nhiều) / Xin lỗi (rất lịch sự)",
en:"Thank you very much / Sorry very much",
word_type_vi:"Cụm từ",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'>どうもすみません</span>。<ruby>助<rt>たす</rt></ruby>かりました。",
example_read:"どうもすみません。たすかりました。",
example_vi:"Cảm ơn anh/chị rất nhiều. Anh/chị đã giúp tôi rất nhiều.",
example_en:"Thank you very much. You really helped me."
},

{
level:"N5",
lesson:10,
id:45,
kanji:"ナンプラー",
kana:"ナンプラー",
hanviet:"",
vi:"nước mắm (nampla)",
en:"fish sauce",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"タイの <ruby>料理<rt>りょうり</rt></ruby>には <span class='target-word'>ナンプラー</span>を よく <ruby>使<rt>つか</rt></ruby>います。",
example_read:"たいの りょうりには なんぷらーを よく つかいます。",
example_vi:"Trong các món ăn Thái người ta thường dùng nước mắm Nam Pla.",
example_en:"Thai dishes often use fish sauce (nam pla)."
},

{
level:"N5",
lesson:10,
id:46,
kanji:"コーナー",
kana:"コーナー",
hanviet:"",
vi:"góc / khu vực",
en:"corner / section",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>魚<rt>さかな</rt></ruby>の <span class='target-word'>コーナー</span>で <ruby>魚<rt>さかな</rt></ruby>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"さかなの こーなーで さかなを かいました。",
example_vi:"Tôi đã mua cá ở khu bán cá.",
example_en:"I bought fish at the fish section."
},

{
level:"N5",
lesson:10,
id:47,
kanji:"一番下",
kana:"いちばんした",
hanviet:"NHẤT PHIÊN HẠ",
vi:"dưới cùng",
en:"bottom",
word_type_vi:"Cụm danh từ",
word_type_en:"Phrase",
category:"Minna 1",
example:"<ruby>電池<rt>でんち</rt></ruby>は <ruby>引<rt>ひ</rt></ruby>き<ruby>出<rt>だ</rt></ruby>しの <span class='target-word'><ruby>一番下<rt>いちばんした</rt></ruby></span>に あります。",
example_read:"でんちは ひきだしの いちばんしたに あります。",
example_vi:"Pin ở ngăn dưới cùng của ngăn kéo.",
example_en:"The batteries are in the bottom drawer."
},

{
level:"N5",
lesson:10,
id:48,
kanji:"東京ディズニーランド",
kana:"とうきょうディズニーランド",
hanviet:"ĐÔNG KINH",
vi:"Tokyo Disneyland",
en:"Tokyo Disneyland",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>今度<rt>こんど</rt></ruby>の <ruby>休<rt>やす</rt></ruby>みに <span class='target-word'><ruby>東京<rt>とうきょう</rt></ruby>ディズニーランド</span>へ <ruby>行<rt>い</rt></ruby>きたいです。",
example_read:"こんどの やすみに とうきょうでぃずにーらんどへ いきたいです。",
example_vi:"Kỳ nghỉ tới tôi muốn đi Tokyo Disneyland.",
example_en:"I want to go to Tokyo Disneyland on my next day off."
},

{
level:"N5",
lesson:10,
id:49,
kanji:"アジアストア",
kana:"アジアストア",
hanviet:"",
vi:"Asia Store",
en:"Asia Store",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>アジアストア</span>で ベトナムの <ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"あじあすとあで べとなむの たべものを かいます。",
example_vi:"Tôi mua đồ ăn Việt Nam ở Asia Store.",
example_en:"I buy Vietnamese food at Asia Store."
}
];