window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[25] = [

{
level:"N5",
lesson:25,
id:1,
kanji:"考えます",
kana:"かんがえます",
hanviet:"KHẢO",
vi:"nghĩ, suy nghĩ",
en:"think, consider",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby>の <ruby>予定<rt>よてい</rt></ruby>を <span class='target-word'><ruby>考<rt>かんが</rt></ruby>えます</span>。",
example_read:"あしたの よていを かんがえます",
example_vi:"Tôi suy nghĩ về kế hoạch ngày mai.",
example_en:"I think about tomorrow's plans."
},

{
level:"N5",
lesson:25,
id:2,
kanji:"着きます",
kana:"つきます",
hanviet:"TRỨ",
vi:"đến, tới",
en:"arrive",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"7<ruby>時<rt>じ</rt></ruby>に <ruby>駅<rt>えき</rt></ruby>に <span class='target-word'><ruby>着<rt>つ</rt></ruby>きました</span>。",
example_read:"しちじに えきに つきました",
example_vi:"Tôi đã đến ga lúc 7 giờ.",
example_en:"I arrived at the station at 7 o'clock."
},

{
level:"N5",
lesson:25,
id:3,
kanji:"取ります",
kana:"とります",
hanviet:"THỦ",
vi:"thêm [tuổi]",
en:"get older (gain years)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>年<rt>とし</rt></ruby>を <span class='target-word'><ruby>取<rt>と</rt></ruby>ります</span>。",
example_read:"ちちは としを とります",
example_vi:"Bố tôi thêm tuổi (già đi).",
example_en:"My father gets older."
},

{
level:"N5",
lesson:25,
id:4,
kanji:"足ります",
kana:"たります",
hanviet:"TÚC",
vi:"đủ",
en:"be enough",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"お<ruby>金<rt>かね</rt></ruby>が <span class='target-word'><ruby>足<rt>た</rt></ruby>ります</span>か。",
example_read:"おかねが たりますか",
example_vi:"Tiền có đủ không?",
example_en:"Is the money enough?"
},

{
level:"N5",
lesson:25,
id:5,
kanji:"田舎",
kana:"いなか",
hanviet:"ĐIỀN XÁ",
vi:"quê, nông thôn",
en:"countryside, hometown",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>田舎<rt>いなか</rt></ruby></span>は <ruby>静<rt>しず</rt></ruby>かな <ruby>所<rt>ところ</rt></ruby>です。",
example_read:"いなかは しずかな ところです",
example_vi:"Nông thôn là một nơi yên tĩnh.",
example_en:"The countryside is a quiet place."
},

{
level:"N5",
lesson:25,
id:6,
kanji:"チャンス",
kana:"チャンス",
hanviet:"",
vi:"cơ hội",
en:"chance, opportunity",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"これは <span class='target-word'>チャンス</span>ですから、<ruby>頑張<rt>がんば</rt></ruby>ります。",
example_read:"これは チャンスですから がんばります",
example_vi:"Vì đây là cơ hội nên tôi sẽ cố gắng.",
example_en:"This is a chance, so I will do my best."
},

{
level:"N5",
lesson:25,
id:7,
kanji:"億",
kana:"おく",
hanviet:"ỨC",
vi:"một trăm triệu",
en:"one hundred million",
word_type_vi:"Danh từ / Đơn vị số",
word_type_en:"Number counter",
category:"Minna 1",
example:"その<ruby>会社<rt>かいしゃ</rt></ruby>は <ruby>売上<rt>うりあげ</rt></ruby>が 10<span class='target-word'><ruby>億<rt>おく</rt></ruby></span><ruby>円<rt>えん</rt></ruby>あります。",
example_read:"その かいしゃは うりあげが じゅうおくえん あります",
example_vi:"Công ty đó có doanh thu 1 tỷ yên.",
example_en:"That company has sales of one billion yen."
},

{
level:"N5",
lesson:25,
id:8,
kanji:"",
kana:"もし～たら",
hanviet:"",
vi:"nếu [~ thì]",
en:"if ~, when ~",
word_type_vi:"Mẫu câu",
word_type_en:"Grammar pattern",
category:"Minna 1",
example:"<span class='target-word'>もし</span><ruby>時間<rt>じかん</rt></ruby>が あったら、<ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"もし じかんが あったら えいがを みます",
example_vi:"Nếu có thời gian thì tôi sẽ xem phim.",
example_en:"If I have time, I will watch a movie."
},

{
level:"N5",
lesson:25,
id:9,
kanji:"意味",
kana:"いみ",
hanviet:"Ý VỊ",
vi:"nghĩa, ý nghĩa",
en:"meaning",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この<ruby>言葉<rt>ことば</rt></ruby>の <span class='target-word'><ruby>意味<rt>いみ</rt></ruby></span>が <ruby>分<rt>わ</rt></ruby>かりません。",
example_read:"この ことばの いみが わかりません",
example_vi:"Tôi không hiểu nghĩa của từ này.",
example_en:"I don't understand the meaning of this word."
},

{
level:"N5",
lesson:25,
id:10,
kanji:"",
kana:"もしもし",
hanviet:"",
vi:"A-lô",
en:"hello (on the phone)",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>もしもし</span>、<ruby>田中<rt>たなか</rt></ruby>さんですか。",
example_read:"もしもし たなかさんですか",
example_vi:"A-lô, có phải anh Tanaka không ạ?",
example_en:"Hello, is this Mr. Tanaka?"
},

{
level:"N5",
lesson:25,
id:11,
kanji:"転勤",
kana:"てんきん",
hanviet:"CHUYỂN CẦN",
vi:"việc chuyển địa điểm làm việc",
en:"job transfer",
word_type_vi:"Danh từ / Động từ nhóm 3 (転勤します)",
word_type_en:"Noun / Suru verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'><ruby>転勤<rt>てんきん</rt></ruby></span>して、<ruby>大阪<rt>おおさか</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きました。",
example_read:"ちちは てんきんして おおさかへ いきました",
example_vi:"Bố tôi chuyển công tác và đã đi đến Osaka.",
example_en:"My father was transferred and went to Osaka."
},

{
level:"N5",
lesson:25,
id:12,
kanji:"こと",
kana:"こと",
hanviet:"",
vi:"việc, chuyện (~のこと: việc ~)",
en:"thing, matter",
word_type_vi:"Danh từ hóa / Danh từ",
word_type_en:"Nominalizer / Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>の <span class='target-word'>こと</span>を もっと <ruby>知<rt>し</rt></ruby>りたいです。",
example_read:"にほんの ことを もっと しりたいです",
example_vi:"Tôi muốn biết thêm về Nhật Bản.",
example_en:"I want to know more about Japan."
},

{
level:"N5",
lesson:25,
id:13,
kanji:"暇",
kana:"ひま",
hanviet:"HẠ",
vi:"thời gian rảnh",
en:"free time",
word_type_vi:"Danh từ / Tính từ đuôi な",
word_type_en:"Noun / Na-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>暇<rt>ひま</rt></ruby></span>な <ruby>時<rt>とき</rt></ruby>、<ruby>本<rt>ほん</rt></ruby>を <ruby>読<rt>よ</rt></ruby>みます。",
example_read:"ひまな とき ほんを よみます",
example_vi:"Khi rảnh tôi đọc sách.",
example_en:"I read books when I have free time."
},

{
level:"N5",
lesson:25,
id:14,
kanji:"色々お世話になりました",
kana:"いろいろ おせわに なりました",
hanviet:"SẮC THẾ THOẠI",
vi:"Anh/chị đã giúp đỡ tôi rất nhiều.",
en:"Thank you for everything you have done for me.",
word_type_vi:"Câu chào hỏi",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'><ruby>色々<rt>いろいろ</rt></ruby>お<ruby>世話<rt>せわ</rt></ruby>になりました</span>。",
example_read:"いろいろ おせわに なりました",
example_vi:"Cảm ơn anh/chị đã giúp đỡ tôi trong thời gian qua.",
example_en:"Thank you very much for all your help."
},

{
level:"N5",
lesson:25,
id:15,
kanji:"頑張ります",
kana:"がんばります",
hanviet:"NGOAN TRƯƠNG",
vi:"cố gắng",
en:"do one's best, try hard",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<span class='target-word'><ruby>頑張<rt>がんば</rt></ruby>ります</span>から、<ruby>応援<rt>おうえん</rt></ruby>してください。",
example_read:"がんばりますから おうえんしてください",
example_vi:"Tôi sẽ cố gắng nên hãy ủng hộ tôi nhé.",
example_en:"I will do my best, so please support me."
},

{
level:"N5",
lesson:25,
id:16,
kanji:"どうぞお元気で",
kana:"どうぞおげんきで",
hanviet:"NGUYÊN KHÍ",
vi:"Chúc anh/chị mạnh khỏe.",
en:"Please take care of yourself.",
word_type_vi:"Câu chào hỏi",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'>どうぞお<ruby>元気<rt>げんき</rt></ruby>で</span>。",
example_read:"どうぞ おげんきで",
example_vi:"Chúc anh/chị luôn mạnh khỏe.",
example_en:"Please stay healthy."
},

{
level:"N5",
lesson:25,
id:17,
kanji:"",
kana:"ベトナム",
hanviet:"",
vi:"Việt Nam",
en:"Vietnam",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ベトナム</span>は <ruby>東南<rt>とうなん</rt></ruby>アジアの <ruby>国<rt>くに</rt></ruby>です。",
example_read:"ベトナムは とうなんアジアの くにです",
example_vi:"Việt Nam là một quốc gia ở Đông Nam Á.",
example_en:"Vietnam is a country in Southeast Asia."
}
];