window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[12] = [

{
level:"N5",
lesson:12,
id:1,
kanji:"簡単[な]",
kana:"かんたん[な]",
hanviet:"GIẢN ĐƠN",
vi:"đơn giản, dễ",
en:"easy / simple",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"これは <span class='target-word'><ruby>簡単<rt>かんたん</rt></ruby>な</span> <ruby>問題<rt>もんだい</rt></ruby>です。",
example_read:"これは かんたんな もんだいです",
example_vi:"Đây là một bài tập đơn giản.",
example_en:"This is an easy problem."
},

{
level:"N5",
lesson:12,
id:2,
kanji:"近い",
kana:"ちかい",
hanviet:"CẬN",
vi:"gần",
en:"near",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>駅<rt>えき</rt></ruby>は <span class='target-word'><ruby>近<rt>ちか</rt></ruby>い</span>です。",
example_read:"この えきは ちかいです",
example_vi:"Nhà ga này ở gần.",
example_en:"This station is near."
},

{
level:"N5",
lesson:12,
id:3,
kanji:"遠い",
kana:"とおい",
hanviet:"VIỄN",
vi:"xa",
en:"far",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>空港<rt>くうこう</rt></ruby>は ここから <span class='target-word'><ruby>遠<rt>とお</rt></ruby>い</span>です。",
example_read:"くうこうは ここから とおいです",
example_vi:"Sân bay ở xa đây",
example_en:"The airport is far from here"
},

{
level:"N5",
lesson:12,
id:4,
kanji:"速い",
kana:"はやい",
hanviet:"TỐC",
vi:"nhanh",
en:"fast",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>航空便<rt>こうくうびん</rt></ruby>の <ruby>方<rt>ほう</rt></ruby>が <span class='target-word'><ruby>速<rt>はや</rt></ruby>い</span>です。",
example_read:"こうくうびんの ほうが はやいです",
example_vi:"Gửi bằng đường hàng không thì nhanh hơn.",
example_en:"Sending by airmail is faster."
},

{
level:"N5",
lesson:12,
id:5,
kanji:"早い",
kana:"はやい",
hanviet:"TẢO",
vi:"sớm",
en:"early",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'><ruby>早<rt>はや</rt></ruby>く</span> <ruby>起<rt>お</rt></ruby>きます。",
example_read:"まいあさ はやく おきます",
example_vi:"Tôi dậy sớm mỗi sáng.",
example_en:"I get up early every morning."
},

{
level:"N5",
lesson:12,
id:6,
kanji:"遅い",
kana:"おそい",
hanviet:"TRÌ",
vi:"chậm, muộn",
en:"slow / late",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>遅<rt>おそ</rt></ruby>い</span> <ruby>時間<rt>じかん</rt></ruby>に <ruby>寝<rt>ね</rt></ruby>ます。",
example_read:"きょうは おそい じかんに ねます",
example_vi:"Hôm nay tôi sẽ ngủ muộn.",
example_en:"I will go to bed late today."
},

{
level:"N5",
lesson:12,
id:7,
kanji:"多い",
kana:"おおい",
hanviet:"ĐA",
vi:"nhiều",
en:"many",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>町<rt>まち</rt></ruby>は <ruby>人<rt>ひと</rt></ruby>が <span class='target-word'><ruby>多<rt>おお</rt></ruby>い</span>です。",
example_read:"この まちは ひとが おおいです",
example_vi:"Thị trấn này đông người.",
example_en:"This town has a lot of people."
},

{
level:"N5",
lesson:12,
id:8,
kanji:"少ない",
kana:"すくない",
hanviet:"THIỂU",
vi:"ít",
en:"few",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この クラスは <ruby>学生<rt>がくせい</rt></ruby>が <span class='target-word'><ruby>少<rt>すく</rt></ruby>ない</span>です。",
example_read:"この クラスは がくせいが すくないです",
example_vi:"Lớp này có ít học sinh.",
example_en:"This class has few students."
},

{
level:"N5",
lesson:12,
id:9,
kanji:"暖かい",
kana:"あたたかい",
hanviet:"NOÃN",
vi:"ấm",
en:"warm",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>春<rt>はる</rt></ruby>は <span class='target-word'><ruby>暖<rt>あたた</rt></ruby>かい</span>です。",
example_read:"はるは あたたかいです",
example_vi:"Mùa xuân thì ấm áp.",
example_en:"Spring is warm."
},

{
level:"N5",
lesson:12,
id:10,
kanji:"涼しい",
kana:"すずしい",
hanviet:"LƯƠNG",
vi:"mát",
en:"cool",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>夜<rt>よる</rt></ruby>は <span class='target-word'><ruby>涼<rt>すず</rt></ruby>しい</span>です。",
example_read:"よるは すずしいです",
example_vi:"Ban đêm thì mát mẻ.",
example_en:"It's cool at night."
},

{
level:"N5",
lesson:12,
id:11,
kanji:"甘い",
kana:"あまい",
hanviet:"CAM",
vi:"ngọt",
en:"sweet",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>甘<rt>あま</rt></ruby>い</span> <ruby>食<rt>た</rt></ruby>べ<ruby>物<rt>もの</rt></ruby>が <ruby>好<rt>す</rt></ruby>きです。",
example_read:"あまい たべものが すきです",
example_vi:"Tôi thích đồ ăn ngọt.",
example_en:"I like sweet foods."
},

{
level:"N5",
lesson:12,
id:12,
kanji:"辛い",
kana:"からい",
hanviet:"TÂN",
vi:"cay",
en:"spicy",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この カレーは <span class='target-word'><ruby>辛<rt>から</rt></ruby>い</span>です。",
example_read:"この カレーは からいです",
example_vi:"Món cà ri này cay.",
example_en:"This curry is spicy."
},

{
level:"N5",
lesson:12,
id:13,
kanji:"重い",
kana:"おもい",
hanviet:"TRỌNG",
vi:"nặng",
en:"heavy",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>重<rt>おも</rt></ruby>い</span>ので、<ruby>一人<rt>ひとり</rt></ruby>で <ruby>持<rt>も</rt></ruby>てません。",
example_read:"おもいので ひとりで もてません",
example_vi:"Vì nặng nên tôi không thể mang một mình.",
example_en:"It's heavy, so I can't carry it by myself."
},

{
level:"N5",
lesson:12,
id:14,
kanji:"軽い",
kana:"かるい",
hanviet:"KHINH",
vi:"nhẹ",
en:"light",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>荷物<rt>にもつ</rt></ruby>は <span class='target-word'><ruby>軽<rt>かる</rt></ruby>い</span>です。",
example_read:"この にもつは かるいです",
example_vi:"Hành lý này nhẹ.",
example_en:"This luggage is light."
},

{
level:"N5",
lesson:12,
id:15,
kanji:"[コーヒーが～]いい",
kana:"[コーヒーが～]いい",
hanviet:"",
vi:"thích, chọn, dùng [cà phê]",
en:"prefer / choose",
word_type_vi:"Tính từ",
word_type_en:"Adjective",
category:"Minna 1",
example:"A：お<ruby>茶<rt>ちゃ</rt></ruby>と コーヒー、どちらが いいですか。<br>B：<span class='target-word'>コーヒーがいい</span>です。",
example_read:"A：おちゃと コーヒー、どちらが いいですか。 B：コーヒーが いいです",
example_vi:"A: Trà và cà phê, bạn chọn món nào? B: Tôi chọn cà phê.",
example_en:"A: Tea or coffee, which would you like? B: I'll have coffee."
},

{
level:"N5",
lesson:12,
id:16,
kanji:"季節",
kana:"きせつ",
hanviet:"QUÝ TIẾT",
vi:"mùa",
en:"season",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>季節<rt>きせつ</rt></ruby></span>は <ruby>四<rt>よっ</rt></ruby>つあります。<ruby>春<rt>はる</rt></ruby>、<ruby>夏<rt>なつ</rt></ruby>、<ruby>秋<rt>あき</rt></ruby>、<ruby>冬<rt>ふゆ</rt></ruby>です。",
example_read:"きせつは よっつあります。はる、なつ、あき、ふゆです",
example_vi:"Có bốn mùa. Đó là xuân, hạ, thu và đông.",
example_en:"There are four seasons: spring, summer, autumn, and winter."
},

{
level:"N5",
lesson:12,
id:17,
kanji:"春",
kana:"はる",
hanviet:"XUÂN",
vi:"mùa xuân",
en:"spring",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>春<rt>はる</rt></ruby></span>は <ruby>暖<rt>あたた</rt></ruby>かいです。",
example_read:"はるは あたたかいです",
example_vi:"Mùa xuân thì ấm áp.",
example_en:"Spring is warm."
},

{
level:"N5",
lesson:12,
id:18,
kanji:"夏",
kana:"なつ",
hanviet:"HẠ",
vi:"mùa hè",
en:"summer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>夏<rt>なつ</rt></ruby></span>は <ruby>暑<rt>あつ</rt></ruby>いです。",
example_read:"なつは あついです",
example_vi:"Mùa hè thì nóng.",
example_en:"Summer is hot."
},

{
level:"N5",
lesson:12,
id:19,
kanji:"秋",
kana:"あき",
hanviet:"THU",
vi:"mùa thu",
en:"autumn",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>秋<rt>あき</rt></ruby></span>は <ruby>涼<rt>すず</rt></ruby>しいです。",
example_read:"あきは すずしいです",
example_vi:"Mùa thu thì mát mẻ.",
example_en:"Autumn is cool."
},

{
level:"N5",
lesson:12,
id:20,
kanji:"冬",
kana:"ふゆ",
hanviet:"ĐÔNG",
vi:"mùa đông",
en:"winter",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>冬<rt>ふゆ</rt></ruby></span>は <ruby>寒<rt>さむ</rt></ruby>いです。",
example_read:"ふゆは さむいです",
example_vi:"Mùa đông thì lạnh.",
example_en:"Winter is cold."
},

{
level:"N5",
lesson:12,
id:21,
kanji:"天気",
kana:"てんき",
hanviet:"THIÊN KHÍ",
vi:"thời tiết",
en:"weather",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>の <span class='target-word'><ruby>天気<rt>てんき</rt></ruby></span>は とても いいので、<ruby>散歩<rt>さんぽ</rt></ruby>したいです。",
example_read:"きょうの てんきは とても いいので、さんぽしたいです",
example_vi:"Hôm nay thời tiết rất đẹp nên tôi muốn đi dạo.",
example_en:"The weather is very nice today, so I want to take a walk."
},

{
level:"N5",
lesson:12,
id:22,
kanji:"雨",
kana:"あめ",
hanviet:"VŨ",
vi:"mưa",
en:"rain",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>雨<rt>あめ</rt></ruby></span>ですから、<ruby>出<rt>で</rt></ruby>かけません。",
example_read:"きょうは あめですから、でかけません",
example_vi:"Hôm nay trời mưa nên tôi không ra ngoài.",
example_en:"It's raining today, so I won't go out."
},

{
level:"N5",
lesson:12,
id:23,
kanji:"雪",
kana:"ゆき",
hanviet:"TUYẾT",
vi:"tuyết",
en:"snow",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby> <span class='target-word'><ruby>雪<rt>ゆき</rt></ruby></span>が <ruby>降<rt>ふ</rt></ruby>りました。",
example_read:"きのう ゆきが ふりました",
example_vi:"Hôm qua có tuyết rơi.",
example_en:"It snowed yesterday."
},

{
level:"N5",
lesson:12,
id:24,
kanji:"曇り",
kana:"くもり",
hanviet:"ĐÀM",
vi:"có mây",
en:"cloudy",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby>は <span class='target-word'><ruby>曇<rt>くも</rt></ruby>り</span>だそうです。",
example_read:"あしたは くもりだそうです",
example_vi:"Nghe nói ngày mai trời nhiều mây.",
example_en:"I heard it will be cloudy tomorrow."
},

{
level:"N5",
lesson:12,
id:25,
kanji:"ホテル",
kana:"ホテル",
hanviet:"",
vi:"khách sạn",
en:"hotel",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'>ホテル</span>に <ruby>泊<rt>と</rt></ruby>まります。",
example_read:"この ホテルに とまります",
example_vi:"Tôi sẽ ở khách sạn này.",
example_en:"I will stay at this hotel."
},

{
level:"N5",
lesson:12,
id:26,
kanji:"空港",
kana:"くうこう",
hanviet:"KHÔNG CẢNG",
vi:"sân bay",
en:"airport",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby> バスで <span class='target-word'><ruby>空港<rt>くうこう</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"あした バスで くうこうへ いきます",
example_vi:"Ngày mai tôi sẽ đi sân bay bằng xe buýt.",
example_en:"I will go to the airport by bus tomorrow."
},

{
level:"N5",
lesson:12,
id:27,
kanji:"海",
kana:"うみ",
hanviet:"HẢI",
vi:"biển",
en:"sea",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夏<rt>なつ</rt></ruby>は <span class='target-word'><ruby>海<rt>うみ</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>くのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"なつは うみへ いくのが すきです",
example_vi:"Vào mùa hè tôi thích đi biển.",
example_en:"I like going to the beach in summer."
},

{
level:"N5",
lesson:12,
id:28,
kanji:"世界",
kana:"せかい",
hanviet:"THẾ GIỚI",
vi:"thế giới",
en:"world",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>世界<rt>せかい</rt></ruby></span>には <ruby>色々<rt>いろいろ</rt></ruby>な <ruby>国<rt>くに</rt></ruby>が あります。",
example_read:"せかいには いろいろな くにが あります",
example_vi:"Trên thế giới có nhiều quốc gia khác nhau.",
example_en:"There are many different countries in the world."
},

{
level:"N5",
lesson:12,
id:29,
kanji:"パーティー",
kana:"パーティー",
hanviet:"",
vi:"tiệc",
en:"party",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'>パーティー</span>を します。",
example_read:"ともだちと パーティーを します",
example_vi:"Tôi sẽ tổ chức tiệc cùng bạn bè.",
example_en:"I will have a party with my friends."
},

{
level:"N5",
lesson:12,
id:30,
kanji:"[お]祭り",
kana:"[お]まつり",
hanviet:"TẾ",
vi:"lễ hội",
en:"festival",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'>お<ruby>祭<rt>まつ</rt></ruby>り</span>なので <ruby>人<rt>ひと</rt></ruby>が <ruby>多<rt>おお</rt></ruby>いです。",
example_read:"きょうは おまつりなので ひとが おおいです",
example_vi:"Hôm nay vì có lễ hội nên rất đông người.",
example_en:"There are a lot of people because there is a festival today."
},

{
level:"N5",
lesson:12,
id:31,
kanji:"すき焼き",
kana:"すきやき",
hanviet:"",
vi:"Sukiyaki (món thịt bò nấu rau)",
en:"Sukiyaki",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>すき<ruby>焼<rt>や</rt></ruby>き</span>は <ruby>日本<rt>にほん</rt></ruby>の <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>料理<rt>りょうり</rt></ruby>です。",
example_read:"すきやきは にほんの ゆうめいな りょうりです。",
example_vi:"Sukiyaki là món ăn nổi tiếng của Nhật Bản.",
example_en:"Sukiyaki is a famous Japanese dish."
},

{
level:"N5",
lesson:12,
id:32,
kanji:"刺身",
kana:"さしみ",
hanviet:"THỨ THÂN",
vi:"Sashimi (gỏi cá sống)",
en:"Sashimi",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>刺身<rt>さしみ</rt></ruby></span>を よく <ruby>食<rt>た</rt></ruby>べます。",
example_read:"さしみを よく たべます。",
example_vi:"Tôi thường ăn sashimi.",
example_en:"I often eat sashimi."
},

{
level:"N5",
lesson:12,
id:33,
kanji:"[お]寿司",
kana:"[お]すし",
hanviet:"THỌ TƯ",
vi:"Sushi",
en:"Sushi",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>寿司<rt>すし</rt></ruby></span>が <ruby>大好<rt>だいす</rt></ruby>きです。",
example_read:"おすしが だいすきです。",
example_vi:"Tôi rất thích sushi.",
example_en:"I really like sushi."
},

{
level:"N5",
lesson:12,
id:34,
kanji:"天ぷら",
kana:"てんぷら",
hanviet:"THIÊN",
vi:"Tempura (hải sản hoặc rau củ tẩm bột chiên kiểu Nhật)",
en:"Tempura",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>天<rt>てん</rt></ruby>ぷら</span>は とても <ruby>美味<rt>おい</rt></ruby>しいです。",
example_read:"てんぷらは とても おいしいです",
example_vi:"Tempura rất ngon.",
example_en:"Tempura is very tasty."
},

{
level:"N5",
lesson:12,
id:35,
kanji:"豚肉",
kana:"ぶたにく",
hanviet:"ĐỒN NHỤC",
vi:"thịt heo, thịt lợn",
en:"Pork",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"スーパーで <span class='target-word'><ruby>豚肉<rt>ぶたにく</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"スーパーで ぶたにくを かいました",
example_vi:"Tôi đã mua thịt heo ở siêu thị.",
example_en:"I bought pork at the supermarket."
},

{
level:"N5",
lesson:12,
id:36,
kanji:"鶏肉",
kana:"とりにく",
hanviet:"KÊ NHỤC",
vi:"thịt gà",
en:"Chicken",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>鶏肉<rt>とりにく</rt></ruby></span>を よく <ruby>食<rt>た</rt></ruby>べます。",
example_read:"とりにくを よく たべます",
example_vi:"Tôi thường ăn thịt gà.",
example_en:"I often eat chicken."
},

{
level:"N5",
lesson:12,
id:37,
kanji:"牛肉",
kana:"ぎゅうにく",
hanviet:"NGƯU NHỤC",
vi:"thịt bò",
en:"Beef",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>牛肉<rt>ぎゅうにく</rt></ruby></span>は <ruby>少<rt>すこ</rt></ruby>し <ruby>高<rt>たか</rt></ruby>いです。",
example_read:"ぎゅうにくは すこし たかいです",
example_vi:"Thịt bò hơi đắt.",
example_en:"Beef is a little expensive."
},

{
level:"N5",
lesson:12,
id:38,
kanji:"レモン",
kana:"レモン",
hanviet:"",
vi:"chanh tây",
en:"Lemon",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>レモン</span>を <ruby>入<rt>い</rt></ruby>れると <ruby>美味<rt>おい</rt></ruby>しいです。",
example_read:"レモンを いれると おいしいです",
example_vi:"Cho chanh vào thì ngon hơn.",
example_en:"It tastes good with lemon."
},

{
level:"N5",
lesson:12,
id:39,
kanji:"生け花",
kana:"いけばな",
hanviet:"SINH HOA",
vi:"nghệ thuật cắm hoa",
en:"Flower arrangement",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>生<rt>い</rt></ruby>け<ruby>花<rt>ばな</rt></ruby></span>を <ruby>習<rt>なら</rt></ruby>っています。",
example_read:"いけばなを ならっています",
example_vi:"Tôi đang học nghệ thuật cắm hoa.",
example_en:"I am learning flower arrangement."
},

{
level:"N5",
lesson:12,
id:40,
kanji:"紅葉",
kana:"もみじ",
hanviet:"HỒNG DIỆP",
vi:"lá đỏ mùa thu",
en:"Autumn leaves",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>紅葉<rt>もみじ</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ともだちと もみじを みに いきます",
example_vi:"Tôi đi ngắm lá đỏ với bạn.",
example_en:"I go to see the autumn leaves with my friend."
},

{
level:"N5",
lesson:12,
id:41,
kanji:"どちら",
kana:"どちら",
hanviet:"",
vi:"cái nào",
en:"which one",
word_type_vi:"Đại từ nghi vấn",
word_type_en:"Interrogative pronoun",
category:"Minna 1",
example:"りんごと みかんと <span class='target-word'>どちら</span>が <ruby>好<rt>す</rt></ruby>きですか。",
example_read:"りんごと みかんと どちらが すきですか",
example_vi:"Bạn thích táo hay quýt hơn?",
example_en:"Which do you like better, apples or oranges?"
},

{
level:"N5",
lesson:12,
id:42,
kanji:"どちらも",
kana:"どちらも",
hanviet:"",
vi:"cả hai",
en:"both",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"コーヒーと お<span class='target-word'>茶</span>、<span class='target-word'>どちらも</span> <ruby>好<rt>す</rt></ruby>きです。",
example_read:"コーヒーと おちゃ、どちらも すきです",
example_vi:"Cà phê và trà, tôi thích cả hai.",
example_en:"Coffee and tea, I like both."
},

{
level:"N5",
lesson:12,
id:43,
kanji:"一番",
kana:"いちばん",
hanviet:"NHẤT PHIÊN",
vi:"nhất",
en:"the most",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>日本料理<rt>にほんりょうり</rt></ruby>で <span class='target-word'><ruby>一番<rt>いちばん</rt></ruby></span> <ruby>好<rt>す</rt></ruby>きなのは <ruby>寿司<rt>すし</rt></ruby>です。",
example_read:"にほんりょうりで いちばん すきなのは すしです",
example_vi:"Trong các món ăn Nhật, món tôi thích nhất là sushi.",
example_en:"My favorite Japanese food is sushi."
},

{
level:"N5",
lesson:12,
id:44,
kanji:"ずっと",
kana:"ずっと",
hanviet:"",
vi:"hơn hẳn, suốt",
en:"much / far",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>昨日<rt>きのう</rt></ruby>より <span class='target-word'>ずっと</span> <ruby>暑<rt>あつ</rt></ruby>いです。",
example_read:"きょうは きのうより ずっと あついです",
example_vi:"Hôm nay nóng hơn hôm qua rất nhiều.",
example_en:"Today is much hotter than yesterday."
},

{
level:"N5",
lesson:12,
id:45,
kanji:"初めて",
kana:"はじめて",
hanviet:"SƠ",
vi:"lần đầu tiên",
en:"for the first time",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>初<rt>はじ</rt></ruby>めて</span> <ruby>日本<rt>にほん</rt></ruby>に <ruby>来<rt>き</rt></ruby>たのは 5<ruby>年前<rt>ねんまえ</rt></ruby>でした。",
example_read:"はじめて にほんに きたのは ごねんまえでした",
example_vi:"Lần đầu tiên tôi đến Nhật là 5 năm trước.",
example_en:"The first time I came to Japan was five years ago."
},

{
level:"N5",
lesson:12,
id:46,
kanji:"只今",
kana:"ただいま",
hanviet:"CHỈ KIM",
vi:"Tôi đã về đây, ngay lúc này, hiện tại",
en:"I'm home; right now / at the moment",
word_type_vi:"Câu chào / Trạng từ",
word_type_en:"Greeting / Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>只今<rt>ただいま</rt></ruby></span> <ruby>会議中<rt>かいぎちゅう</rt></ruby>です。",
example_read:"ただいま かいぎちゅうです",
example_vi:"Hiện tại đang họp.",
example_en:"We are in a meeting right now."
},

{
level:"N5",
lesson:12,
id:47,
kanji:"お帰りなさい",
kana:"おかえりなさい",
hanviet:"QUY",
vi:"Anh/chị đã về đấy à",
en:"Welcome back",
word_type_vi:"Câu chào",
word_type_en:"Greeting",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>が 「<span class='target-word'>お<ruby>帰<rt>かえ</rt></ruby>りなさい</span>」と <ruby>言<rt>い</rt></ruby>ってくれました。",
example_read:"ははが おかえりなさい と いってくれました",
example_vi:"Mẹ đã nói với tôi: “Con về rồi à”.",
example_en:"My mother said, 'Welcome back,' to me."
},

{
level:"N5",
lesson:12,
id:48,
kanji:"凄い",
kana:"すごい",
hanviet:"THÊ",
vi:"giỏi quá, tuyệt quá",
en:"That's great, amazing",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"わあ、<ruby>人<rt>ひと</rt></ruby>が <span class='target-word'><ruby>凄<rt>すご</rt></ruby>い</span>ですね。",
example_read:"わあ、ひとが すごいですね",
example_vi:"Ôi, đông người quá nhỉ!",
example_en:"Wow, there are so many people!"
},

{
level:"N5",
lesson:12,
id:49,
kanji:"疲れました",
kana:"つかれました",
hanviet:"BÌ",
vi:"Đã mệt rồi",
en:"got tired",
word_type_vi:"Động từ nhóm 2 (quá khứ)",
word_type_en:"Group 2 verb (past polite)",
category:"Minna 1",
example:"たくさん <ruby>歩<rt>ある</rt></ruby>いて、<span class='target-word'><ruby>疲<rt>つか</rt></ruby>れました</span>。",
example_read:"たくさん あるいて、つかれました",
example_vi:"Đi bộ nhiều quá nên tôi mệt rồi.",
example_en:"I walked a lot and got tired."
},

{
level:"N5",
lesson:12,
id:50,
kanji:"祇園祭",
kana:"ぎおんまつり",
hanviet:"KÌ VIÊN TẾ",
vi:"Lễ hội Gion",
en:"Gion Festival",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>祇園祭<rt>ぎおんまつり</rt></ruby></span>は <ruby>京都<rt>きょうと</rt></ruby>の <ruby>有名<rt>ゆうめい</rt></ruby>な お<ruby>祭<rt>まつ</rt></ruby>りです。",
example_read:"ぎおんまつりは きょうとの ゆうめいな おまつりです",
example_vi:"Lễ hội Gion là một lễ hội nổi tiếng của Kyoto.",
example_en:"The Gion Festival is a famous festival in Kyoto."
},

{
level:"N5",
lesson:12,
id:51,
kanji:"ホンコン",
kana:"ホンコン",
hanviet:"",
vi:"Hồng Kông",
en:"Hong Kong",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ホンコン</span>へ <ruby>旅行<rt>りょこう</rt></ruby>したいです。",
example_read:"ホンコンへ りょこうしたいです。",
example_vi:"Tôi muốn đi du lịch Hồng Kông.",
example_en:"I want to travel to Hong Kong."
},

{
level:"N5",
lesson:12,
id:52,
kanji:"シンガポール",
kana:"シンガポール",
hanviet:"",
vi:"Singapore",
en:"Singapore",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>シンガポール</span>は <ruby>綺麗<rt>きれい</rt></ruby>な <ruby>国<rt>くに</rt></ruby>です。",
example_read:"シンガポールは きれいな くにです",
example_vi:"Singapore là một đất nước đẹp.",
example_en:"Singapore is a beautiful country."
},

{
level:"N5",
lesson:12,
id:53,
kanji:"ＡＣＢストア",
kana:"エーシービーストア",
hanviet:"",
vi:"Siêu thị ACB",
en:"ACB Store",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ＡＣＢストア</span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>します。",
example_read:"エーシービーストアで かいものします。",
example_vi:"Tôi mua sắm ở siêu thị ACB.",
example_en:"I shop at ACB Store."
},

{
level:"N5",
lesson:12,
id:54,
kanji:"ジャパン",
kana:"ジャパン",
hanviet:"",
vi:"Siêu thị Japan",
en:"Japan Store",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ジャパン</span>で <ruby>野菜<rt>やさい</rt></ruby>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"ジャパンで やさいを かいました。",
example_vi:"Tôi đã mua rau ở siêu thị Japan.",
example_en:"I bought vegetables at Japan Store."
}
];