window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[6] = [

{
level:"N5",
lesson:6,
id:1,
kanji:"食べます",
kana:"たべます",
hanviet:"THỰC",
vi:"Ăn",
en:"Eat",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> パンを <span class='target-word'><ruby>食<rt>た</rt></ruby>べます</span>。",
example_read:"まいにち ぱんを たべます。",
example_vi:"Tôi ăn bánh mì mỗi ngày.",
example_en:"I eat bread every day."
},

{
level:"N5",
lesson:6,
id:2,
kanji:"飲みます",
kana:"のみます",
hanviet:"ẨM",
vi:"Uống",
en:"Drink",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>牛乳<rt>ぎゅうにゅう</rt></ruby>を <span class='target-word'><ruby>飲<rt>の</rt></ruby>みます</span>。",
example_read:"まいあさ ぎゅうにゅうを のみます。",
example_vi:"Mỗi sáng tôi uống sữa.",
example_en:"I drink milk every morning."
},

{
level:"N5",
lesson:6,
id:3,
kanji:"吸います",
kana:"すいます",
hanviet:"HẤP",
vi:"Hút",
en:"Smoke",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は たばこを <span class='target-word'><ruby>吸<rt>す</rt></ruby>います</span>。",
example_read:"ちちは たばこを すいます。",
example_vi:"Bố tôi hút thuốc.",
example_en:"My father smokes."
},

{
level:"N5",
lesson:6,
id:4,
kanji:"見ます",
kana:"みます",
hanviet:"KIẾN",
vi:"Xem, nhìn",
en:"See, watch",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>毎晩<rt>まいばん</rt></ruby> テレビを <span class='target-word'><ruby>見<rt>み</rt></ruby>ます</span>。",
example_read:"まいばん てれびを みます。",
example_vi:"Mỗi tối tôi xem TV.",
example_en:"I watch TV every night."
},

{
level:"N5",
lesson:6,
id:5,
kanji:"聞きます",
kana:"ききます",
hanviet:"VĂN",
vi:"Nghe",
en:"Listen, hear",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>音楽<rt>おんがく</rt></ruby>を <span class='target-word'><ruby>聞<rt>き</rt></ruby>きます</span>。",
example_read:"まいにち おんがくを ききます。",
example_vi:"Tôi nghe nhạc mỗi ngày.",
example_en:"I listen to music every day."
},

{
level:"N5",
lesson:6,
id:6,
kanji:"読みます",
kana:"よみます",
hanviet:"ĐỘC",
vi:"Đọc",
en:"Read",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>新聞<rt>しんぶん</rt></ruby>を <span class='target-word'><ruby>読<rt>よ</rt></ruby>みます</span>。",
example_read:"ちちは まいあさ しんぶんを よみます。",
example_vi:"Bố tôi đọc báo mỗi sáng.",
example_en:"My father reads a newspaper every morning."
},

{
level:"N5",
lesson:6,
id:7,
kanji:"書きます",
kana:"かきます",
hanviet:"THƯ",
vi:"Viết",
en:"Write",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>友達<rt>ともだち</rt></ruby>に <ruby>手紙<rt>てがみ</rt></ruby>を <span class='target-word'><ruby>書<rt>か</rt></ruby>きます</span>。",
example_read:"わたしは ともだちに てがみを かきます。",
example_vi:"Tôi viết thư cho bạn.",
example_en:"I write a letter to my friend."
},

{
level:"N5",
lesson:6,
id:8,
kanji:"買います",
kana:"かいます",
hanviet:"MÃI",
vi:"Mua",
en:"Buy",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>店<rt>みせ</rt></ruby>で パンを <span class='target-word'><ruby>買<rt>か</rt></ruby>います</span>。",
example_read:"まいあさ みせで ぱんを かいます。",
example_vi:"Tôi mua bánh mì ở cửa hàng mỗi sáng.",
example_en:"I buy bread at a store every morning."
},

{
level:"N5",
lesson:6,
id:9,
kanji:"撮ります",
kana:"とります",
hanviet:"NHIẾP",
vi:"Chụp",
en:"Take (a photo)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"あなたは <span class='target-word'><ruby>写真<rt>しゃしん</rt></ruby>を <ruby>撮<rt>と</rt></ruby>ります</span>か。",
example_read:"あなたは しゃしんを とりますか。",
example_vi:"Bạn có chụp ảnh không?",
example_en:"Do you take photos?"
},

{
level:"N5",
lesson:6,
id:10,
kanji:"",
kana:"します",
hanviet:"",
vi:"Làm",
en:"Do",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 Verb",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>宿題<rt>しゅくだい</rt></ruby>を <span class='target-word'>します</span>。",
example_read:"まいにち しゅくだいを します。",
example_vi:"Tôi làm bài tập mỗi ngày.",
example_en:"I do my homework every day."
},

{
level:"N5",
lesson:6,
id:11,
kanji:"会います",
kana:"あいます",
hanviet:"HỘI",
vi:"Gặp",
en:"Meet",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>昼休<rt>ひるやす</rt></ruby>みに <ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'><ruby>会<rt>あ</rt></ruby>います</span>。",
example_read:"ひるやすみに ともだちに あいます。",
example_vi:"Tôi gặp bạn vào giờ nghỉ trưa.",
example_en:"I meet my friend during lunch break."
},

{
level:"N5",
lesson:6,
id:12,
kanji:"ご飯",
kana:"ごはん",
hanviet:"PHẠN",
vi:"Cơm, bữa ăn",
en:"Meal, rice",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>食堂<rt>しょくどう</rt></ruby>で <span class='target-word'><ruby>ご飯<rt>ごはん</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"しょくどうで ごはんを たべます。",
example_vi:"Tôi ăn cơm ở căn tin.",
example_en:"I eat a meal in the cafeteria."
},

{
level:"N5",
lesson:6,
id:13,
kanji:"朝ご飯",
kana:"あさごはん",
hanviet:"TRIỀU PHẠN",
vi:"Bữa sáng",
en:"Breakfast",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>家<rt>いえ</rt></ruby>で <span class='target-word'><ruby>朝ご飯<rt>あさごはん</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"わたしは いえで あさごはんを たべます。",
example_vi:"Tôi ăn sáng ở nhà.",
example_en:"I eat breakfast at home."
},

{
level:"N5",
lesson:6,
id:14,
kanji:"昼ご飯",
kana:"ひるごはん",
hanviet:"TRÚ PHẠN",
vi:"Bữa trưa",
en:"Lunch",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>食堂<rt>しょくどう</rt></ruby>で <span class='target-word'><ruby>昼ご飯<rt>ひるごはん</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"しょくどうで ひるごはんを たべます。",
example_vi:"Tôi ăn trưa ở căn tin.",
example_en:"I eat lunch in the cafeteria."
},

{
level:"N5",
lesson:6,
id:15,
kanji:"晩ご飯",
kana:"ばんごはん",
hanviet:"VÃN PHẠN",
vi:"Bữa tối",
en:"Dinner",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>家族<rt>かぞく</rt></ruby>と <span class='target-word'><ruby>晩<rt>ばん</rt></ruby>ご飯</span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"かぞくと ばんごはんを たべます。",
example_vi:"Tôi ăn tối cùng gia đình.",
example_en:"I eat dinner with my family."
},
{
level:"N5",
lesson:6,
id:16,
kanji:"",
kana:"パン",
hanviet:"",
vi:"Bánh mì",
en:"Bread",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>は <span class='target-word'>パン</span>です。",
example_read:"あさごはんは ぱんです。",
example_vi:"Bữa sáng là bánh mì.",
example_en:"Breakfast is bread."
},

{
level:"N5",
lesson:6,
id:17,
kanji:"卵",
kana:"たまご",
hanviet:"NOÃN",
vi:"Trứng",
en:"Egg",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>に <span class='target-word'><ruby>卵<rt>たまご</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"あさごはんに たまごを たべます。",
example_vi:"Tôi ăn trứng vào bữa sáng.",
example_en:"I eat eggs for breakfast."
},

{
level:"N5",
lesson:6,
id:18,
kanji:"肉",
kana:"にく",
hanviet:"NHỤC",
vi:"Thịt",
en:"Meat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>晩<rt>ばん</rt></ruby>ご<ruby>飯<rt>はん</rt></ruby>に <span class='target-word'><ruby>肉<rt>にく</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"ばんごはんに にくを たべます。",
example_vi:"Tôi ăn thịt vào bữa tối.",
example_en:"I eat meat for dinner."
},

{
level:"N5",
lesson:6,
id:19,
kanji:"魚",
kana:"さかな",
hanviet:"NGƯ",
vi:"Cá",
en:"Fish",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>魚<rt>さかな</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べるのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは さかなを たべるのが すきです。",
example_vi:"Tôi thích ăn cá.",
example_en:"I like eating fish."
},

{
level:"N5",
lesson:6,
id:20,
kanji:"野菜",
kana:"やさい",
hanviet:"DÃ THÁI",
vi:"Rau",
en:"Vegetable",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <span class='target-word'><ruby>野菜<rt>やさい</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"まいにち やさいを たべます。",
example_vi:"Tôi ăn rau mỗi ngày.",
example_en:"I eat vegetables every day."
},

{
level:"N5",
lesson:6,
id:21,
kanji:"果物",
kana:"くだもの",
hanviet:"QUẢ VẬT",
vi:"Hoa quả, trái cây",
en:"Fruit",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>果物<rt>くだもの</rt></ruby></span>を <ruby>食<rt>た</rt></ruby>べるのが いちばん <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは くだものを たべるのが いちばん すきです。",
example_vi:"Tôi thích ăn trái cây nhất.",
example_en:"I like eating fruit the most."
},

{
level:"N5",
lesson:6,
id:22,
kanji:"水",
kana:"みず",
hanviet:"THỦY",
vi:"Nước",
en:"Water",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いですから、<span class='target-word'><ruby>水<rt>みず</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"あついですから みずを のみます。",
example_vi:"Vì trời nóng nên tôi uống nước.",
example_en:"Because it is hot, I drink water."
},

{
level:"N5",
lesson:6,
id:23,
kanji:"お茶",
kana:"おちゃ",
hanviet:"TRÀ",
vi:"Trà",
en:"Tea",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>食事<rt>しょくじ</rt></ruby>の <ruby>後<rt>あと</rt></ruby>で <span class='target-word'><ruby>お茶<rt>おちゃ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"しょくじの あとで おちゃを のみます。",
example_vi:"Sau khi ăn tôi uống trà.",
example_en:"I drink tea after meals."
},

{
level:"N5",
lesson:6,
id:24,
kanji:"紅茶",
kana:"こうちゃ",
hanviet:"HỒNG TRÀ",
vi:"Trà đen",
en:"Black tea",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'><ruby>紅茶<rt>こうちゃ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"まいあさ こうちゃを のみます。",
example_vi:"Tôi uống trà đen mỗi sáng.",
example_en:"I drink black tea every morning."
},

{
level:"N5",
lesson:6,
id:25,
kanji:"牛乳",
kana:"ぎゅうにゅう",
hanviet:"NGƯU NHŨ",
vi:"Sữa bò",
en:"Milk",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'><ruby>牛乳<rt>ぎゅうにゅう</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"まいあさ ぎゅうにゅうを のみます。",
example_vi:"Tôi uống sữa mỗi sáng.",
example_en:"I drink milk every morning."
},

{
level:"N5",
lesson:6,
id:26,
kanji:"",
kana:"ジュース",
hanviet:"",
vi:"Nước trái cây",
en:"Juice",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は リンゴ<span class='target-word'>ジュース</span>が <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは りんごじゅーすが すきです。",
example_vi:"Tôi thích nước ép táo.",
example_en:"I like apple juice."
},

{
level:"N5",
lesson:6,
id:27,
kanji:"",
kana:"ビール",
hanviet:"",
vi:"Bia",
en:"Beer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>の <ruby>後<rt>あと</rt></ruby>で <span class='target-word'>ビール</span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"しごとの あとで びーるを のみます。",
example_vi:"Sau khi làm việc tôi uống bia.",
example_en:"I drink beer after work."
},

{
level:"N5",
lesson:6,
id:28,
kanji:"お酒",
kana:"おさけ",
hanviet:"TỬU",
vi:"Rượu",
en:"Alcohol, sake",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>お酒<rt>おさけ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"ともだちと おさけを のみます。",
example_vi:"Tôi uống rượu với bạn.",
example_en:"I drink alcohol with friends."
},

{
level:"N5",
lesson:6,
id:29,
kanji:"",
kana:"たばこ",
hanviet:"",
vi:"Thuốc lá",
en:"Cigarette",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>たばこ</span>を <ruby>吸<rt>す</rt></ruby>う<ruby>人<rt>ひと</rt></ruby>が <ruby>好<rt>す</rt></ruby>きではありません。",
example_read:"わたしは たばこを すう ひとが すきではありません。",
example_vi:"Tôi không thích người hút thuốc.",
example_en:"I don't like people who smoke."
},

{
level:"N5",
lesson:6,
id:30,
kanji:"手紙",
kana:"てがみ",
hanviet:"THỦ CHỈ",
vi:"Thư",
en:"Letter",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'><ruby>手紙<rt>てがみ</rt></ruby></span>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"ともだちに てがみを かきます。",
example_vi:"Tôi viết thư cho bạn.",
example_en:"I write a letter to my friend."
},
{
level:"N5",
lesson:6,
id:31,
kanji:"",
kana:"レポート",
hanviet:"",
vi:"Báo cáo",
en:"Report",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>大学<rt>だいがく</rt></ruby>で <span class='target-word'>レポート</span>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"だいがくで れぽーとを かきます。",
example_vi:"Tôi viết báo cáo ở trường đại học.",
example_en:"I write a report at university."
},

{
level:"N5",
lesson:6,
id:32,
kanji:"写真",
kana:"しゃしん",
hanviet:"TẢ CHÂN",
vi:"Ảnh",
en:"Photo",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>の <span class='target-word'><ruby>写真<rt>しゃしん</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"ともだちの しゃしんを みます。",
example_vi:"Tôi xem ảnh của bạn.",
example_en:"I look at my friend's photos."
},

{
level:"N5",
lesson:6,
id:33,
kanji:"",
kana:"ビデオ",
hanviet:"",
vi:"Video, băng video, đầu video",
en:"Video",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>家<rt>いえ</rt></ruby>で <span class='target-word'>ビデオ</span>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"いえで びでおを みます。",
example_vi:"Tôi xem video ở nhà.",
example_en:"I watch videos at home."
},

{
level:"N5",
lesson:6,
id:34,
kanji:"店",
kana:"みせ",
hanviet:"ĐIẾM",
vi:"Cửa hàng, tiệm",
en:"Shop, store",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"あの <span class='target-word'><ruby>店<rt>みせ</rt></ruby></span>で パンを <ruby>買<rt>か</rt></ruby>いました。",
example_read:"あの みせで ぱんを かいました。",
example_vi:"Tôi đã mua bánh mì ở cửa hàng đó.",
example_en:"I bought bread at that shop."
},

{
level:"N5",
lesson:6,
id:35,
kanji:"庭",
kana:"にわ",
hanviet:"ĐÌNH",
vi:"Vườn, Sân",
en:"Garden, Yard",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>庭<rt>にわ</rt></ruby></span>で <ruby>写真<rt>しゃしん</rt></ruby>を <ruby>撮<rt>と</rt></ruby>ります。",
example_read:"にわで しゃしんを とります。",
example_vi:"Tôi chụp ảnh trong vườn.",
example_en:"I take pictures in the garden."
},

{
level:"N5",
lesson:6,
id:36,
kanji:"宿題",
kana:"しゅくだい",
hanviet:"TÚC ĐỀ",
vi:"Bài tập về nhà",
en:"Homework",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>宿題<rt>しゅくだい</rt></ruby></span>を してから <ruby>寝<rt>ね</rt></ruby>ます。",
example_read:"しゅくだいを してから ねます。",
example_vi:"Tôi làm bài tập rồi đi ngủ.",
example_en:"I do my homework and then go to sleep."
},

{
level:"N5",
lesson:6,
id:37,
kanji:"",
kana:"テニス",
hanviet:"",
vi:"Quần vợt",
en:"Tennis",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'>テニス</span>を します。",
example_read:"ともだちと てにすを します。",
example_vi:"Tôi chơi tennis với bạn.",
example_en:"I play tennis with my friend."
},

{
level:"N5",
lesson:6,
id:38,
kanji:"",
kana:"サッカー",
hanviet:"",
vi:"Bóng đá",
en:"Soccer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>サッカー</span>を するのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは さっかーを するのが すきです。",
example_vi:"Tôi thích chơi bóng đá.",
example_en:"I like playing soccer."
},

{
level:"N5",
lesson:6,
id:39,
kanji:"花見",
kana:"はなみ",
hanviet:"HOA KIẾN",
vi:"Ngắm hoa anh đào",
en:"Cherry blossom viewing",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>春<rt>はる</rt></ruby>に <span class='target-word'><ruby>花見<rt>はなみ</rt></ruby></span>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"はるに はなみに いきます。",
example_vi:"Mùa xuân tôi đi ngắm hoa anh đào.",
example_en:"I go cherry blossom viewing in spring."
},

{
level:"N5",
lesson:6,
id:40,
kanji:"何",
kana:"なに/なん",
hanviet:"HÀ",
vi:"Cái gì, gì",
en:"What",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 1",
example:"それは <span class='target-word'><ruby>何<rt>なん</rt></ruby></span>ですか。",
example_read:"それは なんですか。",
example_vi:"Đó là cái gì vậy?",
example_en:"What is that?"
},
{
level:"N5",
lesson:6,
id:41,
kanji:"一緒に",
kana:"いっしょに",
hanviet:"NHẤT TỰ",
vi:"Cùng nhau",
en:"Together",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>一緒<rt>いっしょ</rt></ruby>に</span> <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"ともだちと いっしょに えいがを みます。",
example_vi:"Tôi xem phim cùng bạn.",
example_en:"I watch a movie together with my friend."
},

{
level:"N5",
lesson:6,
id:42,
kanji:"",
kana:"ちょっと",
hanviet:"",
vi:"Một chút",
en:"A little",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'>ちょっと</span> <ruby>忙<rt>いそが</rt></ruby>しいです。",
example_read:"きょうは ちょっと いそがしいです。",
example_vi:"Hôm nay tôi hơi bận một chút.",
example_en:"I am a little busy today."
},

{
level:"N5",
lesson:6,
id:43,
kanji:"",
kana:"いつも",
hanviet:"",
vi:"Luôn luôn",
en:"Always",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>いつも</span> <ruby>牛乳<rt>ぎゅうにゅう</rt></ruby>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"わたしは いつも ぎゅうにゅうを のみます。",
example_vi:"Tôi luôn uống sữa.",
example_en:"I always drink milk."
},

{
level:"N5",
lesson:6,
id:44,
kanji:"時々",
kana:"ときどき",
hanviet:"THỜI THỜI",
vi:"Thỉnh thoảng",
en:"Sometimes",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>時々<rt>ときどき</rt></ruby></span> テニスをします。",
example_read:"ときどき てにすをします。",
example_vi:"Thỉnh thoảng tôi chơi quần vợt.",
example_en:"I sometimes play tennis."
},

{
level:"N5",
lesson:6,
id:45,
kanji:"",
kana:"それから",
hanviet:"",
vi:"Sau đó, tiếp theo",
en:"And then",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>晩<rt>ばん</rt></ruby><ruby>ご飯<rt>ごはん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。<span class='target-word'>それから</span> <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"ばんごはんを たべます。それから べんきょうします。",
example_vi:"Tôi ăn tối. Sau đó tôi học bài.",
example_en:"I have dinner, then I study."
},

{
level:"N5",
lesson:6,
id:46,
kanji:"",
kana:"ええ",
hanviet:"",
vi:"Vâng",
en:"Yes",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"A: 田中さんは サッカーを しますか。<br>B: <span class='target-word'>ええ</span>、します。",
example_read:"たなかさんは さっかーを しますか。ええ、します。",
example_vi:"A: Anh Tanaka có chơi bóng đá không? B: Vâng, có.",
example_en:"A: Does Mr. Tanaka play soccer? B: Yes."
},

{
level:"N5",
lesson:6,
id:47,
kanji:"",
kana:"いいですね",
hanviet:"",
vi:"Hay quá nhỉ",
en:"That's nice",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: <ruby>春<rt>はる</rt></ruby>に <ruby>花見<rt>はなみ</rt></ruby>に <ruby>行<rt>い</rt></ruby>きましょう。<br>B: <span class='target-word'>いいですね</span>。",
example_read:"はるに はなみに いきましょう。いいですね。",
example_vi:"A: Mùa xuân chúng ta cùng đi ngắm hoa anh đào nhé. B: Hay quá nhỉ.",
example_en:"A: Let's go cherry blossom viewing in spring. B: That's nice."
},

{
level:"N5",
lesson:6,
id:48,
kanji:"分かりました",
kana:"わかりました",
hanviet:"PHÂN",
vi:"Tôi hiểu rồi",
en:"I understand",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: ７<ruby>時<rt>じ</rt></ruby>に <ruby>来<rt>き</rt></ruby>てください。<br>B: <span class='target-word'><ruby>分<rt>わ</rt></ruby>かりました</span>。",
example_read:"７じに きてください。わかりました。",
example_vi:"A: Hãy đến lúc 7 giờ. B: Tôi hiểu rồi.",
example_en:"A: Please come at 7 o'clock. B: I understand."
},

{
level:"N5",
lesson:6,
id:49,
kanji:"何ですか",
kana:"なんですか",
hanviet:"HÀ",
vi:"Cái gì vậy?",
en:"What?",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 1",
example:"A: すみません。<br>B: <span class='target-word'><ruby>何<rt>なん</rt></ruby></span>ですか。",
example_read:"なんですか。",
example_vi:"A: Xin lỗi. B: Có chuyện gì vậy?",
example_en:"A: Excuse me. B: What is it?"
},

{
level:"N5",
lesson:6,
id:50,
kanji:"じゃ、また[明日]",
kana:"じゃ、また[あした]",
hanviet:"MINH NHẬT",
vi:"Hẹn gặp lại (ngày mai)",
en:"See you (tomorrow)",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: さようなら。<br>B: じゃ、また<span class='target-word'><ruby>明日<rt>あした</rt></ruby></span>。",
example_read:"じゃ、またあした。",
example_vi:"A: Tạm biệt. B: Hẹn gặp lại ngày mai.",
example_en:"A: Goodbye. B: See you tomorrow."
},
{
level:"N5",
lesson:6,
id:51,
kanji:"",
kana:"メキシコ",
hanviet:"",
vi:"Mexico",
en:"Mexico",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>メキシコ</span>へ <ruby>旅行<rt>りょこう</rt></ruby>したいです。",
example_read:"めきしこへ りょこうしたいです。",
example_vi:"Tôi muốn đi du lịch Mexico.",
example_en:"I want to travel to Mexico."
},

{
level:"N5",
lesson:6,
id:52,
kanji:"大阪デパート",
kana:"おおさかデパート",
hanviet:"ĐẠI PHẢN",
vi:"Bách hóa Osaka",
en:"Osaka Department Store",
word_type_vi:"Tên riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>大阪<rt>おおさか</rt></ruby>デパート</span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>をします。",
example_read:"おおさかでぱーとで かいものをします。",
example_vi:"Tôi mua sắm ở bách hóa Osaka.",
example_en:"I shop at Osaka Department Store."
},

{
level:"N5",
lesson:6,
id:53,
kanji:"",
kana:"つるや",
hanviet:"",
vi:"Tsuruya",
en:"Tsuruya",
word_type_vi:"Tên nhà hàng",
word_type_en:"Restaurant name",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'>つるや</span>で <ruby>昼<rt>ひる</rt></ruby><ruby>ご飯<rt>ごはん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"きょうは つるやで ひるごはんを たべます。",
example_vi:"Hôm nay tôi ăn trưa ở nhà hàng Tsuruya.",
example_en:"I will have lunch at Tsuruya today."
},

{
level:"N5",
lesson:6,
id:54,
kanji:"フランス屋",
kana:"フランスや",
hanviet:"",
vi:"Siêu thị France-ya",
en:"France-ya Supermarket",
word_type_vi:"Tên riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>フランス<ruby>屋<rt>や</rt></ruby></span>で パンを <ruby>買<rt>か</rt></ruby>いました。",
example_read:"ふらんすやで ぱんを かいました。",
example_vi:"Tôi đã mua bánh mì ở siêu thị France-ya.",
example_en:"I bought bread at France-ya Supermarket."
},

{
level:"N5",
lesson:6,
id:55,
kanji:"毎日屋",
kana:"まいにちや",
hanviet:"MỖI NHẬT ỐC",
vi:"Siêu thị Mainichiya",
en:"Mainichiya Supermarket",
word_type_vi:"Tên riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>毎日屋<rt>まいにちや</rt></ruby></span>で ジュースを <ruby>買<rt>か</rt></ruby>いたいです。",
example_read:"まいにちやで じゅーすを かいたいです。",
example_vi:"Tôi muốn mua nước trái cây ở siêu thị Mainichiya.",
example_en:"I want to buy juice at Mainichiya Supermarket."
}
];