window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[7] = [

{
level:"N5",
lesson:7,
id:1,
kanji:"切ります",
kana:"きります",
hanviet:"THIẾT",
vi:"Cắt",
en:"Cut",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"はさみで <span class='target-word'><ruby>紙<rt>かみ</rt></ruby></span>を <ruby>切<rt>き</rt></ruby>ります。",
example_read:"はさみで かみを きります。",
example_vi:"Tôi cắt giấy bằng kéo.",
example_en:"I cut paper with scissors."
},

{
level:"N5",
lesson:7,
id:2,
kanji:"送ります",
kana:"おくります",
hanviet:"TỐNG",
vi:"Gửi",
en:"Send",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に メールを <span class='target-word'><ruby>送<rt>おく</rt></ruby>ります</span>。",
example_read:"ともだちに めーるを おくります。",
example_vi:"Tôi gửi email cho bạn.",
example_en:"I send an email to my friend."
},

{
level:"N5",
lesson:7,
id:3,
kanji:"あげます",
kana:"あげます",
hanviet:"",
vi:"Cho, tặng",
en:"Give",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>の <ruby>誕生日<rt>たんじょうび</rt></ruby>に <ruby>花束<rt>はなたば</rt></ruby>を <span class='target-word'>あげました</span>。",
example_read:"ははの たんじょうびに はなたばを あげました。",
example_vi:"Tôi đã tặng một bó hoa vào sinh nhật của mẹ.",
example_en:"I gave a bouquet of flowers to my mother on her birthday."
},

{
level:"N5",
lesson:7,
id:4,
kanji:"貰います",
kana:"もらいます",
hanviet:"THẾ",
vi:"Nhận",
en:"Receive",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に プレゼントを <span class='target-word'><ruby>貰<rt>もら</rt></ruby>います</span>。",
example_read:"ともだちに ぷれぜんとを もらいます。",
example_vi:"Tôi nhận quà từ bạn.",
example_en:"I receive a present from my friend."
},

{
level:"N5",
lesson:7,
id:5,
kanji:"貸します",
kana:"かします",
hanviet:"THẢI",
vi:"Cho mượn",
en:"Lend",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>貸<rt>か</rt></ruby>します</span>。",
example_read:"ともだちに ほんを かします。",
example_vi:"Tôi cho bạn mượn sách.",
example_en:"I lend a book to my friend."
},

{
level:"N5",
lesson:7,
id:6,
kanji:"借ります",
kana:"かります",
hanviet:"TÁ",
vi:"Mượn",
en:"Borrow",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>から <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>借<rt>か</rt></ruby>ります</span>。",
example_read:"ともだちから ほんを かります。",
example_vi:"Tôi mượn sách từ bạn.",
example_en:"I borrow a book from my friend."
},

{
level:"N5",
lesson:7,
id:7,
kanji:"教えます",
kana:"おしえます",
hanviet:"GIÁO",
vi:"Dạy",
en:"Teach",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>が <span class='target-word'><ruby>私<rt>わたし</rt></ruby></span>に <ruby>日本語<rt>にほんご</rt></ruby>を <span class='target-word'><ruby>教<rt>おし</rt></ruby>えます</span>。",
example_read:"せんせいが わたしに にほんごを おしえます。",
example_vi:"Giáo viên dạy tiếng Nhật cho tôi.",
example_en:"The teacher teaches Japanese to me."
},

{
level:"N5",
lesson:7,
id:8,
kanji:"習います",
kana:"ならいます",
hanviet:"TẬP",
vi:"Học",
en:"Learn",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>学校<rt>がっこう</rt></ruby>で <ruby>日本語<rt>にほんご</rt></ruby>を <span class='target-word'><ruby>習<rt>なら</rt></ruby>います</span>。",
example_read:"がっこうで にほんごを ならいます。",
example_vi:"Tôi học tiếng Nhật ở trường.",
example_en:"I learn Japanese at school."
},

{
level:"N5",
lesson:7,
id:9,
kanji:"[電話を]かけます",
kana:"[でんわを]かけます",
hanviet:"ĐIỆN THOẠI",
vi:"Gọi điện",
en:"Call",
word_type_vi:"Cụm động từ",
word_type_en:"Verb phrase",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>に <ruby>電話<rt>でんわ</rt></ruby>を <span class='target-word'>かけます</span>。",
example_read:"ははに でんわを かけます。",
example_vi:"Tôi gọi điện cho mẹ.",
example_en:"I call my mother."
},

{
level:"N5",
lesson:7,
id:10,
kanji:"手",
kana:"て",
hanviet:"THỦ",
vi:"Tay",
en:"Hand",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>手<rt>て</rt></ruby></span>を <ruby>洗<rt>あら</rt></ruby>います。",
example_read:"てを あらいます。",
example_vi:"Tôi rửa tay.",
example_en:"I wash my hands."
},

{
level:"N5",
lesson:7,
id:11,
kanji:"箸",
kana:"はし",
hanviet:"TRỨ",
vi:"Đũa",
en:"Chopsticks",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>箸<rt>はし</rt></ruby></span>で ご<ruby>飯<rt>はん</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"はしで ごはんを たべます。",
example_vi:"Tôi ăn cơm bằng đũa.",
example_en:"I eat with chopsticks."
},

{
level:"N5",
lesson:7,
id:12,
kanji:"スプーン",
kana:"スプーン",
hanviet:"",
vi:"Thìa",
en:"Spoon",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"スープを <span class='target-word'>スプーン</span>で <ruby>食<rt>た</rt></ruby>べます。",
example_read:"すーぷを すぷーんで たべます。",
example_vi:"Tôi ăn súp bằng thìa.",
example_en:"I eat soup with a spoon."
},

{
level:"N5",
lesson:7,
id:13,
kanji:"ナイフ",
kana:"ナイフ",
hanviet:"",
vi:"Dao",
en:"Knife",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"パンを <span class='target-word'>ナイフ</span>で <ruby>切<rt>き</rt></ruby>ります。",
example_read:"ぱんを ないふで きります。",
example_vi:"Tôi cắt bánh mì bằng dao.",
example_en:"I cut bread with a knife."
},

{
level:"N5",
lesson:7,
id:14,
kanji:"フォーク",
kana:"フォーク",
hanviet:"",
vi:"Nĩa",
en:"Fork",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"サラダを <span class='target-word'>フォーク</span>で <ruby>食<rt>た</rt></ruby>べます。",
example_read:"さらだを ふぉーくで たべます。",
example_vi:"Tôi ăn salad bằng nĩa.",
example_en:"I eat salad with a fork."
},

{
level:"N5",
lesson:7,
id:15,
kanji:"はさみ",
kana:"はさみ",
hanviet:"",
vi:"Kéo",
en:"Scissors",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"はさみで <span class='target-word'><ruby>紙<rt>かみ</rt></ruby></span>を <ruby>切<rt>き</rt></ruby>ります。",
example_read:"はさみで かみを きります。",
example_vi:"Tôi cắt giấy bằng kéo.",
example_en:"I cut paper with scissors."
},

{
level:"N5",
lesson:7,
id:16,
kanji:"パソコン",
kana:"パソコン",
hanviet:"",
vi:"Máy tính cá nhân",
en:"Personal computer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>パソコン</span>で <ruby>仕事<rt>しごと</rt></ruby>を します。",
example_read:"ぱそこんで しごとを します。",
example_vi:"Tôi làm việc bằng máy tính.",
example_en:"I work on a computer."
},

{
level:"N5",
lesson:7,
id:17,
kanji:"ケータイ",
kana:"ケータイ",
hanviet:"",
vi:"Điện thoại di động",
en:"Mobile phone",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ケータイ</span>で メールを します。",
example_read:"けーたいで めーるを します。",
example_vi:"Tôi dùng điện thoại để gửi email.",
example_en:"I use my mobile phone to send emails."
},

{
level:"N5",
lesson:7,
id:18,
kanji:"メール",
kana:"メール",
hanviet:"",
vi:"Email",
en:"Email",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'>メール</span>を <ruby>送<rt>おく</rt></ruby>ります。",
example_read:"ともだちに めーるを おくります。",
example_vi:"Tôi gửi email cho bạn.",
example_en:"I send an email to my friend."
},

{
level:"N5",
lesson:7,
id:19,
kanji:"年賀状",
kana:"ねんがじょう",
hanviet:"NIÊN HẠ TRẠNG",
vi:"Thiệp năm mới",
en:"New Year card",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>年末<rt>ねんまつ</rt></ruby>に <span class='target-word'><ruby>年賀状<rt>ねんがじょう</rt></ruby></span>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"ねんまつに ねんがじょうを かきます。",
example_vi:"Tôi viết thiệp năm mới vào cuối năm.",
example_en:"I write New Year's cards at the end of the year."
},

{
level:"N5",
lesson:7,
id:20,
kanji:"パンチ",
kana:"パンチ",
hanviet:"",
vi:"Dụng cụ đục lỗ",
en:"Hole punch",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>パンチ</span>で <ruby>紙<rt>かみ</rt></ruby>に <ruby>穴<rt>あな</rt></ruby>を <ruby>開<rt>あ</rt></ruby>けます。",
example_read:"ぱんちで かみに あなを あけます。",
example_vi:"Tôi đục lỗ trên giấy bằng dụng cụ đục lỗ.",
example_en:"I make holes in paper with a hole punch."
},

{
level:"N5",
lesson:7,
id:21,
kanji:"ホッチキス",
kana:"ホッチキス",
hanviet:"",
vi:"Cái dập ghim",
en:"Stapler",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ホッチキス</span>で <ruby>紙<rt>かみ</rt></ruby>を <ruby>止<rt>と</rt></ruby>めます。",
example_read:"ほっちきすで かみを とめます。",
example_vi:"Tôi ghim giấy bằng dập ghim.",
example_en:"I staple papers with a stapler."
},

{
level:"N5",
lesson:7,
id:22,
kanji:"セロテープ",
kana:"セロテープ",
hanviet:"",
vi:"Băng dính",
en:"Cellophane tape",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>セロテープ</span>で <ruby>紙<rt>かみ</rt></ruby>を <ruby>貼<rt>は</rt></ruby>ります。",
example_read:"せろてーぷで かみを はります。",
example_vi:"Tôi dán giấy bằng băng dính.",
example_en:"I stick paper with tape."
},

{
level:"N5",
lesson:7,
id:23,
kanji:"消しゴム",
kana:"けしゴム",
hanviet:"TIÊU",
vi:"Cục tẩy",
en:"Eraser",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>消<rt>け</rt></ruby>しゴム</span>で <ruby>間違<rt>まちが</rt></ruby>いを <ruby>消<rt>け</rt></ruby>しました。",
example_read:"けしごむで まちがいを けしました。",
example_vi:"Tôi đã dùng tẩy để xóa lỗi.",
example_en:"I erased a mistake with an eraser."
},

{
level:"N5",
lesson:7,
id:24,
kanji:"紙",
kana:"かみ",
hanviet:"CHỈ",
vi:"Giấy",
en:"Paper",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>紙<rt>かみ</rt></ruby></span>に <ruby>名前<rt>なまえ</rt></ruby>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"かみに なまえを かきます。",
example_vi:"Tôi viết tên lên giấy.",
example_en:"I write my name on paper."
},

{
level:"N5",
lesson:7,
id:25,
kanji:"花",
kana:"はな",
hanviet:"HOA",
vi:"Hoa",
en:"Flower",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>に <span class='target-word'><ruby>花<rt>はな</rt></ruby></span>を あげます。",
example_read:"ははに はなを あげます。",
example_vi:"Tôi tặng hoa cho mẹ.",
example_en:"I give flowers to my mother."
},

{
level:"N5",
lesson:7,
id:26,
kanji:"シャツ",
kana:"シャツ",
hanviet:"",
vi:"Áo sơ mi",
en:"Shirt",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <span class='target-word'>シャツ</span>を <ruby>着<rt>き</rt></ruby>ます。",
example_read:"まいにち しゃつを きます。",
example_vi:"Tôi mặc áo sơ mi mỗi ngày.",
example_en:"I wear a shirt every day."
},

{
level:"N5",
lesson:7,
id:27,
kanji:"プレゼント",
kana:"プレゼント",
hanviet:"",
vi:"Quà tặng",
en:"Present",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'>プレゼント</span>を あげます。",
example_read:"ともだちに ぷれぜんとを あげます。",
example_vi:"Tôi tặng quà cho bạn.",
example_en:"I give a present to my friend."
},

{
level:"N5",
lesson:7,
id:28,
kanji:"荷物",
kana:"にもつ",
hanviet:"HÀ VẬT",
vi:"Hành lý, đồ đạc",
en:"Luggage",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>荷物<rt>にもつ</rt></ruby></span>は <ruby>重<rt>おも</rt></ruby>いです。",
example_read:"この にもつは おもいです。",
example_vi:"Hành lý này nặng.",
example_en:"This luggage is heavy."
},

{
level:"N5",
lesson:7,
id:29,
kanji:"お金",
kana:"おかね",
hanviet:"KIM",
vi:"Tiền",
en:"Money",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>お金<rt>おかね</rt></ruby></span>で <ruby>本<rt>ほん</rt></ruby>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"おかねで ほんを かいます。",
example_vi:"Tôi mua sách bằng tiền.",
example_en:"I buy a book with money."
},

{
level:"N5",
lesson:7,
id:30,
kanji:"切符",
kana:"きっぷ",
hanviet:"THIẾT PHÙ",
vi:"Vé",
en:"Ticket",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>で <span class='target-word'><ruby>切符<rt>きっぷ</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"えきで きっぷを かいます。",
example_vi:"Tôi mua vé ở nhà ga.",
example_en:"I buy a ticket at the station."
},

{
level:"N5",
lesson:7,
id:31,
kanji:"クリスマス",
kana:"クリスマス",
hanviet:"",
vi:"Giáng sinh",
en:"Christmas",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <span class='target-word'>クリスマス</span>の プレゼントを <ruby>貰<rt>もら</rt></ruby>いました。",
example_read:"ともだちに くりすますの ぷれぜんとを もらいました。",
example_vi:"Tôi đã nhận quà Giáng sinh từ bạn.",
example_en:"I received a Christmas present from my friend."
},

{
level:"N5",
lesson:7,
id:32,
kanji:"父",
kana:"ちち",
hanviet:"PHỤ",
vi:"Bố (của tôi)",
en:"My father",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>父<rt>ちち</rt></ruby></span>は お<ruby>酒<rt>さけ</rt></ruby>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"ちちは おさけを のみます。",
example_vi:"Bố tôi uống rượu.",
example_en:"My father drinks alcohol."
},

{
level:"N5",
lesson:7,
id:33,
kanji:"母",
kana:"はは",
hanviet:"MẪU",
vi:"Mẹ (của tôi)",
en:"My mother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>母<rt>はは</rt></ruby></span>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>料理<rt>りょうり</rt></ruby>を します。",
example_read:"ははは まいにち りょうりを します。",
example_vi:"Mẹ tôi nấu ăn mỗi ngày.",
example_en:"My mother cooks every day."
},

{
level:"N5",
lesson:7,
id:34,
kanji:"お父さん",
kana:"おとうさん",
hanviet:"PHỤ",
vi:"Bố (nói về bố người khác, hoặc gọi bố mình)",
en:"Father, Dad (someone else's father / polite form)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>父<rt>とう</rt></ruby>さん</span>は <ruby>今<rt>いま</rt></ruby>、<ruby>家<rt>いえ</rt></ruby>に いますか。",
example_read:"おとうさんは いま いえに いますか。",
example_vi:"Bố bạn có ở nhà bây giờ không?",
example_en:"Is your father at home now?"
},

{
level:"N5",
lesson:7,
id:35,
kanji:"お母さん",
kana:"おかあさん",
hanviet:"MẪU",
vi:"Mẹ (nói về mẹ người khác, hoặc gọi mẹ mình)",
en:"Mother, Mom(someone else's mother / polite form)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>母<rt>かあ</rt></ruby>さん</span>は <ruby>優<rt>やさ</rt></ruby>しいです。",
example_read:"おかあさんは やさしいです。",
example_vi:"Mẹ bạn rất hiền.",
example_en:"Your mother is kind."
},

{
level:"N5",
lesson:7,
id:36,
kanji:"もう",
kana:"もう",
hanviet:"",
vi:"Đã, rồi",
en:"Already",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"A: ケーキを <ruby>食<rt>た</rt></ruby>べますか。<br>B: いいえ、<span class='target-word'>もう</span> <ruby>食<rt>た</rt></ruby>べました。",
example_read:"けーきを たべますか。いいえ、もう たべました。",
example_vi:"A: Bạn có ăn bánh không? B: Không, tôi ăn rồi.",
example_en:"A: Would you like some cake? B: No, I have already eaten."
},

{
level:"N5",
lesson:7,
id:37,
kanji:"まだ",
kana:"まだ",
hanviet:"",
vi:"Vẫn chưa",
en:"Not yet",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"A: <ruby>昼<rt>ひる</rt></ruby>ごはんを <ruby>食<rt>た</rt></ruby>べましたか。<br>B: いいえ、<span class='target-word'>まだ</span> <ruby>食<rt>た</rt></ruby>べていません。",
example_read:"ひるごはんを たべましたか。いいえ、まだ たべていません。",
example_vi:"A: Bạn ăn trưa chưa? B: Chưa, tôi vẫn chưa ăn.",
example_en:"A: Have you had lunch? B: No, I haven't eaten yet."
},

{
level:"N5",
lesson:7,
id:38,
kanji:"これから",
kana:"これから",
hanviet:"",
vi:"Từ bây giờ",
en:"From now on",
word_type_vi:"Phó từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>これから</span> <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"これから べんきょうします。",
example_vi:"Từ bây giờ tôi sẽ học bài.",
example_en:"From now on I will study."
},

{
level:"N5",
lesson:7,
id:39,
kanji:"素敵ですね",
kana:"すてきですね",
hanviet:"TỐ ĐỊCH",
vi:"Hay nhỉ / Đẹp nhỉ / Tuyệt vời nhỉ",
en:"That's lovely / That's nice / That's wonderful",
word_type_vi:"Câu cảm thán",
word_type_en:"Fixed expression",
category:"Minna 1",
example:"その <ruby>服<rt>ふく</rt></ruby>は <span class='target-word'><ruby>素敵<rt>すてき</rt></ruby>ですね</span>。",
example_read:"その ふくは すてきですね。",
example_vi:"Bộ quần áo đó đẹp quá nhỉ.",
example_en:"That outfit is wonderful."
},

{
level:"N5",
lesson:7,
id:40,
kanji:"いらっしゃい",
kana:"いらっしゃい",
hanviet:"",
vi:"Chào mừng / Hoan nghênh (khi khách đến)",
en:"Welcome (casual greeting to guests)",
word_type_vi:"Câu chào",
word_type_en:"Greeting",
category:"Minna 1",
example:"<span class='target-word'>いらっしゃい</span>。どうぞ お<ruby>上<rt>あ</rt></ruby>がりください。",
example_read:"いらっしゃい。どうぞ おあがりください。",
example_vi:"Chào mừng, mời vào.",
example_en:"Welcome, please come in."
},

{
level:"N5",
lesson:7,
id:41,
kanji:"どうぞお上がりください",
kana:"どうぞおあがりください",
hanviet:"THƯỢNG",
vi:"Xin mời vào nhà",
en:"Please come in",
word_type_vi:"Câu lịch sự",
word_type_en:"Polite expression",
category:"Minna 1",
example:"A: お<ruby>邪魔<rt>じゃま</rt></ruby>します。<br>B: <span class='target-word'>どうぞ お<ruby>上<rt>あ</rt></ruby>がりください</span>。",
example_read:"おじゃまします。どうぞ おあがりください。",
example_vi:"A: Xin phép làm phiền. B: Xin mời vào nhà.",
example_en:"A: Excuse me for bothering you. B: Please come in."
},

{
level:"N5",
lesson:7,
id:42,
kanji:"失礼します",
kana:"しつれいします",
hanviet:"THẤT LỄ",
vi:"Xin phép / xin lỗi vì làm phiền",
en:"Excuse me (when entering/leaving)",
word_type_vi:"Câu lịch sự",
word_type_en:"Polite expression",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>、<span class='target-word'><ruby>失礼<rt>しつれい</rt></ruby>します</span>。",
example_read:"せんせい、しつれいします。",
example_vi:"Thưa cô/thầy, em xin phép về trước.",
example_en:"Teacher, excuse me."
},

{
level:"N5",
lesson:7,
id:43,
kanji:"[~は]いかがですか",
kana:"[~は]いかがですか",
hanviet:"",
vi:"Bạn dùng thử không? / thế nào?",
en:"How about...? / Would you like...?",
word_type_vi:"Câu lịch sự",
word_type_en:"Polite expression",
category:"Minna 1",
example:"コーヒーは <span class='target-word'>いかがですか</span>。",
example_read:"こーひーはいかがですか。",
example_vi:"Bạn dùng cà phê không?",
example_en:"Would you like some coffee?"
},

{
level:"N5",
lesson:7,
id:44,
kanji:"いただきます",
kana:"いただきます",
hanviet:"",
vi:"Xin mời trước khi ăn",
en:"Let's eat (before meal)",
word_type_vi:"Câu cố định",
word_type_en:"Fixed expression",
category:"Minna 1",
example:"A: どうぞ <ruby>食<rt>た</rt></ruby>べてください。<br>B: <span class='target-word'>いただきます</span>。",
example_read:"どうぞ たべてください。いただきます。",
example_vi:"A: Mời dùng bữa. B: Xin mời (trước khi ăn).",
example_en:"A: Please eat. B: Thank you for the meal."
},

{
level:"N5",
lesson:7,
id:45,
kanji:"ごちそうさま[でした]",
kana:"ごちそうさま[でした]",
hanviet:"",
vi:"Cảm ơn sau bữa ăn",
en:"Thank you for the meal",
word_type_vi:"Câu cố định",
word_type_en:"Fixed expression",
category:"Minna 1",
example:"A: もう お<ruby>腹<rt>なか</rt></ruby>が いっぱいですか。<br>B: はい。<span class='target-word'>ごちそうさまでした</span>。",
example_read:"もう おなかが いっぱいですか。はい。ごちそうさまでした。",
example_vi:"A: Bạn no rồi à? B: Vâng. Cảm ơn vì bữa ăn ngon.",
example_en:"A: Are you full already? B: Yes. Thank you for the meal."
},

{
level:"N5",
lesson:7,
id:46,
kanji:"スペイン",
kana:"スペイン",
hanviet:"",
vi:"Tây Ban Nha",
en:"Spain",
word_type_vi:"Danh từ",
word_type_en:"Country name",
category:"Minna 1",
example:"いつか <span class='target-word'>スペイン</span>に <ruby>行<rt>い</rt></ruby>きたいです。",
example_read:"いつか すぺいんに いきたいです。",
example_vi:"Một ngày nào đó tôi muốn đi Tây Ban Nha.",
example_en:"I want to go to Spain someday."
},
];