window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[23] = [

{
level:"N5",
lesson:23,
id:1,
kanji:"聞きます",
kana:"ききます",
hanviet:"VĂN",
vi:"hỏi",
en:"ask",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>分<rt>わ</rt></ruby>からないことが あったら、<ruby>先生<rt>せんせい</rt></ruby>に <span class='target-word'><ruby>聞<rt>き</rt></ruby>きます</span>。",
example_read:"わからないことが あったら せんせいに ききます",
example_vi:"Nếu có điều gì không hiểu, tôi sẽ hỏi giáo viên.",
example_en:"If there's something I don't understand, I'll ask the teacher."
},

{
level:"N5",
lesson:23,
id:2,
kanji:"回します",
kana:"まわします",
hanviet:"HỒI",
vi:"vặn",
en:"turn",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いので、エアコンの つまみを <span class='target-word'><ruby>回<rt>まわ</rt></ruby>します</span>。",
example_read:"あついので エアコンの つまみを まわします",
example_vi:"Vì nóng nên tôi vặn núm điều hòa.",
example_en:"It's hot, so I turn the air conditioner's knob."
},

{
level:"N5",
lesson:23,
id:3,
kanji:"引きます",
kana:"ひきます",
hanviet:"DẪN",
vi:"kéo",
en:"pull",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>店<rt>みせ</rt></ruby>に <ruby>入<rt>はい</rt></ruby>るとき、ドアを <span class='target-word'><ruby>引<rt>ひ</rt></ruby>きます</span>。",
example_read:"みせに はいるとき ドアを ひきます",
example_vi:"Khi vào cửa hàng, tôi kéo cửa.",
example_en:"When entering the store, I pull the door."
},

{
level:"N5",
lesson:23,
id:4,
kanji:"変えます",
kana:"かえます",
hanviet:"BIẾN",
vi:"đổi, thay đổi",
en:"change",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>気分<rt>きぶん</rt></ruby>を <ruby>変<rt>か</rt></ruby>えるために、<ruby>部屋<rt>へや</rt></ruby>の レイアウトを <span class='target-word'><ruby>変<rt>か</rt></ruby>えます</span>。",
example_read:"きぶんを かえるために へやの レイアウトを かえます",
example_vi:"Để đổi không khí, tôi thay đổi cách bố trí căn phòng.",
example_en:"To refresh my mood, I change the room layout."
},

{
level:"N5",
lesson:23,
id:5,
kanji:"触ります",
kana:"さわります",
hanviet:"XÚC",
vi:"sờ, chạm vào",
en:"touch",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>危<rt>あぶ</rt></ruby>ないですから、その ドアに <span class='target-word'><ruby>触<rt>さわ</rt></ruby>ります</span>な。",
example_read:"あぶないですから その ドアに さわりますな",
example_vi:"Vì nguy hiểm nên đừng chạm vào cánh cửa đó.",
example_en:"It's dangerous, so don't touch that door."
},

{
level:"N5",
lesson:23,
id:6,
kanji:"出ます",
kana:"でます",
hanviet:"XUẤT",
vi:"(tiền thừa) ra",
en:"come out",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"この <ruby>機械<rt>きかい</rt></ruby>は ボタンを <ruby>押<rt>お</rt></ruby>すと、<span class='target-word'><ruby>お釣<rt>つ</rt></ruby>りが 出ます</span>。",
example_read:"この きかいは ボタンを おすと おつりが でます",
example_vi:"Máy này khi bấm nút thì tiền thừa sẽ chạy ra.",
example_en:"When you press the button on this machine, the change comes out."
},

{
level:"N5",
lesson:23,
id:7,
kanji:"歩きます",
kana:"あるきます",
hanviet:"BỘ",
vi:"đi bộ",
en:"walk",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>健康<rt>けんこう</rt></ruby>のために、<ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>公園<rt>こうえん</rt></ruby>を <span class='target-word'><ruby>歩<rt>ある</rt></ruby>きます</span>。",
example_read:"けんこうのために まいあさ こうえんを あるきます",
example_vi:"Vì sức khỏe, mỗi sáng tôi đi bộ trong công viên.",
example_en:"For my health, I walk in the park every morning."
},

{
level:"N5",
lesson:23,
id:8,
kanji:"渡ります",
kana:"わたります",
hanviet:"ĐỘ",
vi:"đi qua",
en:"cross",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>信号<rt>しんごう</rt></ruby>が <ruby>青<rt>あお</rt></ruby>に なってから、<ruby>橋<rt>はし</rt></ruby>を <span class='target-word'><ruby>渡<rt>わた</rt></ruby>ります</span>。",
example_read:"しんごうが あおに なってから はしを わたります",
example_vi:"Khi đèn chuyển xanh, tôi đi qua cây cầu.",
example_en:"After the traffic light turns green, I cross the bridge."
},

{
level:"N5",
lesson:23,
id:9,
kanji:"曲がります",
kana:"まがります",
hanviet:"KHÚC",
vi:"rẽ",
en:"turn",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"その <ruby>交差点<rt>こうさてん</rt></ruby>を <ruby>右<rt>みぎ</rt></ruby>へ <span class='target-word'><ruby>曲<rt>ま</rt></ruby>がります</span>。",
example_read:"その こうさてんを みぎへ まがります",
example_vi:"Rẽ phải ở ngã tư đó.",
example_en:"Turn right at that intersection."
},

{
level:"N5",
lesson:23,
id:10,
kanji:"寂しい",
kana:"さびしい",
hanviet:"TỊCH",
vi:"buồn, cô đơn",
en:"lonely",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>家族<rt>かぞく</rt></ruby>に <ruby>会<rt>あ</rt></ruby>えなくて、<ruby>少<rt>すこ</rt></ruby>し <span class='target-word'><ruby>寂<rt>さび</rt></ruby>しい</span>です。",
example_read:"かぞくに あえなくて すこし さびしいです",
example_vi:"Không được gặp gia đình nên tôi hơi cô đơn.",
example_en:"I feel a little lonely because I can't see my family."
},
{
level:"N5",
lesson:23,
id:11,
kanji:"お湯",
kana:"おゆ",
hanviet:"",
vi:"nước nóng",
en:"hot water",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>寒<rt>さむ</rt></ruby>い <ruby>日<rt>ひ</rt></ruby>は、<span class='target-word'><ruby>お湯<rt>ゆ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>むと <ruby>体<rt>からだ</rt></ruby>が <ruby>温<rt>あたた</rt></ruby>まります。",
example_read:"さむい ひは おゆを のむと からだが あたたまります",
example_vi:"Vào ngày lạnh, uống nước nóng sẽ làm cơ thể ấm lên.",
example_en:"On cold days, drinking hot water warms your body."
},

{
level:"N5",
lesson:23,
id:12,
kanji:"音",
kana:"おと",
hanviet:"ÂM",
vi:"âm thanh",
en:"sound",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>隣<rt>となり</rt></ruby>の <ruby>部屋<rt>へや</rt></ruby>から <span class='target-word'><ruby>音<rt>おと</rt></ruby></span>が <ruby>聞<rt>き</rt></ruby>こえます。",
example_read:"となりの へやから おとが きこえます",
example_vi:"Tôi nghe thấy âm thanh từ phòng bên cạnh.",
example_en:"I can hear a sound coming from the next room."
},

{
level:"N5",
lesson:23,
id:13,
kanji:"サイズ",
kana:"サイズ",
hanviet:"",
vi:"cỡ, kích thước",
en:"size",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>服<rt>ふく</rt></ruby>は <span class='target-word'>サイズ</span>が <ruby>少<rt>すこ</rt></ruby>し <ruby>大<rt>おお</rt></ruby>きいです。",
example_read:"この ふくは サイズが すこし おおきいです",
example_vi:"Bộ quần áo này hơi rộng một chút.",
example_en:"This piece of clothing is a little too big."
},

{
level:"N5",
lesson:23,
id:14,
kanji:"故障",
kana:"こしょう",
hanviet:"CỐ CHƯỚNG",
vi:"hỏng, sự cố",
en:"breakdown, malfunction",
word_type_vi:"Danh từ / Động từ nhóm 3 (故障します)",
word_type_en:"Noun / Suru verb",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby>、<ruby>車<rt>くるま</rt></ruby>が <span class='target-word'><ruby>故障<rt>こしょう</rt></ruby></span>して、<ruby>会社<rt>かいしゃ</rt></ruby>に <ruby>遅<rt>おく</rt></ruby>れました。",
example_read:"きのう くるまが こしょうして かいしゃに おくれました",
example_vi:"Hôm qua xe bị hỏng nên tôi đã đến công ty muộn.",
example_en:"Yesterday, my car broke down, so I was late for work."
},

{
level:"N5",
lesson:23,
id:15,
kanji:"道",
kana:"みち",
hanviet:"ĐẠO",
vi:"đường",
en:"road, way",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>道<rt>みち</rt></ruby></span>を <ruby>真<rt>ま</rt></ruby>っすぐ <ruby>行<rt>い</rt></ruby>くと、<ruby>駅<rt>えき</rt></ruby>があります。",
example_read:"この みちを まっすぐ いくと えきが あります",
example_vi:"Đi thẳng con đường này thì sẽ có nhà ga.",
example_en:"If you go straight along this road, there is a station."
},

{
level:"N5",
lesson:23,
id:16,
kanji:"交差点",
kana:"こうさてん",
hanviet:"GIAO SAI ĐIỂM",
vi:"ngã tư, giao lộ",
en:"intersection",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>交差点<rt>こうさてん</rt></ruby></span>で <ruby>左<rt>ひだり</rt></ruby>に <ruby>曲<rt>ま</rt></ruby>がってください。",
example_read:"こうさてんで ひだりに まがってください",
example_vi:"Hãy rẽ trái ở ngã tư.",
example_en:"Please turn left at the intersection."
},

{
level:"N5",
lesson:23,
id:17,
kanji:"信号",
kana:"しんごう",
hanviet:"TÍN HIỆU",
vi:"đèn tín hiệu giao thông",
en:"traffic light",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>赤<rt>あか</rt></ruby>い <span class='target-word'><ruby>信号<rt>しんごう</rt></ruby></span>の <ruby>時<rt>とき</rt></ruby>は、<ruby>止<rt>と</rt></ruby>まらなければなりません。",
example_read:"あかい しんごうの ときは とまらなければなりません",
example_vi:"Khi đèn đỏ thì phải dừng lại.",
example_en:"You have to stop when the traffic light is red."
},

{
level:"N5",
lesson:23,
id:18,
kanji:"角",
kana:"かど",
hanviet:"GIÁC",
vi:"góc",
en:"corner",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>次<rt>つぎ</rt></ruby>の <span class='target-word'><ruby>角<rt>かど</rt></ruby></span>を <ruby>右<rt>みぎ</rt></ruby>へ <ruby>曲<rt>ま</rt></ruby>がると、<ruby>銀行<rt>ぎんこう</rt></ruby>があります。",
example_read:"つぎの かどを みぎへ まがると ぎんこうが あります",
example_vi:"Rẽ phải ở góc tiếp theo thì sẽ thấy ngân hàng.",
example_en:"If you turn right at the next corner, you'll see a bank."
},

{
level:"N5",
lesson:23,
id:19,
kanji:"橋",
kana:"はし",
hanviet:"KIỀU",
vi:"cầu",
en:"bridge",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby>、この <span class='target-word'><ruby>橋<rt>はし</rt></ruby></span>を <ruby>渡<rt>わた</rt></ruby>って <ruby>学校<rt>がっこう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいあさ この はしを わたって がっこうへ いきます",
example_vi:"Mỗi sáng tôi đi qua cây cầu này để đến trường.",
example_en:"Every morning, I cross this bridge to go to school."
},

{
level:"N5",
lesson:23,
id:20,
kanji:"駐車場",
kana:"ちゅうしゃじょう",
hanviet:"TRÚ XA TRƯỜNG",
vi:"bãi đỗ xe",
en:"parking lot",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>車<rt>くるま</rt></ruby>は <span class='target-word'><ruby>駐車場<rt>ちゅうしゃじょう</rt></ruby></span>に <ruby>止<rt>と</rt></ruby>めてください。",
example_read:"くるまは ちゅうしゃじょうに とめてください",
example_vi:"Hãy đỗ xe ở bãi đỗ xe.",
example_en:"Please park the car in the parking lot."
},
{
level:"N5",
lesson:23,
id:21,
kanji:"建物",
kana:"たてもの",
hanviet:"KIẾN VẬT",
vi:"tòa nhà",
en:"building",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"あの <span class='target-word'><ruby>建物<rt>たてもの</rt></ruby></span>は <ruby>駅<rt>えき</rt></ruby>の <ruby>近<rt>ちか</rt></ruby>くに あります。",
example_read:"あの たてものは えきの ちかくに あります",
example_vi:"Tòa nhà kia nằm gần nhà ga.",
example_en:"That building is near the station."
},

{
level:"N5",
lesson:23,
id:22,
kanji:"何回も",
kana:"なんかいも",
hanviet:"HÀ HỒI",
vi:"nhiều lần",
en:"many times",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>同<rt>おな</rt></ruby>じ <ruby>質問<rt>しつもん</rt></ruby>を <span class='target-word'><ruby>何回<rt>なんかい</rt></ruby>も</span> <ruby>聞<rt>き</rt></ruby>いてしまいました。",
example_read:"おなじ しつもんを なんかいも きいてしまいました",
example_vi:"Tôi đã hỏi cùng một câu hỏi nhiều lần.",
example_en:"I ended up asking the same question many times."
},

{
level:"N5",
lesson:23,
id:23,
kanji:"～目",
kana:"～め",
hanviet:"",
vi:"thứ -, số - (biểu thị thứ tự)",
en:"ordinal number",
word_type_vi:"Hậu tố",
word_type_en:"Suffix",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>日本<rt>にほん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>くのは <span class='target-word'><ruby>二回目<rt>にかいめ</rt></ruby></span>です。",
example_read:"わたしは にほんへ いくのは にかいめです",
example_vi:"Đây là lần thứ hai tôi đến Nhật.",
example_en:"This is my second time going to Japan."
},

{
level:"N5",
lesson:23,
id:24,
kanji:"聖徳太子",
kana:"しょうとくたいし",
hanviet:"THÁNH ĐỨC THÁI TỬ",
vi:"Thái tử Shotoku (574–622)",
en:"Prince Shotoku (574–622)",
word_type_vi:"Tên riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>聖徳太子<rt>しょうとくたいし</rt></ruby></span>は <ruby>日本<rt>にほん</rt></ruby>の <ruby>歴史<rt>れきし</rt></ruby>で <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>人物<rt>じんぶつ</rt></ruby>です。",
example_read:"しょうとくたいしは にほんの れきしで ゆうめいな じんぶつです",
example_vi:"Thái tử Shotoku là một nhân vật nổi tiếng trong lịch sử Nhật Bản.",
example_en:"Prince Shotoku is a famous figure in Japanese history."
},

{
level:"N5",
lesson:23,
id:25,
kanji:"法隆寺",
kana:"ほうりゅうじ",
hanviet:"PHÁP LONG TỰ",
vi:"chùa Horyu-ji",
en:"Horyu-ji Temple",
word_type_vi:"Tên địa danh",
word_type_en:"Place name",
category:"Minna 1",
example:"<span class='target-word'><ruby>法隆寺<rt>ほうりゅうじ</rt></ruby></span>は <ruby>奈良県<rt>ならけん</rt></ruby>に ある <ruby>古<rt>ふる</rt></ruby>い お<ruby>寺<rt>てら</rt></ruby>です。",
example_read:"ほうりゅうじは ならけんに ある ふるい おてらです",
example_vi:"Chùa Horyu-ji là một ngôi chùa cổ ở tỉnh Nara.",
example_en:"Horyu-ji Temple is an old temple located in Nara Prefecture."
},

{
level:"N5",
lesson:23,
id:26,
kanji:"元気茶",
kana:"げんきちゃ",
hanviet:"",
vi:"tên một loại trà (giả tưởng)",
en:"Genki tea (fictional tea name)",
word_type_vi:"Tên sản phẩm",
word_type_en:"Product name",
category:"Minna 1",
example:"<span class='target-word'><ruby>元気茶<rt>げんきちゃ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>むと、<ruby>元気<rt>げんき</rt></ruby>になるそうです。",
example_read:"げんきちゃを のむと げんきに なるそうです",
example_vi:"Nghe nói uống trà Genki sẽ trở nên khỏe khoắn.",
example_en:"They say drinking Genki tea makes you feel energetic."
},

{
level:"N5",
lesson:23,
id:27,
kanji:"本田駅",
kana:"ほんだえき",
hanviet:"",
vi:"tên một nhà ga (giả định)",
en:"Honda Station (fictional station name)",
word_type_vi:"Tên địa danh",
word_type_en:"Place name",
category:"Minna 1",
example:"<span class='target-word'><ruby>本田駅<rt>ほんだえき</rt></ruby></span>で <ruby>電車<rt>でんしゃ</rt></ruby>を <ruby>降<rt>お</rt></ruby>りてください。",
example_read:"ほんだえきで でんしゃを おりてください",
example_vi:"Hãy xuống tàu ở ga Honda.",
example_en:"Please get off the train at Honda Station."
},

{
level:"N5",
lesson:23,
id:28,
kanji:"図書館前",
kana:"としょかんまえ",
hanviet:"",
vi:"tên một bến xe buýt (giả định)",
en:"Library Front (fictional bus stop name)",
word_type_vi:"Tên địa điểm",
word_type_en:"Place name",
category:"Minna 1",
example:"<span class='target-word'><ruby>図書館前<rt>としょかんまえ</rt></ruby></span>で バスを <ruby>待<rt>ま</rt></ruby>っています。",
example_read:"としょかんまえで バスを まっています",
example_vi:"Tôi đang đợi xe buýt ở bến Thư viện.",
example_en:"I'm waiting for the bus at Library Front."
}
];