window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[15] = [

{
level:"N5",
lesson:15,
id:1,
kanji:"置きます",
kana:"おきます",
hanviet:"TRÍ",
vi:"đặt, để",
en:"put, place",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>本<rt>ほん</rt></ruby>を <ruby>机<rt>つくえ</rt></ruby>の <ruby>上<rt>うえ</rt></ruby>に <span class='target-word'><ruby>置<rt>お</rt></ruby>きます</span>。",
example_read:"ほんを つくえの うえに おきます",
example_vi:"Tôi đặt quyển sách lên trên mặt bàn.",
example_en:"I put the book on the desk."
},

{
level:"N5",
lesson:15,
id:2,
kanji:"作ります",
kana:"つくります",
hanviet:"TÁC",
vi:"làm",
en:"make",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>料理<rt>りょうり</rt></ruby>を <span class='target-word'><ruby>作<rt>つく</rt></ruby>ります</span>。",
example_read:"まいにち りょうりを つくります",
example_vi:"Hằng ngày tôi nấu ăn.",
example_en:"I cook meals every day."
},

{
level:"N5",
lesson:15,
id:3,
kanji:"造ります",
kana:"つくります",
hanviet:"TẠO",
vi:"chế tạo, sản xuất",
en:"manufacture, produce",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"この <ruby>工場<rt>こうじょう</rt></ruby>は <ruby>車<rt>くるま</rt></ruby>を <span class='target-word'><ruby>造<rt>つく</rt></ruby>ります</span>。",
example_read:"この こうじょうは くるまを つくります",
example_vi:"Nhà máy này sản xuất ô tô.",
example_en:"This factory manufactures cars."
},

{
level:"N5",
lesson:15,
id:4,
kanji:"売ります",
kana:"うります",
hanviet:"MẠI",
vi:"bán",
en:"sell",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"スーパーで <ruby>野菜<rt>やさい</rt></ruby>を <span class='target-word'><ruby>売<rt>う</rt></ruby>っています</span>。",
example_read:"スーパーで やさいを うっています",
example_vi:"Siêu thị đang bán rau.",
example_en:"The supermarket sells vegetables."
},

{
level:"N5",
lesson:15,
id:5,
kanji:"知ります",
kana:"しります",
hanviet:"TRI",
vi:"biết",
en:"know",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"その <ruby>人<rt>ひと</rt></ruby>を <span class='target-word'><ruby>知<rt>し</rt></ruby>りません</span>。",
example_read:"その ひとを しりません",
example_vi:"Tôi không biết người đó.",
example_en:"I don't know that person."
},

{
level:"N5",
lesson:15,
id:6,
kanji:"住みます",
kana:"すみます",
hanviet:"TRỤ",
vi:"sống, ở",
en:"live",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>東京<rt>とうきょう</rt></ruby>に <span class='target-word'><ruby>住<rt>す</rt></ruby>みます</span>。",
example_read:"わたしは とうきょうに すみます",
example_vi:"Tôi sống ở Tokyo.",
example_en:"I live in Tokyo."
},

{
level:"N5",
lesson:15,
id:7,
kanji:"研究します",
kana:"けんきゅうします",
hanviet:"NGHIÊN CỨU",
vi:"nghiên cứu",
en:"research",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>大学<rt>だいがく</rt></ruby>で <ruby>日本語教育<rt>にほんごきょういく</rt></ruby>を <span class='target-word'><ruby>研究<rt>けんきゅう</rt></ruby>します</span>。",
example_read:"だいがくで にほんごきょういくを けんきゅうします",
example_vi:"Tôi nghiên cứu giáo dục tiếng Nhật ở trường đại học.",
example_en:"I research Japanese language education at university."
},

{
level:"N5",
lesson:15,
id:8,
kanji:"資料",
kana:"しりょう",
hanviet:"TƯ LIỆU",
vi:"tài liệu, tư liệu",
en:"materials, documents",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>図書館<rt>としょかん</rt></ruby>で <span class='target-word'><ruby>資料<rt>しりょう</rt></ruby></span>を <ruby>読<rt>よ</rt></ruby>みます。",
example_read:"としょかんで しりょうを よみます",
example_vi:"Tôi đọc tài liệu ở thư viện.",
example_en:"I read the materials at the library."
},

{
level:"N5",
lesson:15,
id:9,
kanji:"カタログ",
kana:"カタログ",
hanviet:"",
vi:"ca-ta-lô",
en:"catalog",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>新<rt>あたら</rt></ruby>しい <span class='target-word'>カタログ</span>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"あたらしい カタログを みます",
example_vi:"Tôi xem cuốn ca-ta-lô mới.",
example_en:"I look at the new catalog."
},

{
level:"N5",
lesson:15,
id:10,
kanji:"時刻表",
kana:"じこくひょう",
hanviet:"THỜI KHẮC BIỂU",
vi:"bảng giờ tàu chạy",
en:"timetable",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>電車<rt>でんしゃ</rt></ruby>の <span class='target-word'><ruby>時刻表<rt>じこくひょう</rt></ruby></span>を <ruby>調<rt>しら</rt></ruby>べます。",
example_read:"でんしゃの じこくひょうを しらべます",
example_vi:"Tôi kiểm tra bảng giờ tàu điện.",
example_en:"I check the train timetable."
},

{
level:"N5",
lesson:15,
id:11,
kanji:"服",
kana:"ふく",
hanviet:"PHỤC",
vi:"quần áo",
en:"clothes",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"デパートで <span class='target-word'><ruby>服<rt>ふく</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"デパートで ふくを かいます",
example_vi:"Tôi mua quần áo ở cửa hàng bách hóa.",
example_en:"I buy clothes at a department store."
},

{
level:"N5",
lesson:15,
id:12,
kanji:"製品",
kana:"せいひん",
hanviet:"CHẾ PHẨM",
vi:"sản phẩm",
en:"product",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>製品<rt>せいひん</rt></ruby></span>は <ruby>人気<rt>にんき</rt></ruby>です。",
example_read:"この せいひんは にんきです",
example_vi:"Sản phẩm này rất được ưa chuộng.",
example_en:"This product is popular."
},

{
level:"N5",
lesson:15,
id:13,
kanji:"ソフト",
kana:"ソフト",
hanviet:"",
vi:"phần mềm",
en:"software",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>で <ruby>新<rt>あたら</rt></ruby>しい <span class='target-word'>ソフト</span>を <ruby>使<rt>つか</rt></ruby>います。",
example_read:"しごとで あたらしい ソフトを つかいます",
example_vi:"Tôi sử dụng phần mềm mới trong công việc.",
example_en:"I use new software at work."
},

{
level:"N5",
lesson:15,
id:14,
kanji:"電子辞書",
kana:"でんしじしょ",
hanviet:"ĐIỆN TỬ TỪ THƯ",
vi:"kim từ điển",
en:"electronic dictionary",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>する <ruby>時<rt>とき</rt></ruby>、<span class='target-word'><ruby>電子辞書<rt>でんしじしょ</rt></ruby></span>を <ruby>使<rt>つか</rt></ruby>います。",
example_read:"にほんごを べんきょうする とき、でんしじしょを つかいます",
example_vi:"Khi học tiếng Nhật, tôi sử dụng từ điển điện tử.",
example_en:"I use an electronic dictionary when studying Japanese."
},

{
level:"N5",
lesson:15,
id:15,
kanji:"経済",
kana:"けいざい",
hanviet:"KINH TẾ",
vi:"kinh tế",
en:"economy",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>経済<rt>けいざい</rt></ruby></span>に <ruby>興味<rt>きょうみ</rt></ruby>が あります。",
example_read:"けいざいに きょうみが あります",
example_vi:"Tôi có hứng thú với kinh tế.",
example_en:"I am interested in economics."
},

{
level:"N5",
lesson:15,
id:16,
kanji:"市役所",
kana:"しやくしょ",
hanviet:"THỊ DỊCH SỞ",
vi:"tòa thị chính",
en:"city hall",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>住民票<rt>じゅうみんひょう</rt></ruby>を もらいに <span class='target-word'><ruby>市役所<rt>しやくしょ</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"じゅうみんひょうを もらいに しやくしょへ いきます",
example_vi:"Tôi đến tòa thị chính để xin giấy chứng nhận cư trú.",
example_en:"I go to city hall to get a residence certificate."
},

{
level:"N5",
lesson:15,
id:17,
kanji:"高校",
kana:"こうこう",
hanviet:"CAO HIỆU",
vi:"trường trung học phổ thông",
en:"high school",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <span class='target-word'><ruby>高校<rt>こうこう</rt></ruby></span>に <ruby>通<rt>かよ</rt></ruby>っています。",
example_read:"あには こうこうに かよっています",
example_vi:"Anh trai tôi đang học ở trường cấp 3.",
example_en:"My older brother attends high school."
},

{
level:"N5",
lesson:15,
id:18,
kanji:"歯医者",
kana:"はいしゃ",
hanviet:"XỈ Y GIẢ",
vi:"nha sĩ",
en:"dentist",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>歯<rt>は</rt></ruby>が <ruby>痛<rt>いた</rt></ruby>いので、<span class='target-word'><ruby>歯医者<rt>はいしゃ</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"はが いたいので はいしゃへ いきます",
example_vi:"Vì bị đau răng nên tôi đi nha sĩ.",
example_en:"I go to the dentist because I have a toothache."
},

{
level:"N5",
lesson:15,
id:19,
kanji:"独身",
kana:"どくしん",
hanviet:"ĐỘC THÂN",
vi:"độc thân",
en:"single",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>独身<rt>どくしん</rt></ruby></span>です。",
example_read:"わたしは どくしんです",
example_vi:"Tôi đang độc thân.",
example_en:"I am single."
},

{
level:"N5",
lesson:15,
id:20,
kanji:"すみません",
kana:"すみません",
hanviet:"",
vi:"xin lỗi",
en:"excuse me, sorry",
word_type_vi:"Cảm thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>すみません</span>、ちょっと <ruby>聞<rt>き</rt></ruby>いても いいですか。",
example_read:"すみません ちょっと きいても いいですか",
example_vi:"Xin lỗi, cho tôi hỏi một chút được không?",
example_en:"Excuse me, may I ask you something?"
},

{
level:"N5",
lesson:15,
id:21,
kanji:"皆さん",
kana:"みなさん",
hanviet:"GIAI",
vi:"quý vị, các anh chị, các bạn",
en:"everyone",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>皆<rt>みな</rt></ruby>さん</span>、こんにちは。",
example_read:"みなさん こんにちは",
example_vi:"Xin chào mọi người.",
example_en:"Hello everyone."
},

{
level:"N5",
lesson:15,
id:22,
kanji:"思い出します",
kana:"おもいだします",
hanviet:"TƯ XUẤT",
vi:"nhớ lại, hồi tưởng",
en:"remember",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>子供<rt>こども</rt></ruby>のころを <span class='target-word'><ruby>思<rt>おも</rt></ruby>い<ruby>出<rt>だ</rt></ruby>します</span>。",
example_read:"こどものころを おもいだします",
example_vi:"Tôi nhớ lại thời thơ ấu.",
example_en:"I remember my childhood."
},

{
level:"N5",
lesson:15,
id:23,
kanji:"いらっしゃいます",
kana:"いらっしゃいます",
hanviet:"",
vi:"có mặt, ở (kính ngữ của います)",
en:"be, come, go (honorific)",
word_type_vi:"Động từ đặc biệt",
word_type_en:"Special verb",
category:"Minna 1",
example:"すみません、<ruby>先生<rt>せんせい</rt></ruby>は <span class='target-word'>いらっしゃいます</span>か。",
example_read:"すみません せんせいは いらっしゃいますか",
example_vi:"Xin lỗi, thầy/cô có ở đây không ạ?",
example_en:"Excuse me, is the teacher here?"
},

{
level:"N5",
lesson:15,
id:24,
kanji:"日本橋",
kana:"にっぽんばし",
hanviet:"NHẬT BẢN KIỀU",
vi:"Nipponbashi (khu phố ở Osaka)",
en:"Nipponbashi",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>日本橋<rt>にほんばし</rt></ruby></span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>を します。",
example_read:"にほんばしで かいものを します",
example_vi:"Tôi đi mua sắm ở khu phố Nipponbashi.",
example_en:"I go shopping in Nipponbashi."
},

{
level:"N5",
lesson:15,
id:25,
kanji:"皆んなのインタビュー",
kana:"みんなのインタビュー",
hanviet:"GIAI",
vi:"Tên chương trình truyền hình",
en:"Everyone's Interview",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>皆<rt>みな</rt></ruby>んなのインタビュー</span>を <ruby>見<rt>み</rt></ruby>ますか。",
example_read:"みんなのインタビューを みますか",
example_vi:"Bạn có xem chương trình 'Chương trình Phỏng vấn mọi người' không?",
example_en:"Do you watch 'People’s Interview Show'?"
}
];