window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[4] = [

{
level:"N5",
lesson:4,
id:1,
kanji:"起きます",
kana:"おきます",
hanviet:"KHỞI",
vi:"Dậy, thức dậy",
en:"Wake up, get up",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>毎朝<rt>まいあさ</rt></ruby> ６<ruby>時<rt>じ</rt></ruby>に <span class='target-word'><ruby>起<rt>お</rt></ruby>きます</span>。",
example_read:"わたしは まいあさ ろくじに おきます。",
example_vi:"Mỗi sáng tôi thức dậy lúc 6 giờ.",
example_en:"I wake up at 6 o'clock every morning."
},

{
level:"N5",
lesson:4,
id:2,
kanji:"寝ます",
kana:"ねます",
hanviet:"TẨM",
vi:"Ngủ, đi ngủ",
en:"Sleep, go to bed",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>毎晩<rt>まいばん</rt></ruby> １１<ruby>時<rt>じ</rt></ruby>に <span class='target-word'><ruby>寝<rt>ね</rt></ruby>ます</span>。",
example_read:"わたしは まいばん じゅういちじに ねます。",
example_vi:"Mỗi tối tôi đi ngủ lúc 11 giờ.",
example_en:"I go to bed at 11 o'clock every night."
},

{
level:"N5",
lesson:4,
id:3,
kanji:"働きます",
kana:"はたらきます",
hanviet:"ĐỘNG",
vi:"Làm việc",
en:"Work",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>会社員<rt>かいしゃいん</rt></ruby>は <ruby>銀行<rt>ぎんこう</rt></ruby>で <span class='target-word'><ruby>働<rt>はたら</rt></ruby>きます</span>。",
example_read:"かいしゃいんは ぎんこうで はたらきます。",
example_vi:"Nhân viên công ty làm việc ở ngân hàng.",
example_en:"Office workers work at a bank."
},

{
level:"N5",
lesson:4,
id:4,
kanji:"休みます",
kana:"やすみます",
hanviet:"HƯU",
vi:"Nghỉ, nghỉ ngơi",
en:"Rest, take a break",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>は <ruby>日曜日<rt>にちようび</rt></ruby>に <span class='target-word'><ruby>休<rt>やす</rt></ruby>みます</span>。",
example_read:"がくせいは にちようびに やすみます。",
example_vi:"Học sinh nghỉ vào Chủ nhật.",
example_en:"Students rest on Sunday."
},

{
level:"N5",
lesson:4,
id:5,
kanji:"勉強します",
kana:"べんきょうします",
hanviet:"MIỄN CƯỜNG",
vi:"Học",
en:"Study",
word_type_vi:"Danh từ + します (động từ nhóm 3)",
word_type_en:"Suru verb (Group 3 verb)",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>は <ruby>日本語<rt>にほんご</rt></ruby>を <span class='target-word'><ruby>勉強<rt>べんきょう</rt></ruby>します</span>。",
example_read:"がくせいは にほんごを べんきょうします。",
example_vi:"Học sinh học tiếng Nhật.",
example_en:"Students study Japanese."
},

{
level:"N5",
lesson:4,
id:6,
kanji:"終わります",
kana:"おわります",
hanviet:"CHUNG",
vi:"Hết, kết thúc, xong",
en:"Finish, end",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>仕事<rt>しごと</rt></ruby>は ５<ruby>時<rt>じ</rt></ruby>に <span class='target-word'><ruby>終<rt>お</rt></ruby>わります</span>。",
example_read:"しごとは ごじに おわります。",
example_vi:"Công việc thường kết thúc lúc 5 giờ.",
example_en:"Work usually finishes at 5 o'clock."
},

{
level:"N5",
lesson:4,
id:7,
kanji:"",
kana:"デパート",
hanviet:"",
vi:"Cửa hàng bách hóa, trung tâm thương mại lớn",
en:"Department store",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>人々<rt>ひとびと</rt></ruby>は <span class='target-word'>デパート</span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>をします。",
example_read:"ひとびとは でぱーとで かいものをします。",
example_vi:"Mọi người mua sắm ở cửa hàng bách hóa.",
example_en:"People shop at a department store."
},
{
level:"N5",
lesson:4,
id:8,
kanji:"銀行",
kana:"ぎんこう",
hanviet:"NGÂN HÀNH",
vi:"Ngân hàng",
en:"Bank",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>銀行<rt>ぎんこう</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは ぎんこうへ いきます。",
example_vi:"Tôi đi đến ngân hàng.",
example_en:"I go to the bank."
},

{
level:"N5",
lesson:4,
id:9,
kanji:"郵便局",
kana:"ゆうびんきょく",
hanviet:"BƯU TIỆN CỤC",
vi:"Bưu điện",
en:"Post office",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>人々<rt>ひとびと</rt></ruby>は <span class='target-word'><ruby>郵便局<rt>ゆうびんきょく</rt></ruby></span>で <ruby>手紙<rt>てがみ</rt></ruby>を <ruby>送<rt>おく</rt></ruby>ります。",
example_read:"ひとびとは ゆうびんきょくで てがみを おくります。",
example_vi:"Mọi người gửi thư ở bưu điện.",
example_en:"People send letters at the post office."
},

{
level:"N5",
lesson:4,
id:10,
kanji:"図書館",
kana:"としょかん",
hanviet:"ĐỒ THƯ QUÁN",
vi:"Thư viện",
en:"Library",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>は <span class='target-word'><ruby>図書館<rt>としょかん</rt></ruby></span>で <ruby>本<rt>ほん</rt></ruby>を <ruby>読<rt>よ</rt></ruby>みます。",
example_read:"がくせいは としょかんで ほんを よみます。",
example_vi:"Học sinh đọc sách ở thư viện.",
example_en:"Students read books in the library."
},

{
level:"N5",
lesson:4,
id:11,
kanji:"美術館",
kana:"びじゅつかん",
hanviet:"MỸ THUẬT QUÁN",
vi:"Bảo tàng mỹ thuật",
en:"Art museum",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>人々<rt>ひとびと</rt></ruby>は <span class='target-word'><ruby>美術館<rt>びじゅつかん</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ひとびとは びじゅつかんへ いきます。",
example_vi:"Mọi người đi đến bảo tàng mỹ thuật.",
example_en:"People go to the art museum."
},

{
level:"N5",
lesson:4,
id:12,
kanji:"今",
kana:"いま",
hanviet:"KIM",
vi:"Bây giờ",
en:"Now",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>は <span class='target-word'><ruby>今<rt>いま</rt></ruby></span> <ruby>授業<rt>じゅぎょう</rt></ruby>を しています。",
example_read:"せんせいは いま じゅぎょうを しています。",
example_vi:"Giáo viên đang dạy học bây giờ.",
example_en:"The teacher is teaching now."
},

{
level:"N5",
lesson:4,
id:13,
kanji:"時",
kana:"じ",
hanviet:"THỜI",
vi:"Giờ",
en:"O'clock",
word_type_vi:"Hậu tố thời gian",
word_type_en:"Time Counter",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は ７<span class='target-word'><ruby>時<rt>じ</rt></ruby></span>に <ruby>起<rt>お</rt></ruby>きます。",
example_read:"わたしは しちじに おきます。",
example_vi:"Tôi dậy lúc 7 giờ.",
example_en:"I get up at 7 o'clock."
},

{
level:"N5",
lesson:4,
id:14,
kanji:"分",
kana:"ふん",
hanviet:"PHÂN",
vi:"Phút",
en:"Minute",
word_type_vi:"Hậu tố thời gian",
word_type_en:"Time Counter",
category:"Minna 1",
example:"バスは １０<span class='target-word'><ruby>分<rt>ぷん</rt></ruby></span> <ruby>遅<rt>おく</rt></ruby>れます。",
example_read:"ばすは じゅっぷん おくれます。",
example_vi:"Xe buýt đến trễ 10 phút.",
example_en:"The bus is 10 minutes late."
},

{
level:"N5",
lesson:4,
id:15,
kanji:"半",
kana:"はん",
hanviet:"BÁN",
vi:"Rưỡi, nửa",
en:"Half",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Expression",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は ７<ruby>時<rt>じ</rt></ruby><span class='target-word'><ruby>半<rt>はん</rt></ruby></span>に <ruby>朝<rt>あさ</rt></ruby>ごはんを <ruby>食<rt>た</rt></ruby>べます。",
example_read:"わたしは しちじはんに あさごはんを たべます。",
example_vi:"Tôi ăn sáng lúc 7 giờ rưỡi.",
example_en:"I eat breakfast at half past seven."
},

{
level:"N5",
lesson:4,
id:16,
kanji:"何時",
kana:"なんじ",
hanviet:"HÀ THỜI",
vi:"Mấy giờ",
en:"What time",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question Word",
category:"Minna 1",
example:"<ruby>今<rt>いま</rt></ruby> <span class='target-word'><ruby>何時<rt>なんじ</rt></ruby></span>ですか。",
example_read:"いま なんじですか。",
example_vi:"Bây giờ là mấy giờ?",
example_en:"What time is it now?"
},

{
level:"N5",
lesson:4,
id:17,
kanji:"何分",
kana:"なんぷん",
hanviet:"HÀ PHÂN",
vi:"Mấy phút",
en:"How many minutes",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question Word",
category:"Minna 1",
example:"<ruby>今<rt>いま</rt></ruby> <ruby>何時<rt>なんじ</rt></ruby><span class='target-word'><ruby>何分<rt>なんぷん</rt></ruby></span>ですか。",
example_read:"いま なんじなんぷんですか。",
example_vi:"Bây giờ là mấy giờ mấy phút?",
example_en:"What time is it now?"
},

{
level:"N5",
lesson:4,
id:18,
kanji:"午前",
kana:"ごぜん",
hanviet:"NGỌ TIỀN",
vi:"Sáng, trước 12 giờ trưa",
en:"AM",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>学校<rt>がっこう</rt></ruby>は <span class='target-word'><ruby>午前<rt>ごぜん</rt></ruby></span> ８<ruby>時<rt>じ</rt></ruby>からです。",
example_read:"がっこうは ごぜん はちじからです。",
example_vi:"Trường học bắt đầu từ 8 giờ sáng.",
example_en:"School starts at 8 AM."
},

{
level:"N5",
lesson:4,
id:19,
kanji:"午後",
kana:"ごご",
hanviet:"NGỌ HẬU",
vi:"Chiều, sau 12 giờ trưa",
en:"PM",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>今<rt>いま</rt></ruby>は <span class='target-word'><ruby>午後<rt>ごご</rt></ruby></span> ３<ruby>時<rt>じ</rt></ruby>です。",
example_read:"いまは ごご さんじです。",
example_vi:"Hiện tại là 3 giờ chiều.",
example_en:"It is 3 o'clock in the afternoon now."
},

{
level:"N5",
lesson:4,
id:20,
kanji:"朝",
kana:"あさ",
hanviet:"TRIỀU",
vi:"Buổi sáng",
en:"Morning",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>朝<rt>あさ</rt></ruby></span> ６<ruby>時<rt>じ</rt></ruby>に <ruby>起<rt>お</rt></ruby>きます。",
example_read:"わたしは あさ ろくじに おきます。",
example_vi:"Tôi thức dậy lúc 6 giờ vào buổi sáng.",
example_en:"I get up at 6 o'clock in the morning."
},

{
level:"N5",
lesson:4,
id:21,
kanji:"昼",
kana:"ひる",
hanviet:"TRÚ",
vi:"Buổi trưa, trưa",
en:"Noon, lunchtime",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>昼<rt>ひる</rt></ruby></span>に ラーメンを <ruby>食<rt>た</rt></ruby>べます。",
example_read:"わたしは ひるに らーめんを たべます。",
example_vi:"Tôi ăn mì ramen vào buổi trưa.",
example_en:"I eat ramen at noon."
},

{
level:"N5",
lesson:4,
id:22,
kanji:"晩",
kana:"ばん",
hanviet:"VÃN",
vi:"Buổi tối, tối",
en:"Evening",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>晩<rt>ばん</rt></ruby></span>に <ruby>友達<rt>ともだち</rt></ruby>と <ruby>電話<rt>でんわ</rt></ruby>します。",
example_read:"わたしは ばんに ともだちと でんわします。",
example_vi:"Buổi tối tôi gọi điện cho bạn.",
example_en:"I call my friend in the evening."
},

{
level:"N5",
lesson:4,
id:23,
kanji:"一昨日",
kana:"おととい",
hanviet:"NHẤT TẠC NHẬT",
vi:"Hôm kia",
en:"The day before yesterday",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>一昨日<rt>おととい</rt></ruby></span> <ruby>図書館<rt>としょかん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きました。",
example_read:"わたしは おととい としょかんへ いきました。",
example_vi:"Hôm kia tôi đã đi thư viện.",
example_en:"I went to the library the day before yesterday."
},

{
level:"N5",
lesson:4,
id:24,
kanji:"昨日",
kana:"きのう",
hanviet:"TẠC NHẬT",
vi:"Hôm qua",
en:"Yesterday",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>は <span class='target-word'><ruby>昨日<rt>きのう</rt></ruby></span> <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ました。",
example_read:"ともだちは きのう えいがを みました。",
example_vi:"Hôm qua bạn tôi đã xem phim.",
example_en:"My friend watched a movie yesterday."
},

{
level:"N5",
lesson:4,
id:25,
kanji:"今日",
kana:"きょう",
hanviet:"KIM NHẬT ",
vi:"Hôm nay",
en:"Today",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>今日<rt>きょう</rt></ruby></span>は とても いい <ruby>天気<rt>てんき</rt></ruby>です。",
example_read:"きょうは とても いいてんきです。",
example_vi:"Hôm nay thời tiết rất đẹp.",
example_en:"The weather is very nice today."
},

{
level:"N5",
lesson:4,
id:26,
kanji:"明日",
kana:"あした",
hanviet:"MINH NHẬT ",
vi:"Ngày mai",
en:"Tomorrow",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>は <span class='target-word'><ruby>明日<rt>あした</rt></ruby></span> <ruby>学校<rt>がっこう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"がくせいは あした がっこうへ いきます。",
example_vi:"Ngày mai học sinh sẽ đi đến trường.",
example_en:"The student will go to school tomorrow."
},

{
level:"N5",
lesson:4,
id:27,
kanji:"明後日",
kana:"あさって",
hanviet:"MINH HẬU NHẬT ",
vi:"Ngày kia",
en:"The day after tomorrow",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>学生<rt>がくせい</rt></ruby>は <span class='target-word'><ruby>明後日<rt>あさって</rt></ruby></span> <ruby>試験<rt>しけん</rt></ruby>が あります。",
example_read:"がくせいは あさって しけんが あります。",
example_vi:"Học sinh sẽ có kỳ thi vào ngày kia.",
example_en:"The student has an exam the day after tomorrow."
},

{
level:"N5",
lesson:4,
id:28,
kanji:"今朝",
kana:"けさ",
hanviet:"KIM TRIỀU",
vi:"Sáng nay",
en:"This morning",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'><ruby>今朝<rt>けさ</rt></ruby></span> ６<ruby>時<rt>じ</rt></ruby>に <ruby>起<rt>お</rt></ruby>きました。",
example_read:"ちちは けさ ろくじに おきました。",
example_vi:"Sáng nay bố tôi đã thức dậy lúc 6 giờ.",
example_en:"My father got up at 6 this morning."
},

{
level:"N5",
lesson:4,
id:29,
kanji:"今晩",
kana:"こんばん",
hanviet:"KIM VÃN",
vi:"Tối nay",
en:"Tonight",
word_type_vi:"Danh từ thời gian",
word_type_en:"Time Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>今晩<rt>こんばん</rt></ruby></span> <ruby>家族<rt>かぞく</rt></ruby>と <ruby>晩<rt>ばん</rt></ruby>ごはんを <ruby>食<rt>た</rt></ruby>べます。",
example_read:"こんばん かぞくと ばんごはんを たべます。",
example_vi:"Tối nay tôi sẽ ăn tối cùng gia đình.",
example_en:"I will have dinner with my family tonight."
},

{
level:"N5",
lesson:4,
id:30,
kanji:"休み",
kana:"やすみ",
hanviet:"HƯU",
vi:"Nghỉ, nghỉ phép, ngày nghỉ",
en:"Holiday, day off",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>休<rt>やす</rt>み</ruby></span>です。",
example_read:"きょうは やすみです。",
example_vi:"Hôm nay là ngày nghỉ.",
example_en:"Today is a day off."
},

{
level:"N5",
lesson:4,
id:31,
kanji:"昼休み",
kana:"ひるやすみ",
hanviet:"TRÚ HƯU",
vi:"Nghỉ trưa",
en:"Lunch break",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>会社員<rt>かいしゃいん</rt></ruby>は <span class='target-word'><ruby>昼休<rt>ひるやす</rt>み</ruby></span>に お<ruby>弁当<rt>べんとう</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"かいしゃいんは ひるやすみに おべんとうを たべます。",
example_vi:"Nhân viên công ty ăn cơm hộp vào giờ nghỉ trưa.",
example_en:"Office workers eat their lunch during the lunch break."
},

{
level:"N5",
lesson:4,
id:32,
kanji:"試験",
kana:"しけん",
hanviet:"THÍ NGHIỆM",
vi:"Kỳ thi, bài kiểm tra",
en:"Exam, test",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby> <span class='target-word'><ruby>試験<rt>しけん</rt></ruby></span>が あります。",
example_read:"あした しけんが あります。",
example_vi:"Ngày mai có kỳ thi.",
example_en:"There is an exam tomorrow."
},

{
level:"N5",
lesson:4,
id:33,
kanji:"会議",
kana:"かいぎ",
hanviet:"HỘI NGHỊ",
vi:"Cuộc họp, hội nghị",
en:"Meeting",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>会社員<rt>かいしゃいん</rt></ruby>は <ruby>午後<rt>ごご</rt></ruby> <span class='target-word'><ruby>会議<rt>かいぎ</rt></ruby></span>を します。",
example_read:"かいしゃいんは ごご かいぎを します。",
example_vi:"Nhân viên công ty họp vào buổi chiều.",
example_en:"Office workers have a meeting in the afternoon."
},

{
level:"N5",
lesson:4,
id:34,
kanji:"映画",
kana:"えいが",
hanviet:"ÁNH HỌA",
vi:"Phim, điện ảnh",
en:"Movie",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby> <span class='target-word'><ruby>映画<rt>えいが</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"きょう えいがを みに いきます。",
example_vi:"Hôm nay tôi đi xem phim.",
example_en:"I am going to see a movie today."
},

{
level:"N5",
lesson:4,
id:35,
kanji:"毎朝",
kana:"まいあさ",
hanviet:"MỖI TRIỀU",
vi:"Mỗi sáng",
en:"Every morning",
word_type_vi:"Phó từ thời gian",
word_type_en:"Time Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>毎朝<rt>まいあさ</rt></ruby></span> ６<ruby>時<rt>じ</rt></ruby>に <ruby>起<rt>お</rt></ruby>きます。",
example_read:"わたしは まいあさ ろくじに おきます。",
example_vi:"Mỗi sáng tôi dậy lúc 6 giờ.",
example_en:"I get up at 6 every morning."
},

{
level:"N5",
lesson:4,
id:36,
kanji:"毎晩",
kana:"まいばん",
hanviet:"MỖI VÃN",
vi:"Mỗi tối",
en:"Every evening",
word_type_vi:"Phó từ thời gian",
word_type_en:"Time Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>毎晩<rt>まいばん</rt></ruby></span> <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"わたしは まいばん にほんごを べんきょうします。",
example_vi:"Mỗi tối tôi học tiếng Nhật.",
example_en:"I study Japanese every evening."
},

{
level:"N5",
lesson:4,
id:37,
kanji:"毎日",
kana:"まいにち",
hanviet:"MỖI NHẬT",
vi:"Mỗi ngày",
en:"Every day",
word_type_vi:"Phó từ thời gian",
word_type_en:"Time Adverb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'><ruby>毎日<rt>まいにち</rt></ruby></span> <ruby>働<rt>はたら</rt></ruby>きます。",
example_read:"ちちは まいにち はたらきます。",
example_vi:"Bố tôi làm việc mỗi ngày.",
example_en:"My father works every day."
},

{
level:"N5",
lesson:4,
id:38,
kanji:"月曜日",
kana:"げつようび",
hanviet:"NGUYỆT DIỆU NHẬT",
vi:"Thứ hai",
en:"Monday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>月曜日<rt>げつようび</rt></ruby>から <ruby>働<rt>はたら</rt></ruby>きます</span>。",
example_read:"わたしは げつようびから はたらきます。",
example_vi:"Tôi làm việc từ thứ hai.",
example_en:"I work from Monday."
},

{
level:"N5",
lesson:4,
id:39,
kanji:"火曜日",
kana:"かようび",
hanviet:"HỎA DIỆU NHẬT",
vi:"Thứ ba",
en:"Tuesday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>火曜日<rt>かようび</rt></ruby></span>に <ruby>試験<rt>しけん</rt></ruby>が あります。",
example_read:"わたしは かようびに しけんが あります。",
example_vi:"Tôi có kỳ thi vào thứ ba.",
example_en:"I have an exam on Tuesday."
},

{
level:"N5",
lesson:4,
id:40,
kanji:"水曜日",
kana:"すいようび",
hanviet:"THỦY DIỆU NHẬT",
vi:"Thứ tư",
en:"Wednesday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>水曜日<rt>すいようび</rt></ruby></span>が <ruby>休<rt>やす</rt></ruby>みです。",
example_read:"わたしは すいようびが やすみです。",
example_vi:"Tôi nghỉ vào thứ tư.",
example_en:"Wednesday is my day off."
},

{
level:"N5",
lesson:4,
id:41,
kanji:"木曜日",
kana:"もくようび",
hanviet:"MỘC DIỆU NHẬT",
vi:"Thứ năm",
en:"Thursday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>木曜日<rt>もくようび</rt></ruby></span>に <ruby>図書館<rt>としょかん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは もくようびに としょかんへ いきます。",
example_vi:"Tôi đi thư viện vào thứ năm.",
example_en:"I go to the library on Thursday."
},

{
level:"N5",
lesson:4,
id:42,
kanji:"金曜日",
kana:"きんようび",
hanviet:"KIM DIỆU NHẬT",
vi:"Thứ sáu",
en:"Friday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>金曜日<rt>きんようび</rt></ruby></span>に <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"わたしは きんようびに えいがを みます。",
example_vi:"Tôi xem phim vào thứ sáu.",
example_en:"I watch a movie on Friday."
},

{
level:"N5",
lesson:4,
id:43,
kanji:"土曜日",
kana:"どようび",
hanviet:"THỔ DIỆU NHẬT",
vi:"Thứ bảy",
en:"Saturday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>土曜日<rt>どようび</rt></ruby></span>に <ruby>友達<rt>ともだち</rt></ruby>と <ruby>会<rt>あ</rt></ruby>います。",
example_read:"わたしは どようびに ともだちと あいます。",
example_vi:"Tôi gặp bạn vào thứ bảy.",
example_en:"I meet my friend on Saturday."
},

{
level:"N5",
lesson:4,
id:44,
kanji:"日曜日",
kana:"にちようび",
hanviet:"NHẬT DIỆU NHẬT",
vi:"Chủ nhật",
en:"Sunday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>日曜日<rt>にちようび</rt></ruby></span>は <ruby>家<rt>うち</rt></ruby>で <ruby>休<rt>やす</rt></ruby>みます。",
example_read:"にちようびは うちで やすみます。",
example_vi:"Chủ nhật tôi nghỉ ở nhà.",
example_en:"I stay home and rest on Sunday."
},

{
level:"N5",
lesson:4,
id:45,
kanji:"何曜日",
kana:"なんようび",
hanviet:"HÀ DIỆU NHẬT",
vi:"Thứ mấy",
en:"What day of the week",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question Word",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>何曜日<rt>なんようび</rt></ruby></span>ですか。",
example_read:"きょうは なんようびですか。",
example_vi:"Hôm nay là thứ mấy?",
example_en:"What day is it today?"
},

{
level:"N5",
lesson:4,
id:46,
kanji:"",
kana:"～から",
hanviet:"",
vi:"Từ ~",
en:"From ~",
word_type_vi:"Trợ từ",
word_type_en:"Particle",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は ９<ruby>時<rt>じ</rt></ruby><span class='target-word'>から</span> <ruby>働<rt>はたら</rt></ruby>きます。",
example_read:"わたしは くじから はたらきます。",
example_vi:"Tôi làm việc từ 9 giờ.",
example_en:"I work from 9 o'clock."
},

{
level:"N5",
lesson:4,
id:47,
kanji:"",
kana:"～まで",
hanviet:"",
vi:"Đến ~",
en:"Until ~",
word_type_vi:"Trợ từ",
word_type_en:"Particle",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は ５<ruby>時<rt>じ</rt></ruby><span class='target-word'>まで</span> <ruby>働<rt>はたら</rt></ruby>きます。",
example_read:"ちちは ごじまで はたらきます。",
example_vi:"Bố tôi làm việc đến 5 giờ.",
example_en:"My father works until 5 o'clock."
},

{
level:"N5",
lesson:4,
id:48,
kanji:"",
kana:"～と",
hanviet:"",
vi:"Và / với",
en:"And / with",
word_type_vi:"Trợ từ",
word_type_en:"Particle",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>友達<rt>ともだち</rt></ruby><span class='target-word'>と</span> <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"わたしは ともだちと えいがを みます。",
example_vi:"Tôi xem phim cùng bạn.",
example_en:"I watch a movie with my friend."
},

{
level:"N5",
lesson:4,
id:49,
kanji:"大変ですね",
kana:"たいへんですね",
hanviet:"ĐẠI BIẾN",
vi:"Anh/chị vất vả quá",
en:"That must be hard",
word_type_vi:"Câu cảm thán",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>毎日<rt>まいにち</rt></ruby> <ruby>残業<rt>ざんぎょう</rt></ruby>ですか。<span class='target-word'><ruby>大変<rt>たいへん</rt></ruby>ですね</span>。",
example_read:"まいにち ざんぎょうですか。たいへんですね。",
example_vi:"Ngày nào cũng tăng ca à? Vất vả quá nhỉ.",
example_en:"You work overtime every day? That must be hard."
},

{
level:"N5",
lesson:4,
id:50,
kanji:"番号",
kana:"ばんごう",
hanviet:"PHIÊN HIỆU",
vi:"Số",
en:"Number",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"すみません、<ruby>電話<rt>でんわ</rt></ruby> <span class='target-word'><ruby>番号<rt>ばんごう</rt></ruby></span>を <ruby>教<rt>おし</rt></ruby>えてください。",
example_read:"すみません、でんわばんごうを おしえてください。",
example_vi:"Xin lỗi, xin hãy cho tôi biết số điện thoại.",
example_en:"Excuse me, please tell me your phone number."
},

{
level:"N5",
lesson:4,
id:51,
kanji:"何番",
kana:"なんばん",
hanviet:"HÀ PHIÊN",
vi:"Số mấy",
en:"What number",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question Word",
category:"Minna 1",
example:"それは <span class='target-word'><ruby>何番<rt>なんばん</rt></ruby></span>ですか。",
example_read:"それは なんばんですか。",
example_vi:"Đó là số mấy?",
example_en:"What number is that?"
},

{
level:"N5",
lesson:4,
id:52,
kanji:"",
kana:"そちら",
hanviet:"",
vi:"Ông/bà; phía đó",
en:"You; that side",
word_type_vi:"Đại từ lịch sự",
word_type_en:"Polite Pronoun",
category:"Minna 1",
example:"すみませんが、<span class='target-word'>そちら</span>は どなたですか。",
example_read:"すみませんが、そちらは どなたですか。",
example_vi:"Xin lỗi, bên đó là ai ạ?",
example_en:"Excuse me, who is this please?"
},

{
level:"N5",
lesson:4,
id:53,
kanji:"",
kana:"ニューヨーク",
hanviet:"",
vi:"New York",
en:"New York",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>彼<rt>かれ</rt></ruby>は <span class='target-word'>ニューヨーク</span>へ <ruby>行<rt>い</rt></ruby>きたいです。",
example_read:"かれは にゅーよーくへ いきたいです。",
example_vi:"Anh ấy muốn đi New York.",
example_en:"He wants to go to New York."
},

{
level:"N5",
lesson:4,
id:54,
kanji:"",
kana:"ペキン",
hanviet:"",
vi:"Bắc Kinh",
en:"Beijing",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>ペキン</span>は <ruby>中国<rt>ちゅうごく</rt></ruby>の <ruby>首都<rt>しゅと</rt></ruby>です。",
example_read:"ぺきんは ちゅうごくの しゅとです。",
example_vi:"Bắc Kinh là thủ đô Trung Quốc.",
example_en:"Beijing is the capital of China."
},

{
level:"N5",
lesson:4,
id:55,
kanji:"",
kana:"ロサンゼルス",
hanviet:"",
vi:"Los Angeles",
en:"Los Angeles",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>ロサンゼルス</span>へ <ruby>遊<rt>あそ</rt></ruby>びに <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは ろさんぜるすへ あそびに いきます。",
example_vi:"Tôi đi du lịch/đi chơi Los Angeles.",
example_en:"I go to Los Angeles for a trip."
},

{
level:"N5",
lesson:4,
id:56,
kanji:"",
kana:"ロンドン",
hanviet:"",
vi:"Luân Đôn",
en:"London",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>ロンドン</span>に <ruby>友達<rt>ともだち</rt></ruby>が います。",
example_read:"わたしは ろんどんに ともだちが います。",
example_vi:"Tôi có một người bạn ở Luân Đôn.",
example_en:"I have a friend in London."
},

{
level:"N5",
lesson:4,
id:57,
kanji:"",
kana:"あすか",
hanviet:"",
vi:"Asuka (tên nhà hàng giả định)",
en:"Asuka (restaurant name)",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>彼<rt>かれ</rt></ruby>は <span class='target-word'>あすか</span>で <ruby>昼食<rt>ちゅうしょく</rt></ruby>を <ruby>食<rt>た</rt></ruby>べます。",
example_read:"かれは あすかで ちゅうしょくを たべます。",
example_vi:"Anh ấy ăn trưa ở Asuka.",
example_en:"He has lunch at Asuka restaurant."
},

{
level:"N5",
lesson:4,
id:58,
kanji:"アップル銀行",
kana:"あっぷるぎんこう",
hanviet:"",
vi:"Ngân hàng Apple",
en:"Apple Bank",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>アップル<ruby>銀行<rt>ぎんこう</rt></ruby></span>は <ruby>９時<rt>くじ</rt></ruby>から <ruby>開きます<rt>あきます</rt></ruby>。",
example_read:"あっぷるぎんこうは くじから あきます。",
example_vi:"Ngân hàng Apple mở cửa từ 9 giờ.",
example_en:"Apple Bank opens from 9 o'clock."
},

{
level:"N5",
lesson:4,
id:59,
kanji:"みどり図書館",
kana:"みどりとしょかん",
hanviet:"",
vi:"Thư viện Midori",
en:"Midori Library",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>ジョン</ruby>は <span class='target-word'>みどり<ruby>図書館<rt>としょかん</rt></ruby></span>で <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"じょんは みどりとしょかんで べんきょうします。",
example_vi:"John học ở thư viện Midori.",
example_en:"John studies at Midori Library."
},

{
level:"N5",
lesson:4,
id:60,
kanji:"やまと美術館",
kana:"やまとびじゅつかん",
hanviet:"",
vi:"Bảo tàng mỹ thuật Yamato",
en:"Yamato Art Museum",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>やまと<ruby>美術館<rt>びじゅつかん</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは やまとびじゅつかんへ いきます。",
example_vi:"Tôi đi đến bảo tàng mỹ thuật Yamato.",
example_en:"I go to the Yamato Art Museum."
},
];