window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[19] = [

{
level:"N5",
lesson:19,
id:1,
kanji:"登ります",
kana:"のぼります",
hanviet:"ĐĂNG",
vi:"leo",
en:"climb",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>夏休<rt>なつやす</rt></ruby>みに <ruby>富士山<rt>ふじさん</rt></ruby>に <span class='target-word'><ruby>登<rt>のぼ</rt></ruby>ります</span>。",
example_read:"わたしは なつやすみに ふじさんに のぼります",
example_vi:"Kỳ nghỉ hè tôi sẽ leo núi Phú Sĩ.",
example_en:"I'll climb Mount Fuji during summer vacation."
},

{
level:"N5",
lesson:19,
id:2,
kanji:"泊まります",
kana:"とまります",
hanviet:"BẠC",
vi:"trọ, ở (khách sạn)",
en:"stay",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>旅行<rt>りょこう</rt></ruby>の <ruby>時<rt>とき</rt></ruby>は <ruby>駅<rt>えき</rt></ruby>の <ruby>近<rt>ちか</rt></ruby>くの ホテルに <span class='target-word'><ruby>泊<rt>と</rt></ruby>まります</span>。",
example_read:"りょこうの ときは えきの ちかくの ホテルに とまります",
example_vi:"Khi đi du lịch, tôi ở khách sạn gần ga.",
example_en:"When I travel, I stay at a hotel near the station."
},

{
level:"N5",
lesson:19,
id:3,
kanji:"掃除します",
kana:"そうじします",
hanviet:"TẢO TRỪ",
vi:"dọn dẹp, vệ sinh",
en:"clean",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>毎週<rt>まいしゅう</rt></ruby> <ruby>日曜日<rt>にちようび</rt></ruby>に <ruby>部屋<rt>へや</rt></ruby>を <span class='target-word'><ruby>掃除<rt>そうじ</rt></ruby>します</span>。",
example_read:"わたしは まいしゅう にちようびに へやを そうじします",
example_vi:"Chủ nhật nào tôi cũng dọn phòng.",
example_en:"I clean my room every Sunday."
},

{
level:"N5",
lesson:19,
id:4,
kanji:"洗濯します",
kana:"せんたくします",
hanviet:"TẨY TRẠCH",
vi:"giặt",
en:"do the laundry",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>は <ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>服<rt>ふく</rt></ruby>を <span class='target-word'><ruby>洗濯<rt>せんたく</rt></ruby>します</span>。",
example_read:"ははは まいあさ ふくを せんたくします",
example_vi:"Mẹ tôi giặt quần áo mỗi sáng.",
example_en:"My mother does the laundry every morning."
},

{
level:"N5",
lesson:19,
id:5,
kanji:"なります",
kana:"なります",
hanviet:"",
vi:"trở thành, trở nên",
en:"become",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>弟<rt>おとうと</rt></ruby>は <ruby>将来<rt>しょうらい</rt></ruby> <span class='target-word'><ruby>医者<rt>いしゃ</rt></ruby>に なります</span>。",
example_read:"おとうとは しょうらい いしゃに なります",
example_vi:"Em trai tôi sẽ trở thành bác sĩ trong tương lai.",
example_en:"My younger brother will become a doctor in the future."
},

{
level:"N5",
lesson:19,
id:6,
kanji:"眠い",
kana:"ねむい",
hanviet:"MIÊN",
vi:"buồn ngủ",
en:"sleepy",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby> <ruby>遅<rt>おそ</rt></ruby>く <ruby>寝<rt>ね</rt></ruby>たので、<ruby>今日<rt>きょう</rt></ruby>は とても <span class='target-word'><ruby>眠<rt>ねむ</rt></ruby>い</span>です。",
example_read:"きのう おそく ねたので きょうは とても ねむいです",
example_vi:"Hôm qua tôi ngủ muộn nên hôm nay rất buồn ngủ.",
example_en:"I went to bed late yesterday, so I'm very sleepy today."
},

{
level:"N5",
lesson:19,
id:7,
kanji:"強い",
kana:"つよい",
hanviet:"CƯỜNG",
vi:"mạnh",
en:"strong",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は とても <span class='target-word'><ruby>強<rt>つよ</rt></ruby>い</span>ので、<ruby>重<rt>おも</rt></ruby>い <ruby>荷物<rt>にもつ</rt></ruby>も <ruby>持<rt>も</rt></ruby>てます。",
example_read:"あには とても つよいので おもい にもつも もてます",
example_vi:"Anh tôi rất khỏe nên có thể mang cả hành lý nặng.",
example_en:"My older brother is very strong, so he can carry heavy luggage."
},

{
level:"N5",
lesson:19,
id:8,
kanji:"弱い",
kana:"よわい",
hanviet:"NHƯỢC",
vi:"yếu",
en:"weak",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>妹<rt>いもうと</rt></ruby>は <span class='target-word'><ruby>弱<rt>よわ</rt></ruby>い</span>ので、<ruby>重<rt>おも</rt></ruby>い <ruby>物<rt>もの</rt></ruby>は <ruby>持<rt>も</rt></ruby>てません。",
example_read:"いもうとは よわいので おもい ものは もてません",
example_vi:"Em gái tôi yếu nên không mang được đồ nặng.",
example_en:"My younger sister is weak, so she can't carry heavy things."
},

{
level:"N5",
lesson:19,
id:9,
kanji:"ゴルフ",
kana:"ゴルフ",
hanviet:"",
vi:"gôn",
en:"golf",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>休<rt>やす</rt></ruby>みの <ruby>日<rt>ひ</rt></ruby>に <span class='target-word'>ゴルフ</span>を します。",
example_read:"ちちは やすみの ひに ゴルフを します",
example_vi:"Bố tôi chơi gôn vào ngày nghỉ.",
example_en:"My father plays golf on his days off."
},

{
level:"N5",
lesson:19,
id:10,
kanji:"相撲",
kana:"すもう",
hanviet:"TƯƠNG PHÁC",
vi:"vật Sumo",
en:"sumo",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>ったら、<span class='target-word'><ruby>相撲<rt>すもう</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>たいです。",
example_read:"にほんへ いったら すもうを みたいです",
example_vi:"Nếu đến Nhật, tôi muốn xem môn vật Sumo.",
example_en:"If I go to Japan, I'd like to watch sumo."
},

{
level:"N5",
lesson:19,
id:11,
kanji:"お茶",
kana:"おちゃ",
hanviet:"TRÀ",
vi:"trà",
en:"tea",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>食事<rt>しょくじ</rt></ruby>の あとで <span class='target-word'>お<ruby>茶<rt>ちゃ</rt></ruby></span>を <ruby>飲<rt>の</rt></ruby>みます。",
example_read:"しょくじの あとで おちゃを のみます",
example_vi:"Sau bữa ăn tôi uống trà.",
example_en:"I drink tea after meals."
},

{
level:"N5",
lesson:19,
id:12,
kanji:"日",
kana:"ひ",
hanviet:"NHẬT",
vi:"ngày",
en:"day",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>日<rt>ひ</rt></ruby></span>によって <ruby>天気<rt>てんき</rt></ruby>が <ruby>違<rt>ちが</rt></ruby>います。",
example_read:"ひによって てんきが ちがいます",
example_vi:"Thời tiết thay đổi tùy từng ngày.",
example_en:"The weather changes depending on the day."
},

{
level:"N5",
lesson:19,
id:13,
kanji:"調子",
kana:"ちょうし",
hanviet:"ĐIỀU TỬ",
vi:"tình trạng, trạng thái",
en:"condition",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>調子<rt>ちょうし</rt></ruby></span>が いいです。",
example_read:"きょうは ちょうしが いいです",
example_vi:"Hôm nay tình trạng của tôi rất tốt.",
example_en:"I'm feeling well today."
},

{
level:"N5",
lesson:19,
id:14,
kanji:"一度",
kana:"いちど",
hanviet:"NHẤT ĐỘ",
vi:"một lần",
en:"once",
word_type_vi:"Danh từ / Trạng từ",
word_type_en:"Noun / Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>一度<rt>いちど</rt></ruby></span> <ruby>富士山<rt>ふじさん</rt></ruby>に <ruby>登<rt>のぼ</rt></ruby>ってみたいです。",
example_read:"いちど ふじさんに のぼってみたいです",
example_vi:"Tôi muốn thử leo núi Phú Sĩ một lần.",
example_en:"I'd like to climb Mount Fuji at least once."
},

{
level:"N5",
lesson:19,
id:15,
kanji:"一度も",
kana:"いちども",
hanviet:"NHẤT ĐỘ",
vi:"chưa từng... lần nào",
en:"never",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>一度<rt>いちど</rt></ruby>も</span> <ruby>相撲<rt>すもう</rt></ruby>を <ruby>見<rt>み</rt></ruby>たことが ありません。",
example_read:"わたしは いちども すもうを みたことが ありません",
example_vi:"Tôi chưa từng xem Sumo lần nào.",
example_en:"I've never watched sumo."
},

{
level:"N5",
lesson:19,
id:16,
kanji:"段々",
kana:"だんだん",
hanviet:"ĐOẠN ĐOẠN",
vi:"dần dần",
en:"gradually",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>日本語<rt>にほんご</rt></ruby>が <span class='target-word'><ruby>段々<rt>だんだん</rt></ruby></span> わかるように なりました。",
example_read:"にほんごが だんだん わかるように なりました",
example_vi:"Tôi dần dần hiểu được tiếng Nhật.",
example_en:"I'm gradually becoming able to understand Japanese."
},

{
level:"N5",
lesson:19,
id:17,
kanji:"もうすぐ",
kana:"もうすぐ",
hanviet:"",
vi:"sắp",
en:"soon",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>もうすぐ</span> <ruby>春<rt>はる</rt></ruby>です。",
example_read:"もうすぐ はるです",
example_vi:"Sắp đến mùa xuân rồi.",
example_en:"Spring is coming soon."
},

{
level:"N5",
lesson:19,
id:18,
kanji:"おかげさまで",
kana:"おかげさまで",
hanviet:"",
vi:"nhờ vậy mà / nhờ ơn (lịch sự)",
en:"thanks to you",
word_type_vi:"Thán từ",
word_type_en:"Expression",
category:"Minna 1",
example:"A：お<ruby>元気<rt>げんき</rt></ruby>ですか。<br>B：<span class='target-word'>おかげさまで</span>、<ruby>元気<rt>げんき</rt></ruby>です。",
example_read:"おげんきですか おかげさまで げんきです",
example_vi:"A: Bạn khỏe không? B: Vâng, nhờ bạn mà tôi vẫn khỏe.",
example_en:"A: How are you? B: Thanks, I'm doing well."
},

{
level:"N5",
lesson:19,
id:19,
kanji:"でも",
kana:"でも",
hanviet:"",
vi:"nhưng",
en:"but",
word_type_vi:"Liên từ",
word_type_en:"Conjunction",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>忙<rt>いそが</rt></ruby>しいです。<span class='target-word'>でも</span>、<ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"きょうは いそがしいです でも べんきょうします",
example_vi:"Hôm nay tôi bận. Nhưng tôi vẫn học.",
example_en:"I'm busy today, but I'll study."
},

{
level:"N5",
lesson:19,
id:20,
kanji:"乾杯",
kana:"かんぱい",
hanviet:"CÀN BÔI",
vi:"cạn ly! / nâng cốc!",
en:"cheers!",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"みんなで <span class='target-word'><ruby>乾杯<rt>かんぱい</rt></ruby></span>しましょう。",
example_read:"みんなで かんぱいしましょう",
example_vi:"Mọi người cùng nâng cốc nào!",
example_en:"Let's make a toast!"
},

{
level:"N5",
lesson:19,
id:21,
kanji:"ダイエット",
kana:"ダイエット",
hanviet:"",
vi:"việc ăn kiêng, chế độ giảm cân",
en:"diet",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>健康<rt>けんこう</rt></ruby>のために <span class='target-word'>ダイエット</span>を しています。",
example_read:"けんこうのために ダイエットを しています",
example_vi:"Tôi đang ăn kiêng để giữ gìn sức khỏe.",
example_en:"I'm on a diet for my health."
},

{
level:"N5",
lesson:19,
id:22,
kanji:"無理[な]",
kana:"むり[な]",
hanviet:"VÔ LÝ",
vi:"quá sức, không thể",
en:"impossible, too much",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>仕事<rt>しごと</rt></ruby>が <ruby>多<rt>おお</rt></ruby>すぎて、<span class='target-word'><ruby>無理<rt>むり</rt></ruby></span>です。",
example_read:"きょうは しごとが おおすぎて むりです",
example_vi:"Hôm nay công việc quá nhiều nên tôi không kham nổi.",
example_en:"There's too much work today, so it's impossible."
},

{
level:"N5",
lesson:19,
id:23,
kanji:"体にいい",
kana:"からだにいい",
hanviet:"THỂ",
vi:"tốt cho sức khỏe",
en:"good for one's health",
word_type_vi:"Cụm từ",
word_type_en:"Phrase",
category:"Minna 1",
example:"<ruby>野菜<rt>やさい</rt></ruby>は <span class='target-word'><ruby>体<rt>からだ</rt></ruby>にいい</span>です。",
example_read:"やさいは からだに いいです",
example_vi:"Rau rất tốt cho sức khỏe.",
example_en:"Vegetables are good for your health."
},

{
level:"N5",
lesson:19,
id:24,
kanji:"東京スカイツリー",
kana:"とうきょうスカイツリー",
hanviet:"ĐÔNG KINH",
vi:"Tokyo Sky Tree",
en:"Tokyo Skytree",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>去年<rt>きょねん</rt></ruby> <span class='target-word'><ruby>東京<rt>とうきょう</rt></ruby>スカイツリー</span>へ <ruby>行<rt>い</rt></ruby>きました。",
example_read:"きょねん とうきょう スカイツリーへ いきました",
example_vi:"Năm ngoái tôi đã đến Tokyo Skytree.",
example_en:"I went to Tokyo Skytree last year."
},

{
level:"N5",
lesson:19,
id:25,
kanji:"葛飾北斎",
kana:"かつしか ほくさい",
hanviet:"CÁT SỨC BẮC TRAI",
vi:"Katsushika Hokusai",
en:"Katsushika Hokusai",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>葛飾<rt>かつしか</rt></ruby> <ruby>北斎<rt>ほくさい</rt></ruby></span>は <ruby>有名<rt>ゆうめい</rt></ruby>な <ruby>画家<rt>がか</rt></ruby>です。",
example_read:"かつしか ほくさいは ゆうめいな がかです",
example_vi:"Katsushika Hokusai là một họa sĩ nổi tiếng.",
example_en:"Katsushika Hokusai is a famous painter."
}
];