window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[24] = [

{
level:"N5",
lesson:24,
id:1,
kanji:"くれます",
kana:"くれます",
hanviet:"",
vi:"cho, tặng (tôi)",
en:"give (me)",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>が <span class='target-word'>プレゼントを くれます</span>。",
example_read:"ともだちが プレゼントを くれます",
example_vi:"Bạn tôi tặng tôi quà.",
example_en:"My friend gives me a present."
},

{
level:"N5",
lesson:24,
id:2,
kanji:"直します",
kana:"なおします",
hanviet:"TRỰC",
vi:"chữa, sửa",
en:"fix, repair",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>壊<rt>こわ</rt></ruby>れた <ruby>時計<rt>とけい</rt></ruby>を <span class='target-word'><ruby>直<rt>なお</rt></ruby>します</span>。",
example_read:"こわれた とけいを なおします",
example_vi:"Tôi sửa chiếc đồng hồ bị hỏng.",
example_en:"I repair the broken clock."
},

{
level:"N5",
lesson:24,
id:3,
kanji:"連れて行きます",
kana:"つれていきます",
hanviet:"LIÊN HÀNH",
vi:"dẫn đi",
en:"take someone (somewhere)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>弟<rt>おとうと</rt></ruby>を <ruby>公園<rt>こうえん</rt></ruby>へ <span class='target-word'><ruby>連<rt>つ</rt></ruby>れて<ruby>行<rt>い</rt></ruby>きます</span>。",
example_read:"おとうとを こうえんへ つれていきます",
example_vi:"Tôi dẫn em trai đi công viên.",
example_en:"I take my younger brother to the park."
},

{
level:"N5",
lesson:24,
id:4,
kanji:"連れて来ます",
kana:"つれてきます",
hanviet:"LIÊN LAI",
vi:"dẫn đến",
en:"bring someone (here)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>を <ruby>家<rt>いえ</rt></ruby>へ <span class='target-word'><ruby>連<rt>つ</rt></ruby>れて<ruby>来<rt>き</rt></ruby>ます</span>。",
example_read:"ともだちを いえへ つれてきます",
example_vi:"Tôi dẫn bạn đến nhà.",
example_en:"I bring my friend to my house."
},

{
level:"N5",
lesson:24,
id:5,
kanji:"送ります",
kana:"おくります",
hanviet:"TỐNG",
vi:"đưa đi, đưa đến, tiễn [một ai đó]",
en:"take, see off, send",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>まで <ruby>友達<rt>ともだち</rt></ruby>を <span class='target-word'><ruby>送<rt>おく</rt></ruby>ります</span>。",
example_read:"えきまで ともだちを おくります",
example_vi:"Tôi đưa bạn đến nhà ga.",
example_en:"I take my friend to the station."
},

{
level:"N5",
lesson:24,
id:6,
kanji:"紹介します",
kana:"しょうかいします",
hanviet:"THIỆU GIỚI",
vi:"giới thiệu",
en:"introduce",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>を <ruby>先生<rt>せんせい</rt></ruby>に <span class='target-word'><ruby>紹介<rt>しょうかい</rt></ruby>します</span>。",
example_read:"ともだちを せんせいに しょうかいします",
example_vi:"Tôi giới thiệu bạn với giáo viên.",
example_en:"I introduce my friend to the teacher."
},

{
level:"N5",
lesson:24,
id:7,
kanji:"案内します",
kana:"あんないします",
hanviet:"ÁN NỘI",
vi:"hướng dẫn, giới thiệu, dẫn đường",
en:"guide, show around",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>町<rt>まち</rt></ruby>を <span class='target-word'><ruby>案内<rt>あんない</rt></ruby>します</span>。",
example_read:"まちを あんないします",
example_vi:"Tôi dẫn đường, giới thiệu thành phố.",
example_en:"I show someone around the town."
},

{
level:"N5",
lesson:24,
id:8,
kanji:"説明します",
kana:"せつめいします",
hanviet:"THUYẾT MINH",
vi:"giải thích, trình bày",
en:"explain",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>先生<rt>せんせい</rt></ruby>が <ruby>文法<rt>ぶんぽう</rt></ruby>を <span class='target-word'><ruby>説明<rt>せつめい</rt></ruby>します</span>。",
example_read:"せんせいが ぶんぽうを せつめいします",
example_vi:"Giáo viên giải thích ngữ pháp.",
example_en:"The teacher explains grammar."
},

{
level:"N5",
lesson:24,
id:9,
kanji:"おじいさん",
kana:"おじいさん",
hanviet:"",
vi:"ông nội, ông ngoại, ông",
en:"grandfather",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>おじいさん</span>は <ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>散歩<rt>さんぽ</rt></ruby>します。",
example_read:"おじいさんは まいあさ さんぽします",
example_vi:"Ông tôi đi dạo mỗi sáng.",
example_en:"My grandfather takes a walk every morning."
},

{
level:"N5",
lesson:24,
id:10,
kanji:"おばあさん",
kana:"おばあさん",
hanviet:"",
vi:"bà nội, bà ngoại, bà",
en:"grandmother",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>おばあさん</span>は <ruby>料理<rt>りょうり</rt></ruby>が <ruby>上手<rt>じょうず</rt></ruby>です。",
example_read:"おばあさんは りょうりが じょうずです",
example_vi:"Bà tôi nấu ăn giỏi.",
example_en:"My grandmother is good at cooking."
},
{
level:"N5",
lesson:24,
id:11,
kanji:"準備",
kana:"じゅんび",
hanviet:"CHUẨN BỊ",
vi:"chuẩn bị [～します: chuẩn bị]",
en:"preparation, prepare",
word_type_vi:"Danh từ / Động từ nhóm 3",
word_type_en:"Noun / Suru verb",
category:"Minna 1",
example:"<ruby>旅行<rt>りょこう</rt></ruby>の <span class='target-word'><ruby>準備<rt>じゅんび</rt></ruby></span>を します。",
example_read:"りょこうの じゅんびを します",
example_vi:"Tôi chuẩn bị cho chuyến du lịch.",
example_en:"I prepare for the trip."
},

{
level:"N5",
lesson:24,
id:12,
kanji:"引っ越し",
kana:"ひっこし",
hanviet:"DẪN VIỆT",
vi:"sự chuyển nhà",
en:"moving, moving house",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>来月<rt>らいげつ</rt></ruby>、<span class='target-word'><ruby>引<rt>ひ</rt></ruby>っ<ruby>越<rt>こ</rt></ruby>し</span>を します。",
example_read:"らいげつ ひっこしを します",
example_vi:"Tháng sau tôi sẽ chuyển nhà.",
example_en:"I will move house next month."
},

{
level:"N5",
lesson:24,
id:13,
kanji:"お菓子",
kana:"おかし",
hanviet:"QUẢ TỬ",
vi:"bánh kẹo",
en:"sweets, snacks",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>子供<rt>こども</rt></ruby>に <span class='target-word'>お<ruby>菓子<rt>かし</rt></ruby></span>を あげます。",
example_read:"こどもに おかしを あげます",
example_vi:"Tôi cho trẻ em bánh kẹo.",
example_en:"I give sweets to children."
},

{
level:"N5",
lesson:24,
id:14,
kanji:"ホームステイ",
kana:"ホームステイ",
hanviet:"",
vi:"homestay",
en:"homestay",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>で <span class='target-word'>ホームステイ</span>を しました。",
example_read:"にほんで ホームステイを しました",
example_vi:"Tôi đã ở homestay tại Nhật.",
example_en:"I did a homestay in Japan."
},

{
level:"N5",
lesson:24,
id:15,
kanji:"全部",
kana:"ぜんぶ",
hanviet:"TOÀN BỘ",
vi:"toàn bộ, tất cả",
en:"all, everything",
word_type_vi:"Danh từ / Trạng từ",
word_type_en:"Noun / Adverb",
category:"Minna 1",
example:"この <ruby>料理<rt>りょうり</rt></ruby>は <span class='target-word'><ruby>全部<rt>ぜんぶ</rt></ruby></span> <ruby>私<rt>わたし</rt></ruby>が <ruby>作<rt>つく</rt></ruby>りました。",
example_read:"この りょうりは ぜんぶ わたしが つくりました",
example_vi:"Toàn bộ món ăn này là do tôi làm.",
example_en:"I made all of these dishes."
},

{
level:"N5",
lesson:24,
id:16,
kanji:"自分で",
kana:"じぶんで",
hanviet:"TỰ PHÂN",
vi:"tự (mình)",
en:"by oneself",
word_type_vi:"Cụm từ",
word_type_en:"Phrase",
category:"Minna 1",
example:"<span class='target-word'><ruby>自分<rt>じぶん</rt></ruby>で</span> <ruby>料理<rt>りょうり</rt></ruby>を <ruby>作<rt>つく</rt></ruby>ります。",
example_read:"じぶんで りょうりを つくります",
example_vi:"Tôi tự mình nấu ăn.",
example_en:"I cook by myself."
},

{
level:"N5",
lesson:24,
id:17,
kanji:"会話",
kana:"かいわ",
hanviet:"HỘI THOẠI",
vi:"hội thoại, luyện nói",
en:"conversation",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Luyện nghe",
example:"<ruby>日本語<rt>にほんご</rt></ruby>の <span class='target-word'><ruby>会話<rt>かいわ</rt></ruby></span>を <ruby>練習<rt>れんしゅう</rt></ruby>します。",
example_read:"にほんごの かいわを れんしゅうします",
example_vi:"Tôi luyện hội thoại tiếng Nhật.",
example_en:"I practice Japanese conversation."
},

{
level:"N5",
lesson:24,
id:18,
kanji:"他に",
kana:"ほかに",
hanviet:"THA",
vi:"ngoài ra, bên cạnh đó",
en:"besides, other",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'><ruby>他<rt>ほか</rt></ruby>に</span> <ruby>質問<rt>しつもん</rt></ruby>が ありますか。",
example_read:"ほかに しつもんが ありますか",
example_vi:"Ngoài ra bạn còn câu hỏi nào không?",
example_en:"Do you have any other questions?"
},

{
level:"N5",
lesson:24,
id:19,
kanji:"母の日",
kana:"ははのひ",
hanviet:"MẪU NHẬT",
vi:"Ngày của Mẹ",
en:"Mother's Day",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>母<rt>はは</rt></ruby>の<ruby>日<rt>ひ</rt></ruby></span>に <ruby>母<rt>はは</rt></ruby>へ プレゼントを あげます。",
example_read:"ははのひに ははへ プレゼントを あげます",
example_vi:"Tôi tặng quà cho mẹ vào Ngày của Mẹ.",
example_en:"I give my mother a present on Mother's Day."
}
];