window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[18] = [

{
level:"N5",
lesson:18,
id:1,
kanji:"出来ます",
kana:"できます",
hanviet:"XUẤT LAI",
vi:"có thể, làm được",
en:"can, be able to",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>一人<rt>ひとり</rt></ruby>で <ruby>泳<rt>およ</rt></ruby>ぐことが <span class='target-word'><ruby>出来<rt>でき</rt></ruby>ます</span>。",
example_read:"わたしは ひとりで およぐことが できます",
example_vi:"Tôi có thể tự bơi một mình.",
example_en:"I can swim by myself."
},

{
level:"N5",
lesson:18,
id:2,
kanji:"洗います",
kana:"あらいます",
hanviet:"TẨY",
vi:"rửa",
en:"wash",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>は <ruby>食事<rt>しょくじ</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>に <ruby>台所<rt>だいどころ</rt></ruby>で <ruby>手<rt>て</rt></ruby>を <span class='target-word'><ruby>洗<rt>あら</rt></ruby>います</span>。",
example_read:"ははは しょくじのまえに だいどころで てを あらいます",
example_vi:"Mẹ tôi rửa tay trong bếp trước bữa ăn.",
example_en:"My mother washes her hands in the kitchen before meals."
},

{
level:"N5",
lesson:18,
id:3,
kanji:"弾きます",
kana:"ひきます",
hanviet:"ĐÀN",
vi:"chơi (nhạc cụ có dây)",
en:"play (instrument)",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>姉<rt>あね</rt></ruby>は <ruby>毎晩<rt>まいばん</rt></ruby> リビングで ピアノを <span class='target-word'><ruby>弾<rt>ひ</rt></ruby>きます</span>。",
example_read:"あねは まいばん リビングで ピアノを ひきます",
example_vi:"Chị tôi mỗi tối đều chơi piano trong phòng khách.",
example_en:"My older sister plays the piano in the living room every night."
},

{
level:"N5",
lesson:18,
id:4,
kanji:"歌います",
kana:"うたいます",
hanviet:"CA",
vi:"hát",
en:"sing",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>は カラオケで <ruby>大きな声<rt>おおきなこえ</rt></ruby>で <span class='target-word'><ruby>歌<rt>うた</rt></ruby>います</span>。",
example_read:"ともだちは からおけで おおきなこえで うたいます",
example_vi:"Bạn tôi hát rất to ở quán karaoke.",
example_en:"My friend sings loudly at karaoke."
},

{
level:"N5",
lesson:18,
id:5,
kanji:"集めます",
kana:"あつめます",
hanviet:"TẬP",
vi:"sưu tầm, thu thập",
en:"collect",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>弟<rt>おとうと</rt></ruby>は <ruby>部屋<rt>へや</rt></ruby>で <ruby>切手<rt>きって</rt></ruby>を <span class='target-word'><ruby>集<rt>あつ</rt></ruby>めます</span>。",
example_read:"おとうとは へやで きってを あつめます",
example_vi:"Em trai tôi sưu tầm tem trong phòng.",
example_en:"My younger brother collects stamps in his room."
},

{
level:"N5",
lesson:18,
id:6,
kanji:"捨てます",
kana:"すてます",
hanviet:"XẢ",
vi:"vứt, bỏ đi",
en:"throw away",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>古<rt>ふる</rt></ruby>い<ruby>新聞<rt>しんぶん</rt></ruby>を <span class='target-word'><ruby>捨<rt>す</rt></ruby>てます</span>。",
example_read:"ちちは まいあさ ふるいしんぶんを すてます",
example_vi:"Bố tôi mỗi sáng đều vứt báo cũ.",
example_en:"My father throws away old newspapers every morning."
},

{
level:"N5",
lesson:18,
id:7,
kanji:"換えます",
kana:"かえます",
hanviet:"HOÁN",
vi:"đổi, thay",
en:"exchange, change",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>旅行<rt>りょこう</rt></ruby>の<ruby>前<rt>まえ</rt></ruby>に <ruby>銀行<rt>ぎんこう</rt></ruby>で <ruby>お金<rt>おかね</rt></ruby>を <span class='target-word'><ruby>換<rt>か</rt></ruby>えます</span>。",
example_read:"りょこうのまえに ぎんこうで おかねを かえます",
example_vi:"Trước chuyến du lịch tôi đổi tiền ở ngân hàng.",
example_en:"I exchange money at the bank before traveling."
},

{
level:"N5",
lesson:18,
id:8,
kanji:"運転します",
kana:"うんてんします",
hanviet:"VẬN CHUYỂN",
vi:"lái xe",
en:"drive",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>会社<rt>かいしゃ</rt></ruby>まで <ruby>車<rt>くるま</rt></ruby>を <span class='target-word'><ruby>運転<rt>うんてん</rt></ruby>します</span>。",
example_read:"あには まいにち かいしゃまで くるまを うんてんします",
example_vi:"Anh trai tôi lái xe tới công ty mỗi ngày.",
example_en:"My older brother drives to the company every day."
},

{
level:"N5",
lesson:18,
id:9,
kanji:"予約します",
kana:"よやくします",
hanviet:"DỰ ƯỚC",
vi:"đặt chỗ, đặt trước",
en:"reserve",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Suru verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>今日<rt>きょう</rt></ruby> <ruby>電話<rt>でんわ</rt></ruby>で <ruby>レストラン</ruby>を <span class='target-word'><ruby>予約<rt>よやく</rt></ruby>します</span>。",
example_read:"わたしは きょう でんわで レストランを よやくします",
example_vi:"Hôm nay tôi sẽ gọi điện đặt chỗ ở nhà hàng.",
example_en:"Today I'm calling to make a reservation at a restaurant."
},

{
level:"N5",
lesson:18,
id:10,
kanji:"ピアノ",
kana:"ピアノ",
hanviet:"",
vi:"đàn piano",
en:"piano",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>妹<rt>いもうと</rt></ruby>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>家<rt>いえ</rt></ruby>で <span class='target-word'>ピアノ</span>を <ruby>弾<rt>ひ</rt></ruby>きます。",
example_read:"いもうとは まいにち いえで ピアノを ひきます",
example_vi:"Em gái tôi chơi đàn piano ở nhà mỗi ngày.",
example_en:"My younger sister plays the piano at home every day."
},

{
level:"N5",
lesson:18,
id:11,
kanji:"メートル",
kana:"―メートル",
hanviet:"",
vi:"mét",
en:"meter",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <ruby>木<rt>き</rt></ruby>は  <ruby>約<rt>やく</rt></ruby>3<span class='target-word'>メートル</span>くらいあります。",
example_read:"この きは やく さんメートル くらいあります",
example_vi:"Cây này cao khoảng 3 mét.",
example_en:"This tree is about 3 meters tall."
},

{
level:"N5",
lesson:18,
id:12,
kanji:"現金",
kana:"げんきん",
hanviet:"HIỆN KIM",
vi:"tiền mặt",
en:"cash",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>コンビニ</ruby>で <span class='target-word'><ruby>現金<rt>げんきん</rt></ruby></span>で <ruby>支払<rt>しはら</rt></ruby>いました。",
example_read:"わたしは コンビニで げんきんで しはらいました",
example_vi:"Tôi đã thanh toán bằng tiền mặt tại cửa hàng tiện lợi.",
example_en:"I paid in cash at the convenience store."
},

{
level:"N5",
lesson:18,
id:13,
kanji:"趣味",
kana:"しゅみ",
hanviet:"THÚ VỊ",
vi:"sở thích",
en:"hobby",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>の <span class='target-word'>趣味</span>は <ruby>音楽<rt>おんがく</rt></ruby>を <ruby>聞<rt>き</rt></ruby>くことです。",
example_read:"わたしの しゅみは おんがくを きくことです",
example_vi:"Sở thích của tôi là nghe nhạc.",
example_en:"My hobby is listening to music."
},

{
level:"N5",
lesson:18,
id:14,
kanji:"日記",
kana:"にっき",
hanviet:"NHẬT KÝ",
vi:"nhật ký",
en:"diary",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎晩<rt>まいばん</rt></ruby> <ruby>寝<rt>ね</rt></ruby>る <ruby>前<rt>まえ</rt></ruby>に <span class='target-word'>日記</span>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"まいばん ねるまえに にっきを かきます",
example_vi:"Tôi viết nhật ký mỗi tối trước khi đi ngủ.",
example_en:"I write in my diary every night before going to bed."
},

{
level:"N5",
lesson:18,
id:15,
kanji:"[お]祈り",
kana:"[お]いのり",
hanviet:"KÌ",
vi:"việc cầu nguyện",
en:"prayer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>彼女<rt>かのじょ</rt></ruby>は <ruby>神社<rt>じんじゃ</rt></ruby>で <span class='target-word'>お<ruby>祈<rt>いの</rt></ruby>り</span>を しました。",
example_read:"かのじょは じんじゃで おいのりを しました",
example_vi:"Cô ấy đã cầu nguyện tại đền Thần đạo.",
example_en:"She prayed at a Shinto shrine."
},

{
level:"N5",
lesson:18,
id:16,
kanji:"課長",
kana:"かちょう",
hanviet:"KHÓA TRƯỞNG",
vi:"tổ trưởng / quản lý bộ phận",
en:"section manager",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>部下<rt>ぶか</rt></ruby>は <span class='target-word'>課長</span>に <ruby>仕事<rt>しごと</rt></ruby>の <ruby>相談<rt>そうだん</rt></ruby>を しました。",
example_read:"ぶかは かちょうに しごとの そうだんを しました",
example_vi:"Nhân viên đã trao đổi công việc với tổ trưởng.",
example_en:"The employee consulted the section manager about work."
},

{
level:"N5",
lesson:18,
id:17,
kanji:"部長",
kana:"ぶちょう",
hanviet:"BỘ TRƯỞNG",
vi:"trưởng phòng",
en:"department manager",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>部長<rt>ぶちょう</rt></ruby></span>は <ruby>会議<rt>かいぎ</rt></ruby>で <ruby>重要<rt>じゅうよう</rt></ruby>な <ruby>話<rt>はなし</rt></ruby>を しました。",
example_read:"ぶちょうは かいぎで じゅうような はなしを しました",
example_vi:"Trưởng phòng đã trình bày một vấn đề quan trọng trong cuộc họp.",
example_en:"The department manager spoke about an important matter at the meeting."
},

{
level:"N5",
lesson:18,
id:18,
kanji:"社長",
kana:"しゃちょう",
hanviet:"XÃ TRƯỞNG",
vi:"giám đốc",
en:"company president",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>社長<rt>しゃちょう</rt></ruby></span>は <ruby>朝<rt>あさ</rt></ruby>から <ruby>社員<rt>しゃいん</rt></ruby>と <ruby>話<rt>はな</rt></ruby>しています。",
example_read:"しゃちょうは あさから しゃいんと はなしています",
example_vi:"Giám đốc đã nói chuyện với nhân viên từ sáng.",
example_en:"The company president has been talking with the employees since this morning."
},

{
level:"N5",
lesson:18,
id:19,
kanji:"動物",
kana:"どうぶつ",
hanviet:"ĐỘNG VẬT",
vi:"động vật",
en:"animal",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>子供<rt>こども</rt></ruby>たちは <span class='target-word'><ruby>動物<rt>どうぶつ</rt></ruby></span>が <ruby>大好<rt>だいす</rt></ruby>きで、<ruby>毎週<rt>まいしゅう</rt></ruby> <ruby>動物園<rt>どうぶつえん</rt></ruby>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"こどもたちは どうぶつが だいすきで まいしゅう どうぶつえんに いきます",
example_vi:"Bọn trẻ rất thích động vật nên tuần nào cũng đi sở thú.",
example_en:"The children love animals, so they go to the zoo every week."
},

{
level:"N5",
lesson:18,
id:20,
kanji:"馬",
kana:"うま",
hanviet:"MÃ",
vi:"con ngựa",
en:"horse",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>牧場<rt>ぼくじょう</rt></ruby>で <ruby>初<rt>はじ</rt></ruby>めて <span class='target-word'>馬</span>に <ruby>乗<rt>の</rt></ruby>りました。",
example_read:"ぼくじょうで はじめて うまに のりました",
example_vi:"Tôi đã cưỡi ngựa lần đầu tiên ở trang trại.",
example_en:"I rode a horse for the first time at a ranch."
},

{
level:"N5",
lesson:18,
id:21,
kanji:"インターネット",
kana:"インターネット",
hanviet:"",
vi:"internet",
en:"internet",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>インターネット</span>で <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"わたしは インターネットで にほんごを べんきょうしています",
example_vi:"Tôi học tiếng Nhật trên internet.",
example_en:"I study Japanese on the internet."
},

{
level:"N5",
lesson:18,
id:22,
kanji:"特に",
kana:"とくに",
hanviet:"ĐẶC",
vi:"đặc biệt là",
en:"especially",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>日本料理<rt>にほんりょうり</rt></ruby>が <ruby>好<rt>す</rt></ruby>きですが、<span class='target-word'><ruby>特<rt>とく</rt></ruby>に</span> <ruby>寿司<rt>すし</rt></ruby>が <ruby>大好<rt>だいす</rt></ruby>きです。",
example_read:"わたしは にほんりょうりが すきですが とくに すしが だいすきです",
example_vi:"Tôi thích món ăn Nhật, đặc biệt là sushi.",
example_en:"I like Japanese food, especially sushi."
},

{
level:"N5",
lesson:18,
id:23,
kanji:"へえ",
kana:"へえ",
hanviet:"",
vi:"ồ vậy à",
en:"oh really",
word_type_vi:"Cảm thán",
word_type_en:"Interjection",
category:"Minna 1",
example:"A：<ruby>来月<rt>らいげつ</rt></ruby> <ruby>日本<rt>にほん</rt></ruby>へ <ruby>旅行<rt>りょこう</rt></ruby>に <ruby>行<rt>い</rt></ruby>くんだ。B：<span class='target-word'>へぇ</span>、いいですね。",
example_read:"らいげつ にほんへ りょこうに いくんだ へぇ いいですね",
example_vi:"A: Tháng sau tôi sẽ đi du lịch Nhật Bản. B: Ồ, hay đấy.",
example_en:"A: I'm going to Japan next month. B: Oh, that's nice."
},

{
level:"N5",
lesson:18,
id:24,
kanji:"それは面白いですね",
kana:"それはおもしろいですね",
hanviet:"DIỆN BẠCH",
vi:"Cái đó thú vị nhỉ / Nghe có vẻ thú vị đấy.",
en:"That's interesting, isn't it? / That sounds interesting.",
word_type_vi:"Câu cảm thán / Tính từ",
word_type_en:"Sentence pattern (i-adj + ですね)",
category:"Minna 1",
example:"A：<ruby>最近<rt>さいきん</rt></ruby>、このアプリで <ruby>毎日<rt>まいにち</rt></ruby> <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しているんだ。B：<span class='target-word'>それは <ruby>面白<rt>おもしろ</rt></ruby>いですね</span>。",
example_read:"さいきん このアプリで まいにち にほんごを べんきょうしているんだ それはおもしろいですね",
example_vi:"A: Dạo gần đây tôi đang học tiếng Nhật mỗi ngày bằng ứng dụng này. B: Nghe có vẻ thú vị đấy.",
example_en:"A: Recently, I’ve been studying Japanese every day using this app. B: That sounds interesting."
},

{
level:"N5",
lesson:18,
id:25,
kanji:"なかなか",
kana:"なかなか",
hanviet:"",
vi:"khá là / mãi không",
en:"quite / not easily",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>新<rt>あたら</rt></ruby>しい <ruby>仕事<rt>しごと</rt></ruby>には <span class='target-word'>なかなか</span> <ruby>慣<rt>な</rt></ruby>れません。",
example_read:"あたらしい しごとには なかなか なれません",
example_vi:"Tôi mãi vẫn chưa quen với công việc mới.",
example_en:"I still can't get used to my new job."
},

{
level:"N5",
lesson:18,
id:26,
kanji:"本当ですか",
kana:"ほんとうですか",
hanviet:"BẢN ĐƯƠNG",
vi:"thật không?",
en:"really?",
word_type_vi:"Câu hỏi",
word_type_en:"Phrase",
category:"Minna 1",
example:"A：<ruby>来月<rt>らいげつ</rt></ruby> <ruby>日本<rt>にほん</rt></ruby>へ <ruby>引<rt>ひ</rt></ruby>っ<ruby>越<rt>こ</rt></ruby>すんだ。<br>B：へぇ、<span class='target-word'><ruby>本当<rt>ほんとう</rt></ruby>ですか</span>。",
example_read:"らいげつ にほんへ ひっこすんだ へぇ ほんとうですか",
example_vi:"A: Tháng sau mình sẽ chuyển sang Nhật sống. B: Ồ, thật vậy sao?",
example_en:"A: I'm moving to Japan next month. B: Oh, really?"
},

{
level:"N5",
lesson:18,
id:27,
kanji:"是非",
kana:"ぜひ",
hanviet:"THỊ PHI",
vi:"nhất định",
en:"definitely",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>日本<rt>にほん</rt></ruby>へ <ruby>来<rt>き</rt></ruby>たら、<span class='target-word'><ruby>是非<rt>ぜひ</rt></ruby></span> <ruby>遊<rt>あそ</rt></ruby>びに <ruby>来<rt>き</rt></ruby>てくださいね。",
example_read:"にほんへ きたら ぜひ あそびに きてくださいね",
example_vi:"Nếu bạn đến Nhật thì nhất định hãy ghé chơi nhé.",
example_en:"If you come to Japan, definitely come visit me."
},

{
level:"N5",
lesson:18,
id:28,
kanji:"故郷",
kana:"ふるさと",
hanviet:"CỐ HƯƠNG",
vi:"quê hương",
en:"hometown",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夏休<rt>なつやす</rt></ruby>みに <span class='target-word'><ruby>故郷<rt>ふるさと</rt></ruby></span>へ <ruby>帰<rt>かえ</rt></ruby>って、<ruby>家族<rt>かぞく</rt></ruby>と <ruby>楽<rt>たの</rt></ruby>しく <ruby>過<rt>す</rt></ruby>ごしました。",
example_read:"なつやすみに ふるさとへ かえって かぞくと たのしく すごしました",
example_vi:"Kỳ nghỉ hè tôi đã về quê và vui vẻ bên gia đình.",
example_en:"I went back to my hometown during summer vacation and had a wonderful time with my family."
},

{
level:"N5",
lesson:18,
id:29,
kanji:"ビートルズ",
kana:"ビートルズ",
hanviet:"",
vi:"The Beatles",
en:"The Beatles",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'>ビートルズ</span>の <ruby>音楽<rt>おんがく</rt></ruby>を よく <ruby>聞<rt>き</rt></ruby>きます。",
example_read:"ちちは ビートルズの おんがくを よく ききます",
example_vi:"Bố tôi thường nghe nhạc của Beatles.",
example_en:"My father often listens to Beatles music."
},

{
level:"N5",
lesson:18,
id:30,
kanji:"秋葉原",
kana:"あきはばら",
hanviet:"THU DIỆP NGUYÊN",
vi:"Akihabara",
en:"Akihabara (Tokyo district)",
word_type_vi:"Danh từ riêng",
word_type_en:"Place name",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>秋葉原<rt>あきはばら</rt></ruby></span>へ <ruby>行<rt>い</rt></ruby>って、<ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>を しました。",
example_read:"ともだちと あきはばらへ いって かいものを しました",
example_vi:"Tôi đã đến Akihabara cùng bạn và đi mua sắm.",
example_en:"I went to Akihabara with my friend and did some shopping."
}
];