window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[14] = [

{
level:"N5",
lesson:14,
id:1,
kanji:"付けます",
kana:"つけます",
hanviet:"PHÓ",
vi:"bật",
en:"turn on",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>部屋<rt>へや</rt></ruby>に <ruby>入<rt>はい</rt></ruby>って、エアコンを <span class='target-word'><ruby>付<rt>つ</rt></ruby>けます</span>。",
example_read:"へやに はいって エアコンを つけます",
example_vi:"Tôi vào phòng rồi bật máy điều hòa.",
example_en:"I enter the room and turn on the air conditioner."
},

{
level:"N5",
lesson:14,
id:2,
kanji:"消します",
kana:"けします",
hanviet:"TIÊU",
vi:"tắt",
en:"turn off",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>寝<rt>ね</rt></ruby>る <ruby>前<rt>まえ</rt></ruby>に <ruby>電気<rt>でんき</rt></ruby>を <span class='target-word'><ruby>消<rt>け</rt></ruby>します</span>。",
example_read:"ねる まえに でんきを けします",
example_vi:"Trước khi ngủ tôi tắt đèn.",
example_en:"I turn off the light before going to bed."
},

{
level:"N5",
lesson:14,
id:3,
kanji:"開けます",
kana:"あけます",
hanviet:"KHAI",
vi:"mở",
en:"open",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いので <ruby>窓<rt>まど</rt></ruby>を <span class='target-word'><ruby>開<rt>あ</rt></ruby>けます</span>。",
example_read:"あついので まどを あけます",
example_vi:"Vì nóng nên tôi mở cửa sổ.",
example_en:"Because it's hot, I open the window."
},

{
level:"N5",
lesson:14,
id:4,
kanji:"閉めます",
kana:"しめます",
hanviet:"BẾ",
vi:"đóng",
en:"close",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>寒<rt>さむ</rt></ruby>いので ドアを <span class='target-word'><ruby>閉<rt>し</rt></ruby>めます</span>。",
example_read:"さむいので ドアを しめます",
example_vi:"Vì lạnh nên tôi đóng cửa.",
example_en:"Because it's cold, I close the door."
},

{
level:"N5",
lesson:14,
id:5,
kanji:"急ぎます",
kana:"いそぎます",
hanviet:"CẤP",
vi:"vội",
en:"hurry",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>時間<rt>じかん</rt></ruby>が ないので <span class='target-word'><ruby>急<rt>いそ</rt></ruby>ぎます</span>。",
example_read:"じかんが ないので いそぎます",
example_vi:"Vì không có thời gian nên tôi phải vội.",
example_en:"I hurry because I don't have much time."
},

{
level:"N5",
lesson:14,
id:6,
kanji:"待ちます",
kana:"まちます",
hanviet:"ĐÃI",
vi:"đợi, chờ",
en:"wait",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>駅<rt>えき</rt></ruby>で <ruby>友達<rt>ともだち</rt></ruby>を <span class='target-word'><ruby>待<rt>ま</rt></ruby>ちます</span>。",
example_read:"えきで ともだちを まちます",
example_vi:"Tôi đợi bạn ở nhà ga.",
example_en:"I wait for my friend at the station."
},

{
level:"N5",
lesson:14,
id:7,
kanji:"持ちます",
kana:"もちます",
hanviet:"TRÌ",
vi:"mang, cầm",
en:"carry",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>学校<rt>がっこう</rt></ruby>へ かばんを <span class='target-word'><ruby>持<rt>も</rt></ruby>っていきます</span>。",
example_read:"がっこうへ かばんを もっていきます",
example_vi:"Tôi mang cặp đến trường.",
example_en:"I take my bag to school."
},

{
level:"N5",
lesson:14,
id:8,
kanji:"取ります",
kana:"とります",
hanviet:"THỦ",
vi:"lấy",
en:"take",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"すみません、<ruby>塩<rt>しお</rt></ruby>を <span class='target-word'><ruby>取<rt>と</rt></ruby>ってください</span>。",
example_read:"すみません しおを とってください",
example_vi:"Xin lỗi, làm ơn lấy giúp tôi muối.",
example_en:"Excuse me, please pass me the salt."
},

{
level:"N5",
lesson:14,
id:9,
kanji:"手伝います",
kana:"てつだいます",
hanviet:"THỦ TRUYỀN",
vi:"giúp đỡ",
en:"help",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>の <ruby>仕事<rt>しごと</rt></ruby>を <span class='target-word'><ruby>手伝<rt>てつだ</rt></ruby>います</span>。",
example_read:"ははの しごとを てつだいます",
example_vi:"Tôi giúp công việc của mẹ.",
example_en:"I help my mother with her work."
},

{
level:"N5",
lesson:14,
id:10,
kanji:"呼びます",
kana:"よびます",
hanviet:"HÔ",
vi:"gọi",
en:"call",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"タクシーを <span class='target-word'><ruby>呼<rt>よ</rt></ruby>びます</span>。",
example_read:"タクシーを よびます",
example_vi:"Tôi gọi taxi.",
example_en:"I call a taxi."
},

{
level:"N5",
lesson:14,
id:11,
kanji:"話します",
kana:"はなします",
hanviet:"THOẠI",
vi:"nói, nói chuyện",
en:"speak, talk",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>休<rt>やす</rt></ruby>み<ruby>時間<rt>じかん</rt></ruby>に <ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>話<rt>はな</rt></ruby>します</span>。",
example_read:"やすみじかんに ともだちと はなします",
example_vi:"Tôi nói chuyện với bạn bè vào giờ nghỉ.",
example_en:"I talk with my friends during break time."
},

{
level:"N5",
lesson:14,
id:12,
kanji:"使います",
kana:"つかいます",
hanviet:"SỬ",
vi:"dùng, sử dụng",
en:"use",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>する<ruby>時<rt>とき</rt></ruby>、<ruby>辞書<rt>じしょ</rt></ruby>を <span class='target-word'><ruby>使<rt>つか</rt></ruby>います</span>。",
example_read:"にほんごを べんきょうするとき じしょを つかいます",
example_vi:"Khi học tiếng Nhật, tôi sử dụng từ điển.",
example_en:"I use a dictionary when studying Japanese."
},

{
level:"N5",
lesson:14,
id:13,
kanji:"止めます",
kana:"とめます",
hanviet:"CHỈ",
vi:"dừng, đỗ",
en:"stop, park",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"ここに <ruby>車<rt>くるま</rt></ruby>を <span class='target-word'><ruby>止<rt>と</rt></ruby>めます</span>。",
example_read:"ここに くるまを とめます",
example_vi:"Tôi đỗ xe ở đây.",
example_en:"I park my car here."
},

{
level:"N5",
lesson:14,
id:14,
kanji:"見せます",
kana:"みせます",
hanviet:"KIẾN",
vi:"cho xem",
en:"show",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <ruby>写真<rt>しゃしん</rt></ruby>を <span class='target-word'><ruby>見<rt>み</rt></ruby>せます</span>。",
example_read:"ともだちに しゃしんを みせます",
example_vi:"Tôi cho bạn xem ảnh.",
example_en:"I show a photo to my friend."
},

{
level:"N5",
lesson:14,
id:15,
kanji:"教えます",
kana:"おしえます",
hanviet:"GIÁO",
vi:"cho biết, chỉ, dạy",
en:"tell, teach",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>に <ruby>住所<rt>じゅうしょ</rt></ruby>を <span class='target-word'><ruby>教<rt>おし</rt></ruby>えます</span>。",
example_read:"ともだちに じゅうしょを おしえます",
example_vi:"Tôi cho bạn biết địa chỉ.",
example_en:"I tell my friend my address."
},

{
level:"N5",
lesson:14,
id:16,
kanji:"座ります",
kana:"すわります",
hanviet:"TỌA",
vi:"ngồi",
en:"sit down",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>疲<rt>つか</rt></ruby>れていますので、<ruby>椅子<rt>いす</rt></ruby>に <span class='target-word'><ruby>座<rt>すわ</rt></ruby>ります</span>。",
example_read:"つかれていますので いすに すわります",
example_vi:"Vì đang mệt nên tôi ngồi xuống ghế.",
example_en:"I sit down on a chair because I am tired."
},

{
level:"N5",
lesson:14,
id:17,
kanji:"立ちます",
kana:"たちます",
hanviet:"LẬP",
vi:"đứng",
en:"stand up",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>名前<rt>なまえ</rt></ruby>を <ruby>呼<rt>よ</rt></ruby>ばれたので、<span class='target-word'><ruby>立<rt>た</rt></ruby>ちました</span>。",
example_read:"なまえを よばれたので たちました",
example_vi:"Vì được gọi tên nên tôi đã đứng dậy.",
example_en:"I stood up because my name was called."
},

{
level:"N5",
lesson:14,
id:18,
kanji:"入ります",
kana:"はいります",
hanviet:"NHẬP",
vi:"vào",
en:"enter",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"コーヒーを <ruby>飲<rt>の</rt></ruby>みたいので、<ruby>喫茶店<rt>きっさてん</rt></ruby>に <span class='target-word'><ruby>入<rt>はい</rt></ruby>りました</span>。",
example_read:"コーヒーを のみたいので きっさてんに はいりました",
example_vi:"Vì muốn uống cà phê nên tôi đã vào quán cà phê.",
example_en:"I entered the coffee shop because I wanted to drink coffee."
},

{
level:"N5",
lesson:14,
id:19,
kanji:"出ます",
kana:"でます",
hanviet:"XUẤT",
vi:"ra khỏi",
en:"leave, go out",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>授業<rt>じゅぎょう</rt></ruby>が <ruby>終<rt>お</rt></ruby>わったので、<ruby>教室<rt>きょうしつ</rt></ruby>を <span class='target-word'><ruby>出<rt>で</rt></ruby>ます</span>。",
example_read:"じゅぎょうが おわったので きょうしつを でます",
example_vi:"Vì giờ học kết thúc nên tôi ra khỏi lớp học.",
example_en:"I leave the classroom because the class has ended."
},

{
level:"N5",
lesson:14,
id:20,
kanji:"降ります",
kana:"ふります",
hanviet:"HÀNG/GIÁNG",
vi:"rơi (mưa)",
en:"fall",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>雨<rt>あめ</rt></ruby>が <span class='target-word'><ruby>降<rt>ふ</rt></ruby>る</span>ので、<ruby>傘<rt>かさ</rt></ruby>を <ruby>持<rt>も</rt></ruby>って <ruby>行<rt>い</rt></ruby>きます。",
example_read:"あめが ふるので かさを もって いきます",
example_vi:"Vì trời mưa nên tôi mang ô theo.",
example_en:"I take an umbrella because it will rain."
},

{
level:"N5",
lesson:14,
id:21,
kanji:"コピーします",
kana:"コピーします",
hanviet:"",
vi:"sao chép",
en:"copy",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"この <ruby>書類<rt>しょるい</rt></ruby>を <span class='target-word'>コピーします</span>。",
example_read:"この しょるいを コピーします",
example_vi:"Tôi photocopy tài liệu này.",
example_en:"I copy this document."
},

{
level:"N5",
lesson:14,
id:22,
kanji:"電気",
kana:"でんき",
hanviet:"ĐIỆN KHÍ",
vi:"điện, đèn điện",
en:"electricity, light",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>部屋<rt>へや</rt></ruby>が <ruby>暗<rt>くら</rt></ruby>いので、<span class='target-word'><ruby>電気<rt>でんき</rt></ruby></span>を <ruby>付<rt>つ</rt></ruby>けます。",
example_read:"へやが くらいので でんきを つけます",
example_vi:"Vì phòng tối nên tôi bật đèn.",
example_en:"I turn on the light because the room is dark."
},

{
level:"N5",
lesson:14,
id:23,
kanji:"エアコン",
kana:"エアコン",
hanviet:"",
vi:"máy điều hòa",
en:"air conditioner",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>暑<rt>あつ</rt></ruby>いので <span class='target-word'>エアコン</span>を <ruby>付<rt>つ</rt></ruby>けます。",
example_read:"あついので エアコンを つけます",
example_vi:"Vì trời nóng nên tôi bật điều hòa.",
example_en:"I turn on the air conditioner because it's hot."
},

{
level:"N5",
lesson:14,
id:24,
kanji:"パスポート",
kana:"パスポート",
hanviet:"",
vi:"hộ chiếu",
en:"passport",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>空港<rt>くうこう</rt></ruby>で <span class='target-word'>パスポート</span>を <ruby>見<rt>み</rt></ruby>せます。",
example_read:"くうこうで パスポートを みせます",
example_vi:"Tôi trình hộ chiếu ở sân bay.",
example_en:"I show my passport at the airport."
},

{
level:"N5",
lesson:14,
id:25,
kanji:"名前",
kana:"なまえ",
hanviet:"DANH TIỀN",
vi:"tên",
en:"name",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"ここに <span class='target-word'><ruby>名前<rt>なまえ</rt></ruby></span>を <ruby>書<rt>か</rt></ruby>いてください。",
example_read:"ここに なまえを かいてください",
example_vi:"Xin hãy viết tên của bạn vào đây.",
example_en:"Please write your name here."
},

{
level:"N5",
lesson:14,
id:26,
kanji:"住所",
kana:"じゅうしょ",
hanviet:"TRÚ SỞ",
vi:"địa chỉ",
en:"address",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>住所<rt>じゅうしょ</rt></ruby></span>を <ruby>教<rt>おし</rt></ruby>えてください。",
example_read:"じゅうしょを おしえてください",
example_vi:"Xin hãy cho tôi biết địa chỉ.",
example_en:"Please tell me your address."
},

{
level:"N5",
lesson:14,
id:27,
kanji:"地図",
kana:"ちず",
hanviet:"ĐỊA ĐỒ",
vi:"bản đồ",
en:"map",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>道<rt>みち</rt></ruby>が <ruby>分<rt>わ</rt></ruby>からないので、<span class='target-word'><ruby>地図<rt>ちず</rt></ruby></span>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"みちが わからないので ちずを みます",
example_vi:"Vì không biết đường nên tôi xem bản đồ.",
example_en:"I look at a map because I don't know the way."
},

{
level:"N5",
lesson:14,
id:28,
kanji:"塩",
kana:"しお",
hanviet:"DIÊM",
vi:"muối",
en:"salt",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>料理<rt>りょうり</rt></ruby>には <span class='target-word'><ruby>塩<rt>しお</rt></ruby></span>が <ruby>必要<rt>ひつよう</rt></ruby>です。",
example_read:"りょうりには しおが ひつようです",
example_vi:"Nấu ăn thì cần có muối.",
},

{
level:"N5",
lesson:14,
id:29,
kanji:"砂糖",
kana:"さとう",
hanviet:"SA ĐƯỜNG",
vi:"đường",
en:"sugar",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"コーヒーに <span class='target-word'><ruby>砂糖<rt>さとう</rt></ruby></span>を <ruby>入<rt>い</rt></ruby>れます。",
example_read:"コーヒーに さとうを いれます",
example_vi:"Tôi cho đường vào cà phê.",
example_en:"I add sugar to my coffee."
},

{
level:"N5",
lesson:14,
id:30,
kanji:"問題",
kana:"もんだい",
hanviet:"VẤN ĐỀ",
vi:"câu hỏi, vấn đề",
en:"question, problem",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>問題<rt>もんだい</rt></ruby></span>は <ruby>難<rt>むずか</rt></ruby>しいです。",
example_read:"この もんだいは むずかしいです",
example_vi:"Vấn đề này khó.",
example_en:"This problem is difficult."
},

{
level:"N5",
lesson:14,
id:31,
kanji:"答え",
kana:"こたえ",
hanviet:"ĐÁP",
vi:"câu trả lời",
en:"answer",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>問題<rt>もんだい</rt></ruby>を <ruby>読<rt>よ</rt></ruby>んでから、<span class='target-word'><ruby>答<rt>こた</rt></ruby>え</span>を <ruby>書<rt>か</rt></ruby>きます。",
example_read:"もんだいを よんでから こたえを かきます",
example_vi:"Sau khi đọc đề bài, tôi viết đáp án.",
example_en:"After reading the question, I write the answer."
},

{
level:"N5",
lesson:14,
id:32,
kanji:"読み方",
kana:"よみかた",
hanviet:"ĐỘC PHƯƠNG",
vi:"cách đọc",
en:"reading, pronunciation",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>漢字<rt>かんじ</rt></ruby>の <ruby>読<rt>よ</rt></ruby>み<ruby>方<rt>かた</rt></ruby></span>が わかりません。",
example:"この <ruby>漢字<rt>かんじ</rt></ruby>の <span class='target-word'><ruby>読<rt>よ</rt></ruby>み<ruby>方<rt>かた</rt></ruby></span>が <ruby>分<rt>わ</rt></ruby>かりません。",
example_read:"この かんじの よみかたが わかりません",
example_vi:"Tôi không biết cách đọc chữ Kanji này.",
example_en:"I don't know how to read this kanji."
},

{
level:"N5",
lesson:14,
id:33,
kanji:"～方",
kana:"～かた",
hanviet:"PHƯƠNG",
vi:"cách ~",
en:"way of ~",
word_type_vi:"Hậu tố",
word_type_en:"Suffix",
category:"Minna 1",
example:"<span class='target-word'><ruby>使<rt>つか</rt></ruby>い<ruby>方<rt>かた</rt></ruby></span>を おしえてください。",
example:"<span class='target-word'><ruby>使<rt>つか</rt></ruby>い<ruby>方<rt>かた</rt></ruby></span>を <ruby>教<rt>おし</rt></ruby>えてください。",
example_read:"つかいかたを おしえてください",
example_vi:"Xin hãy chỉ cho tôi cách sử dụng.",
example_en:"Please show me how to use it."
},

{
level:"N5",
lesson:14,
id:34,
kanji:"まっすぐ",
kana:"まっすぐ",
hanviet:"",
vi:"thẳng",
en:"straight",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この <ruby>道<rt>みち</rt></ruby>を <span class='target-word'>まっすぐ</span> <ruby>行<rt>い</rt></ruby>ってください。",
example_read:"この みちを まっすぐ いってください",
example_vi:"Xin hãy đi thẳng theo con đường này.",
example_en:"Please go straight along this road."
},

{
level:"N5",
lesson:14,
id:35,
kanji:"ゆっくり",
kana:"ゆっくり",
hanviet:"",
vi:"chậm, thong thả",
en:"slowly",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"すみません、もう <ruby>一度<rt>いちど</rt></ruby> <span class='target-word'>ゆっくり</span> <ruby>話<rt>はな</rt></ruby>してください。",
example_read:"すみません もう いちど ゆっくり はなしてください",
example_vi:"Xin lỗi, xin hãy nói chậm lại một lần nữa.",
example_en:"Excuse me, could you speak more slowly one more time, please?"
},

{
level:"N5",
lesson:14,
id:36,
kanji:"すぐ",
kana:"すぐ",
hanviet:"",
vi:"ngay lập tức",
en:"immediately",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>今<rt>いま</rt></ruby> <span class='target-word'>すぐ</span> <ruby>行<rt>い</rt></ruby>きます。",
example_read:"いま すぐ いきます",
example_vi:"Tôi sẽ đi ngay bây giờ.",
example_en:"I'll go right away."
},

{
level:"N5",
lesson:14,
id:37,
kanji:"また",
kana:"また",
hanviet:"",
vi:"lại, lần nữa",
en:"again",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>また</span> <ruby>明日<rt>あした</rt></ruby> <ruby>会<rt>あ</rt></ruby>いましょう。",
example_read:"また あした あいましょう",
example_vi:"Hẹn gặp lại vào ngày mai nhé.",
example_en:"See you tomorrow."
},

{
level:"N5",
lesson:14,
id:38,
kanji:"後で",
kana:"あとで",
hanviet:"HẬU",
vi:"sau đó",
en:"later",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"また <span class='target-word'><ruby>後<rt>あと</rt></ruby>で</span> <ruby>電話<rt>でんわ</rt></ruby>しますね。",
example_read:"また あとで でんわしますね",
example_vi:"Tôi sẽ gọi lại cho bạn sau nhé.",
example_en:"I'll call you back later."
},

{
level:"N5",
lesson:14,
id:39,
kanji:"もう少し",
kana:"もうすこし",
hanviet:"THIỂU",
vi:"thêm một chút nữa",
en:"a little more",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<span class='target-word'>もう <ruby>少<rt>すこ</rt></ruby>し</span> <ruby>待<rt>ま</rt></ruby>ってください。",
example_read:"もう すこし まってください",
example_vi:"Xin hãy đợi thêm một chút.",
example_en:"Please wait a little longer."
},

{
level:"N5",
lesson:14,
id:40,
kanji:"もう～",
kana:"もう～",
hanviet:"",
vi:"thêm ~",
en:"another ~, one more ~",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"ビールを <span class='target-word'>もう</span> <ruby>一杯<rt>いっぱい</rt></ruby> お<ruby>願<rt>ねが</rt></ruby>いします。",
example_read:"ビールを もう いっぱい おねがいします",
example_vi:"Cho tôi thêm một ly bia nữa.",
example_en:"One more beer, please."
},

{
level:"N5",
lesson:14,
id:41,
kanji:"さあ",
kana:"さあ",
hanviet:"",
vi:"thôi nào, nào",
en:"come on",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>さあ</span>、<ruby>行<rt>い</rt></ruby>きましょう。",
example_read:"さあ いきましょう",
example_vi:"Nào, chúng ta đi thôi!",
example_en:"Come on, let's go!"
},

{
level:"N5",
lesson:14,
id:42,
kanji:"あれ？",
kana:"あれ？",
hanviet:"",
vi:"Ơ?, Ủa?",
en:"Huh?",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>あれ？</span> お<ruby>母<rt>かあ</rt></ruby>さん、<ruby>鍵<rt>かぎ</rt></ruby>は どこに <ruby>置<rt>お</rt></ruby>いていますか。",
example_read:"あれ おかあさん かぎは どこに おいていますか",
example_vi:"Ủa? Mẹ ơi, mẹ để chìa khóa ở đâu vậy?",
example_en:"Huh? Mom, where did you put the key?"
},

{
level:"N5",
lesson:14,
id:43,
kanji:"信号を右へ曲がってください",
kana:"しんごうを みぎへ まがってください",
hanviet:"TÍN HIỆU HỮU KHÚC",
vi:"Hãy rẽ phải ở đèn tín hiệu",
en:"Turn right at the traffic light",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"<span class='target-word'><ruby>信号<rt>しんごう</rt></ruby>を <ruby>右<rt>みぎ</rt></ruby>へ <ruby>曲<rt>ま</rt></ruby>がってください</span>。",
example_read:"しんごうを みぎへ まがってください",
example_vi:"Xin hãy rẽ phải ở đèn tín hiệu.",
example_en:"Turn right at the traffic light."
},

{
level:"N5",
lesson:14,
id:44,
kanji:"これでお願いします",
kana:"これでおねがいします",
hanviet:"NGUYỆN",
vi:"Gửi anh/chị tiền này",
en:"Here you are",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>千円<rt>せんえん</rt></ruby>です。<span class='target-word'>これで お<ruby>願<rt>ねが</rt></ruby>いします</span>。",
example_read:"せんえんです これで おねがいします",
example_vi:"Đây ạ, tôi gửi 1.000 yên.",
example_en:"Here's 1,000 yen."
},

{
level:"N5",
lesson:14,
id:45,
kanji:"お釣り",
kana:"おつり",
hanviet:"ĐIẾU",
vi:"tiền thừa, tiền lẻ",
en:"change",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>お<ruby>釣<rt>つ</rt></ruby>り</span>を <ruby>受<rt>う</rt></ruby>け<ruby>取<rt>と</rt></ruby>ってください。",
example_read:"おつりを うけとってください",
example_vi:"Xin vui lòng nhận lại tiền thừa.",
example_en:"Please take your change."
},

{
level:"N5",
lesson:14,
id:46,
kanji:"みどり町",
kana:"みどりちょう",
hanviet:"ĐINH",
vi:"Thị trấn Midori",
en:"Midori Town",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>みどり<ruby>町<rt>ちょう</rt></ruby></span>に <ruby>住<rt>す</rt></ruby>んでいます。",
example_read:"わたしは みどりちょうに すんでいます",
example_vi:"Tôi sống ở thị trấn Midori.",
example_en:"I live in Midori Town."
}
];