window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[5] = [

{
level:"N5",
lesson:5,
id:1,
kanji:"行きます",
kana:"いきます",
hanviet:"HÀNH",
vi:"Đi",
en:"Go",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>学校<rt>がっこう</rt></ruby>へ <span class='target-word'><ruby>行<rt>い</rt></ruby>きます</span>。",
example_read:"わたしは まいにち がっこうへ いきます。",
example_vi:"Tôi đi đến trường mỗi ngày.",
example_en:"I go to school every day."
},

{
level:"N5",
lesson:5,
id:2,
kanji:"来ます",
kana:"きます",
hanviet:"LAI",
vi:"Đến",
en:"Come",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 Verb",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>が <ruby>家<rt>いえ</rt></ruby>へ <span class='target-word'><ruby>来<rt>き</rt></ruby>ます</span>。",
example_read:"ともだちが いえへ きます。",
example_vi:"Bạn tôi đến nhà.",
example_en:"My friend comes to my house."
},

{
level:"N5",
lesson:5,
id:3,
kanji:"帰ります",
kana:"かえります",
hanviet:"QUY",
vi:"Về",
en:"Return, go home",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は ６<ruby>時<rt>じ</rt></ruby>に <span class='target-word'><ruby>帰<rt>かえ</rt></ruby>ります</span>。",
example_read:"わたしは ろくじに かえります。",
example_vi:"Tôi về lúc 6 giờ.",
example_en:"I go home at 6 o'clock."
},

{
level:"N5",
lesson:5,
id:4,
kanji:"学校",
kana:"がっこう",
hanviet:"HỌC HIỆU",
vi:"Trường học",
en:"School",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>妹<rt>いもうと</rt></ruby>は <span class='target-word'><ruby>学校<rt>がっこう</rt></ruby></span>で <ruby>勉強<rt>べんきょう</rt></ruby>します。",
example_read:"いもうとは がっこうで べんきょうします。",
example_vi:"Em gái tôi học ở trường.",
example_en:"My younger sister studies at school."
},

{
level:"N5",
lesson:5,
id:5,
kanji:"",
kana:"スーパー",
hanviet:"",
vi:"Siêu thị",
en:"Supermarket",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>は <span class='target-word'>スーパー</span>で <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>をします。",
example_read:"ははは すーぱーで かいものをします。",
example_vi:"Mẹ tôi mua sắm ở siêu thị.",
example_en:"My mother shops at a supermarket."
},

{
level:"N5",
lesson:5,
id:6,
kanji:"駅",
kana:"えき",
hanviet:"DỊCH",
vi:"Ga, nhà ga",
en:"Station",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>駅<rt>えき</rt></ruby></span>で <ruby>友達<rt>ともだち</rt></ruby>に <ruby>会<rt>あ</rt></ruby>います。",
example_read:"えきで ともだちに あいます。",
example_vi:"Tôi gặp bạn ở nhà ga.",
example_en:"I meet my friend at the station."
},

{
level:"N5",
lesson:5,
id:7,
kanji:"飛行機",
kana:"ひこうき",
hanviet:"PHI HÀNH CƠ",
vi:"Máy bay",
en:"Airplane",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>飛行機<rt>ひこうき</rt></ruby></span>で <ruby>東京<rt>とうきょう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ひこうきで とうきょうへ いきます。",
example_vi:"Tôi đi Tokyo bằng máy bay.",
example_en:"I go to Tokyo by airplane."
},

{
level:"N5",
lesson:5,
id:8,
kanji:"船",
kana:"ふね",
hanviet:"THUYỀN",
vi:"Thuyền, tàu thủy",
en:"Ship, boat",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>島<rt>しま</rt></ruby>へ <span class='target-word'><ruby>船<rt>ふね</rt></ruby></span>で <ruby>行<rt>い</rt></ruby>きます。",
example_read:"しまへ ふねで いきます。",
example_vi:"Tôi đi đến đảo bằng tàu thủy.",
example_en:"I go to the island by ship."
},

{
level:"N5",
lesson:5,
id:9,
kanji:"電車",
kana:"でんしゃ",
hanviet:"ĐIỆN XA",
vi:"Tàu điện",
en:"Train",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <span class='target-word'><ruby>電車<rt>でんしゃ</rt></ruby></span>で <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいあさ でんしゃで かいしゃへ いきます。",
example_vi:"Mỗi sáng tôi đi đến công ty bằng tàu điện.",
example_en:"I go to work by train every morning."
},

{
level:"N5",
lesson:5,
id:10,
kanji:"地下鉄",
kana:"ちかてつ",
hanviet:"ĐỊA HẠ THIẾT",
vi:"Tàu điện ngầm",
en:"Subway",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>地下鉄<rt>ちかてつ</rt></ruby></span>で <ruby>新宿<rt>しんじゅく</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ちかてつで しんじゅくへ いきます。",
example_vi:"Tôi đi Shinjuku bằng tàu điện ngầm.",
example_en:"I go to Shinjuku by subway."
},

{
level:"N5",
lesson:5,
id:11,
kanji:"新幹線",
kana:"しんかんせん",
hanviet:"TÂN CÁN TUYẾN",
vi:"Tàu Shinkansen (tàu cao tốc)",
en:"Shinkansen (bullet train)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>新幹線<rt>しんかんせん</rt></ruby></span>で <ruby>大阪<rt>おおさか</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"しんかんせんで おおさかへ いきます。",
example_vi:"Tôi đi Osaka bằng tàu Shinkansen.",
example_en:"I go to Osaka by Shinkansen."
},

{
level:"N5",
lesson:5,
id:12,
kanji:"",
kana:"バス",
hanviet:"",
vi:"Xe buýt",
en:"Bus",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>バス</span>で <ruby>学校<rt>がっこう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ばすで がっこうへ いきます。",
example_vi:"Tôi đi học bằng xe buýt.",
example_en:"I go to school by bus."
},

{
level:"N5",
lesson:5,
id:13,
kanji:"",
kana:"タクシー",
hanviet:"",
vi:"Taxi",
en:"Taxi",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>タクシー</span>で <ruby>駅<rt>えき</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"たくしーで えきへ いきます。",
example_vi:"Tôi đi đến nhà ga bằng taxi.",
example_en:"I go to the station by taxi."
},

{
level:"N5",
lesson:5,
id:14,
kanji:"自転車",
kana:"じてんしゃ",
hanviet:"TỰ CHUYỂN XA",
vi:"Xe đạp",
en:"Bicycle",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>自転車<rt>じてんしゃ</rt></ruby></span>で <ruby>公園<rt>こうえん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"じてんしゃで こうえんへ いきます。",
example_vi:"Tôi đi công viên bằng xe đạp.",
example_en:"I go to the park by bicycle."
},

{
level:"N5",
lesson:5,
id:15,
kanji:"歩いて",
kana:"あるいて",
hanviet:"BỘ",
vi:"Đi bộ",
en:"On foot, walk",
word_type_vi:"Động từ thể て",
word_type_en:"Te-form Verb",
category:"Minna 1",
example:"<ruby>学校<rt>がっこう</rt></ruby>まで <span class='target-word'><ruby>歩<rt>ある</rt></ruby>いて</span> <ruby>行<rt>い</rt></ruby>きます。",
example_read:"がっこうまで あるいて いきます。",
example_vi:"Tôi đi bộ đến trường.",
example_en:"I walk to school."
},

{
level:"N5",
lesson:5,
id:16,
kanji:"人",
kana:"ひと",
hanviet:"NHÂN",
vi:"Người",
en:"Person",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>人<rt>ひと</rt></ruby></span>が たくさん います。",
example_read:"ひとが たくさん います。",
example_vi:"Có rất nhiều người.",
example_en:"There are many people."
},

{
level:"N5",
lesson:5,
id:17,
kanji:"友達",
kana:"ともだち",
hanviet:"HỮU ĐẠT",
vi:"Bạn, bạn bè",
en:"Friend",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 2",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>友達<rt>ともだち</rt></ruby></span>と デパートへ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは ともだちと でぱーとへ いきます。",
example_vi:"Tôi đi trung tâm thương mại cùng bạn.",
example_en:"I go to the department store with my friend."
},

{
level:"N5",
lesson:5,
id:18,
kanji:"彼",
kana:"かれ",
hanviet:"BỈ",
vi:"Anh ấy, bạn trai",
en:"He, boyfriend",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 2",
example:"<span class='target-word'><ruby>彼<rt>かれ</rt></ruby></span>は <ruby>会社員<rt>かいしゃいん</rt></ruby>です。",
example_read:"かれは かいしゃいんです。",
example_vi:"Anh ấy là nhân viên công ty.",
example_en:"He is an office worker."
},

{
level:"N5",
lesson:5,
id:19,
kanji:"彼女",
kana:"かのじょ",
hanviet:"BỈ NỮ",
vi:"Chị ấy, bạn gái",
en:"She, girlfriend",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 2",
example:"<span class='target-word'><ruby>彼女<rt>かのじょ</rt></ruby></span>は <ruby>学生<rt>がくせい</rt></ruby>です。",
example_read:"かのじょは がくせいです。",
example_vi:"Cô ấy là học sinh.",
example_en:"She is a student."
},

{
level:"N5",
lesson:5,
id:20,
kanji:"家族",
kana:"かぞく",
hanviet:"GIA TỘC",
vi:"Gia đình",
en:"Family",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 2",
example:"<ruby>私<rt>わたし</rt></ruby>の <span class='target-word'><ruby>家族<rt>かぞく</rt></ruby></span>は ４<ruby>人<rt>にん</rt></ruby>です。",
example_read:"わたしの かぞくは よにんです。",
example_vi:"Gia đình tôi có 4 người.",
example_en:"There are four people in my family."
},

{
level:"N5",
lesson:5,
id:21,
kanji:"一人で",
kana:"ひとりで",
hanviet:"NHẤT NHÂN",
vi:"Một mình",
en:"Alone, by oneself",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 2",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>一人<rt>ひとり</rt></ruby>で</span> <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは ひとりで いきます。",
example_vi:"Tôi đi một mình.",
example_en:"I go alone."
},

{
level:"N5",
lesson:5,
id:22,
kanji:"先週",
kana:"せんしゅう",
hanviet:"TIÊN CHU",
vi:"Tuần trước",
en:"Last week",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>先週<rt>せんしゅう</rt></ruby></span> <ruby>京都<rt>きょうと</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きました。",
example_read:"せんしゅう きょうとへ いきました。",
example_vi:"Tuần trước tôi đã đi Kyoto.",
example_en:"I went to Kyoto last week."
},

{
level:"N5",
lesson:5,
id:23,
kanji:"今週",
kana:"こんしゅう",
hanviet:"KIM CHU",
vi:"Tuần này",
en:"This week",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>今週<rt>こんしゅう</rt></ruby></span>は <ruby>忙<rt>いそが</rt></ruby>しいです。",
example_read:"こんしゅうは いそがしいです。",
example_vi:"Tuần này tôi bận.",
example_en:"I am busy this week."
},

{
level:"N5",
lesson:5,
id:24,
kanji:"来週",
kana:"らいしゅう",
hanviet:"LAI CHU",
vi:"Tuần sau",
en:"Next week",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>来週<rt>らいしゅう</rt></ruby></span> <ruby>京都<rt>きょうと</rt></ruby>へ <ruby>旅行<rt>りょこう</rt></ruby>します。",
example_read:"らいしゅう きょうとへ りょこうします。",
example_vi:"Tuần sau tôi sẽ đi du lịch Kyoto.",
example_en:"I will travel to Kyoto next week."
},

{
level:"N5",
lesson:5,
id:25,
kanji:"先月",
kana:"せんげつ",
hanviet:"TIÊN NGUYỆT",
vi:"Tháng trước",
en:"Last month",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>先月<rt>せんげつ</rt></ruby></span> <ruby>日本<rt>にほん</rt></ruby>へ <ruby>来<rt>き</rt></ruby>ました。",
example_read:"せんげつ にほんへ きました。",
example_vi:"Tháng trước tôi đã đến Nhật Bản.",
example_en:"I came to Japan last month."
},

{
level:"N5",
lesson:5,
id:26,
kanji:"今月",
kana:"こんげつ",
hanviet:"KIM NGUYỆT",
vi:"Tháng này",
en:"This month",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>今月<rt>こんげつ</rt></ruby></span>は <ruby>仕事<rt>しごと</rt></ruby>が <ruby>忙<rt>いそが</rt></ruby>しいです。",
example_read:"こんげつは しごとが いそがしいです。",
example_vi:"Tháng này công việc bận rộn.",
example_en:"Work is busy this month."
},

{
level:"N5",
lesson:5,
id:27,
kanji:"来月",
kana:"らいげつ",
hanviet:"LAI NGUYỆT",
vi:"Tháng sau",
en:"Next month",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>来月<rt>らいげつ</rt></ruby></span> ベトナムへ <ruby>帰<rt>かえ</rt></ruby>ります。",
example_read:"らいげつ べとなむへ かえります。",
example_vi:"Tháng sau tôi sẽ về Việt Nam.",
example_en:"I will return to Vietnam next month."
},

{
level:"N5",
lesson:5,
id:28,
kanji:"去年",
kana:"きょねん",
hanviet:"KHỨ NIÊN",
vi:"Năm ngoái",
en:"Last year",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>去年<rt>きょねん</rt></ruby></span> <ruby>日本<rt>にほん</rt></ruby>へ <ruby>来<rt>き</rt></ruby>ました。",
example_read:"きょねん にほんへ きました。",
example_vi:"Năm ngoái tôi đã đến Nhật Bản.",
example_en:"I came to Japan last year."
},

{
level:"N5",
lesson:5,
id:29,
kanji:"今年",
kana:"ことし",
hanviet:"KIM NIÊN",
vi:"Năm nay",
en:"This year",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>今年<rt>ことし</rt></ruby></span> JLPTを <ruby>受<rt>う</rt></ruby>けます。",
example_read:"ことし じぇいえるぴーてぃーを うけます。",
example_vi:"Năm nay tôi sẽ thi JLPT.",
example_en:"I will take the JLPT this year."
},

{
level:"N5",
lesson:5,
id:30,
kanji:"来年",
kana:"らいねん",
hanviet:"LAI NIÊN",
vi:"Năm sau",
en:"Next year",
word_type_vi:"Danh từ chỉ thời gian",
word_type_en:"Time noun",
category:"Minna 2",
example:"<span class='target-word'><ruby>来年<rt>らいねん</rt></ruby></span> <ruby>大学<rt>だいがく</rt></ruby>に <ruby>入<rt>はい</rt></ruby>ります。",
example_read:"らいねん だいがくに はいります。",
example_vi:"Năm sau tôi sẽ vào đại học.",
example_en:"I will enter university next year."
},

{
level:"N5",
lesson:5,
id:31,
kanji:"～年",
kana:"～ねん",
hanviet:"NIÊN",
vi:"Năm ~",
en:"~ year",
word_type_vi:"Hậu tố đếm năm",
word_type_en:"Counter suffix",
category:"Minna 2",
example:"<ruby>今年<rt>ことし</rt></ruby></span>は2026<span class='target-word'><ruby>年<rt>ねん</rt></ruby></span>です。",
example_read:"ことしは にせんにじゅうごねんです。",
example_vi:"Năm nay là năm 2026.",
example_en:"This year is 2026."
},

{
level:"N5",
lesson:5,
id:32,
kanji:"何年",
kana:"なんねん",
hanviet:"HÀ NIÊN",
vi:"Năm nào, mấy năm",
en:"What year, how many years",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 2",
example:"<span class='target-word'>今<rt>いま</rt></ruby></span>は <span class='target-word'><ruby>何年<rt>なんねん</rt></ruby></span>ですか。",
example_read:"いまは なんねんですか。",
example_vi:"Bây giờ là năm nào?",
example_en:"What year is it now?"
},

{
level:"N5",
lesson:5,
id:33,
kanji:"～月",
kana:"～がつ",
hanviet:"NGUYỆT",
vi:"Tháng ~",
en:"~ month",
word_type_vi:"Hậu tố đếm tháng",
word_type_en:"Counter suffix",
category:"Minna 2",
example:"<span class='target-word'>今月<rt>こんげつ</rt></ruby></span>は ７<span class='target-word'><ruby>月<rt>がつ</rt></ruby></span>です。",
example_read:"こんげつは しちがつです。",
example_vi:"Tháng này là tháng 7.",
example_en:"This month is July."
},

{
level:"N5",
lesson:5,
id:34,
kanji:"何月",
kana:"なんがつ",
hanviet:"HÀ NGUYỆT",
vi:"Tháng mấy",
en:"What month",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 2",
example:"あなたの <ruby>誕生日<rt>たんじょうび</rt></ruby>は <span class='target-word'><ruby>何月<rt>なんがつ</rt></ruby></span>ですか。",
example_read:"あなたの たんじょうびは なんがつですか。",
example_vi:"Sinh nhật của bạn vào tháng mấy?",
example_en:"What month is your birthday?"
},

{
level:"N5",
lesson:5,
id:35,
kanji:"１日",
kana:"ついたち",
hanviet:"NHẤT NHẬT",
vi:"Ngày mồng 1",
en:"First day of the month",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>１<ruby>日<rt>ついたち</rt></ruby></span>に <ruby>東京<rt>とうきょう</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"ついたちに とうきょうへ いきます。",
example_vi:"Tôi sẽ đi Tokyo vào ngày mồng 1.",
example_en:"I will go to Tokyo on the first day of the month."
},

{
level:"N5",
lesson:5,
id:36,
kanji:"２日",
kana:"ふつか",
hanviet:"NHỊ NHẬT",
vi:"Ngày mồng 2, 2 ngày",
en:"Second day of the month, two days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'>２<ruby>日<rt>ふつか</rt></ruby></span>に <ruby>友達<rt>ともだち</rt></ruby>と <ruby>会<rt>あ</rt></ruby>います。",
example_read:"しちがつの ふつかに ともだちと あいます。",
example_vi:"Tôi sẽ gặp bạn vào ngày 2 tháng 7.",
example_en:"I will meet my friend on July 2nd."
},

{
level:"N5",
lesson:5,
id:37,
kanji:"３日",
kana:"みっか",
hanviet:"TAM NHẬT",
vi:"Ngày mồng 3, 3 ngày",
en:"Third day of the month, three days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>３<ruby>日<rt>みっか</rt></ruby></span>に <ruby>大阪<rt>おおさか</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"みっかに おおさかへ いきます。",
example_vi:"Tôi sẽ đi Osaka vào ngày mồng 3.",
example_en:"I will go to Osaka on the third day of the month."
},

{
level:"N5",
lesson:5,
id:38,
kanji:"４日",
kana:"よっか",
hanviet:"TỨ NHẬT",
vi:"Ngày mồng 4, 4 ngày",
en:"Fourth day of the month, four days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>４<ruby>日<rt>よっか</rt></ruby></span>に <ruby>授業<rt>じゅぎょう</rt></ruby>が あります。",
example_read:"よっかに じゅぎょうが あります。",
example_vi:"Có tiết học vào ngày mồng 4.",
example_en:"There is a class on the fourth day of the month."
},

{
level:"N5",
lesson:5,
id:39,
kanji:"５日",
kana:"いつか",
hanviet:"NGŨ NHẬT",
vi:"Ngày mồng 5, 5 ngày",
en:"Fifth day of the month, five days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'>５<ruby>日<rt>いつか</rt></ruby></span>に <ruby>友達<rt>ともだち</rt></ruby>と <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>ます。",
example_read:"しちがつの いつかに ともだちと えいがを みます。",
example_vi:"Tôi sẽ xem phim với bạn vào ngày 5 tháng 7.",
example_en:"I will watch a movie with my friend on July 5th."
},

{
level:"N5",
lesson:5,
id:40,
kanji:"６日",
kana:"むいか",
hanviet:"LỤC NHẬT",
vi:"Ngày mồng 6, 6 ngày",
en:"Sixth day of the month, six days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'>６<ruby>日<rt>むいか</rt></ruby></span>に <ruby>日本語<rt>にほんご</rt></ruby>の <ruby>試験<rt>しけん</rt></ruby>があります。",
example_read:"しちがつの むいかに にほんごの しけんが あります。",
example_vi:"Có kỳ thi tiếng Nhật vào ngày 6 tháng 7.",
example_en:"There is a Japanese exam on July 6th."
},

{
level:"N5",
lesson:5,
id:41,
kanji:"７日",
kana:"なのか",
hanviet:"THẤT NHẬT",
vi:"Ngày mồng 7, 7 ngày",
en:"Seventh day of the month, seven days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'>７<ruby>日<rt>なのか</rt></ruby></span>に デパートで <ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>をします。",
example_read:"しちがつの なのかに でぱーとで かいものをします。",
example_vi:"Tôi sẽ đi mua sắm ở trung tâm thương mại vào ngày 7 tháng 7.",
example_en:"I will go shopping at a department store on July 7th."
},

{
level:"N5",
lesson:5,
id:42,
kanji:"８日",
kana:"ようか",
hanviet:"BÁT NHẬT",
vi:"Ngày mồng 8, 8 ngày",
en:"Eighth day of the month, eight days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'>８<ruby>日<rt>ようか</rt></ruby></span>に <ruby>先生<rt>せんせい</rt></ruby>と <ruby>話<rt>はな</rt></ruby>します。",
example_read:"しちがつの ようかに せんせいと はなします。",
example_vi:"Tôi sẽ nói chuyện với giáo viên vào ngày 8 tháng 7.",
example_en:"I will talk with my teacher on July 8th."
},

{
level:"N5",
lesson:5,
id:43,
kanji:"９日",
kana:"ここのか",
hanviet:"CỬU NHẬT",
vi:"Ngày mồng 9, 9 ngày",
en:"Ninth day of the month, nine days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>９<ruby>日<rt>ここのか</rt></ruby></span>に <ruby>国<rt>くに</rt></ruby>へ <ruby>帰<rt>かえ</rt></ruby>ります。",
example_read:"ここのかに くにへ かえります。",
example_vi:"Tôi sẽ về nước vào ngày mồng 9.",
example_en:"I will return to my country on the ninth day of the month."
},

{
level:"N5",
lesson:5,
id:44,
kanji:"１０日",
kana:"とおか",
hanviet:"THẬP NHẬT",
vi:"Ngày mồng 10, 10 ngày",
en:"Tenth day of the month, ten days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>１０<ruby>日<rt>とおか</rt></ruby></span>に パーティーが あります。",
example_read:"とおかに ぱーてぃーが あります。",
example_vi:"Có bữa tiệc vào ngày mồng 10.",
example_en:"There is a party on the tenth day of the month."
},

{
level:"N5",
lesson:5,
id:45,
kanji:"１４日",
kana:"じゅうよっか",
hanviet:"THẬP TỨ NHẬT",
vi:"Ngày 14, 14 ngày",
en:"Fourteenth day of the month, fourteen days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date expression",
category:"Minna 2",
example:"<span class='target-word'>１４<ruby>日<rt>じゅうよっか</rt></ruby></span>は <ruby>父<rt>ちち</rt></ruby>の <ruby>誕生日<rt>たんじょうび</rt></ruby>です。",
example_read:"じゅうよっかは ちちの たんじょうびです。",
example_vi:"Ngày 14 là sinh nhật của bố tôi.",
example_en:"The fourteenth is my father's birthday."
},

{
level:"N5",
lesson:5,
id:46,
kanji:"２０日",
kana:"はつか",
hanviet:"NHỊ THẬP NHẬT",
vi:"Ngày 20, 20 ngày",
en:"Twentieth day of the month, twenty days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date noun",
category:"Minna 1",
example:"７<ruby>月<rt>がつ</rt></ruby>の <span class='target-word'><ruby>２０日<rt>はつか</rt></ruby></span>に <ruby>日本語<rt>にほんご</rt></ruby>の <ruby>試験<rt>しけん</rt></ruby>があります。",
example_read:"しちがつの はつかに にほんごの しけんが あります。",
example_vi:"Có kỳ thi tiếng Nhật vào ngày 20 tháng 7.",
example_en:"There is a Japanese exam on July 20th."
},

{
level:"N5",
lesson:5,
id:47,
kanji:"２４日",
kana:"にじゅうよっか",
hanviet:"NHỊ THẬP TỨ NHẬT",
vi:"Ngày 24, 24 ngày",
en:"Twenty-fourth day of the month, twenty-four days",
word_type_vi:"Danh từ chỉ ngày tháng",
word_type_en:"Date noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>２４日<rt>にじゅうよっか</rt></ruby></span>に プレゼントを <ruby>買<rt>か</rt></ruby>います。",
example_read:"にじゅうよっかに ぷれぜんとを かいます。",
example_vi:"Tôi sẽ mua quà vào ngày 24.",
example_en:"I buy a present on the twenty-fourth day."
},

{
level:"N5",
lesson:5,
id:48,
kanji:"何日",
kana:"なんにち",
hanviet:"HÀ NHẬT",
vi:"Ngày mấy, ngày bao nhiêu, mấy ngày",
en:"What date, how many days",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 1",
example:"<span class='target-word'><ruby>何日<rt>なんにち</rt></ruby></span>に <ruby>日本<rt>にほん</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きますか。",
example_read:"なんにちに にほんへ いきますか。",
example_vi:"Bạn sẽ đi Nhật vào ngày nào?",
example_en:"What date will you go to Japan?"
},

{
level:"N5",
lesson:5,
id:49,
kanji:"",
kana:"いつ",
hanviet:"",
vi:"Bao giờ, khi nào",
en:"When",
word_type_vi:"Từ nghi vấn",
word_type_en:"Question word",
category:"Minna 1",
example:"<span class='target-word'>いつ</span> <ruby>帰<rt>かえ</rt></ruby>りますか。",
example_read:"いつ かえりますか。",
example_vi:"Khi nào bạn sẽ về?",
example_en:"When will you go home?"
},

{
level:"N5",
lesson:5,
id:50,
kanji:"誕生日",
kana:"たんじょうび",
hanviet:"ĐẢN SINH NHẬT",
vi:"Sinh nhật",
en:"Birthday",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <ruby>私<rt>わたし</rt></ruby>の <span class='target-word'><ruby>誕生日<rt>たんじょうび</rt></ruby></span>です。",
example_read:"きょうは わたしの たんじょうびです。",
example_vi:"Hôm nay là sinh nhật của tôi.",
example_en:"Today is my birthday."
},

{
level:"N5",
lesson:5,
id:51,
kanji:"",
kana:"そうですね",
hanviet:"",
vi:"Ừ nhỉ, đúng nhỉ",
en:"That's right, let me see",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: <ruby>明日<rt>あした</rt></ruby>は <ruby>休<rt>やす</rt></ruby>みですね。<br>B: <span class='target-word'>そうですね</span>。どこかへ <ruby>行<rt>い</rt></ruby>きましょう。",
example_read:"あしたは やすみですね。そうですね。どこかへ いきましょう。",
example_vi:"A: Ngày mai nghỉ nhỉ. B: Đúng nhỉ. Chúng ta đi đâu đó nhé.",
example_en:"A: Tomorrow is a holiday, right? B: That's right. Let's go somewhere."
},

{
level:"N5",
lesson:5,
id:52,
kanji:"",
kana:"どうもありがとうございました",
hanviet:"",
vi:"Xin cảm ơn rất nhiều",
en:"Thank you very much",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: どうぞ、プレゼントです。<br>B: <span class='target-word'>どうもありがとうございました</span>。",
example_read:"どうぞ、ぷれぜんとです。どうもありがとうございました。",
example_vi:"A: Đây, quà tặng cho bạn. B: Xin cảm ơn rất nhiều.",
example_en:"A: Here is a present for you. B: Thank you very much."
},

{
level:"N5",
lesson:5,
id:53,
kanji:"",
kana:"どういたしまして",
hanviet:"",
vi:"Không có gì",
en:"You're welcome",
word_type_vi:"Cụm hội thoại",
word_type_en:"Conversation phrase",
category:"Minna 1",
example:"A: ありがとうございました。<br>B: <span class='target-word'>どういたしまして</span>。",
example_read:"どういたしまして。",
example_vi:"A: Cảm ơn bạn. B: Không có gì.",
example_en:"A: Thank you. B: You're welcome."
},

{
level:"N5",
lesson:5,
id:54,
kanji:"番線",
kana:"ばんせん",
hanviet:"PHIÊN TUYẾN",
vi:"Sân ga số ~",
en:"Platform number ~",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"３<span class='target-word'><ruby>番線<rt>ばんせん</rt></ruby></span>から <ruby>電車<rt>でんしゃ</rt></ruby>が <ruby>出<rt>で</rt></ruby>ます。",
example_read:"さんばんせんから でんしゃが でます。",
example_vi:"Tàu điện xuất phát từ sân ga số 3.",
example_en:"The train leaves from platform number 3."
},

{
level:"N5",
lesson:5,
id:55,
kanji:"次",
kana:"つぎ",
hanviet:"THỨ",
vi:"Tiếp theo, kế tiếp",
en:"Next",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>次<rt>つぎ</rt></ruby></span>の <ruby>電車<rt>でんしゃ</rt></ruby>を <ruby>待<rt>ま</rt></ruby>ちます。",
example_read:"つぎの でんしゃを まちます。",
example_vi:"Tôi đợi chuyến tàu tiếp theo.",
example_en:"I wait for the next train."
},

{
level:"N5",
lesson:5,
id:56,
kanji:"普通",
kana:"ふつう",
hanviet:"PHỔ THÔNG",
vi:"Tàu thường (dừng ở tất cả các ga)",
en:"Local train",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>普通<rt>ふつう</rt></ruby></span>の <ruby>電車<rt>でんしゃ</rt></ruby>は すべての <ruby>駅<rt>えき</rt></ruby>に <ruby>止<rt>と</rt></ruby>まります。",
example_read:"ふつうの でんしゃは すべての えきに とまります。",
example_vi:"Tàu thường dừng ở tất cả các ga.",
example_en:"A local train stops at every station."
},

{
level:"N5",
lesson:5,
id:57,
kanji:"急行",
kana:"きゅうこう",
hanviet:"CẤP HÀNH",
vi:"Tàu tốc hành",
en:"Express train",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>急行<rt>きゅうこう</rt></ruby></span>は この <ruby>駅<rt>えき</rt></ruby>に <ruby>止<rt>と</rt></ruby>まりません。",
example_read:"きゅうこうは この えきに とまりません。",
example_vi:"Tàu tốc hành không dừng ở ga này.",
example_en:"The express train does not stop at this station."
},

{
level:"N5",
lesson:5,
id:58,
kanji:"特急",
kana:"とっきゅう",
hanviet:"ĐẶC CẤP",
vi:"Tàu tốc hành đặc biệt",
en:"Limited express train",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>特急<rt>とっきゅう</rt></ruby></span>で <ruby>大阪<rt>おおさか</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"とっきゅうで おおさかへ いきます。",
example_vi:"Tôi đi Osaka bằng tàu tốc hành đặc biệt.",
example_en:"I go to Osaka by limited express train."
},

{
level:"N5",
lesson:5,
id:59,
kanji:"甲子園",
kana:"こうしえん",
hanviet:"GIÁP TỬ VIÊN",
vi:"Koshien (khu vực nổi tiếng ở Hyogo, nơi có sân vận động Koshien)",
en:"Koshien",
word_type_vi:"Địa danh",
word_type_en:"Place name",
category:"Minna 1",
example:"<span class='target-word'><ruby>甲子園<rt>こうしえん</rt></ruby></span>へ <ruby>野球<rt>やきゅう</rt></ruby>を <ruby>見<rt>み</rt></ruby>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"こうしえんへ やきゅうを みに いきます。",
example_vi:"Tôi đến Koshien để xem bóng chày.",
example_en:"I go to Koshien to watch baseball."
},

{
level:"N5",
lesson:5,
id:60,
kanji:"大阪城",
kana:"おおさかじょう",
hanviet:"ĐẠI PHẢN THÀNH",
vi:"Lâu đài Osaka",
en:"Osaka Castle",
word_type_vi:"Địa danh",
word_type_en:"Place name",
category:"Minna 1",
example:"<span class='target-word'><ruby>大阪城<rt>おおさかじょう</rt></ruby></span>は とても <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"おおさかじょうは とても ゆうめいです。",
example_vi:"Lâu đài Osaka rất nổi tiếng.",
example_en:"Osaka Castle is very famous."
}
];