window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[9] = [

{
level:"N5",
lesson:9,
id:1,
kanji:"分かります",
kana:"わかります",
hanviet:"PHÂN",
vi:"Hiểu, nắm được",
en:"Understand",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 Verb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>日本語<rt>にほんご</rt></ruby>が <span class='target-word'><ruby>分<rt>わ</rt></ruby>かります</span>が、あまり <ruby>話<rt>はな</rt></ruby>せません。",
example_read:"わたしは にほんごが わかりますが、あまり はなせません。",
example_vi:"Tôi hiểu tiếng Nhật nhưng không nói được nhiều.",
example_en:"I understand Japanese, but I can't speak it very well."
},

{
level:"N5",
lesson:9,
id:2,
kanji:"あります",
kana:"あります",
hanviet:"",
vi:"Có (sở hữu)",
en:"Have",
word_type_vi:"Động từ",
word_type_en:"Verb",
category:"Minna 1",
example:"<ruby>公園<rt>こうえん</rt></ruby>の <ruby>隣<rt>となり</rt></ruby>に コンビニが <span class='target-word'>あります</span>。",
example_read:"こうえんの となりに こんびにが あります。",
example_vi:"Có một cửa hàng tiện lợi ở cạnh công viên.",
example_en:"There is a convenience store next to the park."
},

{
level:"N5",
lesson:9,
id:3,
kanji:"好き[な]",
kana:"すき[な]",
hanviet:"HẢO",
vi:"Thích",
en:"Like",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>音楽<rt>おんがく</rt></ruby>が <span class='target-word'><ruby>好<rt>す</rt></ruby>きです</span>。",
example_read:"わたしは おんがくが すきです。",
example_vi:"Tôi thích âm nhạc.",
example_en:"I like music."
},

{
level:"N5",
lesson:9,
id:4,
kanji:"嫌い[な]",
kana:"きらい[な]",
hanviet:"HIỀM",
vi:"Ghét, không thích",
en:"Dislike",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>納豆<rt>なっとう</rt></ruby>が <span class='target-word'><ruby>嫌<rt>きら</rt></ruby>いです</span>。",
example_read:"わたしは なっとうが きらいです。",
example_vi:"Tôi không thích natto.",
example_en:"I don't like natto."
},

{
level:"N5",
lesson:9,
id:5,
kanji:"上手[な]",
kana:"じょうず[な]",
hanviet:"THƯỢNG THỦ",
vi:"Giỏi, khéo",
en:"Good at",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>上手<rt>じょうず</rt></ruby>な</span> <ruby>人<rt>ひと</rt></ruby>は よく <ruby>練習<rt>れんしゅう</rt></ruby>します。",
example_read:"じょうずな ひとは よく れんしゅうします。",
example_vi:"Người giỏi thường luyện tập nhiều.",
example_en:"Skilled people practice a lot."
},

{
level:"N5",
lesson:9,
id:6,
kanji:"下手[な]",
kana:"へた[な]",
hanviet:"HẠ THỦ",
vi:"Kém",
en:"Poor at",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"<span class='target-word'><ruby>下手<rt>へた</rt></ruby>な</span> <ruby>人<rt>ひと</rt></ruby>でも <ruby>練習<rt>れんしゅう</rt></ruby>すれば <ruby>上手<rt>じょうず</rt></ruby>になります。",
example_read:"へたな ひとでも れんしゅうすれば じょうずになります。",
example_vi:"Ngay cả người không giỏi cũng sẽ trở nên giỏi nếu luyện tập.",
example_en:"Even someone who is not good at it can improve through practice."
},

{
level:"N5",
lesson:9,
id:7,
kanji:"飲み物",
kana:"のみもの",
hanviet:"ẨM VẬT",
vi:"Đồ uống",
en:"Drink",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"コンビニで <span class='target-word'><ruby>飲<rt>の</rt></ruby>み<ruby>物<rt>もの</rt></ruby></span>を <ruby>買<rt>か</rt></ruby>います。",
example_read:"こんびにで のみものを かいます。",
example_vi:"Tôi mua đồ uống ở cửa hàng tiện lợi.",
example_en:"I buy a drink at a convenience store."
},

{
level:"N5",
lesson:9,
id:8,
kanji:"料理",
kana:"りょうり",
hanviet:"LIỆU LÝ",
vi:"Món ăn, việc nấu ăn",
en:"Cooking, dish",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>母<rt>はは</rt></ruby>の <span class='target-word'><ruby>料理<rt>りょうり</rt></ruby></span>は <ruby>美味<rt>おい</rt></ruby>しいです。",
example_read:"ははの りょうりは おいしいです。",
example_vi:"Món ăn của mẹ tôi rất ngon.",
example_en:"My mother's cooking is delicious."
},

{
level:"N5",
lesson:9,
id:9,
kanji:"スポーツ",
kana:"スポーツ",
hanviet:"",
vi:"Thể thao",
en:"Sports",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>スポーツ</span>を するのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"すぽーつを するのが すきです。",
example_vi:"Tôi thích chơi thể thao.",
example_en:"I like playing sports."
},

{
level:"N5",
lesson:9,
id:10,
kanji:"野球",
kana:"やきゅう",
hanviet:"DÃ CẦU",
vi:"Bóng chày",
en:"Baseball",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>兄<rt>あに</rt></ruby>は <span class='target-word'><ruby>野球<rt>やきゅう</rt></ruby></span>を よく します。",
example_read:"あには やきゅうを よく します。",
example_vi:"Anh trai tôi thường chơi bóng chày.",
example_en:"My older brother often plays baseball."
},

{
level:"N5",
lesson:9,
id:11,
kanji:"ダンス",
kana:"ダンス",
hanviet:"",
vi:"Nhảy, khiêu vũ",
en:"Dance",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>妹<rt>いもうと</rt></ruby>は <span class='target-word'>ダンス</span>を するのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"いもうとは だんすを するのが すきです。",
example_vi:"Em gái tôi thích nhảy múa.",
example_en:"My younger sister likes dancing."
},

{
level:"N5",
lesson:9,
id:12,
kanji:"旅行",
kana:"りょこう",
hanviet:"LỮ HÀNH",
vi:"Du lịch, chuyến du lịch",
en:"Travel, trip",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>夏休<rt>なつやす</rt></ruby>みに <span class='target-word'><ruby>旅行<rt>りょこう</rt></ruby></span>する <ruby>予定<rt>よてい</rt></ruby>です。",
example_read:"なつやすみに りょこうする よていです。",
example_vi:"Tôi dự định sẽ đi du lịch vào kỳ nghỉ hè.",
example_en:"I plan to travel during summer vacation."
},

{
level:"N5",
lesson:9,
id:13,
kanji:"音楽",
kana:"おんがく",
hanviet:"ÂM NHẠC",
vi:"Âm nhạc",
en:"Music",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>音楽<rt>おんがく</rt></ruby></span>を <ruby>聞<rt>き</rt></ruby>くのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは おんがくを きくのが すきです。",
example_vi:"Tôi thích nghe nhạc.",
example_en:"I like listening to music."
},

{
level:"N5",
lesson:9,
id:14,
kanji:"歌",
kana:"うた",
hanviet:"CA",
vi:"Bài hát",
en:"Song",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>歌<rt>うた</rt></ruby></span>は とても <ruby>有名<rt>ゆうめい</rt></ruby>です。",
example_read:"この うたは とても ゆうめいです。",
example_vi:"Bài hát này rất nổi tiếng.",
example_en:"This song is very popular."
},

{
level:"N5",
lesson:9,
id:15,
kanji:"クラシック",
kana:"クラシック",
hanviet:"",
vi:"Nhạc cổ điển",
en:"Classical music",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>父<rt>ちち</rt></ruby>は <span class='target-word'>クラシック</span>が <ruby>好<rt>す</rt></ruby>きです。",
example_read:"ちちは くらしっくが すきです。",
example_vi:"Bố tôi thích nhạc cổ điển.",
example_en:"My father likes classical music."
},

{
level:"N5",
lesson:9,
id:16,
kanji:"ジャズ",
kana:"ジャズ",
hanviet:"",
vi:"Nhạc jazz",
en:"Jazz",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>は <span class='target-word'>ジャズ</span>を よく <ruby>聞<rt>き</rt></ruby>きます。",
example_read:"ともだちは じゃずを よく ききます。",
example_vi:"Bạn tôi thường nghe nhạc jazz.",
example_en:"My friend often listens to jazz."
},

{
level:"N5",
lesson:9,
id:17,
kanji:"コンサート",
kana:"コンサート",
hanviet:"",
vi:"Buổi hòa nhạc",
en:"Concert",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>来週<rt>らいしゅう</rt></ruby> <span class='target-word'>コンサート</span>へ <ruby>行<rt>い</rt></ruby>きます。",
example_read:"わたしは らいしゅう こんさーとへ いきます。",
example_vi:"Tuần sau tôi sẽ đi xem hòa nhạc.",
example_en:"I will go to a concert next week."
},

{
level:"N5",
lesson:9,
id:18,
kanji:"カラオケ",
kana:"カラオケ",
hanviet:"",
vi:"Karaoke",
en:"Karaoke",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>土曜日<rt>どようび</rt></ruby>に <ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'>カラオケ</span>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"どようびに ともだちと からおけに いきます。",
example_vi:"Thứ Bảy tôi sẽ đi hát karaoke với bạn.",
example_en:"I will go karaoke with my friends on Saturday."
},

{
level:"N5",
lesson:9,
id:19,
kanji:"歌舞伎",
kana:"かぶき",
hanviet:"CA VŨ KỸ",
vi:"Kabuki",
en:"Kabuki",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>歌舞伎<rt>かぶき</rt></ruby></span>は <ruby>日本<rt>にほん</rt></ruby>の <ruby>伝統的<rt>でんとうてき</rt></ruby>な <ruby>芸能<rt>げいのう</rt></ruby>です。",
example_read:"かぶきは にほんの でんとうてきな げいのうです。",
example_vi:"Kabuki là nghệ thuật truyền thống của Nhật Bản.",
example_en:"Kabuki is a traditional Japanese performing art."
},

{
level:"N5",
lesson:9,
id:20,
kanji:"絵",
kana:"え",
hanviet:"HỘI",
vi:"Tranh, hội họa",
en:"Picture, painting",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>絵<rt>え</rt></ruby></span>を <ruby>描<rt>か</rt></ruby>くのが <ruby>好<rt>す</rt></ruby>きです。",
example_read:"わたしは えを かくのが すきです。",
example_vi:"Tôi thích vẽ tranh.",
example_en:"I like drawing pictures."
},

{
level:"N5",
lesson:9,
id:21,
kanji:"字",
kana:"じ",
hanviet:"TỰ",
vi:"Chữ",
en:"Letter, character",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>字<rt>じ</rt></ruby></span>を きれいに <ruby>書<rt>か</rt></ruby>いてください。",
example_read:"じを きれいに かいてください。",
example_vi:"Hãy viết chữ cho đẹp.",
example_en:"Please write the characters neatly."
},

{
level:"N5",
lesson:9,
id:22,
kanji:"漢字",
kana:"かんじ",
hanviet:"HÁN TỰ",
vi:"Chữ Hán",
en:"Kanji",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <ruby>毎日<rt>まいにち</rt></ruby> <span class='target-word'><ruby>漢字<rt>かんじ</rt></ruby></span>を <ruby>練習<rt>れんしゅう</rt></ruby>しています。",
example_read:"わたしは まいにち かんじを れんしゅうしています。",
example_vi:"Tôi luyện tập chữ Hán mỗi ngày.",
example_en:"I practice kanji every day."
},

{
level:"N5",
lesson:9,
id:23,
kanji:"ひらがな",
kana:"ひらがな",
hanviet:"",
vi:"Chữ Hiragana",
en:"Hiragana",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ひらがな</span>は もう <ruby>全部<rt>ぜんぶ</rt></ruby> <ruby>覚<rt>おぼ</rt></ruby>えました。",
example_read:"ひらがなは もう ぜんぶ おぼえました。",
example_vi:"Tôi đã thuộc hết bảng chữ Hiragana rồi.",
example_en:"I have already learned all the hiragana characters."
},

{
level:"N5",
lesson:9,
id:24,
kanji:"カタカナ",
kana:"カタカナ",
hanviet:"",
vi:"Chữ Katakana",
en:"Katakana",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>カタカナ</span>は <ruby>読<rt>よ</rt></ruby>めますが、<ruby>書<rt>か</rt></ruby>くのは ちょっと <ruby>難<rt>むずか</rt></ruby>しいです。",
example_read:"かたかなは よめますが、かくのは ちょっと むずかしいです。",
example_vi:"Tôi đọc được Katakana nhưng viết thì hơi khó.",
example_en:"I can read Katakana, but writing it is a little difficult."
},

{
level:"N5",
lesson:9,
id:25,
kanji:"ローマ字",
kana:"ローマじ",
hanviet:"TỰ",
vi:"Chữ La Mã",
en:"Roman letters",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ローマ<ruby>字<rt>じ</rt></ruby></span>で <ruby>名前<rt>なまえ</rt></ruby>を <ruby>書<rt>か</rt></ruby>いてください。",
example_read:"ろーまじで なまえを かいてください。",
example_vi:"Hãy viết tên bằng chữ La Mã.",
example_en:"Please write your name in Roman letters."
},

{
level:"N5",
lesson:9,
id:26,
kanji:"細かいお金",
kana:"こまかいおかね",
hanviet:"TẾ KIM",
vi:"Tiền lẻ",
en:"Small change",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"すみません、<span class='target-word'><ruby>細<rt>こま</rt></ruby>かい お<ruby>金<rt>かね</rt></ruby></span>が ありますか。",
example_read:"すみません、こまかい おかねが ありますか。",
example_vi:"Xin lỗi, bạn có tiền lẻ không?",
example_en:"Excuse me, do you have any small change?"
},

{
level:"N5",
lesson:9,
id:27,
kanji:"チケット",
kana:"チケット",
hanviet:"",
vi:"Vé",
en:"Ticket",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>昨日<rt>きのう</rt></ruby> コンサートの <span class='target-word'>チケット</span>を <ruby>買<rt>か</rt></ruby>いました。",
example_read:"きのう こんさーとの ちけっとを かいました。",
example_vi:"Hôm qua tôi đã mua vé hòa nhạc.",
example_en:"I bought a concert ticket yesterday."
},

{
level:"N5",
lesson:9,
id:28,
kanji:"時間",
kana:"じかん",
hanviet:"THỜI GIAN",
vi:"Thời gian",
en:"Time",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今<rt>いま</rt></ruby> <span class='target-word'><ruby>時間<rt>じかん</rt></ruby></span>が ありますか。",
example_read:"いま じかんが ありますか。",
example_vi:"Bây giờ bạn có thời gian không?",
example_en:"Do you have time now?"
},

{
level:"N5",
lesson:9,
id:29,
kanji:"用事",
kana:"ようじ",
hanviet:"DỤNG SỰ",
vi:"Công chuyện, việc bận",
en:"Errand, business",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>今日<rt>きょう</rt></ruby>は <span class='target-word'><ruby>用事<rt>ようじ</rt></ruby></span>が ありますから、はやく <ruby>帰<rt>かえ</rt></ruby>ります。",
example_read:"きょうは ようじが ありますから、はやく かえります。",
example_vi:"Hôm nay tôi có việc nên sẽ về sớm.",
example_en:"I have some errands today, so I'll go home early."
},

{
level:"N5",
lesson:9,
id:30,
kanji:"約束",
kana:"やくそく",
hanviet:"ƯỚC THÚC",
vi:"Cuộc hẹn, lời hứa",
en:"Appointment, promise",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>約束<rt>やくそく</rt></ruby></span>が あります。",
example_read:"ともだちと やくそくが あります。",
example_vi:"Tôi có hẹn với bạn.",
example_en:"I have an appointment with my friend."
},

{
level:"N5",
lesson:9,
id:31,
kanji:"アルバイト",
kana:"アルバイト",
hanviet:"",
vi:"Việc làm thêm",
en:"Part-time job",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>アルバイト</span>を しながら <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>しています。",
example_read:"わたしは あるばいとを しながら にほんごを べんきょうしています。",
example_vi:"Tôi vừa đi làm thêm vừa học tiếng Nhật.",
example_en:"I study Japanese while working part-time."
},
{
level:"N5",
lesson:9,
id:32,
kanji:"ご主人",
kana:"ごしゅじん",
hanviet:"CHỦ NHÂN",
vi:"Chồng (chồng người khác)",
en:"Husband (someone else's)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>ご<ruby>主人<rt>しゅじん</rt></ruby></span>は <ruby>何<rt>なに</rt></ruby>が お<ruby>好<rt>す</rt></ruby>きですか。",
example_read:"ごしゅじんは なにが おすきですか。",
example_vi:"Chồng chị thích gì vậy?",
example_en:"What does your husband like?"
},
{
level:"N5",
lesson:9,
id:33,
kanji:"夫 / 主人",
kana:"おっと / しゅじん",
hanviet:"PHU / CHỦ NHÂN",
vi:"Chồng (chồng mình)",
en:"My husband",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>の <span class='target-word'><ruby>夫<rt>おっと</rt></ruby></span>は <ruby>休<rt>やす</rt></ruby>みの <ruby>日<rt>ひ</rt></ruby>によく <ruby>旅行<rt>りょこう</rt></ruby>します。",
example_read:"わたしの おっとは やすみの ひに よく りょこうします。",
example_vi:"Chồng tôi thường đi du lịch vào những ngày nghỉ.",
example_en:"My husband often travels on his days off."
},
{
level:"N5",
lesson:9,
id:34,
kanji:"奥さん",
kana:"おくさん",
hanviet:"ÁO",
vi:"Vợ (vợ người khác)",
en:"Wife (someone else's)",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>奥<rt>おく</rt></ruby>さん</span>は <ruby>料理<rt>りょうり</rt></ruby>が <ruby>上手<rt>じょうず</rt></ruby>ですね。",
example_read:"おくさんは りょうりが じょうずですね。",
example_vi:"Vợ anh nấu ăn giỏi nhỉ.",
example_en:"Your wife is good at cooking."
},
{
level:"N5",
lesson:9,
id:35,
kanji:"妻 / 家内",
kana:"つま / かない",
hanviet:"THÊ / GIA NỘI",
vi:"Vợ (vợ mình)",
en:"My wife",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>の <span class='target-word'><ruby>妻<rt>つま</rt></ruby></span>は <ruby>毎日<rt>まいにち</rt></ruby> <ruby>音楽<rt>おんがく</rt></ruby>を <ruby>聞<rt>き</rt></ruby>いています。",
example_read:"わたしの つまは まいにち おんがくを きいています。",
example_vi:"Vợ tôi ngày nào cũng nghe nhạc.",
example_en:"My wife listens to music every day."
},
{
level:"N5",
lesson:9,
id:36,
kanji:"子供",
kana:"こども",
hanviet:"TỬ CUNG",
vi:"Con cái, trẻ em",
en:"Child, children",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>休<rt>やす</rt></ruby>みの <ruby>日<rt>ひ</rt></ruby>は <span class='target-word'><ruby>子<rt>こ</rt></ruby>ども</span>と <ruby>公園<rt>こうえん</rt></ruby>で <ruby>遊<rt>あそ</rt></ruby>びます。",
example_read:"やすみの ひは こどもと こうえんで あそびます。",
example_vi:"Vào ngày nghỉ, tôi chơi ở công viên cùng con.",
example_en:"I play with my child at the park on my days off."
},
{
level:"N5",
lesson:9,
id:37,
kanji:"よく",
kana:"よく",
hanviet:"",
vi:"Tốt, rõ; thường xuyên",
en:"Well, often",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'>よく</span> <ruby>通勤中<rt>つうきんちゅう</rt></ruby>に <ruby>音楽<rt>おんがく</rt></ruby>を <ruby>聞<rt>き</rt></ruby>きます。",
example_read:"わたしは よく つうきんちゅうに おんがくを ききます。",
example_vi:"Tôi thường nghe nhạc khi đi làm.",
example_en:"I often listen to music while commuting."
},
{
level:"N5",
lesson:9,
id:38,
kanji:"だいたい",
kana:"だいたい",
hanviet:"",
vi:"Đại khái",
en:"Roughly, generally",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"この <ruby>漢字<rt>かんじ</rt></ruby>の <ruby>意味<rt>いみ</rt></ruby>は <span class='target-word'>だいたい</span> <ruby>分<rt>わ</rt></ruby>かります。",
example_read:"この かんじの いみは だいたい わかります。",
example_vi:"Tôi đại khái hiểu nghĩa của chữ Hán này.",
example_en:"I roughly understand the meaning of this kanji."
},
{
level:"N5",
lesson:9,
id:39,
kanji:"たくさん",
kana:"たくさん",
hanviet:"",
vi:"Nhiều",
en:"A lot, many",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>旅行中<rt>りょこうちゅう</rt></ruby>に <span class='target-word'>たくさん</span> <ruby>写真<rt>しゃしん</rt></ruby>を <ruby>撮<rt>と</rt></ruby>りました。",
example_read:"りょこうちゅうに たくさん しゃしんを とりました。",
example_vi:"Tôi đã chụp rất nhiều ảnh trong chuyến du lịch.",
example_en:"I took a lot of photos during my trip."
},
{
level:"N5",
lesson:9,
id:40,
kanji:"少し",
kana:"すこし",
hanviet:"THIỂU",
vi:"Ít, một ít",
en:"A little",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>少<rt>すこ</rt></ruby>し <ruby>日本語<rt>にほんご</rt></ruby>が <ruby>話<rt>はな</rt></ruby>せます。",
example_read:"すこし にほんごが はなせます。",
example_vi:"Tôi nói được một chút tiếng Nhật.",
example_en:"I can speak a little Japanese."
},

{
level:"N5",
lesson:9,
id:41,
kanji:"全然",
kana:"ぜんぜん",
hanviet:"TOÀN NHIÊN",
vi:"Hoàn toàn không ~",
en:"Not at all",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>私<rt>わたし</rt></ruby>は <span class='target-word'><ruby>全然<rt>ぜんぜん</rt></ruby></span> <ruby>歌<rt>うた</rt></ruby>が <ruby>上手<rt>じょうず</rt></ruby>じゃありません。",
example_read:"わたしは ぜんぜん うたが じょうずじゃありません。",
example_vi:"Tôi hoàn toàn không hát hay.",
example_en:"I am not good at singing at all."
},

{
level:"N5",
lesson:9,
id:42,
kanji:"早く / 速く",
kana:"はやく",
hanviet:"TẢO / TỐC",
vi:"Sớm, nhanh",
en:"Early, quickly",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>朝<rt>あさ</rt></ruby>は <span class='target-word'><ruby>早<rt>はや</rt></ruby>く</span> <ruby>起<rt>お</rt></ruby>きて、<span class='target-word'><ruby>速<rt>はや</rt></ruby>い</span> <ruby>バス</ruby>で <ruby>学校<rt>がっこう</rt></ruby>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"あさは はやく おきて はやい ばすで がっこうに いきます。",
example_vi:"Buổi sáng tôi dậy sớm và đi đến trường bằng xe buýt nhanh.",
example_en:"In the morning I get up early and go to school by a fast bus."
},

{
level:"N5",
lesson:9,
id:43,
kanji:"～から",
kana:"～から",
hanviet:"",
vi:"Vì ~",
en:"Because ~",
word_type_vi:"Ngữ pháp",
word_type_en:"Grammar",
category:"Minna 1",
example:"<ruby>時間<rt>じかん</rt></ruby>が ない <span class='target-word'>から</span>、はやく <ruby>帰<rt>かえ</rt></ruby>りたいです。",
example_read:"じかんが ないから、はやく かえりたいです。",
example_vi:"Vì không có thời gian nên tôi muốn về sớm.",
example_en:"Because I don't have time, I want to go home early."
},

{
level:"N5",
lesson:9,
id:44,
kanji:"どうして",
kana:"どうして",
hanviet:"",
vi:"Tại sao",
en:"Why",
word_type_vi:"Nghi vấn từ",
word_type_en:"Question word",
category:"Minna 1",
example:"<span class='target-word'>どうして</span> <ruby>日本語<rt>にほんご</rt></ruby>を <ruby>勉強<rt>べんきょう</rt></ruby>していますか。",
example_read:"どうして にほんごを べんきょうしていますか。",
example_vi:"Tại sao bạn học tiếng Nhật?",
example_en:"Why are you studying Japanese?"
},

{
level:"N5",
lesson:9,
id:45,
kanji:"貸してください",
kana:"かしてください",
hanviet:"THẢI",
vi:"Hãy cho tôi mượn",
en:"Please lend me",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"すみません、その <ruby>本<rt>ほん</rt></ruby>を <span class='target-word'><ruby>貸<rt>か</rt></ruby>してください</span>。",
example_read:"すみません、その ほんを かしてください。",
example_vi:"Xin lỗi, hãy cho tôi mượn cuốn sách đó.",
example_en:"Excuse me, please lend me that book."
},

{
level:"N5",
lesson:9,
id:46,
kanji:"いいですよ",
kana:"いいですよ",
hanviet:"",
vi:"Được chứ / Được ạ",
en:"Sure, no problem",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"A: その <ruby>本<rt>ほん</rt></ruby>、<ruby>貸<rt>か</rt></ruby>してもらえますか。<br>B: <span class='target-word'>いいですよ</span>。",
example_read:"その ほん かしてもらえますか。いいですよ。",
example_vi:"A: Bạn có thể cho tôi mượn cuốn sách đó không? B: Được chứ.",
example_en:"A: Could you lend me that book? B: Sure."
},

{
level:"N5",
lesson:9,
id:47,
kanji:"残念ですね",
kana:"ざんねんですね",
hanviet:"TÀN NIỆM",
vi:"Thật đáng tiếc nhỉ",
en:"That's a pity",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"A: <ruby>今日<rt>きょう</rt></ruby>は コンサートに <ruby>行<rt>い</rt></ruby>けなくて すみません。<br>B: <span class='target-word'><ruby>残念<rt>ざんねん</rt></ruby>ですね</span>。また <ruby>今度<rt>こんど</rt></ruby> <ruby>行<rt>い</rt></ruby>きましょう。",
example_read:"きょうは こんさーとに いけなくて すみません。ざんねんですね。また こんど いきましょう。",
example_vi:"A: Hôm nay tôi không thể đi hòa nhạc, xin lỗi nhé. B: Thật đáng tiếc nhỉ, lần sau chúng ta đi nhé.",
example_en:"A: I can't go to the concert today, sorry. B: That's a pity. Let's go next time."
},

{
level:"N5",
lesson:9,
id:48,
kanji:"ああ",
kana:"ああ",
hanviet:"",
vi:"À, a",
en:"Ah",
word_type_vi:"Thán từ",
word_type_en:"Interjection",
category:"Minna 1",
example:"<span class='target-word'>ああ</span>、<ruby>田中<rt>たなか</rt></ruby>さんですか。",
example_read:"ああ、たなかさんですか。",
example_vi:"À, anh Tanaka phải không?",
example_en:"Ah, is that Mr. Tanaka?"
},

{
level:"N5",
lesson:9,
id:49,
kanji:"一緒にいかがですか",
kana:"いっしょにいかがですか",
hanviet:"NHẤT TỰ",
vi:"Anh/chị cùng ~ với chúng tôi được không?",
en:"Would you like to join us?",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>明日<rt>あした</rt></ruby> コンサート に<span class='target-word'><ruby>一緒<rt>いっしょ</rt></ruby>に <ruby>行<rt>い</rt></ruby>きませんか</span>。",
example_read:"あした こんさーとに いっしょに いきませんか。",
example_vi:"Ngày mai anh/chị có muốn đi xem hòa nhạc cùng chúng tôi không ạ?",
example_en:"Would you like to go to the concert with us tomorrow?"
},

{
level:"N5",
lesson:9,
id:50,
kanji:"～はちょっと…",
kana:"～はちょっと…",
hanviet:"",
vi:"~ thì hơi...",
en:"~ is a little difficult...",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"すみません。<ruby>明日<rt>あした</rt></ruby>は <ruby>都合<rt>つごう</rt></ruby>が <ruby>悪<rt>わる</rt></ruby>くて <span class='target-word'>ちょっと…</span>。",
example_read:"すみません。あしたは つごうが わるくて ちょっと。",
example_vi:"Xin lỗi. Ngày mai tôi hơi không tiện nên...",
example_en:"Sorry. I’m a bit unavailable tomorrow..."
},

{
level:"N5",
lesson:9,
id:51,
kanji:"ダメですか",
kana:"だめですか",
hanviet:"",
vi:"Không được à?",
en:"Is it not possible?",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"A: <ruby>明日<rt>あした</rt></ruby>は ちょっと…。<br>B: <span class='target-word'>やっぱり ダメですか</span>。",
example_read:"あしたは ちょっと。やっぱり だめですか。",
example_vi:"A: Ngày mai thì hơi khó... B: Vẫn không được à?",
example_en:"A: Tomorrow is a bit difficult... B: So it's not possible after all?"
},

{
level:"N5",
lesson:9,
id:52,
kanji:"また今度お願いします",
kana:"またこんどおねがいします",
hanviet:"KIM ĐỘ NGUYỆN",
vi:"Hẹn anh/chị lần sau vậy",
en:"Maybe next time",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"A: <ruby>今日<rt>きょう</rt></ruby> <ruby>映画<rt>えいが</rt></ruby>を <ruby>見<rt>み</rt></ruby>に <ruby>行<rt>い</rt></ruby>きませんか。<br>B: すみません。<ruby>今日<rt>きょう</rt></ruby>は ちょっと…。<br>A: <span class='target-word'><ruby>分<rt>わ</rt></ruby>かりました</span>。また <ruby>今度<rt>こんど</rt></ruby> <ruby>行<rt>い</rt></ruby>きましょう。",
example_read:"きょう えいがを みに いきませんか。すみません。きょうは ちょっと。わかりました。また こんど いきましょう。",
example_vi:"A: Hôm nay đi xem phim nhé? B: Xin lỗi, hôm nay hơi khó. A: Hiểu rồi, lần sau đi nhé.",
example_en:"A: Shall we go watch a movie today? B: Sorry, today is a bit difficult. A: I see. Let's go next time."
}
];