window.N5_DATA = window.N5_DATA || {};

window.N5_DATA[13] = [

{
level:"N5",
lesson:13,
id:1,
kanji:"遊びます",
kana:"あそびます",
hanviet:"DU",
vi:"chơi",
en:"play",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>放課後<rt>ほうかご</rt></ruby>、<ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'><ruby>遊<rt>あそ</rt></ruby>びます</span>。",
example_read:"ほうかご ともだちと あそびます",
example_vi:"Sau giờ học tôi chơi với bạn bè.",
example_en:"I hang out with my friends after school."
},

{
level:"N5",
lesson:13,
id:2,
kanji:"泳ぎます",
kana:"およぎます",
hanviet:"VỊNH",
vi:"bơi",
en:"swim",
word_type_vi:"Động từ nhóm 1",
word_type_en:"Group 1 verb",
category:"Minna 1",
example:"<ruby>毎週<rt>まいしゅう</rt></ruby> の<ruby>日曜日<rt>にちようび</rt></ruby>に プールで <span class='target-word'><ruby>泳<rt>およ</rt></ruby>ぎます</span>。",
example_read:"まいしゅうの にちようびに プールで およぎます",
example_vi:"Chủ nhật nào tôi cũng bơi ở hồ bơi.",
example_en:"I swim in the pool every Sunday."
},

{
level:"N5",
lesson:13,
id:3,
kanji:"迎えます",
kana:"むかえます",
hanviet:"NGHÊNH",
vi:"đón",
en:"pick up",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"<ruby>空港<rt>くうこう</rt></ruby>へ <ruby>家族<rt>かぞく</rt></ruby>を <span class='target-word'><ruby>迎<rt>むか</rt></ruby>えます</span>。",
example_read:"くうこうへ かぞくを むかえます",
example_vi:"Tôi ra sân bay đón gia đình.",
example_en:"I'll pick up my family at the airport."
},

{
level:"N5",
lesson:13,
id:4,
kanji:"疲れます",
kana:"つかれます",
hanviet:"BÌ",
vi:"mệt",
en:"get tired",
word_type_vi:"Động từ nhóm 2",
word_type_en:"Group 2 verb",
category:"Minna 1",
example:"たくさん <ruby>歩<rt>ある</rt></ruby>くと <span class='target-word'><ruby>疲<rt>つか</rt></ruby>れます</span>。",
example_read:"たくさん あるくと つかれます",
example_vi:"Đi bộ nhiều thì sẽ mệt.",
example_en:"If you walk a lot, you get tired."
},

{
level:"N5",
lesson:13,
id:5,
kanji:"結婚します",
kana:"けっこんします",
hanviet:"KẾT HÔN",
vi:"kết hôn",
en:"get married",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>姉<rt>あね</rt></ruby>は <ruby>来年<rt>らいねん</rt></ruby> <span class='target-word'><ruby>結婚<rt>けっこん</rt></ruby>します</span>。",
example_read:"あねは らいねん けっこんします",
example_vi:"Chị gái tôi sẽ kết hôn vào năm sau.",
example_en:"My older sister will get married next year."
},

{
level:"N5",
lesson:13,
id:6,
kanji:"買い物します",
kana:"かいものします",
hanviet:"MÃI VẬT",
vi:"mua sắm",
en:"go shopping",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"デパートで <span class='target-word'><ruby>買<rt>か</rt></ruby>い<ruby>物<rt>もの</rt></ruby>します</span>。",
example_read:"デパートで かいものします",
example_vi:"Tôi mua sắm ở bách hóa.",
example_en:"I go shopping at the department store."
},

{
level:"N5",
lesson:13,
id:7,
kanji:"食事します",
kana:"しょくじします",
hanviet:"THỰC SỰ",
vi:"ăn cơm, dùng bữa",
en:"have a meal",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>毎晩<rt>まいばん</rt></ruby> <ruby>家族<rt>かぞく</rt></ruby>と <span class='target-word'><ruby>食事<rt>しょくじ</rt></ruby>します</span>。",
example_read:"まいばん かぞくと しょくじします",
example_vi:"Tối nào tôi cũng ăn cơm cùng gia đình.",
example_en:"I have meals with my family every evening."
},

{
level:"N5",
lesson:13,
id:8,
kanji:"散歩します",
kana:"さんぽします",
hanviet:"TÁN BỘ",
vi:"đi dạo",
en:"take a walk",
word_type_vi:"Động từ nhóm 3",
word_type_en:"Group 3 verb",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby> <ruby>公園<rt>こうえん</rt></ruby>を <span class='target-word'><ruby>散歩<rt>さんぽ</rt></ruby>します</span>。",
example_read:"まいあさ こうえんを さんぽします",
example_vi:"Mỗi sáng tôi đi dạo trong công viên.",
example_en:"I take a walk in the park every morning."
},

{
level:"N5",
lesson:13,
id:9,
kanji:"大変[な]",
kana:"たいへん[な]",
hanviet:"ĐẠI BIẾN",
vi:"vất vả, khó khăn",
en:"hard, difficult",
word_type_vi:"Tính từ đuôi な",
word_type_en:"Na-adjective",
category:"Minna 1",
example:"この <ruby>仕事<rt>しごと</rt></ruby>は <span class='target-word'><ruby>大変<rt>たいへん</rt></ruby>です</span>。",
example_read:"この しごとは たいへんです",
example_vi:"Công việc này rất vất vả.",
example_en:"This job is tough."
},

{
level:"N5",
lesson:13,
id:10,
kanji:"欲しい",
kana:"ほしい",
hanviet:"DỤC",
vi:"muốn có",
en:"want",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"<ruby>新<rt>あたら</rt></ruby>しい <ruby>車<rt>くるま</rt></ruby>が <span class='target-word'><ruby>欲<rt>ほ</rt></ruby>しい</span>です。",
example_read:"あたらしい くるまが ほしいです",
example_vi:"Tôi muốn có một chiếc xe mới.",
example_en:"I want a new car."
},

{
level:"N5",
lesson:13,
id:11,
kanji:"広い",
kana:"ひろい",
hanviet:"QUẢNG",
vi:"rộng",
en:"wide, spacious",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>部屋<rt>へや</rt></ruby>は <span class='target-word'><ruby>結構<rt>けっこう</rt></ruby> <ruby>広<rt>ひろ</rt></ruby>い</span>です。",
example_read:"この へやは けっこう ひろいです",
example_vi:"Căn phòng này khá rộng.",
example_en:"This room is quite spacious."
},

{
level:"N5",
lesson:13,
id:12,
kanji:"狭い",
kana:"せまい",
hanviet:"HIỆP",
vi:"chật, hẹp",
en:"narrow, small",
word_type_vi:"Tính từ đuôi い",
word_type_en:"I-adjective",
category:"Minna 1",
example:"この <ruby>道<rt>みち</rt></ruby>は ちょっと <span class='target-word'><ruby>狭<rt>せま</rt></ruby>い</span>です。",
example_read:"この みちは ちょっと せまいです",
example_vi:"Con đường này hơi hẹp.",
example_en:"This road is a little narrow."
},

{
level:"N5",
lesson:13,
id:13,
kanji:"プール",
kana:"プール",
hanviet:"",
vi:"hồ bơi",
en:"pool",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'>プール</span>で <ruby>泳<rt>およ</rt></ruby>ぎます。",
example_read:"プールで およぎます",
example_vi:"Tôi bơi ở hồ bơi.",
example_en:"I swim in the pool."
},

{
level:"N5",
lesson:13,
id:14,
kanji:"川",
kana:"かわ",
hanviet:"XUYÊN",
vi:"sông",
en:"river",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"この <span class='target-word'><ruby>川<rt>かわ</rt></ruby></span>の <ruby>水<rt>みず</rt></ruby>が とても <ruby>綺麗<rt>きれい</rt></ruby>ですね。",
example_read:"この かわの みずが とても きれいですね",
example_vi:"Nước con sông này trong và sạch quá nhỉ.",
example_en:"The water in this river is very clear."
},

{
level:"N5",
lesson:13,
id:15,
kanji:"美術",
kana:"びじゅつ",
hanviet:"MỸ THUẬT",
vi:"mỹ thuật",
en:"art",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>美術<rt>びじゅつ</rt></ruby></span>が とても <ruby>好<rt>す</rt></ruby>きです。",
example_read:"びじゅつが とても すきです",
example_vi:"Tôi rất thích mỹ thuật.",
example_en:"I really like art."
},

{
level:"N5",
lesson:13,
id:16,
kanji:"釣り",
kana:"つり",
hanviet:"ĐIẾU",
vi:"câu cá",
en:"fishing",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>週末<rt>しゅうまつ</rt></ruby>に <span class='target-word'><ruby>釣<rt>つ</rt></ruby>り</span>を します。",
example_read:"しゅうまつに つりを します",
example_vi:"Cuối tuần tôi đi câu cá.",
example_en:"I go fishing on the weekends."
},

{
level:"N5",
lesson:13,
id:17,
kanji:"スキー",
kana:"スキー",
hanviet:"",
vi:"trượt tuyết",
en:"skiing",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<ruby>毎年<rt>まいとし</rt></ruby>、<ruby>冬<rt>ふゆ</rt></ruby>に <ruby>友達<rt>ともだち</rt></ruby>と <span class='target-word'>スキー</span>に <ruby>行<rt>い</rt></ruby>きます。",
example_read:"まいとし ふゆに ともだちと スキーに いきます",
example_vi:"Mỗi năm, vào mùa đông tôi đi trượt tuyết với bạn bè.",
example_en:"I go skiing with my friends every winter."
},

{
level:"N5",
lesson:13,
id:18,
kanji:"週末",
kana:"しゅうまつ",
hanviet:"CHU MẠT",
vi:"cuối tuần",
en:"weekend",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>週末<rt>しゅうまつ</rt></ruby></span>は <ruby>何<rt>なに</rt></ruby>を しますか。",
example_read:"しゅうまつは なにを しますか",
example_vi:"Cuối tuần bạn làm gì?",
example_en:"What do you do on weekends?"
},

{
level:"N5",
lesson:13,
id:19,
kanji:"[お]正月",
kana:"[お]しょうがつ",
hanviet:"CHÍNH NGUYỆT",
vi:"Tết",
en:"New Year",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"お正月に 家族と 一緒に 旅行します。",
example_read:"おしょうがつに かぞくと いっしょに りょこうします",
example_vi:"Tết tôi đi du lịch cùng gia đình.",
example_en:"I travel with my family during New Year."
},

{
level:"N5",
lesson:13,
id:20,
kanji:"～頃",
kana:"～ごろ",
hanviet:"KHOẢNH",
vi:"khoảng ~",
en:"about, around",
word_type_vi:"Trợ từ",
word_type_en:"Suffix",
category:"Minna 1",
example:"A: 今日は もう 帰りますか。 B: はい、7時<span class='target-word'><ruby>頃<rt>ごろ</rt></ruby></span>に 帰ります。",
example_read:"A: きょうは もう かえりますか。 B: はい、しちじごろに かえります",
example_vi:"A: Hôm nay bạn về rồi à? B: Vâng, khoảng 7 giờ tôi sẽ về.",
example_en:"A: Are you going home already today? B: Yes, I’ll go home around 7."
},

{
level:"N5",
lesson:13,
id:21,
kanji:"何か",
kana:"なにか",
hanviet:"HÀ",
vi:"cái gì đó",
en:"something",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"A: <span class='target-word'><ruby>何<rt>なに</rt></ruby>か</span> 食べますか。 B: はい、サンドイッチが 食べたいです。",
example_read:"A: なにか たべますか。 B: はい、サンドイッチが たべたいです",
example_vi:"A: Bạn có muốn ăn gì không? B: Vâng, tôi muốn ăn sandwich.",
example_en:"A: Would you like something to eat? B: Yes, I'd like a sandwich."
},

{
level:"N5",
lesson:13,
id:22,
kanji:"どこか",
kana:"どこか",
hanviet:"",
vi:"đâu đó",
en:"somewhere",
word_type_vi:"Đại từ",
word_type_en:"Pronoun",
category:"Minna 1",
example:"A: <ruby>週末<rt>しゅうまつ</rt></ruby>は <ruby>何<rt>なに</rt></ruby>を しますか。 B: <span class='target-word'>どこか</span>へ <ruby>行<rt>い</rt></ruby>きたいです。",
example_read:"A: しゅうまつは なにを しますか。 B: どこかへ いきたいです",
example_vi:"A: Cuối tuần bạn định làm gì? B: Tôi muốn đi đâu đó.",
example_en:"A: What are you planning to do this weekend? B: I'd like to go somewhere."
},

{
level:"N5",
lesson:13,
id:23,
kanji:"喉が渇きます",
kana:"のどが かわきます",
hanviet:"HẦU KIỀN",
vi:"khát nước",
en:"be thirsty",
word_type_vi:"Cụm động từ",
word_type_en:"Verb phrase",
category:"Minna 1",
example:"たくさん <ruby>話<rt>はな</rt></ruby>したので、<span class='target-word'><ruby>喉<rt>のど</rt></ruby>が <ruby>渇<rt>かわ</rt></ruby>きました</span>。",
example_read:"たくさん はなしたので のどが かわきました",
example_vi:"Vì nói nhiều nên tôi khát nước.",
example_en:"I got thirsty because I talked a lot."
},

{
level:"N5",
lesson:13,
id:24,
kanji:"お腹が空きます",
kana:"おなかが すきます",
hanviet:"PHÚC KHÔNG",
vi:"đói bụng",
en:"be hungry",
word_type_vi:"Cụm động từ",
word_type_en:"Verb phrase",
category:"Minna 1",
example:"もう <ruby>昼<rt>ひる</rt></ruby>ですね。<span class='target-word'>お<ruby>腹<rt>なか</rt></ruby>が <ruby>空<rt>す</rt></ruby>きました</span>。",
example_read:"もう ひるですね おなかが すきました",
example_vi:"Đến trưa rồi nhỉ, tôi đói bụng quá.",
example_en:"It's already noon. I'm getting hungry."
},

{
level:"N5",
lesson:13,
id:25,
kanji:"そうしましょう",
kana:"そうしましょう",
hanviet:"",
vi:"chúng ta làm vậy đi",
en:"Let's do that",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"いいですね。<span class='target-word'>そうしましょう</span>。",
example_read:"いいですね そうしましょう",
example_vi:"Được đấy. Chúng ta làm vậy đi.",
example_en:"Sounds good. Let's do that."
},

{
level:"N5",
lesson:13,
id:26,
kanji:"ご注文は？",
kana:"ごちゅうもんは",
hanviet:"CHÚ VĂN",
vi:"Quý khách gọi món gì ạ?",
en:"May I take your order?",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"いらっしゃいませ。<span class='target-word'>ご<ruby>注文<rt>ちゅうもん</rt></ruby>は お<ruby>決<rt>き</rt></ruby>まりですか。</span>",
example_read:"いらっしゃいませ ごちゅうもんは おきまりですか",
example_vi:"Xin chào quý khách. Quý khách đã chọn món chưa ạ?",
example_en:"Welcome. May I take your order?"
},

{
level:"N5",
lesson:13,
id:27,
kanji:"定食",
kana:"ていしょく",
hanviet:"ĐỊNH THỰC",
vi:"cơm phần, cơm suất",
en:"set meal",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"すみません。<span class='target-word'><ruby>定食<rt>ていしょく</rt></ruby></span>を <ruby>一<rt>ひと</rt></ruby>つ <ruby>お願<rt>ねが</rt></ruby>いします。",
example_read:"すみません ていしょくを ひとつ おねがいします",
example_vi:"Xin lỗi, cho tôi một phần cơm suất.",
example_en:"One set meal, please."
},

{
level:"N5",
lesson:13,
id:28,
kanji:"牛丼",
kana:"ぎゅうどん",
hanviet:"NGƯU ĐẢM",
vi:"cơm bò",
en:"beef bowl",
word_type_vi:"Danh từ",
word_type_en:"Noun",
category:"Minna 1",
example:"<span class='target-word'><ruby>牛丼<rt>ぎゅうどん</rt></ruby></span>を よく <ruby>食<rt>た</rt></ruby>べます。",
example_read:"ぎゅうどんを よく たべます",
example_vi:"Tôi thường ăn cơm bò.",
example_en:"I often eat gyudon."
},

{
level:"N5",
lesson:13,
id:29,
kanji:"[少々]お待ちください",
kana:"[しょうしょう]おまちください",
hanviet:"THIỂU ĐÃI",
vi:"xin vui lòng đợi một chút",
en:"please wait a moment",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"<ruby>こちら</ruby>で <span class='target-word'>[<ruby>少々<rt>しょうしょう</rt></ruby>]お<ruby>待<rt>ま</rt></ruby>ちください</span>。",
example_read:"こちらで しょうしょう おまちください",
example_vi:"Xin vui lòng đợi ở đây một lát.",
example_en:"Please wait here for a moment."
},

{
level:"N5",
lesson:13,
id:30,
kanji:"～でございます",
kana:"～でございます",
hanviet:"",
vi:"là (cách nói lịch sự của です)",
en:"is (polite form of desu)",
word_type_vi:"Mẫu câu",
word_type_en:"Expression",
category:"Minna 1",
example:"こちらが メニュー<span class='target-word'>でございます</span>。",
example_read:"こちらが メニューでございます",
example_vi:"Đây là thực đơn ạ.",
example_en:"This is the menu."
},

{
level:"N5",
lesson:13,
id:31,
kanji:"別々に",
kana:"べつべつに",
hanviet:"BIỆT",
vi:"riêng ra, riêng từng người",
en:"separately",
word_type_vi:"Trạng từ",
word_type_en:"Adverb",
category:"Minna 1",
example:"<ruby>支払<rt>しはら</rt></ruby>いは <span class='target-word'><ruby>別々<rt>べつべつ</rt></ruby>に</span> お<ruby>願<rt>ねが</rt></ruby>いします。",
example_read:"しはらいは べつべつに おねがいします",
example_vi:"Cho chúng tôi thanh toán riêng.",
example_en:"We'd like to pay separately."
},

{
level:"N5",
lesson:13,
id:32,
kanji:"アキックス",
kana:"アキックス",
hanviet:"",
vi:"Công ty Akix",
en:"Akix",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<span class='target-word'>アキックス</span>で <ruby>働<rt>はたら</rt></ruby>いています。",
example_read:"アキックスで はたらいています",
example_vi:"Tôi đang làm việc tại công ty Akix.",
example_en:"I work for Akix."
},

{
level:"N5",
lesson:13,
id:33,
kanji:"おはようテレビ",
kana:"おはようテレビ",
hanviet:"",
vi:"Chương trình Ohayou TV",
en:"Ohayou TV",
word_type_vi:"Danh từ riêng",
word_type_en:"Proper noun",
category:"Minna 1",
example:"<ruby>毎朝<rt>まいあさ</rt></ruby>、<span class='target-word'>おはようテレビ</span>を <ruby>見<rt>み</rt></ruby>ています。",
example_read:"まいあさ おはようテレビを みています",
example_vi:"Sáng nào tôi cũng xem chương trình Ohayou TV.",
example_en:"I watch Ohayou TV every morning."
}
];